### ISSUE TITLE
System.Net.HttpClient does not have a 'PatchAsync' built-in method.

### ISSUE THREAD

**Issue by shaunol** [NSwag/NSwag#107]
The CSharp code generator ClientTemplate t4 template uses the `SwaggerOperationMethod` enum converted to a string to determine which http method and System.Net.HttpClient method to use when calling operations.

This means the C# HttpClient is used like so:

```
client_.GetAsync
client_.PostAsync
client_.PutAsync
```

Unfortunately the System.Net.HttpClient class has no built-in `PatchAsync` method, therefore we need to provide a polyfill (via extension methods) or change the convention for emitting the method calls.

See: https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration/CodeGenerators/CSharp/Templates/ClientTemplate.tt#L106

I don't have a solution at this time but am posting a work-around as seen here: http://stackoverflow.com/a/26218765/134869

```csharp
public static async Task<HttpResponseMessage> PatchAsync(this HttpClient client, string requestUri, HttpContent content, CancellationToken cancellationToken)
{
    var method = new HttpMethod("PATCH");
    var request = new HttpRequestMessage(method, requestUri)
    {
        Content = content
    };

    var response = await client.SendAsync(request, cancellationToken);
    return response;
}
```

Work-around is not exhaustive of all possibilities (ie. no content in request/response). I have also not checked for existence of the other operations on the HttpClient class either.

Right now this is causing invalid C# code to be generated when generating code from schemas' containing PATCH requests.

Cheers for the great library.

**Comment by rsuter** [comment]
Thanks, I think generating the extension methods in a private class would be the simplest solution... (with check if method is required)

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/389caf4a1a309dd06cbeb2e24f539a45fe7277ec
