### ISSUE TITLE
WebApiToSwagger: Produces invalid json (parameter and response types)

### ISSUE THREAD

**Issue by vdecristofaro** [NSwag/NSwag#108]
I did used NSwag to generate a json file for each controller I have. 
However it seems that the generated json is invalid. 

Please have a look at the following discussion for further details.
https://github.com/dotnet/docfx/issues/181#issuecomment-219175889

Thank you

**Comment by rsuter** [comment]
you are right, this should generate: 

```
"schema": {
	"oneOf": [
		{
			"type": "null"
		}, 
		{
			"$ref": "#/definitions/CouponRedeemViewModel"
		}
	]
}
```

I'll look into this as soon as possible...

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/e81e344f5357b6b542e6e651614e0660f4f1a1d9, please try again with v2.24

**Comment by vdecristofaro** [comment]
Hello,
I dont think the problem is solved. Please have a look at [this](https://github.com/dotnet/docfx/issues/181#issuecomment-222430034
)

**Comment by rsuter** [comment]
I can see the following two issues: 

Swagger schema validation failed. 
  Additional properties not allowed: typeName at #/definitions/Sender
  Additional properties not allowed: cp/redeem,cp/create at #/paths

the typeName makes sense because it is an additional property
but i don't understand why "cp/redeem" and "cp/create" has a problem, maybe the validator is broken?

**Comment by domecbuilder** [comment]
@rsuter 
thanks a lot for your answer. This makes sense to me. Apart for the additional property I think that the biggest problem would be that the NSwag tool is already supporting feature from an incoming specification revision.
Could you please advice, if you know of course, any tool which is able to generate a [Open API v2](http://swagger.io/specification/) compatible swagger file for a single controller as NSwag does?

Thank you.

**Comment by vdecristofaro** [comment]
@rsuter 
thanks a lot for your answer. This makes sense to me. Apart for the additional property I think that the biggest problem would be that the NSwag tool is already supporting feature from an incoming specification revision.
Could you please advice, if you know of course, any tool which is able to generate a [Open API v2](http://swagger.io/specification/) compatible swagger file for a single controller as NSwag does?

Thank you.

**Comment by rsuter** [comment]
From the Swagger spec: "Primitive data types in the Swagger Specification are based on the types supported by the JSON-Schema Draft 4"

It seems that your tool must support JSON Schema v4 in order to work properly, and it seems it doesn't... Maybe you have to switch to a JSON Schema/Swagger library which correctly supports the standard (for example NSwag :-)). But I don't know your project, maybe this is not the issue here...

**Comment by rsuter** [comment]
Ok, i see the problem: The paths do not start with a /, will fix that... the custom properties will be extended with a "x-" so that they are valid...

**Comment by rsuter** [comment]
In NSwag v2.43, the missing `/` prefix is added to the paths and the `typeName` and `enumNames` fields are prefixed with `x-` (custom fields). Now the generated Swagger spec should be valid...

**Comment by rsuter** [comment]
Ok, just checked with the swagger team: Swagger uses required instead of oneOf to express nullability. I will add on option to genererate both variants in NJsonSchema and NSwag will use required by default.. Then it should produce valid json as expected...

**Comment by rsuter** [comment]
Added PropertyNullHandling  setting: https://github.com/NJsonSchema/NJsonSchema/commit/aaae36eb4e7c106ba18dcb4cf5adad3faee33594

**Comment by rsuter** [comment]
Please try again with latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o

**Comment by rsuter** [comment]
Now the Swagger spec should be correct (no oneOf)

**Comment by vdecristofaro** [comment]
@rsuter How do I use it? Should I pass an option to the command line? 
I have executed the command line as before and `oneOf` is still present.

**Comment by rsuter** [comment]
Its enabled by default... Have you downloaded the bits from the build server? Here: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by vdecristofaro** [comment]
@rsuter Ok I have been able to try with the latest build.
I have created a swagger from a temporary controller which you can find attached. You are right, there is not any more oneOf in the generated swagger. However this is not yet validated by the validator [here](http://bigstickcarpet.com/swagger-parser/www/index.html)..

The errors now are as follow:

```
Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//cp/redeem/put/responses/200
    Missing required property: description at #/paths//cp/redeem/put/responses/200
    Missing required property: $ref at #/paths//cp/redeem/put/responses/200
 
JSON_OBJECT_VALIDATION_FAILED
```
I think that this could depend from he fact that the controller signature does not specify a result like

`public async Task<HttpResponseMessage> ...`

**Comment by rsuter** [comment]
Hmm, why is there still a problem with oneOf? Always adding description is easy. The ref problem is also strange...

**Comment by rsuter** [comment]
But i think we have fixed it soon :-)

**Comment by rsuter** [comment]
Ok, after adding the "description" field, the schema is valid. Try latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/304

**Comment by vdecristofaro** [comment]
I think we're coming to a solution. Actually the json is validated without errors [here](http://bigstickcarpet.com/swagger-parser/www/index.html).

However DocFx still has errors with it:

```
Error: System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Self referencing loop detected with type 'Microsoft.DocAsCode.Build.RestApi.Swagger.Internals.SwaggerObject'. Path ''.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)

```

I am going to check it with them. I think that this one can be closed and would like to thank you for the great support you gave. Great, keep up the good work!

**Comment by rsuter** [comment]
Cool :-) finally ..

**Comment by rsuter** [comment]
Thanks for using the project
