### ISSUE TITLE
NSwagStudio & Cmd Line: Support .NET Core assemblies [on hold]

### ISSUE THREAD

**Issue by dmikov** [NSwag/NSwag#110]
I am using core dnx web project and with dnx all references are not copied. Unfortunately studio seems to be ignroing the "Path to search for referenced assembly" I cannot load web api, because it doesn't find dependencies. If I copy core.dll into the API directory it can find it, but then it cannot find any nuget packages, so it's not an option.

![image](https://cloud.githubusercontent.com/assets/5971459/15325592/f071c3d6-1c18-11e6-87de-2caa556f8f67.png)

**Comment by rsuter** [comment]
Did you follow the instructions here: https://github.com/NSwag/NSwag/wiki/WebApiAssemblyToSwaggerGenerator
?

**Comment by dmikov** [comment]
Yes, I tried it too (First). It couldn't find core.dll. I guess I moved too soon to root package directory. Because, I just tried it now (it's still doesn't find core.dll), but if I copy it into the folder  manually. Now it finds .net assemblies fine.

**Comment by rsuter** [comment]
Yes, its a little strange for .NET Core as not everything is copied into one output directory... Is this issue solved?

**Comment by dmikov** [comment]
well, no it's still cannot get dll from the reference path.
http://screencloud.net/v/mL96

**Comment by rsuter** [comment]
Can you provide a sample project?

**Comment by rsuter** [comment]
Im just trying to load a .net core project, but with rc2 it no longer works... have to investigate further

**Comment by rsuter** [comment]
It seems that with RC2, .NET Core assemblies can no longer be loaded in a full .NET 4.6 process... I will wait until .NET Core and .NET 4.6.2 is released and try again when everything is stable... 

Until then, you can install the new .NET Core middlewares in your project and serve the Swagger spec directly from your project: https://github.com/NSwag/NSwag/wiki/OwinMiddleware

After starting the web project, open NSwagStudio and load the Swagger spec via URL: 

![image](https://cloud.githubusercontent.com/assets/2603405/16149769/31f8927a-3493-11e6-9786-f22808a36010.png)

**Comment by rsuter** [comment]
.Net core 1.0 assemblies require .net standard 1.6 and it seems that only .Net 4.6.3 will support that...

**Comment by rsuter** [comment]
With v6.2 .NET Core support is now working in NSwagStudio and the command line tools. 

Fix: https://github.com/NSwag/NSwag/commit/507f4b917d567fcf6fba9be8a48afd89d6836ced

**Comment by rsuter** [comment]
Updated wiki: https://github.com/NSwag/NSwag/wiki/WebApiAssemblyToSwaggerGenerator#net-core

**Comment by rsuter** [comment]
Still issues with .NET Core system NuGet packages: BadFormatException

Maybe try debug publish?

**Comment by rsuter** [comment]
Updated wiki with a way to load .net core libs
