### ISSUE TITLE
Typescript Generator: Incorrect success response handling

### ISSUE THREAD

**Issue by TerryHighfield** [NSwag/NSwag#111]
The generated response handler is not correct:
`private processGetPermissions(response: Response) {
        var data = response.text();
        var status = response.status.toString();

        if (status === "200") {
            var result200: UserPermissionSetContract = null;
            result200 = data === "" ? null : <UserPermissionSetContract>JSON.parse(data, this.jsonParseReviver);
            return result200;
        }
        else
        {
            throw "error_no_callback_for_the_received_http_status";
        }
    }`

There are other "success" status' 20* and 304. In my case I'd like to use 304 to enable client side caching of results.

Could the generated code be changed to allow the caller to handle the response or can the NSag code be changed to allow custom templates to be used?

Thanks

**Comment by TerryHighfield** [comment]
So I can add the 304 handling using Annotations:
`private processGetPermissions(response: Response) {
        var data = response.text();
        var status = response.status.toString(); 

        if (status === "304") {
            var result304: Void = null; 
            result304 = data === "" ? null : <Void>JSON.parse(data, this.jsonParseReviver);
            throw result304; 
        }
        else
        if (status === "200") {
            var result200: UserPermissionSetContract = null; 
            result200 = data === "" ? null : <UserPermissionSetContract>JSON.parse(data, this.jsonParseReviver);
            return result200; 
        }
        else
        {
            throw "error_no_callback_for_the_received_http_status"; 
        }
    }`

This doesn't assist Http Caching quite enough. The request method creates a request with headers. To support HttpCaching i would need to add the Etag to the request headers
`getPermissions(): Observable<UserPermissionSetContract> {
        var url = this.baseUrl + "/v1/permissions/userpermissions?"; 

        var content = "";

        return this.http.request(url, {
            body: content,
            method: "get",
            headers: **new Headers({
                "Content-Type": "application/json; charset=UTF-8"
            })**
        }).map((response) => {
            return this.processGetPermissions(response);
        });
    }`

This is a great utility btw. It has helped me a lot!

**Comment by rsuter** [comment]
I added some extension points. See
https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code

Would this be sufficient for you?

**Comment by rsuter** [comment]
Now you can use the extension points `transformOptions` and `transformResult`... (v2.35)
