### ISSUE TITLE
Just show Base Class Model Schema

### ISSUE THREAD

**Issue by carldai0106** [NSwag/NSwag#12]
Dear Author;
I found a bug, If I use code as follow to generate swagger json.
and use swagger to parse the json, but the CC model schema is wrong.

Correctly is 
{
  "address": "string",
  "lastName": "string",
  "firstName": "string"
}

but it shows as below
{
    "firstName": "string"
}

    public class AA
    {
        public string FirstName { get; set; }
    }

    public class BB : AA
    {
        public string LastName { get; set; }
    }

    public class CC : BB
    {
        public string Address { get; set; }
    }

 public class PersonsController : ApiController
  {
     public void Post([FromBody]CC value)
        {
        }
  }

**Comment by rsuter** [comment]
The swagger for your PersonsController looks like this: 

	{
	  "swagger": "2.0",
	  "info": {
		"title": "",
		"version": ""
	  },
	  "schemes": [],
	  "paths": {
		"api/Persons/Post": {
		  "Post": {
			"tags": [],
			"operationId": "Post",
			"parameters": [
			  {
				"name": "value",
				"in": "Body",
				"schema": {
				  "type": "object",
				  "$ref": "#/definitions/CC"
				}
			  }
			],
			"responses": {
			  "200": {}
			}
		  }
		}
	  },
	  "definitions": {
		"CC": {
		  "typeName": "CC",
		  "additionalProperties": false,
		  "type": "object",
		  "properties": {
			"Address": {
			  "type": "string"
			}
		  },
		  "allOf": [
			{
			  "typeName": "BB",
			  "type": "object",
			  "allOf": [
				{
				  "typeName": "AA",
				  "type": "object",
				  "$ref": "#/definitions/AA"
				}
			  ],
			  "$ref": "#/definitions/BB"
			}
		  ]
		},
		"BB": {
		  "typeName": "BB",
		  "additionalProperties": false,
		  "type": "object",
		  "properties": {
			"LastName": {
			  "type": "string"
			}
		  },
		  "allOf": [
			{
			  "typeName": "AA",
			  "type": "object",
			  "$ref": "#/definitions/AA"
			}
		  ]
		},
		"AA": {
		  "typeName": "AA",
		  "additionalProperties": false,
		  "type": "object",
		  "properties": {
			"FirstName": {
			  "type": "string"
			}
		  }
		}
	  },
	  "responses": {},
	  "securityDefinitions": {}
	}

As you can see, the JSON Schema for CC uses the `allOf` to "simulate" inheritance... The only bug here is that in CC the allOf proprties are nested... will fix this..

**Comment by rsuter** [comment]
Ok, fixed in v1.5, Swagger looks correct now: 

	{
	  "swagger": "2.0",
	  "info": {
		"title": "",
		"version": ""
	  },
	  "schemes": [],
	  "paths": {
		"api/Test/Post": {
		  "Post": {
			"tags": [],
			"operationId": "Post",
			"parameters": [
			  {
				"name": "value",
				"in": "Body",
				"schema": {
				  "type": "object",
				  "$ref": "#/definitions/CC"
				}
			  }
			],
			"responses": {
			  "200": {}
			}
		  }
		}
	  },
	  "definitions": {
		"CC": {
		  "typeName": "CC",
		  "additionalProperties": false,
		  "type": "object",
		  "properties": {
			"Address": {
			  "type": "string"
			}
		  },
		  "allOf": [
			{
			  "typeName": "BB",
			  "type": "object",
			  "$ref": "#/definitions/BB"
			}
		  ]
		},
		"BB": {
		  "typeName": "BB",
		  "additionalProperties": false,
		  "type": "object",
		  "properties": {
			"LastName": {
			  "type": "string"
			}
		  },
		  "allOf": [
			{
			  "typeName": "AA",
			  "type": "object",
			  "$ref": "#/definitions/AA"
			}
		  ]
		},
		"AA": {
		  "typeName": "AA",
		  "additionalProperties": false,
		  "type": "object",
		  "properties": {
			"FirstName": {
			  "type": "string"
			}
		  }
		}
	  },
	  "responses": {},
	  "securityDefinitions": {}
	}

**Comment by rsuter** [comment]
Opened an issue in NJsonSchema which I think reflects your problem: https://github.com/NJsonSchema/NJsonSchema/issues/5

**Comment by rsuter** [comment]
Added the option to the GUI: 

![image](https://cloud.githubusercontent.com/assets/2603405/11457366/1726804a-96a7-11e5-8e86-de20ed1ea2ae.png)

Output is now: 

	{
	  "swagger": "2.0",
	  "info": {
		"title": "",
		"version": ""
	  },
	  "schemes": [],
	  "paths": {
		"api/Persons2/Post": {
		  "Post": {
			"tags": [],
			"operationId": "Post",
			"parameters": [
			  {
				"name": "value",
				"in": "Body",
				"schema": {
				  "type": "object",
				  "$ref": "#/definitions/CC"
				}
			  }
			],
			"responses": {
			  "200": {}
			}
		  }
		}
	  },
	  "definitions": {
		"CC": {
		  "typeName": "CC",
		  "additionalProperties": false,
		  "type": "object",
		  "properties": {
			"Address": {
			  "type": "string"
			},
			"LastName": {
			  "type": "string"
			},
			"FirstName": {
			  "type": "string"
			}
		  }
		}
	  },
	  "responses": {},
	  "securityDefinitions": {}
	}

Added in release v1.5
