### ISSUE TITLE
CSharp client generation is creating duplicate declarations

### ISSUE THREAD

**Issue by benbward** [NSwag/NSwag#124]
I generated a client for the Swagger Pet Store demo using NSwagStudio and it generated duplicate members.  I repeated the exercise using a T4 template and encountered the same result.

NSwagStudio Application Version: 2.30.5983.35577

For the T4 template, I was using NSwag.Core version 2.30.5983.35397.

**Comment by rsuter** [comment]
For this sample you need to select SingleClientFromOperationId as OperationGenerationMode

https://github.com/NSwag/NSwag/wiki/ClientGeneratorBase

**Comment by rsuter** [comment]
Now also possible with MultipleClientsFromOperationId: https://github.com/NSwag/NSwag/commit/2f4baa4400f1351fa8689981f04c2ef795c48e36
