### ISSUE TITLE
TypeScript: Add client template for Aurelia

### ISSUE THREAD

**Issue by MaartenThomassen** [NSwag/NSwag#13]
Hey,

Thanks for creating this awesome project! I just integrated it into our development environment for generating the types our WebApi exposed for our Typescript project. It was exactly was I was looking for!

I am currently generating only types, not xhr class definitions because we use a framework (Aurelia) for our Typescript project and do not use jquery. Also, we would like some other code bits injected in our xhr's (for example for file upload progress etc).

I dug into your source code and noticed you use template files to generate the code (you currently use it to differentiate between Callbacks and Q). Would it be possible to add a method for us to allow us to use our own custom template file?

It's not a "must" in our current sprint so I don't have time to impelment it myself. If you don't have time, I might implement this in the future if we would require the functionality. However, I think this might be usefull for many others using NSwag to be able to define how they would like thier xhr request code to be generated (especially if you don't want to use the default jquery interface, or for people who would like to use the new fetch api instead of xhr).

Regards,
Maarten

**Comment by rsuter** [comment]
Of course, you can create a pull request with a new template for Aurelia... My next template will be for Angular 1.x... I do not know how Aurelia handles HTTP but writing a new template should be pretty simple...

**Comment by MaartenThomassen** [comment]
I think we're going to do that in the future. I'll have to discuss it with my team first how we are going to approach this, but if it comes to it ill make a pull request for it.

**Comment by rsuter** [comment]
So, you need an option to generate this?

	export enum WebcamImageOrientation
	{
		Default = 0, 
		Rotate90 = 1, 
		Rotate180 = 2, 
		Rotate270 = 3, 
	}

E.g. `EnumAsInteger`

**Comment by MaartenThomassen** [comment]
Yes, exactly.

I believe, if i understand the typescript documents correctly (we've only just begun using typescript in our project so its still a learning curve for us). if you omet the "=0, =1" etc, typescript will auto-generate the numbers for you in sequence starting with 0.

**Comment by rsuter** [comment]
Correct, but the numbers may not be in order so we should generate them...

**Comment by rsuter** [comment]
(ah, this is the wrong issue for discussing this)

**Comment by MaartenThomassen** [comment]
XD

**Comment by rsuter** [comment]
Btw: I just created the angular template draft im 1 hour...

**Comment by MaartenThomassen** [comment]
Yes i saw, very nice. As soon as we have defined the way we want to work with http-requests in aurelia, I will add a template for that aswell.

**Comment by rsuter** [comment]
Are you still interested in an Aurelia template?

**Comment by MaartenThomassen** [comment]
We're still using NSwag, but at the moment only for interface generation. I think you can close this issue for now. If we ever decide we are going to use automatic method generation I will create a PR with the template.

**Comment by rsuter** [comment]
What do you think? https://github.com/NJsonSchema/NJsonSchema/issues/119

**Comment by rsuter** [comment]
Btw. there is now a window.fetch template whose client can  be easily injected into aurelia view models... (im using it for an aurelia project right now). For me the aurelia scenario is covered.

Please create specific issues if required...

**Comment by rsuter** [comment]
Just FYI: Now Aurelia has its own template, uses the injected HttpClient: 

https://github.com/NSwag/NSwag/commit/5f89cd4149a2fa73f7cf2f3f31b9affa49cacb53
