### ISSUE TITLE
Newlines are not well supported in comments

### ISSUE THREAD

**Issue by AlainBolduc** [NSwag/NSwag#139]
When an operation has newlines in summary, the summary triple-slash is not generated:

given the swagger definition:

`
 "/v2/myapi/myoperation": {
      "get": {
        "tags": [
          "Operation"
        ],
        "summary": "Line 1 is OK\r\n Line1 is not",
`
the following will be generated:
`
/// <summary>Line 1 is OK
line 2 is not </summary>
`

and obviously gives compilation errors.

**Comment by rsuter** [comment]
Why did you close this?

**Comment by AlainBolduc** [comment]
When I edited  the comment, I somehow created a new issue ( #141 )  instead of editing this one.

**Comment by rsuter** [comment]
Ah, i wondered why i got the mail twice...
