### ISSUE TITLE
Typescript: Incorrect generation of enums

### ISSUE THREAD

**Issue by MaartenThomassen** [NSwag/NSwag#14]
Hello again,

When setting "DefaultEnumHandling" to "EnumHandling.String" in the WebApiToSwaggerGenerator, and then using the "SwaggerToTypeScriptGenerator" to generate typescript, enums are outputted incorrectly;

Example:

```
export enum WebcamImageOrientation
{
    Default = <any>"Default", 
    Rotate90 = <any>"Rotate90", 
    Rotate180 = <any>"Rotate180", 
    Rotate270 = <any>"Rotate270", 
}
```

Is outputted from the C# enum

```
enum WebcamImageOrientation
{
    Default
    Rotate90,
    Rotate180,
    Rotate270,
}
```

The typescript variant is not valid typescript (Generates TS1066 "Ambient enum elements can only have integer literal initializers.")

If i set the swagger spec to use numbers, the entire enum is gone and types being an enum type in C# result in being a number in Typescript. I do want to use the Typescript enum definitions (so not just use the number which represents the enum value).

I suggest changing generated enums to:

```
export enum WebcamImageOrientation
{
    Default, 
    Rotate90, 
    Rotate180, 
    Rotate270, 
}
```

**Comment by rsuter** [comment]
Your suggestion is not valid TypeScript and the <any> hack is just a workaround to have string enums in TypeScript. 

See https://github.com/Microsoft/TypeScript/issues/1206
And https://blog.rsuter.com/how-to-implement-an-enum-with-string-values-in-typescript/

**Comment by MaartenThomassen** [comment]
How is my solution not valid typescript for using numbers as enum values?

For some reason, Visual Studio 2015 throws errors for the current impelmentation, though it seems it is indeed value typescript.

**Comment by rsuter** [comment]
What version of TS are you using? (check your .csproj file)

**Comment by MaartenThomassen** [comment]
I'm using the latest version available, which is 1.6.3

**Comment by rsuter** [comment]
Strange, it works in my TS 1.6 project without compiler errors...

**Comment by MaartenThomassen** [comment]
That is indeed strange. I've also set NoImplicitAny to false, so it should work...

**Comment by rsuter** [comment]
Yes, me too

**Comment by MaartenThomassen** [comment]
Right well ill have a look if its something at my end though.

Nevertheless, it would be nice to have an option which would generate the enum values as numbers like here: https://basarat.gitbooks.io/typescript/content/docs/enums.html

**Comment by rsuter** [comment]
Isnt this what EnumHandling.Number does?

**Comment by MaartenThomassen** [comment]
EnumHandling.Number removes the enums altogether and makes enum properties a "number". Example:

```
export interface WebCamReference {
    Id: string;
    WebcamImageOrientation: WebcamImageOrientation;
}
```

becomes:

```
export interface WebCamReference {
    Id: string;
    WebcamImageOrientation: number;
}
```

and the ```export enum WebcamImageOrientation``` is gone.

**Comment by rsuter** [comment]
The Swagger specification uses JSON Schema to describe types and enums. As you can see here: 

http://json-schema.org/example2.html

...you cannot define a name and a value for an enum, just the allowed values. This is why it is only possible to generate int fields without enum typing or enum fields and string enums...

**Comment by rsuter** [comment]
The only way to solve this problem is to enhance the JSON Schema standard with additional data (e.g. a property `enumNames`).

**Comment by MJLHThomassen** [comment]
Well, thats a problem for us then, haha.

Any way around this? We could always fork your project and make our own adjustments, but then we'd have to maintain that aswell.

**Comment by MaartenThomassen** [comment]
Well, thats a problem for us then, haha.

Any way around this? We could always fork your project and make our own adjustments, but then we'd have to maintain that aswell.

**Comment by rsuter** [comment]
As i said, we could extend the JSON Schema so that integer enums with names can be defined... I have to think about it. As you said, you should not fork and this enum problem is a common problem and should be solved in some way...

**Comment by rsuter** [comment]
In general it's this problem: https://groups.google.com/forum/m/#!topic/json-schema/w_5mVYB7OHg
The last answer looks like a good idea to me... Then even the xml doc can be transferred/generated...

**Comment by rsuter** [comment]
Maybe we should use enumNames as proposed here: 
https://github.com/json-schema/json-schema/wiki/enumNames-(v5-proposal)

**Comment by rsuter** [comment]
And BTW: This is more a NJsonSchema issue than an NSwag issue: 
https://github.com/NJsonSchema/NJsonSchema

**Comment by MaartenThomassen** [comment]
Probably, thanks for looking in to this. I personally have no experience or knowledge about JSON schema so I trust your judgement on that. I just want the typescript generation to be in a specific way haha.

Anyway, your proposal abut using enumNames sounds good.

**Comment by rsuter** [comment]
Version v1.11 now supports generating string and integer enums, please try newest version

**Comment by MaartenThomassen** [comment]
Great thanks, I'll try it out tomorrow.

How should i be using this now?

**Comment by rsuter** [comment]
The difference is that the default is integer enum handling and this also generates an enum, but i still recommend string enums as reordering the values is not a breaking change..
