### ISSUE TITLE
When using SwaggerResponse attribute, return type is invalid

### ISSUE THREAD

**Issue by AlainBolduc** [NSwag/NSwag#140]
When using SwaggerResponse attribute, but not providing the return type, the Async methods return default(Task< T >) but should return default(T).

For example, if we use 

`[SwaggerResponse(HttpStatusCode.NotFound, "Something not found"]`
it will give the following swagger spec:

`"responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/MySchema"
            }
          },
          "404": {
            "description": "Something not found"
          }`

and nswag studio will generate the following (stripped down for simplicity):

 public async Task<MyDto> MyOperationAsync([...])
        {
        [...]    
            if (status_ == "200") 
            {
                var result_ = default(MyDto); 
               [...]
            }
            else        if (status_ == "404") 
            {
                **return default(Task< MyDto >)**;     
            }
[...]

which gives a compilation error, specifying that the method should return MyDto instead of Task< MyDto >

**Comment by rsuter** [comment]
Can you provide the full swagger spec which produces the wrong code?

**Comment by rsuter** [comment]
Fixed in v2.38
