### ISSUE TITLE
Newlines are not well supported in comments

### ISSUE THREAD

**Issue by AlainBolduc** [NSwag/NSwag#141]
When an operation has newlines in summary, the summary triple-slash is not generated:

given the swagger definition:

 "/v2/myapi/myoperation": {
      "get": {
        "tags": [
          "Operation"
        ],
        "summary": "Line 1 is OK\r\n Line2 is not",

the following will be generated:

/// < summary >Line 1 is OK
line 2 is not < /summary >

and obviously gives compilation errors.

**Comment by rsuter** [comment]
Fixed in v2.38
