### ISSUE TITLE
Doesn't Support FileStream

### ISSUE THREAD

**Issue by nandhu** [NSwag/NSwag#145]
Hi,
It doesn't support file parameter type for c# client. it creates custom types instead of that. Is there any workaround for this.

Thanks & Regards,
Nanda

**Comment by rsuter** [comment]
Can you post a sample (C# and expected Swagger/Client output)?

**Comment by nandhu** [comment]
**This is the sample operation. the first parameter type is 'File'**
`"/api/projects/upload": {
      "post": {
        "tags": [ "upload-composite-controller" ],
        "summary": "handleFileUpload",
        "description": "upload",
        "operationId": "handleFileUploadUsingPOST",
        "consumes": [ "multipart/form-data" ],
        "produces": [ "application/xml", "application/json" ],
        "parameters": [
          {
            "name": "filestream",
            "in": "formData",
            "description": "filestream",
            "required": true,
            "type": "**file**"
          },
          {
            "name": "projectId",
            "in": "formData",
            "description": "projectId",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": { "type": "string" }
          },
          "201": { "description": "Created" },
          "401": { "description": "Unauthorized" },
          "403": { "description": "Forbidden" },
          "404": { "description": "Not Found" }
        }
      }
    }
}`

The Generated C# Code is 

public Task<string> HandleFileUploadUsingPOSTAsync(**filestream** filestream, string projectId, string docId, string groupId, string authorization)
        {
            return HandleFileUploadUsingPOSTAsync(filestream, projectId, docId, groupId, authorization, CancellationToken.None);
        }

public async Task<string> HandleFileUploadUsingPOSTAsync(filestream filestream, string projectId, string docId, string groupId, string authorization, CancellationToken cancellationToken)
        {
            var url_ = string.Format("{0}/{1}?", BaseUrl, "api/projects/upload");
    
    
            var client_ = new HttpClient();
            PrepareRequest(ref client_, ref url_);
    
            client_.DefaultRequestHeaders.TryAddWithoutValidation("Authorization", authorization);
    
            var content_ = new MultipartFormDataContent();
            if (filestream == null)
                throw new ArgumentNullException("filestream");
            else
                content_.Add(new StringContent(filestream.ToString()), "filestream");
            if (projectId == null)
                throw new ArgumentNullException("projectId");
            else
                content_.Add(new StringContent(projectId.ToString()), "projectId");

            var response_ = await client_.PostAsync(url_, content_, cancellationToken).ConfigureAwait(false);
            ProcessResponse(client_, response_);
    
            var responseData_ = await response_.Content.ReadAsByteArrayAsync().ConfigureAwait(false); 
            var status_ = ((int)response_.StatusCode).ToString();
    
            if (status_ == "200") 
            {
                var result_ = default(string); 
                try
                {
                    if (responseData_.Length > 0)
                        result_ = JsonConvert.DeserializeObject<string>(Encoding.UTF8.GetString(responseData_));                                
                    return result_; 
                } 
                catch (Exception exception) 
                {
                    throw new SwaggerException("Could not deserialize the response body.", response_.StatusCode, responseData_, exception);
                }
            }
        }

 public partial class **filestream** : INotifyPropertyChanged
    {
    
        public event PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return JsonConvert.SerializeObject(this);
        }
        
        public static filestream FromJson(string data)
        {
            return JsonConvert.DeserializeObject<filestream>(data);
        }
        
        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

**Comment by rsuter** [comment]
Same as https://github.com/NSwag/NSwag/issues/19

**Comment by rsuter** [comment]
Fixed in v3.14, form data fully supported in c#
