### ISSUE TITLE
Downloads broken, Classes missing.

### ISSUE THREAD

**Issue by razer21** [NSwag/NSwag#15]
Hi,

no download link you`ve posted works. All i get as a response is {"message":"Specified cloud file not found."}..

When i try build from source its missing files : 
Error 1 Source file 'Commands\AssemblyTypeToSwaggerCommand.cs' could not be found.

**Comment by rsuter** [comment]
Should be working now... try again

**Comment by razer21** [comment]
Thank you, can build the solution now. Downloads work too.

Cheers,
Norman
