### ISSUE TITLE
AssemblyTypeToSwagger not available on command line

### ISSUE THREAD

**Issue by JannesMeyer** [NSwag/NSwag#152]
How would you use .net dlls as input on the command line? Is this currently not possible?

**Comment by rsuter** [comment]
The command exists but is not registered in the cmd line tool :-), will be added as "type2swagger". Ok? Next version today or tomorrow...

**Comment by JannesMeyer** [comment]
Awesome! Sounds great!

**Comment by rsuter** [comment]
I think I call it "types2swagger" because it supports multiple types... just type "nswag help" to list all commands and see the actual naming :) (as soon as its released)

**Comment by rsuter** [comment]
Its live now, v2.45
