### ISSUE TITLE
TypeScript client for jQuery-Promises uses both '$' and 'jQuery' to access jquery methods

### ISSUE THREAD

**Issue by smax48** [NSwag/NSwag#155]
For some reason, this client uses `$.ajax(...)` to load data, but `jQuery.parseJSON()` to parse the result.
Probably it should use only `jQuery` everywhere.

**Comment by rsuter** [comment]
Is there a difference between the two?

**Comment by smax48** [comment]
Both reference exactly the same object. But `$` sometimes clashes with other libraries, especially when you have a TypeScript project with global typings for jquery, karma & jasmine test frameworks. In this case I have to explicitly add a line (before generated TS client code): `import * as $ from 'jquery'` to override the global `$` symbol.
So it would be nicer to use just `jQuery` everywhere for consistency and less potential conflicts.

**Comment by rsuter** [comment]
Can you try again with the latest CI build? Once it has completed, you can download the installer/cmd line tools under "Artifacts": https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/299

**Comment by smax48** [comment]
Thanks! It works fine with that CI build!

**Comment by rsuter** [comment]
Ok, thanks for using the project. The changes will be released soon...
