### ISSUE TITLE
JsonProperty Required value incorrectly set in generated C#

### ISSUE THREAD

**Issue by retupmoc1** [NSwag/NSwag#163]
Just installed NSwag Studio v3.3, now getting "Required.Always" set in generated client code for bools, datetimes, enums, but not strings or byte[]. Did not occur in 2.46:
```
        [JsonProperty("BlockStart", Required = Required.Always)]
        public DateTime BlockStart
        {
            get { return _blockStart; }...
```

Model used in Web Api:
```
        [DataMember()]
        public virtual System.DateTime BlockStart
        {
            get
            {
                return _BlockStart;... 
```
"Required properties must be defined..." checkbox is checked in CSharp Client Settings.

**Comment by rsuter** [comment]
Yes, I had to change the nullability behavior to produce correct Swagger specs... Non-nullable properties are now always required (in JSON Schema everything is nullable by default) and thus `Required = Required.Always` is generated in C#... Is this really a problem for you?

**Comment by retupmoc1** [comment]
We had hoped to selectively mark properties using [Required] only for those actually required in the data store. 

We generate our model code. If we change our generator to use the Json attributes instead of Runtime.Serialization and mark non-required properties with Required.Default, would NSwag then generate client code that way? Or would it still generate these types as Required.Always?

BTW, Rico, we love this tool! Thanks a million for it and for your rapid response.

**Comment by rsuter** [comment]
The problem is the Swagger spec: It uses a simplified JSON Schema where you can only define if a property is nullable or not (in the real JSON Schema you have two flags: One for required and one for nullability). The problem is that I want to generate correct Swagger specs and thus only have the nullable flag... And because for example a DateTime is not nullable, it generates the JsonProperty like that... Can you provide a list of all scenarios and how they should behave?

**Comment by retupmoc1** [comment]
I understand your dilemma. While I'm considering "required" to mean logically required by functional specs, you're constrained by the standard and its interpretation of the non-nullable nature of a primitive making a value required by definition. I guess I don't know how you could satisfy both!

**Comment by rsuter** [comment]
Here is the point: 

- With the Swagger spec, you cannot define whether a property is required (i.e. it can be omitted in the JSON data) and thus the JsonPropertyAttribute.Required property cannot be generated correctly. The `required` attribute on the object specifies the not-nullable properties...
- With JSON Schema, you can define whether a property is required (`required` array on object) and whether it is nullable (via the `null` type)

**Comment by rsuter** [comment]
My suggestion: 

- We generate the [Required] attribute if the property type is nullable and the property must not be nullable
- For Swagger specs (not JSON Schema) to C# we always use `Required.Default` in the `JsonPropertyAttribute.Required`

Would this be ok?

**Comment by retupmoc1** [comment]
Sounds good, Rico, thanks for your response.

**Comment by rsuter** [comment]
Ok I think this implementation should be fine: 

    public string JsonPropertyRequired
    {
        get
        {
            if (_settings.RequiredPropertiesMustBeDefined && _property.IsRequired)
            {
                if (!_property.IsNullable(_settings.NullHandling))
                    return "Required.Always";
                else
                    return "Required.AllowNull";
            }
            else
            {
                if (!_property.IsNullable(_settings.NullHandling))
                    return "Required.DisallowNull";
                else
                    return "Required.Default";
            }
        }
    }

    public bool RenderRequiredAttribute
    {
        get
        {
            if (_property.IsNullable(_settings.NullHandling))
                return false;

            return _property.ActualPropertySchema.Type.HasFlag(JsonObjectType.Object) ||
                    _property.ActualPropertySchema.Type.HasFlag(JsonObjectType.String) ||
                    _property.ActualPropertySchema.Type.HasFlag(JsonObjectType.Array);
        }
    }

See http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Required.htm

What do you think?

**Comment by rsuter** [comment]
Btw: In Swagger spec, IsRequired and IsNullable are the same...

**Comment by retupmoc1** [comment]
Looks great. Thanks, Rico!

**Comment by rsuter** [comment]
V3.4 released
