### ISSUE TITLE
C# generator: missing using statement for Required attribute

### ISSUE THREAD

**Issue by jsmarsch** [NSwag/NSwag#169]
I Used NSwag Studio to generate C# pocos.  The output does not compile (I created a separate issue for each of the errors)

The generator marks required elements with the [Required] attribute, but it does not import the correct namespace, so they show up as compiler errors.

Need to have:
using System.ComponentModel.DataAnnotations;

I noticed that it does generate a using for System.ComponentModel, but that doesn't get the attribute, and resharper greys it out as "unused".

BTW:  I was targeting .Net 4.6.1

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/32e50c38a2165cb2d33519b172474baa6be097a2
Thanks for reporting the bug

**Comment by jsmarsch** [comment]
That was amazingly fast!  Thank you!

**Comment by rsuter** [comment]
everything fine now?

**Comment by jsmarsch** [comment]
Yes, it correctly generates the System.ComponentModel.DataAnnotations using clause.
