### ISSUE TITLE
Title and version is not set. If use "WebApiToSwaggerGenerator"

### ISSUE THREAD

**Issue by 7474** [NSwag/NSwag#176]
Titile and version of infoObject required, but it would have been generated by the empty when use the `WebApiToSwaggerGenerator`.

```
{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": ""
  },
...
```

Can set them?

Ex: To add properties to `WebApiToSwaggerGeneratorSettings`.

See: http://swagger.io/specification/#infoObject

**Comment by rsuter** [comment]
You can set them on the generated service object. How do you use NSwag? In C#?

**Comment by 7474** [comment]
Only it is set directly in the generated service object?

My project is ASP.NET 4(C#).
I am considering the two approaches.

1. [MSBuild] (https://github.com/NSwag/NSwag/wiki/MSBuild)
2. [OwinMiddleware] (https://github.com/NSwag/NSwag/wiki/OwinMiddleware) with Swagger UI

I want to use these simple approach if possible.

**Comment by rsuter** [comment]
The problem is, that title and version cannot be "", right?

**Comment by 7474** [comment]
Yes.
If these values are "", to validation errors in other programs.

If manually set the value, to succeed.

**Comment by rsuter** [comment]
Ok, I will set them to "n/a" and "1.0.0" by default. With the OWIN middleware you can add a service transformer to add custom texts.. (next version, in the next hours)

**Comment by 7474** [comment]
Thank you.
It is convenient to be able to post-processing.

**Comment by rsuter** [comment]
Ok see https://github.com/NSwag/NSwag/wiki/OwinMiddleware
Release in 15 mins

**Comment by rsuter** [comment]
Release v3.11
