### ISSUE TITLE
Support the PetShop-Example

### ISSUE THREAD

**Issue by wapolinar** [NSwag/NSwag#18]
Hi, I tried to use it to create a TypeScript client (from a swagger.json), but was not successful, then I tried the petshop example (http://petstore.swagger.io/v2/swagger.json), but this also did not work (even after removing the "tag" field which gives the first error).

It would be great, if more different swagger.json files would be supported, but for a start, it would be nice, if the "official" example swagger.json is supported.

**Comment by rsuter** [comment]
The current version 1.14 supports the PetStore... If your own Swagger file still has problem, please report another, more specific issue...
