### ISSUE TITLE
Customize OperationID member value

### ISSUE THREAD

**Issue by vdecristofaro** [NSwag/NSwag#181]
When generating the swagger file NSwag automatically create an `OperationID` attribute for each endpoint. Convention is `<nameOfController>_<nameOfMethod>`

Can this be customized?

**Comment by rsuter** [comment]
Currently not.. what is your preferred solution? A lambda/function to generate the id?

**Comment by vdecristofaro** [comment]
Probably there are 2/3 good solutions. In my case, where I am using the command line tools, the best method would be an attribute, NSwagMetadata, where the programmer can customize some strings. Something like

`[NSwagMetadata( "OperationId", ... )]`

Then at runtime, the attribute can be read by the tool to add customization. It should fallback to actual behaviour if no attribute is found.

**Comment by rsuter** [comment]
What about a `SwaggerOperationAttribute`?

**Comment by vdecristofaro** [comment]
Sounds good!

**Comment by rsuter** [comment]
Ok, will be added soon, I just have to add some unit tests..

**Comment by rsuter** [comment]
Added in v3.14: https://github.com/NSwag/NSwag/commit/bf832283ee8f9cbb8f9b1861b2ccec31cfd97a1d

Install NSwag.Annotations to use the attribute...

**Comment by vdecristofaro** [comment]
@rsuter: Great Job!
