### ISSUE TITLE
Add extensibility points for the Swagger definition generation process

### ISSUE THREAD

**Issue by davidkeaveny** [NSwag/NSwag#185]
Are there any plans to offer something similar to Swashbuckle's IOperationFilter? I am writing some custom attributes to help with the documentation, and would like to be able to inject the code to translate those attributes into the WebApiToSwaggerGenerator.

**Comment by rsuter** [comment]
Is this interface for transforming each operation ok? 

    /// <summary>Post processes a generated <see cref="SwaggerOperation"/>.</summary>
    public interface IOperationProcessor
    {
        /// <summary>Processes the specified method information.</summary>
        /// <param name="methodInfo">The method information.</param>
        /// <param name="path">The path.</param>
        /// <param name="method">The method.</param>
        /// <param name="operation">The operation to process.</param>
        /// <returns>true if the operation should be added to the Swagger specification.</returns>
        bool Process(MethodInfo methodInfo, string path, SwaggerOperationMethod method, SwaggerOperation operation);
    }

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/commit/4b3fe7ecc6ece8e1597b981994f7fadc8795d46f

**Comment by rsuter** [comment]
v3.16
