### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by prochnowc** [NSwag/NSwag#188]
NSwag does not understand .NET Core attributes for routes / response type.

Please add support for following attributes:

- [x] `RouteAttribute` on class level (former `RoutePrefixAttribute`)
- [x] `Http*Attribute` with route template arguments
- [x] `ProducesResponseTypeAttribute`

The following code has two problems:
- Swagger thinks multiple Get methods exist (which is not true because of different routes)
- Response types are not recognized

```
[Route("applications")]
public class ApplicationsController
{
  [HttpGet]
  [ProducesResponseType(typeof(IList<ApplicationModel>), 200)]
  public Task<IActionResult> Get() { ... }
 
  [HttpGet("{applicationName}"]
  [ProducesResponseType(typeof(ApplicationModel), 200)]
  public Task<IActionResult> Get(string applicationName) { ... }
}
```

**Comment by rsuter** [comment]
Thanks for creating the issue for this problem, will fix this soon..

**Comment by rsuter** [comment]
Will be fixed tomorrow

**Comment by prochnowc** [comment]
Still not working correctly. With the above code snippet and `DefaultUrlTemplate = "/{controller}/{id}"`
it produces wrong route `/Applications` for `public Task<IActionResult> Get() { ... }`. The route should be `/applications` because of RouteAttribute on class level.

**Comment by rsuter** [comment]
So if the class has a RouteAttribute then all each action method has the same route as defined in the RouteAttribute? Are you sure?

**Comment by prochnowc** [comment]
Yes, see this log:
`2016-07-05 15:01:18 [Information] Request starting HTTP/1.1 GET http://localhost:13899/Applications`
`2016-07-05 15:01:18 [Debug] Request successfully matched the route with name 'null' and template '"applications"'.`

**Comment by prochnowc** [comment]
Works like a charm now. Thanks.
