### ISSUE TITLE
How to add XML documentation to .NET Core Swagger?

### ISSUE THREAD

**Issue by prochnowc** [NSwag/NSwag#189]
I cannot figure out how to add my generated XML doc to the NSwag generation process. Is this supported?

**Comment by rsuter** [comment]
Yes, this is supported... How are you using NSwag (cmd line, NSwagStudio, Owin)?

**Comment by rsuter** [comment]
XML documentation is currently not supported for .NET Core because reading/writing XML files has changed for .NET Core... I have to check how to implement this feature for .NET Core

**Comment by prochnowc** [comment]
If you lead me to the right direction (current XML doc reader source) i could help implementing it.

**Comment by rsuter** [comment]
Its implemented in the NJsonSchema project which is PCL (so you wont have direct access to file/XML apis).. 

https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema/Infrastructure/XmlDocumentationExtensions.cs

**Comment by rsuter** [comment]
I think i already found a solution..

**Comment by rsuter** [comment]
Will be fixed tomorrow

**Comment by rsuter** [comment]
See https://github.com/NJsonSchema/NJsonSchema/wiki/XML-Documentation

**Comment by prochnowc** [comment]
Now it works - thank you.
