### ISSUE TITLE
XML Doc comments for POST is not displayed in help

### ISSUE THREAD

**Issue by prochnowc** [NSwag/NSwag#193]
Somehow my documentation of a POST method is not showing up in the UI.
Using ASP.NET Core..

```
        /// <summary>
        /// Appends events.
        /// </summary>
        /// <param name="events">List of events which should be appended.</param>
        /// <returns>HTTP Response code 201 with location header.</returns>
        [HttpPost]
        public IActionResult Post([FromBody] IList<EventModel> events)
```

XML docs file includes my docs .. but the Swagger UI shows nothing ...

![swagger_xmldoc](https://cloud.githubusercontent.com/assets/10866701/16587199/c5012a34-42c9-11e6-997c-ad32e4d87d20.png)

**Comment by rsuter** [comment]
Does it show up in the generated swagger spec?

**Comment by prochnowc** [comment]
No, it doesnt show up in the swagger spec.

**Comment by rsuter** [comment]
But other XML Docs are read? Have you manually installed the two packages described here? https://github.com/NJsonSchema/NJsonSchema/wiki/XML-Documentation

**Comment by rsuter** [comment]
This is a bug in the XML Doc reader...

The reader searches for 

M:NSwag.Demo.OwinCoreWeb.Controllers.PersonController.Post(System.Collections.Generic.IList`1[[NSwag.Demo.OwinCoreWeb.Controllers.EventModel, NSwag.Demo.OwinCoreWeb, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])

But the name is 

M:NSwag.Demo.OwinCoreWeb.Controllers.PersonController.Post(System.Collections.Generic.IList{NSwag.Demo.OwinCoreWeb.Controllers.EventModel})

In

    private static string GetXmlDocumentation(this MemberInfo member, XDocument xml)

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/124062f476ff80199045f62923d757a2519eec97

**Comment by rsuter** [comment]
Now working for me with v3.19

**Comment by prochnowc** [comment]
Docs for POST methods are now displayed correctly. Thanks!
