### ISSUE TITLE
T4 Generated Typescript only has Action Parameters not Return Types

### ISSUE THREAD

**Issue by Swellenator** [NSwag/NSwag#2]
Hi Again!

I have successfully generated the T4 Typescript. It looks good. Except that it only has the types for the parameters to the WebAPI Controller methods. The return types in the Typescript are all "(result: any) " but I have marked my controller methods with things like "[ResponseType(typeof(SyncDataResponse))]". Is it possible to get these as types as well?

Thanks!

**Comment by rsuter** [comment]
Can you post the Web API method (signature) code which is not working for you?

**Comment by rsuter** [comment]
If an operation can have multiple result types, then any is used to support the scenario... If you only define one result type... then this should fix the problem.

**Comment by Swellenator** [comment]
https://gist.github.com/Swellenator/4cad9759b96d222517e6

Yep I thought setting the ResponseType attribute would override anything. In fact, having snooped around in the NJsonSchema a bit it does pick up the type in the attribute. 

Note that we wanted to add a custom token to the header of the response so we use a custom response type to achieve this.

**Comment by rsuter** [comment]
This looks fine: Just one response type... Please try again with the latest release (some hours old)

**Comment by rsuter** [comment]
Ok, just tried this and I can now reproduce your problem...

**Comment by rsuter** [comment]
First problem: You use the ResponseTypeAttribute, but the generator uses ResultTypeAttribute...

**Comment by rsuter** [comment]
Ok, I'll rewrite the generator and use ResponseTypeAttribute... I'll create a new release...

**Comment by rsuter** [comment]
The newest release 0.15 works with 

    public class SyncDataRequest
    {
        public string Foo { get; set; }
    }

    public class SyncDataResponse
    {
       public string Bar { get; set; }
    }

    public class MyController : ApiController
    {

        [ResponseType(typeof(SyncDataResponse))]
        [HttpPost]
        public IHttpActionResult SyncData(SyncDataRequest syncRequest)
        {
            return new CustomOkResult<SyncDataResponse>(new SyncDataResponse(), this) { Token = "" };
        }
    }
    
    public class CustomOkResult<T> : OkNegotiatedContentResult<T>
    {
        public CustomOkResult(T content, ApiController controller)
            : base(content, controller)
        { }

        public CustomOkResult(T content, IContentNegotiator contentNegotiator, HttpRequestMessage request, IEnumerable<MediaTypeFormatter> formatters)
            : base(content, contentNegotiator, request, formatters)
        { }

        public string Token { get; set; }

        public override async Task<HttpResponseMessage> ExecuteAsync(CancellationToken cancellationToken)
        {
            HttpResponseMessage response = await base.ExecuteAsync(cancellationToken);
            response.Headers.Add("asdfasf", this.Token);
            return response;
        }
    }

Please try again...

**Comment by rsuter** [comment]
I've updated the documentation, 
https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator
you can now use the ResponseType attribute

**Comment by Swellenator** [comment]
You are a machine! It works well. Thanks.
