### ISSUE TITLE
Support Header Parameters

### ISSUE THREAD

**Issue by wapolinar** [NSwag/NSwag#20]
Hi, thanks a lot for your very fast reaction on the last issue!

After looking through the generated code, I think that you do not support header parameters, right? Maybe this would be a nice extension for the converter?

Additionally, if a parameter includes the "-" sign, it is taken as it is, which apparently is wrong in TypeScript. Imagine a parameter that is named "X-User" (which is common for header parameters), this will be translated to a variable named "X-User", which is an error in TypeScript. Maybe it should be converted to XUser (if no other parameter with that name exists) or something similar?

Again, this is more like an enhancement request that allows to support header parameters.

**Comment by rsuter** [comment]
There are a lot of possible scenarios how a RESTful service can be implemented and described... I currently use the tools in conjunction with the Web API generator (full chain) so there are less unexpected cases :-)...

**Comment by rsuter** [comment]
Can you provide a sample Swagger spec with the issues?

**Comment by wapolinar** [comment]
Sure:
```javascript
{
    "swagger": "2.0",
    "info": {
        "title": "Test API",
        "version": "1.0.0"
    },
    "host": "localhost",
    "basePath": "/",
    "tags": [
        {
            "name": "test"
        }
    ],
    "schemes": [
        "http"
    ],
    "paths": {
        "/addElement": {
            "put": {
                "tags": [
                    "test"
                ],
                "summary": "Add a new element",
                "description": "This method is for internal use by the front-end",
                "operationId": "addElement",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "X-My-Header",
                        "in": "header",
                        "description": "A header parameter",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "normal-parameter",
                        "in": "query",
                        "description": "A normal query parameter",
                        "required": false,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            }
        }
    },
"definitions" : { }
}
```

**Comment by rsuter** [comment]
Ok, this should be simple, but all templates have to be extended...

**Comment by rsuter** [comment]
Added in commit https://github.com/NSwag/NSwag/commit/d5e6d4159fa312a08295f18fbb98af91b678d4aa

Can you verify TS/C# output or write some unit tests for this?
