### ISSUE TITLE
NSwag.AspNetCore does not work for "ASP.NET Core Web Application (.NET Framework)"

### ISSUE THREAD

**Issue by thunder7553** [NSwag/NSwag#200]
When you use the Visual Studio project template "Visual C# / Web / ASp.NET Core Web Application (.NET Framework)", a ASP.NET Core application (project.json) targeting .NET 4.6 will be created. 

Enabling Swagger UI using NSwag does not work: 

NSwag.AspNet.Owin requires the IAppBuilder
while 
NSwag.AspNetCore depends on .NET Standard 1.6 (only)

If you try to install NSwag.AspNetCore, the package manager will produce following output:

```
    Package NSwag.AspNetCore 3.22.0 is not compatible with net46 (.NETFramework,Version=v4.6). Package NSwag.AspNetCore 3.22.0 supports: netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETFramework,Version=v4.6.
```

**Comment by rsuter** [comment]
Have you tried to add .NET Standard 1.6 as additional platform in your project.json and install "NSwag.AspNetCore"? Full .NET 4.6 projects should also support .NET Standard 1.6 libs

**Comment by thunder7553** [comment]
That does not seem to help. If I have this configuration:

```
  "frameworks": {
    "net46": {
      "dependencies": {
      }
    },
    "netstandard1.6": {
      "dependencies": {
        "NETStandard.Library": "1.6.0"
      }
    }
  },
```

Then I face two problems:
* the package manager complains that the .net 4.6 packages are not compatible with .net standard 1.6 (since .net standard seems to be a subset of 4.6)
* in the package manager, the "install" option is grayed out.

**Comment by rsuter** [comment]
But its an ASP.NET Core project?

**Comment by rsuter** [comment]
I'm not sure if net46 is already compatible, try net462...

**Comment by rsuter** [comment]
I think currently <= .NET 4.6.2 does not support netstandard 1.6, see https://docs.microsoft.com/en-us/dotnet/articles/standard/library

According to the table only 4.6.3 will support 1.6 but ASP.NET Core 1.0 requires 1.6...

**Comment by thunder7553** [comment]
I tried net463, net462 and net461, but it says that this does not work. So you think this is a problem with the visual studio template? (Visual Studio 2015 with latest updates). I was talking about the official Template in Visual Studio, which indeed does create an ASP.NET Core application based on .NET Framework. 

I do think that you are right - Microsoft is to blame. And the released the "tooling" as "preview" for a reason I guess :-)

Anyways, I managed to get it to work, although this looks like a Hack:

Add the nuget package "AspNet.Hosting.Katana.Extensions" (which in turn includes Microsoft.AspNetCore.Owin). This provides an extension method called "UseKatana".

``` C#
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler();
            }
            app.UseMvc();
            var swaggerUISettings = new NSwag.AspNet.Owin.SwaggerUiOwinSettings()
            {

            };
            app.UseKatana(cfg => NSwag.AspNet.Owin.SwaggerUiExtensions.UseSwaggerUi(cfg, typeof(Program).Assembly, swaggerUISettings));
        }
```

**Comment by thunder7553** [comment]
(this of course requires NSwag.AspNet.Owin).

As for "AspNetCore" requires .NET Standard 1.6 - that's not entirely true. if you take a look at the Microsoft.AspNetCore.* nuget packages, they depend on .NET 4.5.1 **OR** .NETStandard (ranging from 1.3 to 1.6 in different pacakges. Mostly 1.6 though)

**Comment by rsuter** [comment]
Maybe I can add .NET 4.5.1 as additional target to the NSwag.AspNetCore package...

**Comment by rsuter** [comment]
Try again with v3.22.1:

https://www.nuget.org/packages/NSwag.AspNetCore/3.22.1

**Comment by rsuter** [comment]
Can you confirm that the newest version works with .NET 4.5.1 and ASP.NET Core?

**Comment by thunder7553** [comment]
Yes, it does work 👍
