### ISSUE TITLE
Support OAuth Application flow in Swagger UI

### ISSUE THREAD

**Issue by rsuter** [NSwag/NSwag#207]
See: http://www.wmpratt.com/part-ii-swagger-and-asp-net-web-api-enabling-oauth2/
Working in branch: https://github.com/NSwag/NSwag/tree/OAuth2

**Comment by rsuter** [comment]
@prochnowz with latest (not released) Swagger UI, the button shows up. I further improved the builders and fixed a bug in an enum... Clone the project and check yourself, start the Demo.AspNet.Owin project: 

![image](https://cloud.githubusercontent.com/assets/2603405/16889118/7b52c050-4ae4-11e6-8573-512fdb8e94d7.png)

**Comment by rsuter** [comment]
With the current implementation (in dev branch: Owin only) you can set up oauth2 like this: 

            app.UseSwaggerUi(typeof(Startup).Assembly, new SwaggerUiOwinSettings
            {
                Title = "NSwag Sample API",
                OAuth2 = new OAuth2Settings
                {
                    ClientId = "foo",
                    ClientSecret = "bar",
                    AppName = "my_app",
                    Realm = "my_realm",
                    AdditionalQueryStringParameters =
                    {
                        { "foo", "bar" }
                    }
                },
                OperationProcessors =
                {
                    new OAuth2OperationSecurityAppender()
                },
                DocumentProcessors =
                {
                    new OAuth2SchemeAppender("auth", new SwaggerSecurityScheme
                    {
                        Description = "Foo",
                        Flow = "implicit",
                        AuthorizationUrl = "https://localhost:44333/core/connect/authorize",
                        TokenUrl = "https://localhost:44333/core/connect/token",
                        Scopes =
                        {
                            { "read", "Read access to protected resources" },
                            { "write", "Write access to protected resources" }
                        }
                    })
                }
            });

**Comment by rsuter** [comment]
Please try v3.26.1 for .net core...

**Comment by rsuter** [comment]
Usage: https://github.com/NSwag/NSwag/blob/master/src/NSwag.Demo.OwinWeb/App_Start/Startup.cs

**Comment by prochnowc** [comment]
Ok, this partly works now. Partly, because when i use 'Application' flow i want that the user enters the clientId and clientCredentials - i do not want to put credentials in index.html. Might it be possible to display clientId and clientSecret input boxes when they're null in index.html ? If not, i'll copy index.html and modify to my needs. But this might not apply to NSwag, i suppose it's missing in Swagger UI.

**Comment by rsuter** [comment]
Maybe you should first check this with the swagger UI guys: https://github.com/swagger-api/swagger-ui

If there is a simple way to modify the index.html then we can implement this in our NSwagStudio copy of swagger UI..

**Comment by rsuter** [comment]
Can you post a sample startup.cs so I can try your settings?

**Comment by rsuter** [comment]
Ok thanks, let's see what they propose...

**Comment by rsuter** [comment]
No answer yet, but how about you inject some JavaScript into the Swagger UI. It's not very nice integrated into the UI but this way you have something that works now : 

    OAuth2Client = new OAuth2Settings
    {
        ClientId = "' + prompt('Please enter ClientId: ') + '",
        ClientSecret = "' + prompt('Please enter ClientSecret: ') + '",
        AppName = "my_app",
        Realm = "my_realm",
        AdditionalQueryStringParameters =
        {
            { "foo", "bar" }
        }
    },

What do you think? Does this work?

**Comment by rsuter** [comment]
It works for me, updated docu: https://github.com/NSwag/NSwag/wiki/OwinMiddleware#ask-user-for-client-id-and-client-secret
