### ISSUE TITLE
.NET Core: FromQueryAttribute is not honored

### ISSUE THREAD

**Issue by prochnowc** [NSwag/NSwag#208]
i've controller that has action which has argument decorated with [FromQuery] attribute.
In the swagger ui i see "Parameter Type" -> "Body" which is not correct.

**Comment by rsuter** [comment]
FromQueryAttribute is the same as the FromUriAttribute?

**Comment by rsuter** [comment]
Added support in https://github.com/NSwag/NSwag/commit/cb59a9e4c5bd66455a1544a98abd8a39185260f4 and https://github.com/NSwag/NSwag/commit/09c00659e771c3947cd175653029cbd7ec8eba19

**Comment by rsuter** [comment]
Do you think this is enough for now?

**Comment by prochnowc** [comment]
Works. Thanks.
