### ISSUE TITLE
.NET Core: Exception in WebApiToSwaggerGenerator when action has more than one parameter

### ISSUE THREAD

**Issue by prochnowc** [NSwag/NSwag#209]
LoadParameters in WebApiToSwaggerGenerator.cs throws exception for controller actions which have multiple parameters (which is valid in AspNetCore).

Consider this Action-Method:
public Task<IActionResult> Get([FromQuery] Model model, CancellationToken cancellationToken)

there could be more arguments which are decorated with [FromServices]

see here: https://docs.asp.net/en/latest/mvc/models/model-binding.html

**Comment by rsuter** [comment]
Improved support https://github.com/NSwag/NSwag/commit/ab46164c8c4dfb418da0f71882dec65642998650

**Comment by rsuter** [comment]
Do you think this is enough for now?

**Comment by prochnowc** [comment]
Works, thanks.
