### ISSUE TITLE
Default value and C# 6.0 when generating proxy class

### ISSUE THREAD

**Issue by ThisNoName** [NSwag/NSwag#215]
I use what's described in this [Swagger Default Attribute] (http://stackoverflow.com/questions/28911023/default-model-example-in-swashbuckle-swagger) to generate default values, but that's just for convenience during test at UI level.  I don't want them when generating proxy classes.  Is there a command line switch to turn it off?

Also, is it possible to NOT use C# 6.0 syntax in the generated proxy?

Thanks.

**Tasks:**

- [x] Add GenerateDefaultValues setting
- [x] Add GenerateDefaultValues setting to cmd line and NSwagStudio UI (use `/GenerateDefaultValues=false`)

**Comment by rsuter** [comment]
Currently there is no way to disable these two features, but it should be simple to do so... 

Can you tell me where/which C# 6 features are used?

**Comment by rsuter** [comment]
Added GenerateDefaultValues: https://github.com/NJsonSchema/NJsonSchema/commit/81b76788afd5d45693379acfe1696cdf4cd4bbb0

**Comment by rsuter** [comment]
I think the only used C# 6 feature is the assignment of the default value - and if you disable this feature in the future you should be fine...

**Comment by rsuter** [comment]
Updated cmd line and UI: https://github.com/NSwag/NSwag/commit/63924a833e8574b69ed097c5a16bbd4b6c136823

**Comment by rsuter** [comment]
Please create a new issue if you still have problems with C# 6... (with sample output code)

**Comment by ThisNoName** [comment]
Works great!  Amazing how fast you updated everything everywhere!
