### ISSUE TITLE
Generating Swagger Specification of a WebAPI 2.2 service generates error about "Could not find value type of dictionary type 'System.Collections.Hashtable'"

### ISSUE THREAD

**Issue by dcjulian29** [NSwag/NSwag#220]
I've attempted to use both the Cake add-in, the command line, and the NSwagStudio.

When I select my Web API Assembly, I get the error: Could not find value type of dictionary type 'System.Collections.Hashtable' I've scanned my Web API projects and cannot find a usuage of a Hashtable in the code.

After I get the error message "Object reference not set to an instance of an object" twice in NSwagStudio, but not the Cake add-in or the command line....

**Comment by rsuter** [comment]
You can ignore the second exception as it occurs because the swagger spec could not be generated... The first exception occurred because you have a non-generic hashtable somewhere in the public API (i.e. in one of the web api controllers or a dto class). Can you locate it? Just replace it with Hashtable<T>...

**Comment by rsuter** [comment]
Use the NSwagStudio to find out which controller has the problem, the check if the controller classes exposes a "special" .NET Framework class (ie ActionResult). If we know the used class, we can implement a special treatment for it...

**Comment by rsuter** [comment]
Btw: ActionResult is handled correctly, it must be something like that...

**Comment by rsuter** [comment]
If possible, post a sample controller where this problem happens..

**Comment by rsuter** [comment]
Added support for non-generic dictionary (e.g. Hashtable): https://github.com/NJsonSchema/NJsonSchema/commit/cce3f6998650cdc80ff2109382f93708f6638979

(generates Dictionary<string, object>)

**Comment by dcjulian29** [comment]
Sorry it took so long to get back to you on this... I just downloaded the latest version of NSwagStudio and ran it against the code... The original exception is gone and the second has been replaced with the "No Specification" message. But, now I am getting a different exception... "The JSON property 'ItemOf' is defined multiple times on type 'System.Xml.XmlAttributeCollection'. 

The class that is generating this...
```
public class QuestionController : ApiController
{
    private IRepository<QuestionTemplate, int> _templateRepository;

    public QuestionController(IRepository<QuestionTemplate, int> templateRepository)
    {
        _templateRepository = templateRepository;
    }

    public QuestionController()
    {
    }

    [ValidAccessTokenRequired]
    public HttpResponseMessage Get(int id)
    {
        using (var repository = _templateRepository ?? new QuestionRepository())
        {
            var entity = repository.FindById(id);

            if (entity == null)
            {
                return new HttpResponseMessage(HttpStatusCode.NotFound);
            }

            return new HttpResponseMessage
            {
                Content = new StringContent(entity.Template.OuterXml, Encoding.UTF8, "application/xml")
            };
        }
    }

    [SuperUserRequired]
    public IHttpActionResult Post([FromBody]XmlDocument xmlDocument)
    {
        var entity = new QuestionTemplate(xmlDocument.OuterXml);

        using (var repository = _templateRepository ?? new QuestionRepository())
        {
            repository.Save(entity);
        }

        var location = Url.Link(
            "DefaultApi",
            new
            {
                id = entity.Id.ToString()
            });

        return Created(location, entity);
    }

    [SuperUserRequired]
    public IHttpActionResult Post(string xmlContent)
    {
        var xml = new XmlDocument();

        try
        {
            xml.LoadXml(xmlContent);
        }
        catch (Exception)
        {
            return BadRequest();
        }

        return Post(xml);
    }
}
```

I can create a new issue if you want and we can work from there...

**Comment by rsuter** [comment]
The problem is, that XmlDocument is not supported... what JSON do you expect here?

**Comment by dcjulian29** [comment]
Unfortunately, the requirement of the web service is to return/accept XML to/from the client instead of JSON... so I'm not really sure what the appropriate output would be in this case...

**Comment by rsuter** [comment]
Currently XML schemas are not supported... but for now I think we should treat XmlDocument as string...

**Comment by rsuter** [comment]
Can you create a new issue for that?

**Comment by dcjulian29** [comment]
@rsuter sure...
