### ISSUE TITLE
swagger2tsclient: parameters not parsed

### ISSUE THREAD

**Issue by paxos** [NSwag/NSwag#223]
I see the following exception:

```
---> (Inner Exception #0) Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[NSwag.SwaggerParameter]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
```

It seems to be a problem when using the parameters definition object, as it has the same name as the path item object:

http://swagger.io/specification/#parametersDefinitionsObject

Example JSON:
https://dl.dropboxusercontent.com/u/6239/Keep/swagger.json

**Comment by rsuter** [comment]
Parameter refs are currently not supported, but ill see how we can implement a more generic ref handling..

**Comment by rsuter** [comment]
... for now you have to preprocess the swagger spec and inline those param refs..

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/9cc992c88492e269430cb6753eeee36c12dfdb12

**Comment by rsuter** [comment]
Try v4.2... you should use MultipleClientsFromPathSegments as OperationGenerationMode because the operation IDs are missing in your Swagger spec...

**Comment by rsuter** [comment]
Please report if everything works fine with this update...
