### ISSUE TITLE
Parameters behavior changed in version 4.0

### ISSUE THREAD

**Issue by AlainBolduc** [NSwag/NSwag#225]
Looking at code generated with v3, a null parameter behavior would be handled like this:

```
 if (parameter != null)
                url_ += string.Format("areaCode={0}&", Uri.EscapeUriString(parameter .ToString()));

```
which would eventually produce a url like:

`http://localhost/api/GetSomething`

now with v4, a null parameter is handled like this:

`            url_ += string.Format("parameter={0}&", Uri.EscapeUriString(parameter!= null ? parameter.ToString() : "null"));`

which produces an url like:

`http://localhost/api/GetSomething?parameter=null
`
How am I supposed to handle this change if I have no control over the server API?

**Comment by rsuter** [comment]
Can you post the corresponding swagger operation?

**Comment by rsuter** [comment]
I think the parameter is required and thus it must always be in the query... Try setting the parameter to not required in the swagger spec...

**Comment by AlainBolduc** [comment]
No, the parameters are not required. 

Unfortunately I cannot publicly post the URL or operation definition. However will send you the definition at mail@rsuter.com , as found in your profile. is this OK for you?

Thank you for your support!

**Comment by rsuter** [comment]
Ok thats fine.. but i think we have to change the generator again..

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/d13a33fb9a752d1346be916efe4dd162ec12787a

**Comment by AlainBolduc** [comment]
Looks good, thanks!

**Comment by rsuter** [comment]
Release v4.1
