### ISSUE TITLE
MSBuild, how to get all references in project

### ISSUE THREAD

**Issue by pkupilas** [NSwag/NSwag#228]
Is there any variable or property which i could use in msbuild command to get all referencies in project?

`NSwag.exe webapi2swagger /assembly:@(GimmeAllReferencies?) /controller:Namespace.MyController /output:SwaggerFiles/MyControllerSwagger.json`

**Comment by rsuter** [comment]
You are using NSwag in your .csproj file and want to load all assemblies from the solution? I don't know if there is a built-in function in MSBuild for that... you should google it or ask on StackOverflow.

**Comment by pkupilas** [comment]
Thank you for your answer. I will keep looking then.

**Comment by rsuter** [comment]
The other option is to add support for wildcars in the `/assembly:bin/*.dll` parameter...

**Comment by rsuter** [comment]
Added support for wildcards: https://github.com/NSwag/NSwag/commit/45a990e7c63136573d45cc5e99e808a5b894b2cc

**Comment by rsuter** [comment]
NSwag v5 has been released, please check if your problem is solved and reopen the issue if it still remains...
