### ISSUE TITLE
NSwagStudio exe: Error on Web API Assembly load

### ISSUE THREAD

**Issue by crgeee** [NSwag/NSwag#23]
I'm trying to load a WebAPI project DLL in NSwagStudio and keep receiving this error:

Could not load file or assembly 'System.Web.Http', Version=4.0.0.0...or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

I am running Swashbuckle which is a fork of Swagger - not sure if this is supported. It appears to have some reliance on System.Web.Http version 4.0.0.0 but the binding redirects in web.config redirect it to 5.2.3.

I attempted to resolve by:
- Reinstalling Microsoft.AspNet.WebApi via nuget (running version WebAPI 5.2.3)
- Checking web.config
- Checking packages.config
- Fiddling with assembly references in web.config

Any idea as to how to get past this issue? The solution builds and runs in VS2013 without errors or warnings so I'm not sure why the mismatch is occurring. 

Thanks

**Comment by rsuter** [comment]
Can you attach the output (i.e. Dlls, etc.) of a sample project?

Why did you close the issue?

**Comment by crgeee** [comment]
[Swashbuckle-master.zip](https://github.com/NSwag/NSwag/files/80094/Swashbuckle-master.zip)

Attached is a sample web app from Swashbuckle (https://github.com/domaindrivendev/Swashbuckle). The WebAPI controllers are under Swashbuckle.Dummy.Core DLL.

**Comment by rsuter** [comment]
I can't even select the DLL so that the controllers are shown... 

Exception thrown: 'System.TypeLoadException' in mscorlib.dll

Additional information: Method 'Apply' in type 'Swashbuckle.Dummy.SwaggerExtensions.AddDefaultResponse' from assembly 'Swashbuckle.Dummy.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Have you tried to download the NSwag sources and start the NSwagStudio with debugger, so that you have more detailed exception info?

**Comment by rsuter** [comment]
Can you postbyour binding redirects in your web.config?

**Comment by crgeee** [comment]
I haven't tried the NSwag sources and debugger method. Below are the full binding redirects:

      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="WebGrease" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-1.5.2.14234" newVersion="1.5.2.14234" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="EntityFramework" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http.WebHost" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>

**Comment by rsuter** [comment]
Ok, now the app uses the app.config/web.config from the DLL directory... Please try again with v1.19
