### ISSUE TITLE
Support for HttpPatchAttribute

### ISSUE THREAD

**Issue by cryovat** [NSwag/NSwag#230]
Hi, thanks for your work on this project! :smiley: 

NSwag currently ignores `[HttpPatch]` attributes on controller methods, and incorrectly generates a Swagger document where these are designated as using the POST verb.

Seeing  this behavior with NSwag.AspNetCore 4.2.0 and NSwag.CodeGeneration v.4.3.6065.35519.

**Comment by rsuter** [comment]
Fixed: https://github.com/NSwag/NSwag/commit/88517082a4e154d3e781b979ab0b8114dc955b5c

**Comment by cryovat** [comment]
Thank you for the (amazingly) quick resolution!
