### ISSUE TITLE
Provide better support to json schema generation

### ISSUE THREAD

**Issue by vdecristofaro** [NSwag/NSwag#231]
In the same direction of #181 I am going here to ask a bunch of improvements that can be done in order to give the developer better control over schema generation.

- When the signature of the API use a generic data structure (e.g. `HttpResponseMessage`) it would be good to decorate the method signature with an attribute that can drive the schema generation by giving more informations to NSwag. An example of this is the Swashbuckle library which let you decorate a method with the following attribute
> [SwaggerResponse( HttpStatusCode.OK, Type = typeof( BaseServiceResult ) )]
> [SwaggerResponse( HttpStatusCode.NotFound, Type = typeof( BaseServiceResult ) )]
> [SwaggerResponse( HttpStatusCode.BadRequest, Type = typeof( BaseServiceResult ) )]

- One improvement, regarding previous point would to add also a description parameter and a tag/list of tags parameter to also fill the tags and description node of the path item  and the response

- Provide a way to have control, maybe at the controller level, of the section info of the swagger specification by using a title and version of the API itself. Example:
```
"info": {
    "title": "Web API Swagger specification",
    "version": "1.0.0"
  },
```

Thanks

**Comment by rsuter** [comment]
1. Use the `ResponseTypeAttribute` (same functionality as SwaggerResponse): See https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator#specify-the-response-type-of-an-action
2. You can use the DescriptionAttribute and SwaggerTagsAttribute for that: See https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator#supported-aspnet-web-api-attributes and https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator#supported-swagger-attributes
3. You can post process the generated Swagger spec: See https://github.com/NSwag/NSwag/wiki/OwinMiddleware#post-process-the-served-swagger-specification

**Comment by vdecristofaro** [comment]
Great!

**Comment by vdecristofaro** [comment]
Sorry, one more question.
How can I postprocess the generated swagger if I am only using the command line version?
Do you have any working sample?

Thanks

**Comment by rsuter** [comment]
What do you want to postprocess/change?

**Comment by vdecristofaro** [comment]
The info section. I thought this was best done by using an attribute at the controller level.

**Comment by rsuter** [comment]
At the controller level is not suitable because a Swagger spec may contain multiple controllers... I think I'll add optional cmd line arguments...

**Comment by vdecristofaro** [comment]
Hi @rsuter,
any update about the proposed solution?

**Comment by rsuter** [comment]
There are cmd line arguments for the description and version.. just run the help command..
