### ISSUE TITLE
MSBuild, adding comments from xml

### ISSUE THREAD

**Issue by pkupilas** [NSwag/NSwag#233]
Is it a way to add comments from .cs file (which are saved in .xml file) to output .json which is generating in MSBuild?

**Comment by rsuter** [comment]
Sorry I dont understand your question. 

If you generate xml doc output files, then they should be picked up by the generator...

**Comment by pkupilas** [comment]
So when i use NSwag in MSBuild it should already include the comments in .cs to json?

**Comment by rsuter** [comment]
Yes, but you have to enable xml doc generation in your cs project and the xml must have the same name as the assemblies (default).

**Comment by rsuter** [comment]
See https://github.com/NJsonSchema/NJsonSchema/wiki/XML-Documentation

**Comment by pkupilas** [comment]
But if i use few assemblies to generate it:
`"$(NSwagExe) webapi2swagger /assembly:../Dir1/MyWebAssembly1.dll , ../../Dir2/MyWebAssembly2.dll /controller:MyNamespace.MyController /output:swagger.json"`
It should have same name as the last one or there is another way to do it?

**Comment by rsuter** [comment]
Each dll has its own xml, you have to enable xml output for every proj

**Comment by pkupilas** [comment]
Unfortunately, for every project which i use to generate dll, field with xml documentation file is enabled and it's still not working.

**Comment by rsuter** [comment]
Check your project output directory. Are the xml files generated for each project/assembly?

**Comment by pkupilas** [comment]
Yep, i've checked. All files are generated.

**Comment by rsuter** [comment]
they must be in the same directory as the assembly with the same name but .xml as extension

**Comment by pkupilas** [comment]
The problem disappeared when i changed property copy local of referenced projects to true. I doubt that is good solution but it works for now..

**Comment by rsuter** [comment]
Yes, if the XML files are in the same directory as the corresponding assembly, the comments are loaded... Can we close this issue?

**Comment by pkupilas** [comment]
The better solution is to use _/referencepath: C:\path\to\the\solution_ (to avoid copying dlls)
Example:
`NSwag webapi2swagger /assembly:C:\absolute\path\to\the\assembly\MyWebAssembly1.dll /referencepath: C:\path\to\the\solution /controller:MyNamespace.MyController /output:swagger.json`
If you work with visual you can replace _C:\absolute\path\to\the\assembly\MyWebAssembly1.dll_ with variable $(TargetPath).
In my case i didn't need to provide any other dependent assemblies in _/assembly_ parameter, _/referencepath_ make it work.
We can close this issue : )

**Comment by rsuter** [comment]
Is it also working with v5?
