### ISSUE TITLE
[NSwagStudio - TypeScript/Angular2 & C#] Generated Code has Generic Type error

### ISSUE THREAD

**Issue by darius-iko** [NSwag/NSwag#234]
Hi, there is an issue with the generated code which contains generic type. Below is the screenshot for generated TypeScript/Angular2 code:

![image](https://cloud.githubusercontent.com/assets/8023913/17647742/862de108-6231-11e6-9123-b4145108cdad.png)

Note that generated C# code also has the same error with generic type.

**Comment by rsuter** [comment]
Generics are currently not supported. But we should transform this into an allowed name. For now, see https://github.com/NSwag/NSwag/issues/83

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/79c36913d8c0955178fd2c8e4f5d9f6b537e29ed

**Comment by rsuter** [comment]
NSwag v5 has been released, please check if your problem is solved and reopen the issue if it still remains...

**Comment by darius-iko** [comment]
Thank you.
