### ISSUE TITLE
Encoding.GetString calls in Portable Class Library projects

### ISSUE THREAD

**Issue by mki0** [NSwag/NSwag#236]
The C# code generated calls the Encoding.UTF8.GetString() with just the byte[] parameter, but for Portable Class Library projects, there is only the call with the bytes, index and count. Would it be possible to put this behavior in by default?

Example of code currently generated:
`result_ = JsonConvert.DeserializeObject<OrderResponse>(Encoding.UTF8.GetString(responseData_));`

Example of code that will should on any project type:
`result_ = JsonConvert.DeserializeObject<OrderResponse>(Encoding.UTF8.GetString(responseData_, 0, responseData_.Length));`

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/10ef3baa3ed1e05810e4af7070489f15503dbd24
