### ISSUE TITLE
Fields vs Properties

### ISSUE THREAD

**Issue by michaelaird** [NSwag/NSwag#237]
It seems like public fields in "dtos" aren't getting picked up. Is that intentional? or due to how it gets generated by swagger?

**Comment by rsuter** [comment]
This is intentional, as exposing a field in a public api is bad practice... However it would be possible to implement this...

**Comment by michaelaird** [comment]
Our DTOs are as plain as we can get them. Just a set of fields with no methods or constructor. We use Automapper to populate them. 

Without starting a "holy war", why do you think a field is bad practice in this scenario?

(BTW: just started playing around with NSwag and I am blown away! Great work! )

**Comment by rsuter** [comment]
See http://programmers.stackexchange.com/questions/161303/is-it-bad-practice-to-use-public-fields

However the JSON Schema generator should behave according to the Json.NET serializer. I think this serializer also accepts public fields and thus we should also support public fields... 

But currently I have other open issues im working on which are more important to me...

**Comment by michaelaird** [comment]
I buy those arguments on the .net side but for DTOs (that should be logical-less) I don't think it's as important to future-proof the API with getters/setters. Also, as a counter example, if someone were to write logic in the getter/setter on the C# side that logic won't get translated into the "client" representation of the DTO and could cause some confusing side effects.

I'd be willing to take a crack at implementing this. Should it be here or in NJsonSchema?

**Comment by rsuter** [comment]
I just implemented this feature: https://github.com/NJsonSchema/NJsonSchema/commit/1fc06ea811d9f6041865655a1a907a3808660f74

**Comment by rsuter** [comment]
... but to use it, you have to wait for the next release. I'm currently working on some bigger changes (refactorings and more extension points)

**Comment by rsuter** [comment]
NSwag v5 has been released, please check if your problem is solved and reopen the issue if it still remains...
