### ISSUE TITLE
[Typescript] Support Typescript Namespaces

### ISSUE THREAD

**Issue by michaelaird** [NSwag/NSwag#238]
How about supporting namespaces as well as modules?

https://www.typescriptlang.org/docs/handbook/namespaces.html

**Comment by rsuter** [comment]
How should this be implemented? An additional setting where you can set a namespace and all generated classes are in this namespace?

**Comment by michaelaird** [comment]
I think it works exactly like module name, it's just a syntax thing:

```typescript
namespace MyName.Space.Script
{
export class X
{}
}
```

vs 

```typescript
module MyName.Space.Script
{
export class X
{}
}
```

Maybe with a boolean flag to choose between namespace and module?

We use the namespace approach to allow us to compile all our typescript files together into a single JS file.

**Comment by rsuter** [comment]
and what if both - the namespace and module - is set?

**Comment by michaelaird** [comment]
Sorry. I mean one setting for the name and a flag to choose between
module/namespace.

**Comment by rsuter** [comment]
Isn't it allowed to have a namespace in a module?

**Comment by michaelaird** [comment]
No. Typescript namespaces are what used to be called "internal modules". https://www.typescriptlang.org/docs/handbook/namespaces.html

**Comment by rsuter** [comment]
Ah ok, then this should be a easy thing to do..

**Comment by michaelaird** [comment]
Thanks! I will have a look soon.
