### ISSUE TITLE
NSwagStudio exe: Error on Web API Assembly load

### ISSUE THREAD

**Issue by crgeee** [NSwag/NSwag#24]
I'm trying to load a WebAPI project DLL and keep receiving this error:

Could not load file or assembly 'System.Web.Http', Version=4.0.0.0...or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

I attempted to resolve by:
- Reinstalling Microsoft.AspNet.WebApi via nuget (running version WebAPI 5.2.3)
- Checking web.config
- Checking packages.config

Still seeing the same issue. Any idea as to how to get past this issue? The solution builds and runs perfectly so I'm not sure why the mismatch is occurring. 

Thanks,
Chris

**Comment by rsuter** [comment]
Can you attach the output (i.e. Dlls, etc.) of a sample project?

Why did you close the issue?

**Comment by crgeee** [comment]
I was on WiFi that cut out and submitted the issue twice. I'll add a sample
to open issue #23.
