### ISSUE TITLE
[Typescript] Prefer const/let over var

### ISSUE THREAD

**Issue by michaelaird** [NSwag/NSwag#240]
It's a better practice to use const/let instead of var. unless NSwag needs to target TypeScript < 1.5.

**Comment by rsuter** [comment]
Good idea.

**Comment by michaelaird** [comment]
I'm keen to try to help with some of these refactorings of the TypeScript templates. What's the best way to chat about them? Gitter?

**Comment by rsuter** [comment]
The best location is here as comment or edit the issue text...

**Comment by rsuter** [comment]
I think we should ignore old ts versions for now...

**Comment by michaelaird** [comment]
Should it be a goal for the generated TypeScript to pass TSLint?

**Comment by rsuter** [comment]
Why not? Are there many issues?

**Comment by michaelaird** [comment]
To be honest, I haven't run it on output yet. I'm planning to spend a bit of time on this tonight and I'll let you know what I find.

**Comment by michaelaird** [comment]
Here's a first crack 2d68fa89532bbf904a62ad8da60e524c80d200f4
