### ISSUE TITLE
[NSwag, MSBuild] Custom AppBase

### ISSUE THREAD

**Issue by pkupilas** [NSwag/NSwag#242]
Is there a posibility to add support to change the default directory root in AssemblyLoader?
For example:
`NSwag.exe webapi2swagger /assembly: MyAssembly.dll /controller:MyController /output:MyControllerSwagger.json /customappbase:C:\dir\startlookinghere`

**Comment by rsuter** [comment]
Yes, its possible to add this feature... What exactly is the usage scenario?

**Comment by rsuter** [comment]
So you want to define a custom ApplicationBase: 

![image](https://cloud.githubusercontent.com/assets/2603405/17775425/79192764-6558-11e6-8fa8-2811a24f1922.png)

Currently its always `Path.GetDirectoryName(Path.GetFullPath(Settings.AssemblyPath))`

**Comment by pkupilas** [comment]
Well, in my case i need to run NSwag with a few assemblies which are placed in a different directories in solution.
Even if i pass whole paths to the assemblies (example:)
`NSwag.exe webapi2swagger /assembly: C:\gitrepo\solution\dir\dirtoassembly1\MyAssembly1.dll,C:\gitrepo\solution\dir\dirtoassembly2\MyAssembly2.dll,C:\gitrepo\solution\dir2\MyAssembly3.dll /controller:MyController /output:MyControllerSwagger.json`
the appbase path is strictly set to _C:\gitrepo\solution\dir\dirtoassembly1_.
I changed variable rootDirectory in GetAllDirectories function by adding "\\..\\.." to force it start looking from C:\gitrepo\solution. All what would be nice to have is a parameter or something to change it from exe command (example: /rootDirectory:C:\gitrepo\solution) : )

**Comment by rsuter** [comment]
Have you also tried to add your DLL paths as "ReferencePaths"?

https://github.com/NSwag/NSwag/blob/master/src/NSwag/Commands/WebApiToSwaggerCommand.cs#L48

**Comment by pkupilas** [comment]
Well, i've tried as follows:
`NSwag.exe webapi2swagger /assembly: C:\gitrepo\solution\dir\dirtoassembly1\MyAssembly1.dll,C:\gitrepo\solution\dir\dirtoassembly2\MyAssembly2.dll,C:\gitrepo\solution\dir2\MyAssembly3.dll /referencepaths:C:\gitrepo\solution\dir\dirtoassembly1,C:\gitrepo\solution\dir\dirtoassembly2,C:\gitrepo\solution\dir2 /controller:MyController /output:MyControllerSwagger.json`
and it didn't work.
So now when you reminded me about this parameter i tried again simply use it like:
`NSwag.exe webapi2swagger /assembly: C:\gitrepo\solution\dir\dirtoassembly1\MyAssembly1.dll,C:\gitrepo\solution\dir\dirtoassembly2\MyAssembly2.dll,C:\gitrepo\solution\dir2\MyAssembly3.dll /referencepaths:C:\gitrepo\solution /controller:MyController /output:MyControllerSwagger.json`
and it's working (for now at least, i need to test it closely) without messing up with the code (changing rootDirectory in GetAllDirectories).
So yeah, thank you : )

**Comment by rsuter** [comment]
And if you have some assembly loading problems (ie missnig binding redirects) you should wait until the next version and try with this... In v5 the assembly loader is improved...

**Comment by rsuter** [comment]
Maybe we should create a wiki page describing all these DLL/assembly parameters and how to use them in some scenarios... (ie multiple directories, .net core, etc.)

**Comment by pkupilas** [comment]
It would be very helpfull : )

**Comment by rsuter** [comment]
Is it also working with v5?

**Comment by rsuter** [comment]
The application base is now set to the first assembly directory, each assembly directory is now added automatically to the reference paths... you don't need to manually add them to the reference paths.

https://github.com/NSwag/NSwag/commit/1e6726be437621a249cf4fe4aef4f081e872e57f

**Comment by rsuter** [comment]
Added new issue: https://github.com/NSwag/NSwag/issues/256
Can we close this one?

**Comment by pkupilas** [comment]
It's working on v5. We can close.

**Comment by pkupilas** [comment]
I think the problem is still here. I checked with the newest version and without adding /referencepaths it acts strange. In Visual for one project in the solution works fine and for the other is not. What's more it doesn't work when I use exe command in cmd or powershell.
Maybe i do something wrong but with /referencepaths it works everywhere.
