### ISSUE TITLE
[NSwagStudio] Sort controller names

### ISSUE THREAD

**Issue by michaelaird** [NSwag/NSwag#245]
Controller names should be sorted, ideally by name, ascending.

**Comment by rsuter** [comment]
In the list of the UI?

**Comment by michaelaird** [comment]
Yes. 

![image](https://cloud.githubusercontent.com/assets/219113/17788640/ae698c66-655c-11e6-95a1-0f2751dbcd90.png)

**Comment by rsuter** [comment]
Fixed: https://github.com/NSwag/NSwag/commit/78b4f3c91d9b42635b915e83c6afae3d1432ac1e

**Comment by rsuter** [comment]
Released tomortow
