### ISSUE TITLE
onSuccess is not called, when a web service returns nothing (void) - TypeScript

### ISSUE THREAD

**Issue by wapolinar** [NSwag/NSwag#25]
When a web service does not return any object, the onSuccess method is not called in the process* methods.
Example (this is the code that is currently generated):
````javascript
    private processRemoveElement(xhr: any, onSuccess?: any, onFail?: any) {
        var data = xhr.responseText; 
        var status = xhr.status.toString(); 

        {
            var result: any = null; 
            try { 
                result = <any>jQuery.parseJSON(data);
            } catch(e) { 
                if (onFail !== undefined)
                    onFail(null, "error_parsing", e);
                return;
            }
            if (onFail !== undefined)
                onFail(result, "error_exception");
        }
    }
````
Instead, the generated code could look like follows (note that these *void* methods might return the http status code **204** instead of 200):
````javascript
    private processRemoveElement(xhr: any, onSuccess?: any, onFail?: any) {
        var data = xhr.responseText; 
        var status = xhr.status.toString(); 

         if (status === "200" || status === "204") {
             if (onSuccess !== undefined)
             {
                 onSuccess();
             }
            return;
        }
    }
````
Alternatively, the onSuccess method could use the status code as parameter. Additionally, the onFail method should be called if the status is not 2XX.

An example JSON file looks like this:
````
{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Test API"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "tags": [
        {
            "name": "api"
        }
    ],
    "schemes": [
        "http"
    ],
    "paths": {
        "/removeElement": {
            "delete": {
                "tags": [
                    "api"
                ],
                "summary": "Removes an element",
                "description": "Removes an element",
                "operationId": "removeElement",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "X-User",
                        "in": "header",
                        "description": "User identifier",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "elementId",
                        "in": "query",
                        "description": "The id of an existing element that should be removed",
                        "required": true,
                        "type": "integer",
                        "format": "int64"
                    }
                ],
                "responses": {
                    "default": {
                        "description": "successful operation"
                    }
                }
            }
        }
    },
    "definitions" : { }
}
````
Edit: Added **"definitions": { }** to the example JSON file. This is necessary for NSwag.

**Comment by rsuter** [comment]
As you can see in the [Swagger spec](http://swagger.io/specification/), the "default" response is usually used for error handling: 

```
{
  "200": {
    "description": "a pet to be returned",
    "schema": {
      "$ref": "#/definitions/Pet"
    }
  },
  "default": {
    "description": "Unexpected error",
    "schema": {
      "$ref": "#/definitions/ErrorModel"
    }
  }
}
```
There is no easy way to determine if a response is a success or failure... (currently only HTTP 2xx are success)

**Comment by rsuter** [comment]
Maybe we define the "default" response as success if no other success response is available...

**Comment by wapolinar** [comment]
Interesting, because the swagger file was created by io.swagger.swagger-jaxrs and not written by hand.

Maybe when there is only a default response *and* a response code "2XX" is returned, then the call is regarded as a success? Currently, onFail will be called anyway, since the data is empty/undefined.

**Comment by rsuter** [comment]
Good idea

**Comment by rsuter** [comment]
Something like this?

    private processRemoveElement(xhr: any, onSuccess?: any, onFail?: any) {
        var data = xhr.responseText; 
        var status = xhr.status.toString(); 

        {
            var result: any = null; 
            try { 
                result = <any>jQuery.parseJSON(data);
            } catch(e) { 
                if (onFail !== undefined)
                    onFail(null, "error_parsing", e);
                return;
            }

            if (status.length === 3 && status.indexOf("2") === 0) {
                if (onSuccess !== undefined)
                    onSuccess(result);
            } else {
                if (onFail !== undefined)
                    onFail(result, "error_exception");
            }
        }
    }

**Comment by wapolinar** [comment]
The problem is that this will end up in the catch method, when there is no result returned (which is the case when the status code is 204). For these kind of *void* methods this is not necessarily an error.

**Comment by rsuter** [comment]
Ok, I think this should be fine: 

    private processRemoveElement(xhr: any, onSuccess?: any, onFail?: any) {
        var data = xhr.responseText; 
        var status = xhr.status.toString(); 

        {
            var result: any = null; 
			
			if (data !== undefined && data !== null && data !== "") {
				try { 
						result = <any>jQuery.parseJSON(data);
				} catch(e) { 
					if (onFail !== undefined)
						onFail(null, "error_parsing", e);
					return;
				}
			}

			if (status.length === 3 && status.indexOf("2") === 0) {
				if (onSuccess !== undefined)
					onSuccess(result);
			} else {
				if (onFail !== undefined)
					onFail(result, "error_exception");
			}
        }
    }

This way the result is `null` if the received data is undefined, null or empty...

**Comment by wapolinar** [comment]
Yes, I tested it, it works perfectly. Thanks again for the quick response!

**Comment by rsuter** [comment]
New version coming in 30 mins
