### ISSUE TITLE
Web API to Swagger: Error loading  [EnableQuery] 

### ISSUE THREAD

**Issue by rsuter** [NSwag/NSwag#254]

**Comment by michaelaird** [comment]
[WebApplication10.zip](https://github.com/NSwag/NSwag/files/439815/WebApplication10.zip)

Here's a simple solution that repros the issue for me. I tried it with the latest NSWagStudio (5.2.6075.31152)

**Comment by rsuter** [comment]
I tried this with the latest version in "master" and it work without problems on my machine...

**Comment by rsuter** [comment]
... with NSwagStudio. Are you using the cmd line tool?

**Comment by michaelaird** [comment]
I'm using NSwagStudio. I wonder if the dll is somewhere in the path/GAC on your machine. Want me to try to run it with Fuslogvw and see all the paths that are checked?

**Comment by rsuter** [comment]
Ill check out this tool and investigate further... What is your exact exception msg?

**Comment by michaelaird** [comment]
![image](https://cloud.githubusercontent.com/assets/219113/18093163/eec532b2-6e9c-11e6-9e07-679c16851789.png)

**Comment by michaelaird** [comment]
I have this binding redirect in the web.config
```
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>
```

and this is the version in the bin folder

![image](https://cloud.githubusercontent.com/assets/219113/18093249/383aa526-6e9d-11e6-8ef0-8bb4bf12e3b8.png)

**Comment by rsuter** [comment]
Have you manually set the path to the Web.config in the UI?

**Comment by michaelaird** [comment]
I did not. I tried setting it and got the same result.

**Comment by rsuter** [comment]
Then it seems that the redirect is not picked up or ignored...

**Comment by rsuter** [comment]
You should debug nswagstudio and see if the transformed web.config is correct:

https://github.com/NSwag/NSwag/blob/master/src/NSwag.AssemblyLoader/Infrastructure/AssemblyConfigurationFileTransformer.cs#L50 

Or maybe the wrong dll is loaded here: 

https://github.com/NSwag/NSwag/blob/master/src/NSwag.AssemblyLoader/SwaggerGenerators/AssemblyLoader.cs#L42

**Comment by rsuter** [comment]
Can you try with the latest version in the "master" branch? The assembly loading has changed since this issue has been opened...

**Comment by michaelaird** [comment]
Sorry for the late reply. I still get the same error with v5.6.6095.40772

**Comment by rsuter** [comment]
Please try with this version: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by michaelaird** [comment]
Same error. Here is the output from fuslovgw:

> *** Assembly Binder Log Entry  (10/3/2016 @ 12:35:12 PM) ***
> 
> The operation failed.
> Bind result: hr = 0x80070002. The system cannot find the file specified.
> 
> Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
> Running under executable  C:\Program Files (x86)\Rico Suter\NSwagStudio\NSwagStudio.exe
> --- A detailed error log follows. 
> 
> === Pre-bind state information ===
> LOG: DisplayName = System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
>  (Fully-specified)
> LOG: Appbase = file:///C:/Program Files (x86)/Rico Suter/NSwagStudio/
> LOG: Initial PrivatePath = NULL
> LOG: Dynamic Base = NULL
> LOG: Cache Base = NULL
> LOG: AppName = NSwagStudio.exe
> Calling assembly : System.Web.Http.OData, Version=5.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
> ===
> LOG: This bind starts in LoadFrom load context.
> WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
> LOG: No application configuration file found.
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Post-policy reference: System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> LOG: GAC Lookup was unsuccessful.
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Rico Suter/NSwagStudio/System.Web.Http.DLL.
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Rico Suter/NSwagStudio/System.Web.Http/System.Web.Http.DLL.
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Rico Suter/NSwagStudio/System.Web.Http.EXE.
> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Rico Suter/NSwagStudio/System.Web.Http/System.Web.Http.EXE.
> LOG: Attempting download of new URL file:///E:/TempProjects/WebApplication10/WebApplication10/bin/System.Web.Http.DLL.
> LOG: Assembly download was successful. Attempting setup of file: E:\TempProjects\WebApplication10\WebApplication10\bin\System.Web.Http.dll
> LOG: Entering download cache setup phase.
> LOG: Assembly Name is: System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> WRN: Comparing the assembly name resulted in the mismatch: Build Number
> ERR: The assembly reference did not match the assembly definition found.
> ERR: Setup failed with hr = 0x80131040.
> LOG: Attempting download of new URL file:///E:/TempProjects/WebApplication10/WebApplication10/bin/System.Web.Http/System.Web.Http.DLL.
> LOG: Attempting download of new URL file:///E:/TempProjects/WebApplication10/WebApplication10/bin/System.Web.Http.EXE.
> LOG: Attempting download of new URL file:///E:/TempProjects/WebApplication10/WebApplication10/bin/System.Web.Http/System.Web.Http.EXE.
> LOG: All probing URLs attempted and failed.

**Comment by rsuter** [comment]
My suggestion is to use the OWIN middleware. This middleware is run as part of your web application host and thus a lot of reflection problems are gone (plus you have the Swagger UI to test your API): 

https://blog.rsuter.com/nswag-tutorial-integrate-the-nswag-toolchain-into-your-asp-net-web-api-project/

With this, you can load the Swagger spec via URL....

Is this an option?

**Comment by michaelaird** [comment]
I'll have a look and let you know.

**Comment by rsuter** [comment]
And your are sure that 

    System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

is in either the directory of the selected Web API assembly or one of the specified "Reference paths"?

**Comment by rsuter** [comment]
Maybe you have to select "Copy local" for "System.Web.Http" in VS reference properties, so that it is copied to the output directory...

**Comment by michaelaird** [comment]
The assembly loading finds  System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 in the bin directory and this redirect is in my web.config:

>       <dependentAssembly>
>         <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
>       </dependentAssembly>

**Comment by rsuter** [comment]
Ok, and the web.config is selected in nswagstudio? Otherwise the redirects are ignored...

**Comment by michaelaird** [comment]
I tried it with leaving that blank and selecting it. failed both ways...

**Comment by rsuter** [comment]
Its strange, it works for me with your sample solution: 

![image](https://cloud.githubusercontent.com/assets/2603405/19046669/bdf90cb8-899e-11e6-8a8f-8127ebcc3660.png)

**Comment by rsuter** [comment]
Now, I can reproduce...

**Comment by rsuter** [comment]
I think I've found the bug: https://github.com/NSwag/NSwag/commit/bb5a3fdf660f560358d7a9859581055af719bf11

Please test with the latest CI build (MSI installer can be downloaded here too): https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/1056/artifacts

**Comment by rsuter** [comment]
Check out v6.1

**Comment by michaelaird** [comment]
That did the trick!

**Comment by rsuter** [comment]
Cool. Thx for helping here and for using NSwag. Fix is already released...
