### ISSUE TITLE
[MSBuild] Override attributes

### ISSUE THREAD

**Issue by pkupilas** [NSwag/NSwag#259]
When I use MSBuild to generate the swagger file I don't know the target web server. 
Is there any way to override attributes like "host" or "basePath" after the file was generated?

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/d2472df356b92b70d4b10c60a9fb93891f18793e

**Comment by rsuter** [comment]
You want to preprocess the swagger during the client generation?

**Comment by pkupilas** [comment]
Yes : )

**Comment by rsuter** [comment]
Added cmd line new params: 

- ServiceSchemes (http, https, etc.)
- ServiceHost
- InfoTitle
- InfoDescription
- InfoVersion

https://github.com/NSwag/NSwag/commit/cb2246fdfa78d90abedbddfb1c997bb35d127395

v5.3
