### ISSUE TITLE
Unexpected character encountered while parsing value: 1.Path'[0].timelineDate

### ISSUE THREAD

**Issue by Emasoft** [NSwag/NSwag#264]
I'm developing an app that consumes the Swagger API below:

http://pickee-sopeople.rhcloud.com/pickee/v2/api-docs?group=pickee

The API is a valid json swagger api, as you can check from the online Swagger Editor.

I generated the C# Client class with NSwag, but the result is not working.

The method I call from the NSwag generated client is this one (the string is a token needed to auth):

```c# 
ObservableCollection<TimelineResponse> timeline = client._getTimelineAsync ("e4dd6777-ef22-48a5-b1cb-390c3e3dc3ba").Result;
``` 

Here is the error I get:

```
Pickee.API.SwaggerException: Could not deserialize the response body. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: 1.Path'[0].timelineDate', line 1, position 483.
```

It seems that NSwag client do not parse the date-time type correctly. Is this a bug?

**Comment by rsuter** [comment]
Can you post sample JSON data?

**Comment by Emasoft** [comment]
You can easily reproduce the bug following these steps:

- Generate a c# client with NSwag GUI using the following url (its a json file) : http://pickee-sopeople.rhcloud.com/pickee/v2/api-docs?group=pickee
- Import the class in a c# project and instantiate the client 
- Ad this call after the client instantiation: ObservableCollection<TimelineResponse> timeline = client._getTimelineAsync ("e4dd6777-ef22-48a5-b1cb-390c3e3dc3ba").Result;
- you should get the exception immediately. You can debug the server response adding this line to the client in the _getTimelineAsync method (just after the "var responseData_ = await...etc." line): 

Debug.WriteLine ("RESPONSE: " + Encoding.UTF8.GetString (responseData_, 0, responseData_.Length));

**Comment by rsuter** [comment]
The Swagger spec is wrong. We have this: 

				"timelineDate": {
					"type": "string",
					"format": "date-time"
				},

But the JSON data is: 

    "timelineDate": 1478286591534,

which is not a string but a number...

**Comment by rsuter** [comment]
Also see http://stackoverflow.com/a/36167215/876814

**Comment by rsuter** [comment]
Just use `long` as "Date Time Type": 

![image](https://cloud.githubusercontent.com/assets/2603405/18181886/c5e77aec-708d-11e6-886f-142bb67005e9.png)

This works for me

**Comment by rsuter** [comment]
You can then create a partial class with additional properties converting the long datetime properties...

**Comment by Emasoft** [comment]
Ok, thanks. I'll try using "long". But how I can create a DateTime object from that? Is it compatible with DateTime long constructor? I tried but it returns an impossible date (year "0002" or something).

**Comment by rsuter** [comment]
Maybe its a unix timestamp? You have to check this with the API provider... But usually a datetime should be serialized as ISO datetime string.

**Comment by rsuter** [comment]
Can we close this?

**Comment by Emasoft** [comment]
Yes, thanky you. I solved in this way, in case somebody will encounter the same problem in the future:

* I changed the Date Time Type in NSwag editor to "long".

* Then with the generated client I parsed the json, and used this to convert the long to the DateTime format:

``` c#
DateTime parsed_data = DateTimeExtensions.FromUnixTimeStamp (input_date_in_long_format);
```

This is the DateTimeExtensions class:

``` c#
	public static class DateTimeExtensions
		{
		public const long EpochTicks = 621355968000000000;
		public const long TicksPeriod = 10000000;
		public const long TicksPeriodMs = 10000;

		//epoch time
		public static readonly DateTime Epoch = new DateTime (EpochTicks, DateTimeKind.Utc);

		/// <summary>
		/// Number of milliseconds since epoch(1/1/1970).
		/// </summary>
		/// <param name="date">DateTime to convert</param>
		/// <returns>Number of milliseconds since 1/1/1970 (Unix timestamp)</returns>
		public static long ToMilliSecondsTimestamp (this DateTime date)
			{
			long ts = (date.Ticks - EpochTicks) / TicksPeriodMs;
			return ts;
			}

		/// <summary>
		/// Number of seconds since epoch(1/1/1970).
		/// </summary>
		/// <param name="date">DateTime to convert</param>
		/// <returns>Number of seconds since 1/1/1970 (Unix timestamp)</returns>
		public static long ToSecondsTimestamp (this DateTime date)
			{
			long ts = (date.Ticks - EpochTicks) / TicksPeriod;
			return ts;
			}

		/// <summary>
		/// Round a timestamp in seconds.
		/// </summary>
		/// <param name="date">DateTime to convert</param>
		/// <param name="factor">Round factor in seconds.</param>
		/// <returns>Rounded Timestamp in seconds.</returns>
		public static long ToRoundedSecondsTimestamp (this DateTime date, long factor)
			{
			return ((long)date.ToSecondsTimestamp () / factor) * factor;
			}

                /// <summary>
		/// Convert a unixTimestamp Int64 value to a DateTime
		/// </summary>
		/// <param name="unixTimestamp">Number of milliseconds since 1/1/1970 (Unix timestamp)</param>
		/// <returns>Converted time in a DateTime object</returns>
		public static DateTime FromUnixTimeStampLong (this long unixTimestamp)
			{
			return new DateTime (1970, 1, 1).AddMilliseconds (unixTimestamp);
			}

               /// <summary>
		/// Convert a unixTimestamp string numerical value to a DateTime
		/// </summary>
		/// <param name="unixTimestamp">String with the number of milliseconds since 1/1/1970 (Unix timestamp)</param>
		/// <returns>Converted time in a DateTime object</returns>
              public static DateTime FromUnixTimeStampString(this string unixTimestamp)
		{
			long input_date;
			long.TryParse (unixTimestamp, out input_date);
			DateTime parsed_date = DateTimeExtensions.FromUnixTimeStampLong (input_date);

			return parsed_date;
		} 

                /// <summary>
		/// Convert DateTime to Unix timestamp (number of milliseconds since epoch(1/1/1970)).
		/// </summary>
		/// <param name="date">DateTime to convert</param>
		/// <returns>Number of milliseconds since 1/1/1970 (Unix timestamp)</returns>
		public static long ToUnixTimeStamp (this DateTime date)
			{
			var epoc = new DateTime (1970, 1, 1);
			var timeSpan = date - epoc;

			return (long)timeSpan.TotalMilliseconds;
			}

		}
```
