### ISSUE TITLE
Initialize required array in typescript

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#268]
Hi,

First of all thanks a lot!

I was just wondering, if I have a swagger definition with a required array attribute, shouldn't it be initialized in the constructor ? currently the array is created only if I pass in the contructor parameter an array for the element. like this:

```
if (data["reminders"] && data["reminders"].constructor === Array) {
                this.reminders = [];
                for (let item of data["reminders"])
                    this.reminders.push(ReminderDefinition.fromJS(item));
            }
```

it would be really great if the array could be initialized when it's marked as required ?

Thanks a lot.

**Comment by rsuter** [comment]
Good idea.

**Comment by rsuter** [comment]
Implemented in https://github.com/NJsonSchema/NJsonSchema/commit/2759395df1ca77bf1633761c7251c3385090300e

**Comment by rsuter** [comment]
NJS updated => try MSI from this build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/814/artifacts

**Comment by rsuter** [comment]
I have to do some more tests with this change, then ill release this new feature (next 2-3 days)...

**Comment by no-more** [comment]
Hi,

Thanks a lot, I'll try this right now. I was wondering if it was possible to do the same for required objects?

**Comment by no-more** [comment]
I have just installed the msi but didn't see any changes in the generated ts code.

**Comment by rsuter** [comment]
Its only enabled for properties Swagger properties which are required and of type array or dictionary... In NSwagStudio "About", is it using NJsonSchema v4.4?

**Comment by no-more** [comment]
NSwag: 5.4.6091.25840
NJsonSchema: 4.4.6091.25564

I have checked and I was missing the required status, probably a bug in the framework I'm using which does not mark array as required.

I have updated the definition manually (in the left panel), but I still don't have the arrays initialization.

**Comment by rsuter** [comment]
You have to set the required array on the object not on the property. Can you post a sample swagger spec?

**Comment by no-more** [comment]
```
{
  "swagger": "2.0",
  "host": "localhost:3000",
  "basePath": "/api/frontend",
  "schemes": [
    "http"
  ],
  "info": {
    "title": "API documentation",
    "version": "0.1.0"
  },
  "tags": [
    {
      "name": "api/frontend/action",
      "description": "Action data"
    }
  ],
  "paths": {
    "/action": {
      "get": {
        "summary": "Get all elements for synchronisation",
        "operationId": "getApiFrontendAction",
        "parameters": [
          {
            "type": "string",
            "name": "authorization",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "format": "date",
            "name": "updatedSince",
            "in": "path"
          }
        ],
        "tags": [
          "action"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/ActionDefinition"
            },
            "description": "Successful"
          }
        }
      }
    }
  },
  "definitions": {
    "ReminderDefinition": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "beforeStartDate",
            "beforeEndDate"
          ]
        },
        "level": {
          "type": "string",
          "enum": [
            "info",
            "warn",
            "critic"
          ]
        },
        "days": {
          "type": "number"
        },
        "label": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "level",
        "days"
      ]
    },
    "reminders": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ReminderDefinition"
      }
    },
    "ActionDefinition": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "reminders": {
          "$ref": "#/definitions/reminders"
        }
      },
      "required": [
        "label",
        "reminders"
      ]
    }
  }
}
```


Here it is, thanks

**Comment by no-more** [comment]
The swagger definition is generated with hapi-swagger and required properties are listed seperatly in the required section.

**Comment by rsuter** [comment]
Seems fine to me... ill check...

**Comment by rsuter** [comment]
The deferencing for properties was missing... 
Try this (test) msi installer: 
[NSwagStudio.zip](https://github.com/NSwag/NSwag/files/454016/NSwagStudio.zip)

**Comment by rsuter** [comment]
Object initializers should now also be added, test this too please...

**Comment by no-more** [comment]
Yeah !!! 

works great on array, but you have double initialization, once the class attribute definition, and once if the element is provided in the parameter. I think you can skip this one.

For object you have correctly initialized the class property but in the constructor if the data is not present you set it back to null.

**Comment by rsuter** [comment]
Now it should work as expected... only problem now: double initialization but i think this is ok. What do you think?

[NSwagStudio.zip](https://github.com/NSwag/NSwag/files/454041/NSwagStudio.zip)

**Comment by no-more** [comment]
Thanks, but I'm still having the issue on Objects:

Here is the definition:
```
{
  "swagger": "2.0",
  "host": "localhost:3000",
  "basePath": "/api/frontend",
  "schemes": [
    "http"
  ],
  "info": {
    "title": "API documentation",
    "version": "0.1.0"
  },
  "tags": [
    {
      "name": "api/frontend/action",
      "description": "Action data"
    }
  ],
  "paths": {
    "/action": {
      "get": {
        "summary": "Get all elements for synchronisation",
        "operationId": "getApiFrontendAction",
        "parameters": [
          {
            "type": "string",
            "name": "authorization",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "format": "date",
            "name": "updatedSince",
            "in": "path"
          }
        ],
        "tags": [
          "action"
        ],
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/ActionDefinition"
            },
            "description": "Successful"
          }
        }
      }
    }
  },
  "definitions": {
    "ReminderDefinition": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "beforeStartDate",
            "beforeEndDate"
          ]
        },
        "level": {
          "type": "string",
          "enum": [
            "info",
            "warn",
            "critic"
          ]
        },
        "days": {
          "type": "number"
        },
        "label": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "level",
        "days"
      ]
    },
    "reminders": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ReminderDefinition"
      }
    },
    "ActionDefinition": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "reminders": {
          "$ref": "#/definitions/reminders"
        },
        "reminders2": {
          "$ref": "#/definitions/ReminderDefinition"
        }
      },
      "required": [
        "label",
        "reminders",
        "reminders2"
      ]
    }
  }
}
```

and this is what I have in ts constructor:
`this.reminders2 = data["reminders2"] ? ReminderDefinition.fromJS(data["reminders2"]) : null;`

Fot the double initialization it's not bug, so it's not a problem to leave it.

**Comment by rsuter** [comment]
It seems good now...
[NSwagStudio.zip](https://github.com/NSwag/NSwag/files/454068/NSwagStudio.zip)

**Comment by no-more** [comment]
Hi,

Sorry for the late response, I'll try the new version later today.

Thanks a lot.

**Comment by no-more** [comment]
Hi,

It's working great. Thanks a lot.
The only point that could be improved is the duplicate initialization, for objects which can be recursive it's not always the best. couldn't you just remove the default initialization on the class property element?
If you leave the initialization only in the constructor it will be perfect.

Once again thanks a lot!

**Comment by rsuter** [comment]
I thought about this too - but if you have a recursion, then you have a model which is invalid (you cannot create the object graph so that it always satisfies the required constraints)... this is why I think its fine...

**Comment by rsuter** [comment]
Available in v5.5

**Comment by no-more** [comment]
Thanks,

By recursion I was thinking about an object which contains another type of object ... 
It's not a recursion but just multi level. By having 2 initialization, that means all the tree is generated twice. Of course this might quite limited because I don't see lots of case with more of 2 or 3 depth level.  but That's still  double the job. In my case I'm loading an array of object store in the js form, so I have to apply the fromJS on each item, which for a big array could mean a lot of useless double initialization. But I can deal with it, this was just an extra improvement.

Thanks.

**Comment by rsuter** [comment]
Ah ok, yes we should fix double initialization anyway...
