### ISSUE TITLE
+ character becomes [space] in parameter to post

### ISSUE THREAD

**Issue by dbruning** [NSwag/NSwag#269]
Hi,

I've got an endpoint that I post string parameters to. 

My nswag-generated client uses Uri.EscapeUriString() on the parameter, like this:

```
if (email == null)
  throw new ArgumentNullException("email");
 else
   url_ += string.Format("email={0}&", Uri.EscapeUriString(email.ToString()));

```
Unfortunately Uri.EscapeUriString() leaves the + unescaped, so inside my controller it arrives as a space character.

I've patched the nswag-generated client to use with Uri.EscapeDataString() instead, and it does indeed then arrive in my controller as the expected string (with the '+' intact)

Is there a reason that the generated client is using Uri.EscapeUriString() instead of Uri.EscapeDataString()? I'm far from a URI expert, but [this SO answer](http://stackoverflow.com/a/27943434) suggests Uri.EscapeDataString() is the one to use, and the answer below it is pretty scathing about Uri.EscapeUriString()

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/bd7055ea0d4c757fd22ddbebe9f6c09d452903db

**Comment by rsuter** [comment]
Try v5.5

**Comment by dbruning** [comment]
Epic - looks perfect, thanks.

**Comment by rsuter** [comment]
Ok. Nice. Thanks for using the project.

**Comment by rsuter** [comment]
Ok. Nice. Thanks for using the project.
