### ISSUE TITLE
SwaggerMiddleware not invoking correctly on IIS with virtual directory

### ISSUE THREAD

**Issue by DorianGreen** [NSwag/NSwag#271]
I am hosting an API with swagger on IIS with a virtual directory. e.g., localhost/virtual.
In the SwaggerMiddleware, the Uri matching condition is failing due to the OWIN pipeline injecting the entire path with the virtual directory instead of just the relative path.

context.Request.Uri.PathAndQuery returns "virtual/swagger/v1/swagger.json"

```
if (context.Request.Uri.PathAndQuery.Trim('/') == this._path.Trim('/'))
      {
        context.Response.StatusCode = 200;
        context.Response.Write(this.GenerateSwagger(context));
      }
```

Should be:

```
if (context.Request.Path.Trim('/') == this._path.Trim('/'))
      {
        context.Response.StatusCode = 200;
        context.Response.Write(this.GenerateSwagger(context));
      }
```

**Comment by rsuter** [comment]
Are you sure that this is correct in all circumstances?

**Comment by DorianGreen** [comment]
context.Request.Path can be manipulated by other middleware so I suppose its best not to rely on it.
The problem with Uri.PathAndQuery is two fold.
First, there is no reason to look at the query params. you could use AbsolutePath instead.
The main problem is that AbsolutePath (and therefore PathAndUri) returns all the path after the host and port. i.e., the virtual path will be included.

To solve this you could change the condition to:
```
if (context.Request.Uri.PathAndQuery.Contains(this._path.Trim('/')))
 {
     context.Response.StatusCode = 200;
     context.Response.Write(this.GenerateSwagger(context));
 }
```

Or even better, for a case insensive check :
```
if (context.Request.Uri.PathAndQuery.IndexOf(this._path.Trim('/'), StringComparison.OrdinalIgnoreCase) > 0)
 {
     context.Response.StatusCode = 200;
     context.Response.Write(this.GenerateSwagger(context));
 }
```

**Comment by DorianGreen** [comment]
In general, all string comparisons should be case insensitive, unless explicitly necessary.

**Comment by rsuter** [comment]
Is this fine? 
https://github.com/NSwag/NSwag/commit/414233145d81e482ef5c51e7efc3f847686102c6

**Comment by DorianGreen** [comment]
The commit will not always work.
I mentioned that Request.Path is problematic.
it can be changes by other middleware and if you use app.Map("/swagger") then Request.Path = "/"

best to still use Request.Url.PathAndQuery but to check for contains and not equals

**Comment by rsuter** [comment]
For app.Map, we have `OwinBasePath` which is then "subtracted" from the swagger path... I think contains is much more dangerous..

**Comment by DorianGreen** [comment]
fair enough.

**Comment by rsuter** [comment]
Ok, can you check the latest version in the master branch? Is this working for you?

**Comment by DorianGreen** [comment]
I ran the Owin demo on IIS Express with and without a virtual subdirectory.
it works fine without a subdirectory, but fails with.
No ui and no swagger.json can be loaded.
Tried various combinations of modifying the routes and setting the middleware path.

#275 is related

**Comment by rsuter** [comment]
How can i run it in a virtual directory? Just add it to the url in project settings?

**Comment by DorianGreen** [comment]
correct

**Comment by rsuter** [comment]
It works for me in the latest version in the master branch (localhost:port/ and localhost:port/test)

**Comment by rsuter** [comment]
Ok no, the redirect is wrong..

**Comment by DorianGreen** [comment]
I managed to get it to work now.
If you dont use app.map("/swagger") then MiddlewareBasePath = "/{virtualPath}"
If you do, then MiddlewareBasePath = "/{virtualPath}/swagger"

Both SwaggerRoute and SwaggerUiRoute should be prepended with "/{virtualPath}"

**Comment by rsuter** [comment]
I fixed the problems with the middlewares (hopefully), please check latest commit in master: 

https://github.com/NSwag/NSwag/commit/da564f9b74b73e20e3a58e6d01fb2ffd53119577

**Comment by rsuter** [comment]
Please test with next release and reopen if the problem persists
