### ISSUE TITLE
Can't find a way to add file name for content disposition

### ISSUE THREAD

**Issue by dziedrius** [NSwag/NSwag#272]
I need to upload file to API, so I use multipart content. So in swagger there is file type property and everything would work fine, if I would be able to pass file name for content disposition.

Basically this line in client template should have third parameter as file name:
`content_.Add(new StreamContent(<#=parameter.VariableNameLower#>), "<#=parameter.Name#>");`

If content disposition header is missing, MultipartFormDataStreamProvider assumes that data is not file and writes that data to FormData instead to FileData.

I'm I missing something obvious or that is a limitation in NSwag?

**Comment by rsuter** [comment]
I think this is a bug. What is the third parameter?

**Comment by rsuter** [comment]
What should we use as file name? Same as parameter name?

**Comment by dziedrius** [comment]
I think it would be best to add additional argument to method declaration, for example if we had two file parameters (imageFile and xmlFile) in swagger json, method declaration would look like this:
`public Task<Response> AddFilesAsync(Stream imageFile, string imageFileName, Stream xmlFile, string xmlFileName).`

The overload for adding content would be this:
https://msdn.microsoft.com/en-us/library/hh193551(v=vs.118).aspx

**Comment by rsuter** [comment]
What about a FileParameter struct with a Name and optional FileName field (set to Name by default)?

**Comment by dziedrius** [comment]
My idea was simply append "Name" to original File type parameter name, so if original property in Swagger is imageFile, second parameter name would be imageFileName.
Although I don't have strong arguments against having struct also (just may be not a struct, as keeping reference types in struct is not a good/common practice).

**Comment by rsuter** [comment]
I think a FileParameter class (not struct) is better because it reduces the number of method parameters and also makes the file name optional in a nice way.

**Comment by rsuter** [comment]
Improved file handling: https://github.com/NSwag/NSwag/commit/aa33130d3b16affc5db3a3568046e617b87a497d

What do you think?

**Comment by dziedrius** [comment]
Looks great.
