### ISSUE TITLE
SwaggerSecurityScheme serialization

### ISSUE THREAD

**Issue by rgonzalezVW** [NSwag/NSwag#274]
When using SwaggerSecuritySchemeType.ApiKey, "scopes" should not be there according to the specs: [http://swagger.io/specification/#securitySchemeObject](http://swagger.io/specification/#securitySchemeObject)
But since it's initialized in the constructor, is always serialized as en empty array. Please, don't initialize in constructor or provide a custom serializer to remove the field when using ApiKey.
Thanks,
  Rubén

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/54312a89bffbf2207b48e122b8d9dbd72253dce7
