### ISSUE TITLE
RedirectMiddleware doesn't work when in a subfolder

### ISSUE THREAD

**Issue by rgonzalezVW** [NSwag/NSwag#275]
When hosting the site in a subfolder, the redirection doesn't work, because RedirectMiddleware doesn't use Request.PathBase, which result in a redirection to root, instead of the proper subfolder. Also affects the "swagger.json" path.
A better implementation would be passing both routes instead of the final URIs, and building the final URI when redirecting. See below.

```
    internal class RedirectMiddleware {
        private readonly RequestDelegate nextDelegate;
        private readonly string swaggerUiRoute;
        private readonly string swaggerRoute;

        public RedirectMiddleware(RequestDelegate nextDelegate, string swaggerUiRoute, string swaggerRoute) {
            this.nextDelegate = nextDelegate;
            this.swaggerUiRoute = swaggerUiRoute;
            this.swaggerRoute = swaggerRoute;
        }

        public async Task Invoke(HttpContext context) {
            if (context.Request.Path.Value.Trim('/') == swaggerUiRoute.Trim('/')) {
                context.Response.StatusCode = 301;
                context.Response.Headers.Add("Location", context.Request.PathBase + "/" + swaggerUiRoute.Trim('/') + "/index.html?url=" + Uri.EscapeUriString(context.Request.PathBase + swaggerRoute));
            } else
                await nextDelegate.Invoke(context);
        }
    }
```
Right now I'm using this implementation just before calling "UseSwaggerUi" to fix the redirection problem.
Thanks,
  Rubén

**Comment by rsuter** [comment]
Can you try with the latest version in the master branch? You can set the base path with MiddlewareBasePath and the other paths (SwaggerRoute and SwaggerUiRoute) must be absolute...

**Comment by rgonzalezVW** [comment]
I've found a couple bugs in your fix. 
First, in SwaggerExtensions.cs line 106, you are using ActualSwaggerUiRoute for both the parameters for RedirectMiddleware, and the second one should be ActualSwaggerRoute, or the redirection will be to an invalid swagger.json url.
Second, since you put context.Request.PathBase.HasValue in the condition for the RedirectMiddleware.Invoke, it has stopped working when no PathBase is defined, which is very common when testing in localhost. A better solution would be:
```
        public async Task Invoke(HttpContext context)
        {
            if (context.Request.Path.HasValue &&
                string.Equals(context.Request.Path.Value.Trim('/'), _fromPath.Trim('/'), StringComparison.OrdinalIgnoreCase))
            {
                context.Response.StatusCode = 302;
                if (context.Request.PathBase.HasValue) 
                {
                    context.Response.Headers.Add("Location", context.Request.PathBase.Value + _fromPath + "/index.html?url=" + context.Request.PathBase.Value + _swaggerPath);
                } 
                else 
                {
                    context.Response.Headers.Add("Location", _fromPath + "/index.html?url=" + _swaggerPath);
                }
            }
            else
                await _nextDelegate.Invoke(context);
        }

```

**Comment by rsuter** [comment]
Ok now?

**Comment by rgonzalezVW** [comment]
Yes :+1:
