### ISSUE TITLE
ClientTemplate.tt returns always ok when operation response has no type

### ISSUE THREAD

**Issue by rgonzalezVW** [NSwag/NSwag#276]
I don't know if this is intended or a bug, but I think it should return an Exception if the Response.IsSuccess equals false, just like it does when the operation response has type. 

ClientTemplate.tt: Line 206
```
<#}else{#>
<#  if(operation.HasResultType){#>
            return default(<#=operation.ResultType.Substring(5, operation.ResultType.Length - 6)#>);
<#  }else{#>
            return;     
<#  }#> 
<#}#>
```

**Comment by rsuter** [comment]
Yes, it seems that this is missing...

**Comment by rsuter** [comment]
Fixed in https://github.com/NSwag/NSwag/commit/09a1c1089662fd52fee9673e2a187a077a999d4b
