### ISSUE TITLE
Comparison to Swashbuckle

### ISSUE THREAD

**Issue by SebastianStehle** [NSwag/NSwag#277]
Hi,

I would like to know, what your goal is in comparison with swashbuckle. 

Do you plan support for inheritance?

**Comment by rsuter** [comment]
Inheritance is already supported

**Comment by rsuter** [comment]
See https://github.com/NJsonSchema/NJsonSchema/wiki/Inheritance

**Comment by SebastianStehle** [comment]
Awesome. Too bad that Swagger-UI does not support it yet.

I guess that "x-typeName" is not required, because as far as I understand the specs correctly, the default type identifier is the model name, isn't it?

**Comment by rsuter** [comment]
Nope x-typeName is a custom field, because sometimes, schemas are not defined in a "definitions" field and lack the key with their name... So you can specify the class/type name with that...

**Comment by rsuter** [comment]
What is the model name? The default type name is the key of the "definitions" dictionary...

**Comment by SebastianStehle** [comment]
This is what I mean with "Model name"

**Comment by SebastianStehle** [comment]
I see, but in the context of swagger it is not needed, right? Can it be removed in this case? I know, that it does not really matter...

Btw:  What do you think about removing the dependency from JsonInheritanceConverter when it is about to detect the dependency? Would be awesome to have some extension point here. I have a complex type hierarchy and try to avoid writing DTO's and mapping code for them. It has some advantages and disadvantages, of course. This is the reason why I try to do all configuration for json and swagger outside of this type hierarchy.

I don't know how to do it in the PostProcess step, because I don't have information about the .NET types anymore at this point.

Btw: Awesome work so far, I like the concept to have a separate project for the Json Schema. I hope that they follow this approach in swagger and do not create a custom version of the schema in the coming releases.

**Comment by rsuter** [comment]
The Swagger schema is already different from the JSON Schema... (i.e. required property handling)

**Comment by rsuter** [comment]
You can disable DTO generation...

**Comment by rsuter** [comment]
TypeName is removed.. the tools only use the definition keys...
