### ISSUE TITLE
Void response model for DELETE Action

### ISSUE THREAD

**Issue by SebastianStehle** [NSwag/NSwag#278]
Hi,

I have the following action:

        [HttpDelete]
        [Route("...")]
        [ProducesResponseType(typeof(void), 204)]
        public async Task<ActionResult> Delete(string name)
        {
            await CommandBus.PublishAsync(...);

            return NoContent();
        }

in this case the code generator produces a Void ContentType

**Comment by rsuter** [comment]
Use the ResponseTypeAttribute: 

    [ResponseType(typeof(void))]

See: https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator#specify-the-response-type-of-an-action

**Comment by SebastianStehle** [comment]
I have forgotten to mention that I am using asp.net core. I cannot find ResponseTypeAttribute there.

**Comment by rsuter** [comment]
Ok, just install NSwag.Annotations NuGet package

**Comment by SebastianStehle** [comment]
This is a workaround, but it does not make sense, I think ;)

**Comment by rsuter** [comment]
Is ProducesResponseType a native .NET core attribute?

**Comment by SebastianStehle** [comment]
Yes

**Comment by rsuter** [comment]
Just checked, ProducesResponseTypeAttribute should be supported...

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration/SwaggerGenerators/WebApi/WebApiToSwaggerGenerator.cs#L667

**Comment by SebastianStehle** [comment]
The status code is fine, but the problem is the Void-Definition

     "responses": {
          "204": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Void"
            },
            "x-nullable": true
          }
        }

"Void": {
      "type": "object",
      "x-typeName": "Void",
      "additionalProperties": false,
      "allOf": [
        {
          "$ref": "#/definitions/ValueType"
        }
      ]
    },

**Comment by rgonzalezVW** [comment]
I'm sorry to reopen this issue, but the fix is not complete. It only works for ResponseTypeAttribute, but not for ProducesResponseTypeAttribute, because the IsVoidResponse check is missing in the second foreach.

**Comment by rgonzalezVW** [comment]
Also consider that IsNullableRaw is set always, and when the return has no schema it makes no sense. IsNullableRaw should only be set when IsVoidResponse is false.

**Comment by rsuter** [comment]
Ah shit, sorry

**Comment by rsuter** [comment]
Nullable fix: https://github.com/NSwag/NSwag/commit/fdbf39c173419a54c408c2579a1a030d0491adf2
