### ISSUE TITLE
CSharp: Generate Guid type fields for properties with string type, uuid format

### ISSUE THREAD

**Issue by dziedrius** [NSwag/NSwag#281]
Currently if property type is string and format uuid, string type property is generated, may be it would be possible to generate Guid type properties.

**Comment by rsuter** [comment]
You have to use "guid" as format string, but we can implement the generator so that "uuid" also works

**Comment by rsuter** [comment]
Fixed: https://github.com/NJsonSchema/NJsonSchema/commit/3926e55b33202eb5920750ac6eaca4f2e1988b11

**Comment by duongphuhiep** [comment]
How to customize Guid.ToString() for the generated codes?

in may case, the Guid is on the URL, and is convert to string using the default format "D" (with hyphen)

![image](https://github.com/RicoSuter/NSwag/assets/1638594/be293962-b225-448e-9655-d32541f11d18)

Except that the server accept Guid only in the "N" format (without hyphen)

=> so the generated codes couldn't work
