### ISSUE TITLE
Feature Request: SwaggerMiddleware for multi tenant application in ASP.NET Core

### ISSUE THREAD

**Issue by SebastianStehle** [NSwag/NSwag#282]
I am planing a multi tenant application with one swagger definition by tenant / domain. This is not possible with the current SwaggerMiddleware because it generates the schema once.

I suggest the following changes:

1. Two extension methods: 
     * app.UseSwagger(assembly);
     * app.UseSwaggerUI();
2. UseSwaggerUI should not create a SwaggerMiddleware
3. Base class for SwaggerMiddleware (https://gist.github.com/SebastianStehle/42a164793b9008f808038bdf0a0fc35d)

**Comment by rsuter** [comment]
Can't you define a swagger UI per domain?

**Comment by SebastianStehle** [comment]
How would this help me?

**Comment by rsuter** [comment]
So the Swagger spec is the same for all tenants but the URL is different?

**Comment by SebastianStehle** [comment]
No, every tenant gets another swagger definition, depending on permissions, account type, configuration and so on. I use the subdomain to identify the tenant.

**Comment by rsuter** [comment]
Ok this seems rather specific. I think you should write your own middleware and use the NSwag swagger generator class...

**Comment by rsuter** [comment]
Or yes, i can use your middleware base class...

**Comment by SebastianStehle** [comment]
This was the idea, therefore my feature requests above. I can copy and paste code, of course, but I cannot integrate the UI-Middleware only.

**Comment by rsuter** [comment]
Check posted commits, you should be fine now...

**Comment by SebastianStehle** [comment]
I am really happy, that you are so fast. But I am not happy yet ;)

1. Whenever I use app.UseSwaggerUI, I also get the normal SwaggerMiddleware, but SwaggerUiMiddleware is internal. I need a extension method, that just adds the UI Middleware and the Static file middleware only.

2. I think deriving from the SwaggerMiddleware is fragile, because you require me to set parameters in the constructor that I don't need. 

	class MyMiddleware : SwaggerMiddleware
	{
		public MyMiddleware(RequestDelegate nextDelegate, string path, IEnumerable<Type> controllerTypes, SwaggerOwinSettings settings, SwaggerJsonSchemaGenerator schemaGenerator)
			: base(nextDelegate, path, null, null, null)
		{
		}
	}

And this only works because I know the implementation details and because you don't check for null references in the constructor. Therefore I think my idea with the base class is better ;)



Btw: Isn't it easier to use Map('/swagger/vs/swagger.json', o => o.UseMiddleware<SwaggerMiddleware>()); instead of checking the path within the middleware?
