### ISSUE TITLE
Support for not valid c# names

### ISSUE THREAD

**Issue by wooboo** [NSwag/NSwag#288]
Hi,
I'm trying to use your CodeGeneration tools to generate c# client for swagger specyfication based on OData endpoint.
The problem is that I have multiple endpoint paramterers and model properties that are invalid c# names, like $expand, $filter, @odata.context.
Since I want to generate c# code I need to escape those invalid characters and I can't find any way except rewriting full template.

**Comment by rsuter** [comment]
So everything is fine except the  parameter names? This should be simple to fix.

**Comment by rsuter** [comment]
Can you post a sample Swagger spec?

**Comment by wooboo** [comment]
Here you go: [v1.txt](https://github.com/NSwag/NSwag/files/468050/v1.txt)
