### ISSUE TITLE
Question: typescript class extensions

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#289]
Hi,

Could someone explain me or point to a doc where it explain how to use class extensions for typescript in NGswagStudio.
I'm quite new to typescript and I'm not even sure what this is for but I feel like I'm missing something if I don't use this feature.

Thanks a lot.

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code

**Comment by rsuter** [comment]
Sample: https://github.com/NSwag/NSwag/blob/master/src/NSwag.Integration.TypeScriptWeb/scripts/serviceClientsJQueryPromises.extensions.ts

**Comment by rsuter** [comment]
Can we close this issue?

**Comment by rsuter** [comment]
Did you find your answers in the posted links?

**Comment by no-more** [comment]
Hi,

Yes you can close this.

Thanks a lot for this great tool.
