### ISSUE TITLE
WebApiToSwaggerGenerator: "The method 'Get' on path '/rest/v1/???' is registered multiple times." when using a base class

### ISSUE THREAD

**Issue by DoneInSeconds** [NSwag/NSwag#290]
I have the following base class:

```
    public class ApiControllerBase : ApiController
    {
        public IEnumerable<string> GetCsvStrings(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return new string[0];
            }

            return value.Split(',');
        }

        public IEnumerable<int> GetCsvInts(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return new int[0];
            }

            return value.Split(',').Select(x=> int.Parse(x)).ToList();
        }     
    }
```

And a single controller:

```
    [TokenAuthenticationFilter]
    public class FooController : ApiControllerBase
    {
        [HttpGet]
        [ResponseType("200", typeof(NameDto))]
        public HttpResponseMessage Get(int id, [FromUri]GetOptionsDto options, int? version = null) { }

        [HttpGet]
        [ResponseType("200", typeof(NameDto))]
        [SwaggerIgnore]
        public HttpResponseMessage Get([FromUri]GetDto value) { }
    }
```

And I'm generating the JSON in another controller I'm calling from a normal HTML page:

```
    public class DocsController : ApiControllerBase
    {
        public object Get()
        {
            var settings = new WebApiToSwaggerGeneratorSettings
            {
                DefaultUrlTemplate = "rest/v1/{controller}/{id}",
                DefaultEnumHandling = EnumHandling.Integer,
                DefaultPropertyNameHandling = PropertyNameHandling.CamelCase,
                NullHandling = NullHandling.Swagger,
                Title = "API 2.11 (API)",
                Version = "V1.0",
                Description = "<p>Documentation for the Test API.</p> <div>Below you'll find some <b>random</b> info" +
                    "Test, Dave, Steve, Bob</div>"
            };

            WebApiToSwaggerGenerator generator = new WebApiToSwaggerGenerator(settings);
            SwaggerService service = generator.GenerateForControllers(new Type[]
            {
                typeof(FooController)
            });

            string json = service.ToJson();

            var response = Request.CreateResponse(HttpStatusCode.OK);
            response.Content = new StringContent(json, Encoding.UTF8, "application/json");
            return response;
        }
    }
```

On the line GenerateForControllers, I get the exception:
"Additional information: The method 'Get' on path '/rest/v1/Foo' is registered multiple times."

If I change the controller to inherit from ApiController directly, then it works fine. I'm using WebAPI version 4.0.30506.

My route is:
```
            Route newRoute = RouteTable.Routes.MapHttpRoute(
                name: "RestDefault",
                routeTemplate: "rest/v1/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
```

**Comment by rsuter** [comment]
It seems that the `SwaggerIgnoreAttribute` is not correctly processed..

**Comment by DoneInSeconds** [comment]
I actually get the same bug as well if I remove both the get methods, so I'm not sure it's down to the Ignore attribute?

**Comment by rsuter** [comment]
Try adding `[SwaggerIgnore]` to `GetCsvStrings` and `GetCsvInts` and `HttpResponseMessage Get([FromUri]GetDto value)`

**Comment by DoneInSeconds** [comment]
Yep, that fixes the issue (although I didn't mean to have an Ignore on the Get in the first place, so I didn't put the ignore on that). Just this change fixes the problem:

```
    public class ApiControllerBase : ApiController
    {
        [SwaggerIgnore]
        public IEnumerable<string> GetCsvStrings(string value) { }

        [SwaggerIgnore]
        public IEnumerable<int> GetCsvInts(string value) { }
    }
```

**Comment by rsuter** [comment]
A Web API question: If you inherit from a base controller, are its methods also exposed as Web API action methods? I.e. can you call `GetCsvStrings` directly?

**Comment by DoneInSeconds** [comment]
I'm not sure. It's certainly not what WebAPI was designed for. As far as I'm aware, WebAPI only supports 5 methods and purely designed around REST methodologies:

- GET (single)
- GET (many)
- POST
- PUT
- DELETE

_...I think!_

**Comment by rsuter** [comment]
I just checked your sample locally, and with your 4 action methods (inherited) and the default route template "api/{controller}/{id}" you cannot call all 4 actions, thus your code is not working correctly. 

If you use routes or the default route template "api/{controller}/{action}/{id}" then inheritance works in Web API and also generates a correct Swagger spec with NSwag.

**Comment by DoneInSeconds** [comment]
The default route of WebAPI is api/{controller}/{id} isn't it?

**Comment by rsuter** [comment]
Yes, I think so...
