### ISSUE TITLE
Improve description/summary reading (attrs, xml doc) and extend SwaggerTagsAttribute

### ISSUE THREAD

**Issue by DoneInSeconds** [NSwag/NSwag#292]
I'm using ReDoc to display my Swagger Spec generated from WebApiToSwaggerGenerator:
![descriptions](https://cloud.githubusercontent.com/assets/22151993/18468870/c4975ee6-799d-11e6-9644-cb6632746e39.png)

But I can't work out how to specify the descriptions for the:
- Tag sections
- Methods
- Parameters (id)
- Query Parameters (getCustomFields & version)

Is it possible to do this using WebApiToSwaggerGenerator? This [docs](https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator) referring to [this](https://github.com/NJsonSchema/NJsonSchema/wiki/JsonSchemaGenerator) seem to suggest so.

This is my Get method:

```
[ResponseType("200", typeof(PackagingDto))]
[SwaggerTags("Packaging")]
[Description("Get an individual packaging item.")]
public HttpResponseMessage Get(int id, [FromUri]PackagingGetOptionsDto options, int? version = null) { }
```

This is the PackagingGetOptionsDto (which I've tried adding some attributes to, that don't seem to work):

```

    [Newtonsoft.Json.JsonProperty(PropertyName ="Property Name")]
    [Description("When true, custom field data will be provided in the response.")]
    [DisplayName("Test Test Test")]
    [System.ComponentModel.DataAnnotations.Display(Description ="Description", ShortName ="ShortName")]
    [DataMember(Name = "Foo Foo Foo")]
    public bool GetCustomFields { get; set; }
```

None of the above values are output in the generated JSON.

**Comment by DoneInSeconds** [comment]
I'm suprised that this doesn't seem to be supported? Looking through the code, there's no handling for anything but GetXmlDocumentation. 

This works for queryParameters in FromUri:

```
        private SwaggerParameter CreatePrimitiveParameter(string name, string description, Type type, IList<Attribute> parentAttributes,
            ISchemaResolver schemaResolver, ISchemaDefinitionAppender schemaDefinitionAppender)
        {
            var typeDescription = JsonObjectTypeDescription.FromType(type, parentAttributes, Settings.DefaultEnumHandling);
            var parameterType = typeDescription.Type.HasFlag(JsonObjectType.Object) ? typeof(string) : type; // object types must be treated as string

            var operationParameter = _schemaGenerator.Generate<SwaggerParameter>(parameterType, parentAttributes, schemaResolver, schemaDefinitionAppender);
            if (parameterType.GetTypeInfo().IsEnum)
                operationParameter.Schema = _schemaGenerator.Generate<JsonSchema4>(parameterType, parentAttributes, schemaResolver, schemaDefinitionAppender);
            else
                _schemaGenerator.ApplyPropertyAnnotations(operationParameter, type, parentAttributes, typeDescription);

            operationParameter.Name = name;
            operationParameter.IsRequired = parentAttributes?.Any(a => a.GetType().Name == "RequiredAttribute") ?? false;
            operationParameter.IsNullableRaw = typeDescription.IsNullable;

           // The description passed through is just the description from GetXmlDocumentation, why can't it check the description attribute as well?
           dynamic descriptionAttribute = parentAttributes.SingleOrDefault(a => a.GetType().Name == "DescriptionAttribute");
            if (descriptionAttribute != null)
                description = descriptionAttribute.Description;

            if (description != string.Empty)
                operationParameter.Description = description;

            return operationParameter;
        }
```
Is this something that's likely to be implemented soon? Or is there a reason it wasn't?

**Comment by rsuter** [comment]
I dont think you can set a description for a tag...
Currently, you can set the Summary property via the DescriptionAttribute on the Web API action. Is there also a description?

**Comment by DoneInSeconds** [comment]
You can set descriptions for a tag. Check out the [Swagger Petstore example](http://petstore.swagger.io/):
```
  "tags": [
    {
      "name": "pet",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http:\/\/swagger.io"
      }
    },
    {
      "name": "store",
      "description": "Access to Petstore orders"
    },
    {
      "name": "user",
      "description": "Operations about user",
      "externalDocs": {
        "description": "Find out more about our store",
        "url": "http:\/\/swagger.io"
      }
    }
  ],
```
And I had a quick fiddle with the WebApiToSwaggerGenerator source code and you can set the description there as well:

```
  private void LoadMetaData(SwaggerOperation operation, MethodInfo method)
  {
      dynamic descriptionAttribute = method.GetCustomAttributes()
          .SingleOrDefault(a => a.GetType().Name == "DescriptionAttribute");

      if (descriptionAttribute != null)
      {
                operation.Summary = descriptionAttribute.Description;
                operation.Description = "Helpful description of the method"; // <-- Here
      }
      else
      {
            ...
      }
  }
```

**Comment by DoneInSeconds** [comment]
Right, I've worked out how to set **Tag** descriptions:

```
service.Tags = new List<SwaggerTag>();
service.Tags.Add(new SwaggerTag() { Name = "Packaging", Description = "Some description about this tag with the heading 'Packaging'" });
```

But I don't think there's any way to set descriptions of each method, unless you can implement it as per the code in my previous post somehow?

**Comment by rsuter** [comment]
There are two things to do here: 

[ ] Extend SwaggerTagsAttribute so that you can also set the description
[ ] Use DescriptionAttribute to set the operation description and provide a second attribute to set the summary

**Comment by DoneInSeconds** [comment]
You could avoid a breaking change by just using the description as the summary if a summary isn't provided?

**Comment by DoneInSeconds** [comment]
This says help wanted, but also says committed? Do you still need help implementing this? I might be able to get it done.

**Comment by rsuter** [comment]
PRs are welcome :). Thx

**Comment by AndersPhilipsson** [comment]
You could add another method in NJsonSchema.Infrastructure.XmlDocumentationExtensions: GetXmlRemarks
Write code to extract "remarks" from the XML-documentation file similar to that of" summary":

Typical use of remarks
        /// <summary>This is a summary of the operation</summary>
        /// <param name="someParameter">This is a parameter description</param>
        /// <remarks>This contains a longer description of the operation and should be shown as 'Implementation Notes' in swagger ui</remarks>
        [HttpGet("[action]/{someParameter}")]
        public someReturn SomeOperation(int someParameter)


Use the remarks as descption on the operation:
        private void LoadMetaData(SwaggerOperation operation, MethodInfo method)
        {
            dynamic descriptionAttribute = method.GetCustomAttributes()
                .SingleOrDefault(a => a.GetType().Name == "DescriptionAttribute");
            if (descriptionAttribute != null)
                operation.Summary = descriptionAttribute.Description;
            else
            {
                var summary = method.GetXmlDocumentation();
                if (summary != string.Empty)
                    operation.Summary = summary;
            }
            var remarks = method.GetXmlRemarks();
            if (remarks != string.Empty)
                operation.Description = remarks;
        }

**Comment by rsuter** [comment]
Added GetXmlRemarks https://github.com/NJsonSchema/NJsonSchema/commit/47b2cec3761b28bfa392902cf0b2a2345e1ff005

**Comment by rsuter** [comment]
- Support for remarks added
- Support for tag attribute on controller added: https://github.com/NSwag/NSwag/issues/403
