### ISSUE TITLE
[MSBuild, Question] Security definitions object support

### ISSUE THREAD

**Issue by pkupilas** [NSwag/NSwag#293]
Is there any way to add [security definitions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object) to swagger file in build time?

**Comment by rsuter** [comment]
Via command line?

**Comment by pkupilas** [comment]
Yep

**Comment by rsuter** [comment]
No there is no way to do this. How should this look like?

**Comment by rsuter** [comment]
Added in https://github.com/NSwag/NSwag/commit/3690230fa38986a5377a775aaa75b9f251b5d7a6

Cmd line parameter: DocumentTemplate

![image](https://cloud.githubusercontent.com/assets/2603405/18602919/79135006-7c6d-11e6-97e6-a26516e017be.png)
