### ISSUE TITLE
swagger2csclient: Incorrect generation when WebApi controller method contains a generic type with more than 2 arguments

### ISSUE THREAD

**Issue by lojell** [NSwag/NSwag#296]
Hello,
Let's imagine we have WebApi method like:

`public Documents[] GetDocuments(Find<DocumentFilterParams, DocumentGroupByType> request);`

Based on this method there will be generated a next class for the argument above:

`public partial class FindOfDocumentFilterParams,DocumentGroupByType`

Please note a coma in the middle. 
Can you help to find solution please?

**Comment by rsuter** [comment]
Currently only one generic param is supported (as you found out). I think this should be simple to implement...

**Comment by rsuter** [comment]
Also there's an open issue to support "real" generics: https://github.com/NJsonSchema/NJsonSchema/issues/23

But this will be a bit more challenging :)

**Comment by rsuter** [comment]
Fixed: https://github.com/NJsonSchema/NJsonSchema/commit/b974ec43450ef2cedc8ad17d02a9242910eca5db

**Comment by rsuter** [comment]
... but I'm not sure if this really solves your problem (I could not reproduce it so that it generates a comma in the class name). Can you provide a simple sample project?

**Comment by rsuter** [comment]
Can you retry with the latest version in the "master" branch.

**Comment by lojell** [comment]
Excellent, thanks for your help.
Now it works perfectly
