### ISSUE TITLE
Allow custom Route attributes implementing IHttpRouteInfoProvider

### ISSUE THREAD

**Issue by p7ayfu77** [NSwag/NSwag#300]
Currently the implementation in WebApiToSwaggerGenerator only correctly generates API paths when using RouteAttribute decorators.

Typically API development n large project means custom routing is implemented in order to keep the "magic string" problem in one place and not spread across the project.
This typically involves inheriting from IHttpRouteInfoProvider, (which is what RouteAttribute does), whete the Template is provided.

Would it be possible to change the following:
`
  var routeAttributes = method.GetCustomAttributes()
                .Where(a => a.GetType().Name == "RouteAttribute")
                .ToList();
`

To somthing that would work in both normal use of RouteAttribute and any custom implementation as follows:

`
  var routeAttributes = method.GetCustomAttributes()
                .Where(a => a.GetType().InheritsFrom("IHttpRouteInfoProvider", TypeNameStyle.Name))
                .ToList();
`

Thanks
Maria

**Comment by rsuter** [comment]
I think the best would be to use: 

```
var routeAttributes = method.GetCustomAttributes() 
	.Where(a => a.GetType().Name == "RouteAttribute" || 
				a.GetType().InheritsFrom("IHttpRouteInfoProvider", TypeNameStyle.Name))
	.ToList(); 
```

I'm not sure if the RouteAttribute still inherits from IHttpRouteInfoProvider in ASP.NET Core...

**Comment by p7ayfu77** [comment]
Looks great! Thanks for this!

**Comment by rsuter** [comment]
Fixed here: https://github.com/NSwag/NSwag/commit/0dedece8083e5ea8fc16351761f7023d87179e9b

Can you retest with latest version in "master" branch?

**Comment by rsuter** [comment]
InheritsFrom only checks for class inheritance, but we have interface implementations here. Fixed: https://github.com/NSwag/NSwag/commits/master
