### ISSUE TITLE
[Typescript] Generate interface for each class

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#302]
Hi,

It would be great to be able to activate interface code generation for each data class (like it's possible to activate for the client), it could be a great way to control input data instead of using <any> in the constructor.
As the constructor is able to complete the missing required fields perhaps all fields in the interface could be optional ?

Thanks.

**Comment by rsuter** [comment]
Good idea.

**Comment by rsuter** [comment]
Can you provide a sample? Should the DTO classes implement the interfaces or take the interface in their constructor?

**Comment by no-more** [comment]
Hi,

I Think both, the class should implements the interface, and to constructor should take data matching the interface. On the other hand the constructor input could be less strict to allow input data that contains additional or missing fields as the constructor it self is in charge of selecting only accepted fields, and creating default values for missing ones (this should not be changed for sure).

Thanks.

**Comment by no-more** [comment]
I have a side question to this one,

I have several input and outputs objects, in the same or in a separate services, which share some common properties.
For example the could have a common design pattern like : label, description, id, created_at and updated_at. And I could have some of my definitions to implements this pattern. do you think it's possible to manually define an interface or abstract class that could be implemented/extended by them ?
I'm not sure if my question is very clear.

Here is an example of an interface I'm using, and currently after code generation I manually add this to all the objects that are concerned:
```

export interface ResourceI {
    id?: string;
    label?: string;
    subLabel?: string;
    description?: string;
    _recordMetaData?: BaseRecordMetaDataI;
}

export interface ResourceClassI<T> extends ResourceI {
    toJS(data?: T): ResourceI;
    fromJS(data?: ResourceI): T;
    // fromJSON(data?: string) : T;
    toJSON(): string;
    clone(): T;
}
```

In order to do this of course would require a way to tell in the swagger.json definition the corresponding interface. I'm not even sure this is possible.
