### ISSUE TITLE
WepApi object parameter generating as IDictionary<string, object>

### ISSUE THREAD

**Issue by aarro** [NSwag/NSwag#303]
I have the following endpoint in my web api, which is currently using Swashbuckle to generate swagger:

`public async Task<IHttpActionResult> Put(string parentId, string id, [FromBody]dynamic body, bool isBatch = false)`

On my swagger doc the body parameter is created as this:

```         {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Object"
            }
          }```

My problem is that the NSwag client code generator creates this parameter as an `IDictionary<string, object>` instead of just an `object`. From my digging it seems to be something in JsonSchema4 inside NJsonSchema, but I don't know what the proper fix would be. In my research I did notice that the IsDictionary property was set to true, but I'm unsure of the importance of that. To me, nothing about that parameter in swagger suggests it should be a dictionary. Thanks.

**Comment by rsuter** [comment]
Can you post the definition of "Object"?

**Comment by aarro** [comment]
`    "Object": {
      "type": "object",
      "properties": {}
    }`

**Comment by rsuter** [comment]
Ok i think we need a special treatment for this scenario...

**Comment by rsuter** [comment]
By default a schema of type object and no properties is treated as dictionary (there is no explicit dictionary type in JSON Schema). But we can handle dictionary schemas with the name "object" as JObject type (this is what the Json.NET serialzes object properties to anyway).

**Comment by rsuter** [comment]
Would this be fine for you?

**Comment by aarro** [comment]
Yeah that sounds like it'll work. Thanks.

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/7894b8f8d8d53546bfcae45a0e6c960a1860cce6
