### ISSUE TITLE
.NET Core: Documentation of query parameters not shown

### ISSUE THREAD

**Issue by prochnowc** [NSwag/NSwag#306]
Using .NET Core, documentation of query parameters from XMLDOC does not show up.
Description in swagger spec is empty.

Query parameters are taken from request model ([FromQueryAttribute]). All properties in the request model contain "summary" xml tag.

When looking at the spec there is no documentation for any of the properties defined in model types.

**Comment by rsuter** [comment]
- Did you enable XML doc generation (so that an .xml file is generated alongside the .dll)?
- Did you install the required NuGet packages (see https://github.com/NJsonSchema/NJsonSchema/wiki/XML-Documentation)?

**Comment by prochnowc** [comment]
Seems to because for descriptions of controller actions and action parameters documentation is correctly extracted.

**Comment by rsuter** [comment]
Can you post a sample action? And its current output?

**Comment by rsuter** [comment]
It works for me. 

Controller: 

        /// <summary>
        /// Appends events.
        /// </summary>
        /// <param name="events">List of events which should be appended.</param>
        /// <returns>HTTP Response code 201 with location header.</returns>
        [HttpPost, Route("api/Person/SaveEvents")]
        public IActionResult Post([FromBody] IList<EventModel> events)
        {
            return null;
        }

TypeScript output: 

```
    /**
     * Appends events.
     * @events (optional) List of events which should be appended.
     * @return HTTP Response code 201 with location header.
     */
    post(events: EventModel[], onSuccess?: (result: any) => void, onFail?: (exception: string, reason: string) => void) {
```

**Comment by prochnowc** [comment]
Model
```
public class Model
{
    /// <summary>Some name</summary>
    public string Name { get; set; }
}
```

Controller
```
public IActionResult Post([FromQuery] Model)
{
}

```

Description of 'Name' does not show up.

**Comment by rsuter** [comment]
It works for me: 

![image](https://cloud.githubusercontent.com/assets/2603405/19159616/6de0c648-8bed-11e6-976e-069119f72794.png)

And the controller:

![image](https://cloud.githubusercontent.com/assets/2603405/19159634/7f1798ba-8bed-11e6-895a-b91378a8d5f0.png)

**Comment by prochnowc** [comment]
Sorry, i had the model in different assembly which was not producing XML doc file.

**Comment by rsuter** [comment]
Nonetheless, i found a bug in the XML doc reader (for nested types) :-)
