### ISSUE TITLE
[TypeScript] Return plain objects with custom type names from client API methods

### ISSUE THREAD

**Issue by grovesNL** [NSwag/NSwag#307]
I have been testing this library and it looks great. I have a question about avoiding the generated typed classes in favor of plain objects with type interfaces. I can modify the template to support my use case but I'd rather not create my own template if this is a common case.

If I use `GenerateDtoTypes = false`, the generator doesn't create the classes but it still expects the classes to exist. For example, with a controller exporting type `ExampleDto<int>`, I'll get a line such as:
`result200 = resultData200 ? ExampleDtoOfInt32.fromJS(resultData200) : new ExampleDtoOfInt32();`

Instead I'd rather be able to return a regular object that uses an interface name that I specify in the generator settings. For example, if I specified `ExampleDto<>` types should use the interface name `ExampleDto`, I'd prefer the client API method to have a return type of `ExampleDto<number>`. The actual data type returned would be a plain object, not a class instance of `ExampleDtoOfInt32`.

**Comment by rsuter** [comment]
Can you post a sample controller and dto class and the expected output?

**Comment by grovesNL** [comment]
@rsuter Sure, [I've created a gist to demonstrate](https://gist.github.com/grovesNL/9882cf089995036d108a8791e9ca97df). `GeneratedOriginal.ts` is the current output I received, `GeneratedModified.ts` is closer to the output I would like.

You can see I've skipped `resultData200` entirely and create an object of my custom type. I also import `ExampleDto<T>` from a module somewhere else in my project (this could be a pre-existing module or `*.d.ts` file containing the type declarations).

**Comment by rsuter** [comment]
I think you can implement your own TypeScriptTypeResolver and pass it to the SwaggerToTypeScriptClientGenerator. Just override: 

        public override string Resolve(JsonSchema4 schema, bool isNullable, string typeNameHint)

and and return "ExampleDto<T>" if its the ExampleDto schema (and do nothing)... The required (custom) interface can be added to the output via [extension code](https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code). 

Also possible: Implement generics: https://github.com/NJsonSchema/NJsonSchema/issues/23 (not exactly your output, but generates a generic DTO)

**Comment by grovesNL** [comment]
Thanks for the ideas! I overrode `Resolve` but I'm not sure how to pass in the custom `TypeScriptTypeResolver` I created. The constructor of `SwaggerToTypeScriptClientGenerator` creates its own instance of the `TypeScriptTypeResolver`.

Although I think the template will still generate class instances with this change. For example, even if I am able to modify `Resolve` I think the template will try to instantiate a class type. I want to use plain objects (the deserialized JSON) that have been annotated with interface types, not class instances ([example here](https://gist.github.com/grovesNL/6d13e783a1005cd8571816e438231ce4)).

The issue is that I don't want any of the generated classes for the return types (I want to supply these myself), I just want NSwag to create the client code to call the controller. I could add another layer that casts everything back to the types that I want, but then most of the benefits of automatic client code are lost.

**Comment by rsuter** [comment]
Hmm, have you tried the setting Type Style with "Interface"?

**Comment by rsuter** [comment]
Ok, this is not a public extension point... Will add a new ctor for SwaggerToTypeScriptClientGenerator to pass a custom resolver

**Comment by grovesNL** [comment]
That's perfect, `TypeStyle = TypeScriptTypeStyle.Interface` is exactly what I wanted.

After I can pass a custom resolver I think I'll have everything I need. Thanks for the quick responses.

**Comment by rsuter** [comment]
Ok, should work with this: https://github.com/NSwag/NSwag/commit/d66ea87c4ba0f38115980ab2aa18748010d26de7

**Comment by grovesNL** [comment]
Just tested it out and it works great. Thanks!

Also, what is the purpose of the [`FileParameter` interface that's included in the default file generator](https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration/CodeGenerators/TypeScript/Templates/FileTemplate.tt#L35)? Is there a way to disable it if I have no file upload endpoints? I want to avoid post-processing the generated TypeScript if possible.

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/60209816f461b0c01840af317f53bd59e991b2f3

**Comment by grovesNL** [comment]
Fantastic :)

**Comment by rsuter** [comment]
If you have the time it would be great if you add a tutorial for this advanced setup to the wiki..

**Comment by grovesNL** [comment]
Definitely, I plan on documenting most of what I've discovered by browsing through the templates.

**Comment by timsar2** [comment]
> @RSuter Sure, [I've created a gist to demonstrate](https://gist.github.com/grovesNL/9882cf089995036d108a8791e9ca97df). `GeneratedOriginal.ts` is the current output I received, `GeneratedModified.ts` is closer to the output I would like.
> 
> You can see I've skipped `resultData200` entirely and create an object of my custom type. I also import `ExampleDto<T>` from a module somewhere else in my project (this could be a pre-existing module or `*.d.ts` file containing the type declarations). I also dropped the `FileParameter` interface because it shouldn't be required in this case.

So finally is there any documentation how to generate an exact file like GeneratedModified.ts?
after 2 days of googling about the same output, I found this issue. I hope there is a good documentation

**Comment by timsar2** [comment]
> If you have the time it would be great if you add a tutorial for this advanced setup to the wiki..

So Finally is there any documentation of how to generate the exact output as GeneratedModified.ts?
