### ISSUE TITLE
C# client code generator - any successful examples?

### ISSUE THREAD

**Issue by Blastnsmash** [NSwag/NSwag#309]
I'm using nswag studio and swags basic api demo example: 

http://petstore.swagger.io/v2/swagger.json

This generates a CSharp Client that isn't compilable in .net framework 4.6. (EnumMember, for example, is not found)

What .net frameworks should you be targeting to use the client generator code? Do you have a tutorial available that shows how to successfully generate a CSharpClient from Swags basic demo that works out of the box?

**Comment by rsuter** [comment]
This is definitely needed... 

You need to reference these assemblies: 

- System.Runtime.Serialization
- System.ComponentModel.DataAnnotations

For now here a sample PCL client: https://github.com/NSwag/NSwag/tree/master/src/NSwag.Integration.ClientPCL

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/wiki/SwaggerToCSharpClientGenerator#required-dependencies-for-the-client

**Comment by Emasoft** [comment]
Have you heard? PCL are going to be deprecated by Microsoft. I think that very soon you'll need to migrate NSwag from PCL to the new ".Net Standard". I quote:

> .NET Standard will replace Portable Class Libraries (PCLs) as the tooling story for building multi-platform .NET libraries.

Please read here the announcement: https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/

**Comment by rsuter** [comment]
NSwag already supports .NET Standard 1.0... (required for the .NET Core integration)
