### ISSUE TITLE
Compile error in generated source when generating c# client

### ISSUE THREAD

**Issue by mcintyre321** [NSwag/NSwag#31]
Hi. I'm trying to use NSwag to write a Linqpad Swagger Driver. I'm running into a problem when I generate a client against https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-expanded.json

The generated methods are of return type `Task<SomeType>` but the method contains `return default( Error );`  which fails to compile as Error doesn't cast to SomeType.

I would reccomend

- an exception should be thrown if a non default return type needs to be returned, or
- a discriminated union type should be returned (see my project OneOf https://github.com/mcintyre321/OneOf for an example (although I wouldn't take a dependency, I would recommend copying the source, its just a single file
)).

**Comment by rsuter** [comment]
I think this OneOf is a good idea, but not very C#-like and needs lot of generated code... I currently fixed it with the exception approach...

Fixed in v1.25

**Comment by mcintyre321** [comment]
Awesome, thanks!

**Comment by rsuter** [comment]
Is it working for you?

**Comment by fguemara** [comment]
Hi Eric,

I am having the following similar issue in the client files (NSwag 12.3.1.0) :

`System.Threading.Tasks.Task<Envelope`1OfOfList`1OfOfAgenceDtoAndCoreAnd_0AndCulture=neutralAndPublicKeyToken=nullAndCoreLibAnd_0AndCulture=neutralAndPublicKeyToken=7cec85d7bea7798e> GetAgencesAsync(bool? inclureApporteurs, bool? agenceMisc)`

instead of 
`System.Threading.Tasks.Task<EnvelopeOfListOfAgenceDto> GetAgencesAsync(bool? inclureApporteurs, bool? agenceMisc)`
  
very similar issue with the contrat files.

Many thanks for feedback to resolve this

**Comment by RicoSuter** [comment]
Was this working before?

**Comment by fguemara** [comment]
Yes it was. This error happens since 2-3 weeks

**Comment by RicoSuter** [comment]
Did you enable strong naming on your assembly in this period?

**Comment by fguemara** [comment]
No. I did some code refactoring, just normal things.

**Comment by fguemara** [comment]
Rico, Is there a quick fix or work around ? I need to go ahead today. Many thanks for any tip you could provide.

**Comment by fguemara** [comment]
I might be related to `c.CustomSchemaIds(x => x.FullName);`
First error occurred after I added this

**Comment by RicoSuter** [comment]
Yep this seems to be the problem...

And it seems that you use Swashbuckle and not nswag to generate the specs, so we cannot do much to fix this in nswag

**Comment by fguemara** [comment]
Solved via the Swashbuckle [thread](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/752#issuecomment-494790796)

Add an implementation to align Swashbuckle output with the NSwag Studio naming convention TypeOfType

If this can help. Cheers
