### ISSUE TITLE
TypeScript: Only output FileParameter if needed

### ISSUE THREAD

**Issue by rsuter** [NSwag/NSwag#310]

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/60209816f461b0c01840af317f53bd59e991b2f3

**Comment by Liero** [comment]
How do I prevent FileParameter being generated?

I've splitted generation into multiple files, so I've DTO's in separate files from the client classes, but FileParameter is included in both:

    var contractsSettings = CreateBasicSettings();
    contractsSettings.CSharpGeneratorSettings.Namespace += ".Contracts";
    contractsSettings.GenerateClientClasses = false;
    contractsSettings.GenerateDtoTypes = true;
    contractsSettings.GenerateClientInterfaces = false;
    contractsSettings.GenerateExceptionClasses = true;
    Generate(swaggerDocument, contractsSettings, outputFolder + @"\Contracts\Entities.g.cs");


    var interfacesSettings = CreateBasicSettings();
    interfacesSettings.CSharpGeneratorSettings.Namespace += ".Contracts";
    interfacesSettings.GenerateClientClasses = false;
    interfacesSettings.GenerateSyncMethods = false;
    interfacesSettings.GenerateExceptionClasses = false;
    interfacesSettings.GenerateClientInterfaces = true;
    interfacesSettings.GenerateDtoTypes = false;
    Generate(swaggerDocument, interfacesSettings, outputFolder + @"\Contracts\Interfaces.g.cs");


    var communicationSettings = CreateBasicSettings();
    communicationSettings.CSharpGeneratorSettings.Namespace += ".Communication";
    communicationSettings.GenerateClientClasses = true;
    communicationSettings.GenerateClientInterfaces = false;
    communicationSettings.GenerateDtoTypes = false;
    communicationSettings.GenerateExceptionClasses = false;
    communicationSettings.AdditionalNamespaceUsages = new[] { contractsSettings.CSharpGeneratorSettings.Namespace };
    Generate(swaggerDocument, communicationSettings, outputFolder + @"\Communication\ClientProxy.g.cs");
