### ISSUE TITLE
Can you publish the latest stable release for NSwagStudio.msi?

### ISSUE THREAD

**Issue by Emasoft** [NSwag/NSwag#311]
Can you publish the latest stable release for NSwagStudio.msi? The most recent is from 20 days ago.
I need the latest swagger api.

**Comment by rsuter** [comment]
I will release it next week, but you can download the latest MSI here: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by Emasoft** [comment]
Thx!

**Comment by Emasoft** [comment]
I downloaded it, and generated the Client. But it gives me an error:

> Client.cs(170,170): Error CS0246: The type or namespace name `JsonExceptionConverter' could not be found. Are you missing an assembly reference? (CS0246)

**Comment by rsuter** [comment]
I fixed this in this commit: https://github.com/NSwag/NSwag/commit/11ee063e1d74eff0cd87c0c3e43b62eaebae1332

Try installing the latest MSI...

**Comment by rsuter** [comment]
![image](https://cloud.githubusercontent.com/assets/2603405/18923723/be62df16-85ad-11e6-8136-2034c83d1de3.png)

**Comment by Emasoft** [comment]
Ok, I installed the last version now.
The error about JsconExceptionConverter is gone now. 
But there is another error that I get compiling the class:

> Client.cs(42,42): Error CS0117: `System.Net.Http.HttpMethod' does not contain a definition for `Patch' (CS0117) 

The line of code with error is this:

` request_.Method = HttpMethod.Patch;`

I googled it, and I found this on stackoverflow:
http://stackoverflow.com/questions/23599817/web-api-routing-constraint-patch-missing-in-httpmethod

**Comment by rsuter** [comment]
Ok, so

    request_.Method = new HttpMethod("PATCH")

compiles and works?

**Comment by Emasoft** [comment]
Yes, I changed the line of code to that and now compiles with 0 errors.

**Comment by rsuter** [comment]
Ok fixed: https://github.com/NSwag/NSwag/commits/master
Just wait for the CI build to finish then download the MSI

**Comment by rsuter** [comment]
Sorry, this commit: Fixed bug with special http methods (CS)

**Comment by rsuter** [comment]
Please report any other bugs so that we can release a good version next week...
