### ISSUE TITLE
Add HttpClientHandler as optional parameter to constructor of generated c-sharp client 

### ISSUE THREAD

**Issue by bingebong** [NSwag/NSwag#312]
This is to enable passing credentials to the generated c-sharp client through HttpClientHandler.

**Comment by rsuter** [comment]
You can customize the creation of the http client with the UseHttpClientCreationMethod setting and add a custom handler there:  https://github.com/NSwag/NSwag/wiki/SwaggerToCSharpClientGenerator

**Comment by rsuter** [comment]
Could you solve your problem?

**Comment by bingebong** [comment]
Yes. It did.
