### ISSUE TITLE
NSwagstudio generated client hangs on "JsonConvert.DeserializeObject"

### ISSUE THREAD

**Issue by Emasoft** [NSwag/NSwag#318]
I have another issue with the new updated NSwagstudio. The generated client class hangs on "JsonConvert.DeserializeObject". It never returns. The Debug.Writeline method I put after it is never called.

I think this is related somehow to the fact that I choosen "long" as the Date type when generating it.

The json Swagger API I consume is this: 
[http://pickee-sopeople.rhcloud.com/pickee/v2/api-docs?group=pickee](http://pickee-sopeople.rhcloud.com/pickee/v2/api-docs?group=pickee)

This is the json response that return from the server:
[http://pastebin.com/wvWmLDu3](http://pastebin.com/wvWmLDu3)

And this is the NSwagStudio generated Client.cs Class:
[http://pastebin.com/BJY3WrKV](http://pastebin.com/BJY3WrKV)

To reproduce, just call this method with this session token:
`Client._getTimelineAsync ("e4dd6777-ef22-48a5-b1cb-390c3e3dc3ba", CancellationToken.None);`

You can see that I've added a debug line to the original generated client code:

```c#
if (status_ == "200") 
            {
                var result_ = default(ObservableCollection<TimelineResponse>); 
                try
                {
                    if (responseData_.Length > 0)
                        result_ = JsonConvert.DeserializeObject<ObservableCollection<TimelineResponse>>(Encoding.UTF8.GetString(responseData_, 0, responseData_.Length));
			            System.Diagnostics.Debug.WriteLine ("RESULT IS DESERIALIZED CORRECTLY! (BUG: unfortunately this is never called)");
                    return result_; 
                } 
                catch (Exception exception) 
                {
                    throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, exception);
                }
            }
```

The debug message "RESULT IS DESERIALIZED CORRECTLY!" never appears. The execution hangs to the line before. No exception is rised.

**Comment by rsuter** [comment]
It works for me with your pastebin code: 

![image](https://cloud.githubusercontent.com/assets/2603405/18996444/a3593da8-8730-11e6-93fd-eaa686897e76.png)

I'm using Newtonsoft.Json 9.0.1: 

    <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net451" />

**Comment by Emasoft** [comment]
I use Xamarin.Forms, but the file is the same: 

```xml
 <package id="Newtonsoft.Json" version="9.0.1" targetFramework="portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10" />
```

It should not work anyway, because there is a null value in a mandatory field.
The bug is that the exception is not rised. It should be.

**Comment by rsuter** [comment]
Maybe some problem with reflection in Xamarin? Have you tried to use List as array type instead of ObservableCollection?

**Comment by Emasoft** [comment]
Yes, I tried with a List, and that is not the issue. The exception is not rised for some reason.
Can you add some more verbose debug log code to the class? Maybe optional, but something that gives more informations on what is going with the json parsing?

**Comment by rsuter** [comment]
JSON parsing is completely done by Newtonsoft.Json... If the `JsonConvert.DeserializeObject` blocks, cant you pause the debugger and see where it hangs?

**Comment by Emasoft** [comment]
I already debugged the NSwag generated class, and it hangs at the line with "JsonConvert.DeserializeObject".

**Comment by Emasoft** [comment]
Are you suggesting to debug the Newtonsoft.Json source code and debug that?

**Comment by rsuter** [comment]
Yes. Maybe you can add the symbols and debug into `JsonConvert.DeserializeObject`... on what platform are you using Xamarin?

**Comment by rsuter** [comment]
Ah, now I have an exception with your client and sample data: 

```
An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Newtonsoft.Json.dll

Additional information: Required property 'landscapeImgCropped' expects a value but got null. Path '[0].activity', line 83, position 9.
```

**Comment by rsuter** [comment]
DTO property: 

        [JsonProperty("landscapeImgCropped", Required = Required.Always)]
        [Required]
        public ImageSummary LandscapeImgCropped

JSON: 

    "landscapeImgCropped": null

**Comment by rsuter** [comment]
And in your Swagger spec, the EventSummary has a required property landscapeImgCropped but in the response it is null. So the Swagger spec is wrong.

**Comment by Emasoft** [comment]
Yes, that is the issue I discovered looking at the json. The problem is why my code didn't rise the exception.

**Comment by rsuter** [comment]
Yes, that is strange...

**Comment by rsuter** [comment]
Maybe it is raised but not handled and thus the app stops running (hangs). Have you tried to add a try-catch around the call? Maybe you can catch it this way...

**Comment by Emasoft** [comment]
There should be some more verbose error logging in your code IMHO, something beyond exceptions.
Anyway, for now I solved this changing the Required.Always to Required.Default. You can close the issue. If I found other instances of this problem with exceptions, I'll tell you.

**Comment by rsuter** [comment]
You can add logging via partial class methods: 
https://github.com/NSwag/NSwag/wiki/SwaggerToCSharpClientGenerator#customize-the-generated-client-class

i.e. the PrepareRequest and ProcessResponse methods

**Comment by rsuter** [comment]
I want to leave the clients as simple and general as possible

**Comment by Emasoft** [comment]
You are right in doing so, but you can add an option to the nswagstudio to generate a special version of the client. Something like "Generate debug version" with some detailed json logging code added. It would be very helpful.

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/issues/321
