### ISSUE TITLE
Support for Vendor Extensions

### ISSUE THREAD

**Issue by sharmavishalvk** [NSwag/NSwag#319]
I came across a requirement where I need to read vendor extensions as well, and know that NSwag doesn't support vendor extensions. This would be a good use case to have a support for vendor extensions in NSwag.

**Comment by rsuter** [comment]
On what classes do you want to add these extensions?

**Comment by rsuter** [comment]
Just add the following property to the classes which should support vendor extensions: 

        [JsonExtensionData]
        public IDictionary<string, object> ExtensionData { get; set; }

**Comment by sharmavishalvk** [comment]
thanks for your guidance, however 'ExtensionData' will hide the inherited member from JsonSchema4.ExtensionData thus will be adding a new property as 'VendorExtensionData'

**Comment by rsuter** [comment]
If there is already a ExtensionData property, then you can use this, do not add a new one... it seems that the feature is already implemented :-)

**Comment by sharmavishalvk** [comment]
yea true, i checked it after putting my above last comment :P creating a pull request for you to review and accept the changes. thanks.

**Comment by adrianrbezzina** [comment]
Is it possible to include the extensions on the actual swagger part of the specification such as:

http://swagger.io/specification/#pathsObject

> ^x-	Any	Allows extensions to the Swagger Schema. The field name MUST begin with x-, for example, x-internal-id. The value can be null, a primitive, an array or an object. See Vendor Extensions for further details: http://swagger.io/specification/#vendorExtensions

This could be described as XVendorExtensions.  Just to recap this isn't part of the JsonSchema component of swagger, but swagger schema itself.

**Comment by sharmavishalvk** [comment]
I believe as per current version this is not supported out of the box, need to tweak some code. please can you share a sample json what you are trying to achieve?

**Comment by rsuter** [comment]
Reference: https://github.com/NSwag/NSwag/pull/322

**Comment by adrianrbezzina** [comment]
Hopefully these examples are enough to convey the requirement (notice the x-apis-json):

https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md

```javascript
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Analysis",
    "description" : "Provides access to blog posts and analysis across the API Evangelist network.",
    "x-apis-json" : {
        "image": "https://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png",
        "humanURL": "http://developer.apievangelist.com",
        "baseURL": "http://api.apievangelist.com/definitions/Analysis",
        "tags": [
            "blog",
            "industry",
            "analysis",
            "new",
            "API",
            "Application Programming Interface"
        ],
        "properties": [
            {
                "type": "X-signup",
                "url": "https://apievangelist.3scale.net/"
            },
            {
                "type": "X-blog",
                "url": "http://developer.apievangelist.com/blog/"
            },
            {
                "type": "X-apicommonsmanifest",
                "url": "https://raw.githubusercontent.com/kinlane/analysis-api/master/api-commons-manifest.json"
            }
        ],
     }
  },
  "basePath": "/",
  "paths": {
     ...
  }
}
```

**Comment by sharmavishalvk** [comment]
@adrianrbezzina thanks I'll get back to you on this. Parameter and response definition objects supports vendor extensions as per current release however others I need to check what all classes I need to amend to extend support.
@rsuter #322 talks about extension data / vendor extensions only to response object.

**Comment by rsuter** [comment]
@sharmavishalvk Added just for reference

**Comment by sharmavishalvk** [comment]
@adrianrbezzina objects like Info, operation and tag can be supported with some code changes. Still i need to look into security-scheme and path and will come back to you
omkarmore83 has added support for Operation object

**Comment by sharmavishalvk** [comment]
@adrianrbezzina objects i have made changes to Info, Security and tag objects thus they will support vendor extensions. I need to look into the Path now and will come back to you on this.

**Comment by sharmavishalvk** [comment]
@adrianrbezzina oh Paths is nothing but collection of SwaggerOperations

**Comment by sharmavishalvk** [comment]
@adrianrbezzina “NSwag” build (version 6.11) now supports vendor extensions to following objects:-
1.	Info
2.	Operations
3.	SecurityScheme
4.	Tag
5.	Paths (as this is collection of Operations)
6.	Responses (support added in ver6.0)
Hope this helps.
