### ISSUE TITLE
Accept HttpStatusCode enum in ResponseTypeAttribute

### ISSUE THREAD

**Issue by grovesNL** [NSwag/NSwag#332]
It would be useful to use enum values from `HttpStatusCode` (i.e. `HttpStatusCode.OK`) instead of passing string (i.e. `"200"`) in [`ResponseTypeAttribute`](https://github.com/NSwag/NSwag/blob/master/src/NSwag.Annotations/ResponseTypeAttribute.cs). Could I add an overload here?

**Comment by rsuter** [comment]
The problem is that the enum is not available in the PCL library...

**Comment by rsuter** [comment]
But you can implement your own ResponseTypeAttribute, just use your own ctor but use the same class name and property names and types....

**Comment by grovesNL** [comment]
Oh ok, I didn't realize PCL omitted it. Thanks!

**Comment by rsuter** [comment]
Did you try my workaround?

Also swagger allows to use "default" (the fallback response)...

**Comment by grovesNL** [comment]
Yes, your workaround works great. I just inherited the regular `ResponseTypeAttribute` and added a new constructor. It would be nice if we could avoid naming them identically somehow, but it works well for now.

**Comment by grovesNL** [comment]
@RSuter Was this resolved in #389? It seems like I don't have to implement my own anymore.

**Comment by RSuter** [comment]
This was added in 

https://github.com/RSuter/NSwag/commit/08f2835a

But the class is now deprecated, I recommend to use SwaggerResponseAttribute instead.

**Comment by grovesNL** [comment]
@RSuter That's great! Thanks.

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/wiki/WebApiToSwaggerGenerator#additionally-supported-attributes

New: SwaggerDefaultResponseAttribute
Coming soon: NotNull and SwaggerDefaultResponseAttribute.IsNullable
