### ISSUE TITLE
Provide setting for customizing generated exception class name

### ISSUE THREAD

**Issue by cpx** [NSwag/NSwag#333]
It would be quite useful if it was possible to customize the SwaggerException class name to something that is more specific to the API in question.

E.g. let's say I have two APIs, Foo and Bar. If a consumer uses NSwag-generated clients for both, then I could customize the client exceptions to be FooClientException and BarClientException. This has two benefits:
* The exception name clearly indicates which client threw the exception.
* If the two clients are in different assemblies and used in the same code path, you can avoid having to disambiguate the two SwaggerException types.

Thoughts?

**Comment by rsuter** [comment]
Yes, I thought about this too... 
Now, you can define the exception class name (supporting the {controller} placeholder).

**Comment by rsuter** [comment]
Implemented in v6.4, released soon

**Comment by cpx** [comment]
Cool, thanks for a speedy fix! :)
