### ISSUE TITLE
Multiple controllers and explicit ClassName generates duplicate GeneratedCode attributes in client

### ISSUE THREAD

**Issue by cpx** [NSwag/NSwag#334]
When you have an assembly containing two controllers, and explicitly specify the ClassName when generating the client, the GeneratedCode attribute is specified once per each partial class declaration.

Example code for generating client:
```csharp
var swaggerSettings = new WebApiToSwaggerGeneratorSettings();
var swaggerGenerator = new WebApiToSwaggerGenerator(swaggerSettings);
var service = swaggerGenerator.GenerateForControllers(new[] { typeof(EchoController), typeof(GreeterController) });
var clientSettings = new SwaggerToCSharpClientGeneratorSettings
{
	ClassName = "MyClass",
};
var clientGenerator = new SwaggerToCSharpClientGenerator(service, clientSettings);
var code = clientGenerator.GenerateFile().Dump();
```

Resulting generated client code (redacted):
```csharp
namespace MyNamespace
{
    [GeneratedCode("NSwag", "6.3.6121.29191")]
    public partial class MyClass 
    {
        // ...
    }
    
    [GeneratedCode("NSwag", "6.3.6121.29191")]
    public partial class MyClass 
    {
        // ...
    }
}
```

This will not compile, because the GeneratedCode attribute specifies AllowMultiple=false

**Comment by rsuter** [comment]
If you have multiple controllers, you have to either choose `OperationGenerationMode.SingleClientFromOperationId` or use the placeholder `{controller}` in your controller class name.

**Comment by cpx** [comment]
So merging multiple controllers into a single client is not supported? That would be good to have documented :)

Also, some type of warning would be nice if the configuration provided will generate invalid code.

**Comment by rsuter** [comment]
It is supported with the `OperationGenerationMode.SingleClientFromOperationId` setting...

**Comment by cpx** [comment]
Got it, thanks. Still, would be nice with a warning :)

**Comment by cpx** [comment]
Got it, thanks. Still, would be nice with a warning :)

**Comment by rsuter** [comment]
You are right...

Here's the documentation: 
https://github.com/NSwag/NSwag/wiki/ClientGeneratorBaseSettings
