### ISSUE TITLE
WebApiToSwaggerGenerator.GenerateForControllers does not take into account DocumentProcessors

### ISSUE THREAD

**Issue by cosmin-ciuc** [NSwag/NSwag#336]
I have the following function:

```csharp
private static readonly Lazy<byte[]> _swagger = new Lazy<byte[]>(() =>
                 {
                       var controllers = new[]
                                                      {
                                                           typeof(ElmahController),
                                                           typeof(SdlTypeApiController)
                                                      };
                       var settings = new WebApiToSwaggerGeneratorSettings
                                                      {
                                                           DefaultUrlTemplate = "api/{controller}/{id}",
                                                           Description = "Swagger description of MY API",
                                                           Title = "MY API",
                                                           DocumentProcessors =
                                                               {
                                                                   new SecurityDefinitionAppender(
                                                                           "basicAuth",
                                                                            new SwaggerSecurityScheme
                                                                                    {
                                                                                        Type = SwaggerSecuritySchemeType.Basic
                                                                                    })
                                                               },
                                                          OperationProcessors =
                                                               {
                                                                    new OperationSecurityScopeAppender("basicAuth")
                                                               }                                                                                       
                                                       };

                         var generator = new WebApiToSwaggerGenerator(settings);
                         var service =  generator.GenerateForControllers(controllers);
                         return Encoding.UTF8.GetBytes(service.ToJson());
              });
```
The generated json file has an empty securityDefinitions element. It should contain this:

    "securityDefinitions": { "basicauth": { "type": "basic" } }

but instead it contains this:

    "securityDefinitions": {}

**Comment by rsuter** [comment]
Strange, it works for me in the demo project. Can you provide a sample project?

**Comment by cosmin-ciuc** [comment]
I have attached to this comment a Visual Studio 2015 solution which replicates this issue.
Thank you.
[NSwagIssue336.zip](https://github.com/NSwag/NSwag/files/510704/NSwagIssue336.zip)

**Comment by rsuter** [comment]
At the moment the DocumentProcessors and OperationProcessors are only processed when using the OWIN middlewares: https://github.com/NSwag/NSwag/wiki/OwinGlobalAsax

But I should move this logic to the `GenerateForControllers` method...

**Comment by cosmin-ciuc** [comment]
I totally agree. I have just tested it with the same project and if I use OWIN middleware everything is alright.

However I would prefer to use `GenerateForControllers` because in this way I can control which controllers are included in the generated specification. With OWIN middleware all controllers are included unless I mark them with SwaggerIgnoreAttribute. And I have a lot of Web API methods to exclude. 😞

**Comment by rsuter** [comment]
With the OWIN middleware, you can also provide a list of controller types (see overload of UseSwagger/UseSwaggerUi)... plus you get the Swagger UI.

But your problem is fixed: https://github.com/NSwag/NSwag/commit/62d3d89188c31bc6f69c3bea8709456b152e4271

I think this will be released today or tomorrow...

**Comment by cosmin-ciuc** [comment]
Thank you very much.

**Comment by rsuter** [comment]
v6.5 released.. please check if its working for you

**Comment by cosmin-ciuc** [comment]
Yes, it is working. Thank you.
