### ISSUE TITLE
Update the tutorial for using OWIN middleware

### ISSUE THREAD

**Issue by cosmin-ciuc** [NSwag/NSwag#337]
Would it be possible to change the tutorial for [usage of OWIN middleware](https://github.com/NSwag/NSwag/wiki/OwinGlobalAsax) so that instead of recommending to route all the requests through ASP.NET pipeline
```
<system.webServer>
        ...
        <modules runAllManagedModulesForAllRequests="true">
            ...
```
it would recommend to add the following three lines in web.config file:
```
<system.webServer>
     ...
    <handlers>
       ...
      <add name="SwaggerIndex" path="swagger/index.html" verb="*" type="NSwag.AspNet.Owin.SwaggerUiIndexMiddleware" />
      <add name="SwaggerGenerator" path="swagger/v1/swagger.json" verb="*" type="NSwag.AspNet.Owin.SwaggerMiddleware" />
      <add name="SwaggerRedirect" path="swagger" verb="*" type="NSwag.AspNet.Owin.RedirectMiddleware" />
```
?

**Comment by rsuter** [comment]
I agree with you that piping all request through .NET may be problematic...

**Comment by cosmin-ciuc** [comment]
I have tested the settings I've wrote above and they work. Of course, you have to register SwaggerUI on "/swagger" address like this:
```csharp
                RouteTable.Routes.MapOwinPath(
                    "swagger",
                    app =>
                        {
                            app.UseSwaggerUi(
                                typeof(Global).Assembly,
                                new SwaggerUiOwinSettings
                                    {
                                        MiddlewareBasePath = "/swagger"
```

**Comment by rsuter** [comment]
Ok? https://github.com/NSwag/NSwag/wiki/OwinGlobalAsax

**Comment by cosmin-ciuc** [comment]
Perfect. Thank you.

**Comment by rsuter** [comment]
Thank you for helping here. Btw: You can also create a PR to change the wiki with your suggestions :-)...

**Comment by chucklu** [comment]
Hi @RSuter, @cosmin-ciuc ,
     I can only work with the first configuration in modules level, when I try to use the second. Configured it in handler, it did not work.
     Could you provided a sample for the second configuration?
    **By the way, I am working this tutorial :** https://github.com/RSuter/NSwag/wiki/OWIN-Middleware
