### ISSUE TITLE
ASP.NET Core swagger proxy generation error

### ISSUE THREAD

**Issue by ismcagdas** [NSwag/NSwag#341]
Hi,

I have tried to generate angular2 typescript proxies from swagger specification ASP.NET MVC 5.x and it worked very well.

When I tried to do it with ASP.NET Core and swagger specification I got the below error. 
Is this the expected behaviour ?

![image](https://cloud.githubusercontent.com/assets/4133525/19153352/deae997c-8bde-11e6-99c4-b591451ad60e.png)

Thanks a lot.

**Comment by rsuter** [comment]
"modelbinding" is not an allowed "in" value. See http://swagger.io/specification/#parameterObject

**Comment by rsuter** [comment]
With what tool did you generate the Swagger spec?

**Comment by ismcagdas** [comment]
Hi,

I did it with Swashbuckle for ASP.NET Core https://github.com/domaindrivendev/Ahoy.
Thanks for the clarification, I will try to do it with NSwag.

**Comment by rsuter** [comment]
I think we should fix this if this is a valid scenario... Is this produced by a modelbindingattribute? Im not sure if nswag handles this correctly... Im just testing the .net core support and there are still some minor issues...

**Comment by hikalkan** [comment]
Hi,

(we are in the same team with @ismcagdas)

ModelBinding is the default binding rule for AspNet Core. It's not a custom attribute. See it's source code: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/ModelBinding/BindingSource.cs#L56

From it's summary:

> A BindingSource for model binding. Includes form-data, query-string and route data from the request.

It's also documented here: https://docs.asp.net/en/latest/mvc/models/model-binding.html#how-model-binding-works

That means it checks "form data", "route (path)" and "query string" to bind data to the parameter. If you fill any of them, it will work. I suggest to you to use query string when you see modelbinding.

**Comment by rsuter** [comment]
Ok, now this: 

        [HttpGet("Test")]
        public async Task Test([ModelBinder]string foo)
        {

        }
        

Produces this: 

    "/api/Events/Test": {
      "get": {
        "tags": [
          "EventsController"
        ],
        "operationId": "Events_Test",
        "parameters": [
          {
            "type": "string",
            "name": "foo",
            "in": "query",
            "required": true,
            "x-nullable": true
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    },

This should be fine, right?

**Comment by hikalkan** [comment]
Yes, that seems fine. It also should be same if we don't add [ModelBinder].

**Comment by hikalkan** [comment]
BTW, we are using Swashbuckle to generate the json api definition file. So, I suggest you to do same in the generator too. Even you see "modelbinding" in the generator, you can interpret it as "query".
Thanks.

**Comment by rsuter** [comment]
Added parameter kind: https://github.com/NSwag/NSwag/commit/8210fe83f3e977892b4d68a653acec3b5689fa61

Will be in v6.7

**Comment by hikalkan** [comment]
Thanks a lot.
