### ISSUE TITLE
Provide a change log file

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#345]
Hi,

Thanks a lot for your great tool.
Could you just provide some changelog file in order to make it easier to track changes between each release. I'm using the studio and just got an update from 5.6 to 6.6 but don't know what have changed or if there's any breaking change with this major release.

Thanks a lot.

**Comment by rsuter** [comment]
It could be better but see here: https://github.com/NSwag/NSwag/releases

**Comment by kapsiR** [comment]
@RicoSuter I know, this is extra work and not always easy, but are there any plans to improve the changelogs? (Maybe at least auto-generated ones?)

Thanks!
