### ISSUE TITLE
No support for RoutePrefix with parameters?

### ISSUE THREAD

**Issue by cosmin-ciuc** [NSwag/NSwag#348]
Hello, 

I have a controller class defined like this:
```csharp
    [RoutePrefix("api/{companyIdentifier:guid}")]
    public class ExtendedApiController : ApiController
    {
        [HttpGet]
        [Route("documents")]
        [CompanyFilterAuthorization(permission: ApplicationPermissions.Company.SDL.Read)]
        public IHttpActionResult GetDocuments(int oslId, int? sdlId = null, SearchDirection searchDirection = SearchDirection.Parents, string query = null)
        {
            return Ok(_repository.GetDocuments(oslId, sdlId, searchDirection, query));
        }
    }
```

But the generated Swagger specification does not include the ```companyIdentifier``` parameter in the path for the action. I'm getting a path like this: "/api//documents". Is this scenario supported by NSwag?

Thank you.

**Comment by rsuter** [comment]
This is not yet supported... But I'll look into this...

**Comment by rsuter** [comment]
Where is this path parameter used in your sample?

**Comment by cosmin-ciuc** [comment]
That CompanyFilterAuthorization attribute is using it.

**Comment by rsuter** [comment]
What is the type of this parameter if you dont specify "guid"?

**Comment by cosmin-ciuc** [comment]
This is the attribute source code:

```csharp
    public class CompanyFilterAuthorizationAttribute : System.Web.Http.AuthorizeAttribute
    {
        private int permissionId;
        private string permissionName;

        public CompanyFilterAuthorizationAttribute()
        { 
        }

        public CompanyFilterAuthorizationAttribute(object permission)
        {
            this.permissionId = (int)permission;
            this.permissionName = string.Format("{0}.{1}", permission.GetType().Name, permission);
        }

        protected override bool IsAuthorized(System.Web.Http.Controllers.HttpActionContext actionContext)
        {
            bool result = true;
            string userName = "?";

            object companyIdentifier;
            if (actionContext.ControllerContext.RouteData.Values.TryGetValue("companyIdentifier", out companyIdentifier))
            {
                IPrincipal user = Thread.CurrentPrincipal;
                if (user.Identity.IsAuthenticated)
                {
                    userName = user.Identity.Name;
                    //IAuthorizationManager authorizationManager = new AuthorizationManager(Constants.USER_ADMINISTRATOR);
                    //result = authorizationManager.IsAuthorized((string)companyIdentifier, user.Identity.Name, this.permissionName);
                }
            }

            AuditEntryDto auditEntryDto = new AuditEntryDto();
            auditEntryDto.AuditType = result ? AuditEntryType.Success : AuditEntryType.Failure;
            auditEntryDto.UserName = userName;
            auditEntryDto.CompanyIdentifier = (string)(companyIdentifier ?? "?");
            auditEntryDto.PermissionTypeName = permissionName;

            IAuditEntryRepository auditEntryRepository = BusinessFactory.GetAuditEntryRepository(userName);
            auditEntryRepository.AuditEntryToCompany(auditEntryDto);

            return result;
        }
    }
```

**Comment by rsuter** [comment]
Ok, ill check this... For now just add the parameter to the action method and it should not be ignired ..

**Comment by cosmin-ciuc** [comment]
Thank you.

**Comment by rsuter** [comment]
With https://github.com/NSwag/NSwag/commit/804194b67a8fcbb6cdb5f1acfb2e72996b73180b these path parameters are appended at the end of the parameter list: 

For your sample: 

        "parameters": [
          {
            "type": "string",
            "name": "query",
            "in": "query",
            "required": true,
            "x-nullable": true
          },
          {
            "type": "string",
            "name": "companyIdentifier",
            "in": "path",
            "required": true,
            "x-nullable": false,
            "format": "guid"
          }
        ],

Is this fine for you?
Please test it with the latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by cosmin-ciuc** [comment]
Hello,

Thank you for looking into the problem. Unfortunately the CI build you've pointed out has failed and there are no artifacts on it.

**Comment by rsuter** [comment]
Another extension required for this feature: https://github.com/NSwag/NSwag/commit/f13f39c535d3c5824bfbe16351eface17757756a

**Comment by rsuter** [comment]
v6.8

**Comment by rsuter** [comment]
The feature broke some scenarios, i had to add an option for your feature: https://github.com/NSwag/NSwag/commit/cf97542e964b92e9430e22849c3298fac49a2053
