### ISSUE TITLE
WebApiToSwaggerGenerator.GenerateForController() NullReferenceException with no helpful message when type not found in assembly

### ISSUE THREAD

**Issue by voxoid0** [NSwag/NSwag#35]
The following should (imho) throw an exception with an error message like $"Type {type} not found in assembly ${assemblyPath}" (after line 77 of WebApiToSwaggerGenerator.cs) , but instead throws a generic NullReferenceException at line 81 (because controllerType is null): 

            var settings = new WebApiAssemblyToSwaggerGeneratorSettings
            {
                AssemblyPath = @"value/path/to/assembly.dll",
                DefaultUrlTemplate = "api/{controller}/{action}/{id}"
            };

            var generator = new WebApiAssemblyToSwaggerGenerator(settings);
            var swaggerService = generator.GenerateForController("NonExistingClass");

**Comment by voxoid0** [comment]
I couldn't figure out the cause of the NullReferenceException by using the NSwag nuget package; I had to download the source code and include it in my solution so that I could debug the code. Hope this helps. Thanks for the great project.

**Comment by rsuter** [comment]
Now throwing a TypeLoadException. Thanks for using the project.
https://github.com/NSwag/NSwag/commit/34a924b1c66133183bba6a8fbee204f48bcca52f

**Comment by voxoid0** [comment]
Awesome, thanks!

**Comment by rsuter** [comment]
Pushed to nuget => https://www.nuget.org/packages/NSwag.CodeGeneration/1.34.5878.35657
