### ISSUE TITLE
NSwag.MsBuild requires .NETFramework,Version=v4.6.2

### ISSUE THREAD

**Issue by rusanov-vladimir** [NSwag/NSwag#350]
This morning I've installed this package and in NSwag.exe.config there was sku=".NETFramework,Version=v4.6", while now the latest version seems to be sku=".NETFramework,Version=v4.6.2". Since I'm running .Net 4.5.2 and I'm unable to install soon updated version of .NET Framework, the question is if .Net v4.6.2 is really required? I guess it could be required for OWIN. If so, maybe it would be possible to split OWIN and IIS implementations in two nuget packages, so there would be possibility to run NSwag.MsBuild for IIS on non latest version of .NET framework?
Btw, changing the version in config to v4.5.2 made it launch on .NET 4.5.2 without any issues.

**Comment by rusanov-vladimir** [comment]
Double check the packages.config, targetFramework version is indicated correctly.
<package id="NSwag.MSBuild" version="6.7.0" targetFramework="net452"/>

**Comment by rsuter** [comment]
Yes, it has been updated to .NET v4.6.2 because i thought this is required for loading .NET Core assemblies. But I think it may be not a requirement and if this is true, I'll roll back... Just give me some minutes.

**Comment by rsuter** [comment]
Ok, it seems that only "Prefer 32 bit" must be disabled and then v4.6 also works...

**Comment by rsuter** [comment]
Ok downgraded to .NET 4.6.. https://github.com/NSwag/NSwag/commit/4e0b2b2ff46b1dbe5d4be05e418ca9c7a2e401b7

Release v6.8

**Comment by rusanov-vladimir** [comment]
Thanks, but do you think it's safe to run it under .NET 4.5.2 when not dealing with OWIN/.NET Core?

**Comment by rsuter** [comment]
NSwag.MSBuild is not added as reference to your project, but run by Visual Studio... It does not matter what .NET version your project uses, it only matters that Visual Studio runs with .NET 4.6+

**Comment by rusanov-vladimir** [comment]
Yes, but in my case things are a little bit more complicated. I'm working on kind of web application generator. This tool allows you to create a custom solution(sln), that is built(with msbuild) on customer side and generates a website. In case I'll use NSwag.MsBuild customers who are using my generator would be restricted to have .NET 4.6+, while currently they are running .NET 4.5.2. I was thinking to use the package, changing the config to sku=".NETFramework,Version=v4.5.2", because I'm not using .NET Core or Owin features.
