### ISSUE TITLE
[Typescript] make output comply with TsLint

### ISSUE THREAD

**Issue by chrizy** [NSwag/NSwag#356]
It would be great if the Angular2 template would comply with TsLint.

VScode gives me an error due to the number of warnings.
![image](https://cloud.githubusercontent.com/assets/3624292/19309022/652903a8-907a-11e6-8739-1801d39f317b.png)

Great tool.
Thanks
Chris

**Comment by rsuter** [comment]
Is there also a way to mark a file as generated and disable tslint for it?

**Comment by chrizy** [comment]
doesn't seem to be an easy way to ignore file. there is an open issue on TsLint for this feature.
https://github.com/palantir/tslint/issues/73

**Comment by rsuter** [comment]
What about 

tslint: disable

?

https://github.com/palantir/tslint/issues/144

**Comment by rsuter** [comment]
At the beginning of the generated file?

**Comment by rsuter** [comment]
We use the same technique for the generated C# code...

**Comment by grovesNL** [comment]
I do this by adding `/* tslint: disable */` to the generated output, but it may be useful to support this option natively.

For example:
`var output = "/* tslint:disable */\n" + new SwaggerToTypeScriptGenerator(/*...*/).GenerateFile();`

**Comment by rsuter** [comment]
Yes, i will add this to the ts file template...

**Comment by rsuter** [comment]
Is this ok? https://github.com/NSwag/NSwag/commit/3ceb078d9bbf17d951d5ee7cb1161b30ca8f8570

**Comment by grovesNL** [comment]
Looks good, thanks!

**Comment by rsuter** [comment]
v6.12
