### ISSUE TITLE
Trying a custom T4 gives me FileNotFoundException

### ISSUE THREAD

**Issue by mkenyon2** [NSwag/NSwag#358]
I'm trying to create a custom T4 in Visual Studio 2015 using NSwag. When I try to do this:

```
var service = generator.GenerateForController(controllerClass);
```

I get this message:

> Error      Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration, Version=6.6.6124.16498, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
> File name: 'NSwag.CodeGeneration, Version=6.6.6124.16498, Culture=neutral, PublicKeyToken=null'
> 
> Server stack trace: 
>    at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForController(String controllerClassName, String settingsData)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

My T4 looks like this:

```
<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".txt" #>
<#@ include file="T4Toolbox.tt" #>
<#@ assembly name="C:\Testing\NSwag\NSwag\src\NSwag.CodeGeneration\bin\Debug\NSwag.Core.dll" #>
<#@ assembly name="C:\Testing\NSwag\NSwag\src\NSwag.CodeGeneration\bin\Debug\Newtonsoft.Json.dll" #>
<#@ assembly name="C:\Program Files (x86)\Rico Suter\NSwagStudio\NSwag.AssemblyLoader.dll" #>
<#@ assembly name="C:\Testing\NSwag\NSwag\src\NSwag.CodeGeneration\bin\Debug\NJsonSchema.dll" #>
<#@ assembly name="C:\Testing\NSwag\NSwag\src\NSwag.CodeGeneration\bin\Debug\NSwag.CodeGeneration.dll" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="Newtonsoft.Json" #>
<#@ import namespace="NSwag" #>
<#@ import namespace="NSwag.CodeGeneration.Infrastructure" #>
<#@ import namespace="NSwag.CodeGeneration.SwaggerGenerators.WebApi" #>
<#@ import namespace="NSwag.Collections" #>

<#
    // CONFIGURATION
    var controllerClass = "MyNamespace.Api.Controllers.Products.ItemController";
    var defaultUrlTemplate = "api/{controller}/{id}";
    string[] paths = new string[]{"C:\\Users\\SomeUser\\Source\\Repos\\MyNamespace.Api\\bin\\MyNamespace.Api.dll"};
    // -------------

    var generator = new WebApiAssemblyToSwaggerGenerator(new WebApiAssemblyToSwaggerGeneratorSettings
    {
        AssemblyPaths = paths, 
        DefaultUrlTemplate = defaultUrlTemplate
    });

    var controllerName = controllerClass.Remove(0, controllerClass.LastIndexOf(".") + 1).Replace("Controller","");
    Console.WriteLine("Starting the generator.");
    var service = generator.GenerateForController(controllerClass);

    // TODO: Add client code generation (see below)
    var fileName = string.Format(@"{0}Client.gen.cs", controllerName);

#>
```

**Comment by rsuter** [comment]
The dlls have a strong name and the versions must match... Download the zip archive and reference everyting from there.. currently, you load the dlls from different locations which may not be compatible...

**Comment by mkenyon2** [comment]
Tried that. Unzipped them to C:\Testing\NSwagZip\. Now get a bunch of this:

>Failed to resolve assembly reference. The path 'C:\Testing\NSwagZip\Newtonsoft.Json.dll' must be either local to this computer or part of your trusted zone. If you have downloaded this template, you may need to 'Unblock' it using the properties page for the template file in File Explorer.

Tried unblocking all the files, still get these.

**Comment by rsuter** [comment]
You have to "unblock" all files (select all, right-click and select "Properties").

**Comment by mkenyon2** [comment]
Even using the 6.12 NuGet Packages we get that. Other people seem to get it also:
http://stackoverflow.com/questions/40001202/t4-errors-when-run-but-not-when-debugged?noredirect=1#comment67340337_40001202

**Comment by mkenyon2** [comment]
I downloaded the zip, unblocked ALL files, tried to point my T4 assembly statements to the files in this folder, and still receive:

>Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration, Version=6.12.6130.41018, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'NSwag.CodeGeneration, Version=6.12.6130.41018, Culture=neutral, PublicKeyToken=null'

>Server stack trace: 
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.WebApiAssemblyLoader.GenerateForController(String controllerClassName, String settingsData)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

My T4 header looks like this:

	<#@ template debug="false" hostspecific="false" language="C#" #>
	<#@ output extension=".cs" #>
	<#@ include file="T4Toolbox.tt" #>
	<#@ assembly name="System.Core" #>
	<#@ assembly name="System.Collections" #>
	<#@ assembly name="System.Runtime" #>
	<#@ assembly name="System.ObjectModel" #>
	<#@ assembly name="C:\Testing\NSwagZip\NJsonSchema.dll" #>
	<#@ assembly name="C:\Testing\NSwagZip\Newtonsoft.Json.dll" #>
	<#@ assembly name="C:\Testing\NSwagZip\NSwag.Core.dll" #>
	<#@ assembly name="C:\Testing\NSwagZip\NSwag.AssemblyLoader.dll" #>
	<#@ assembly name="C:\Testing\NSwagZip\NSwag.CodeGeneration.dll" #>
	<#@ assembly name="$(SolutionDir)Clark.Chains.Api\bin\Clark.Chains.Api.dll" #>
	<#@ assembly name="$(SolutionDir)Clark.Chains.Core\bin\Debug\Clark.Chains.Core.dll" #>

**Comment by rsuter** [comment]
Maybe theres a problem with the signing/strong name of the assemblies?

**Comment by mkenyon2** [comment]
It could be, how can I check that?

We have been moving forward, I have a T4 that uses NSwag, but only by doing 'Debug T4 Template'.

**Comment by rsuter** [comment]
Debug works?

**Comment by mkenyon2** [comment]
Yes, Debug works, so I know the Template works. I'm attaching the T4 files. I'm sure they can be refactored, but they generate the code we want. Maybe you can see something in the way I'm trying to use them.
[GenerateClient.zip](https://github.com/NSwag/NSwag/files/539683/GenerateClient.zip)

**Comment by rsuter** [comment]
Can you provide a full sample project?

**Comment by mkenyon2** [comment]
I haven't been able to pull one together, but are your assemblies implementing IDisposable?

**Comment by rsuter** [comment]
How can an assembly implement idisposable?

**Comment by mkenyon2** [comment]
Does WebApiAssemblyToSwaggerGenerator implement IDisposable?

**Comment by psimoneau22** [comment]
I'm having the same issue.  I added the nuget package for NSwag.Assembly loader which automatically adds the following dependencies/dlls to my references/packages with the listed versions.

NSwag.Annotations                   7.0.6156.29526
NSwag.AssemblyLoader            7.0.6156.29527
NSwag.CodeGeneration            7.0.6156.29526
NSwag.Commands                    7.0.6156.29526
NSwag.Core                               7.0.6156.29525
NJsonSchema                            7.0.6156.29526
NJsonSchema.CodeGeneration 5.16.6156.29215
Newtonsoft.Json                        9.0.0.0
NConsole                                   3.2.6148.42382

my .tt template looks like this, and it fails on the line 'generator.GetControllerClasses() with the listed error:

<#@ assembly name="System.Core" #>
<#@ assembly name="System.Runtime" #>
<#@ assembly name="$(ProjectDir)\bin\debug\Newtonsoft.Json.dll" #>
<#@ assembly name="$(ProjectDir)\bin\debug\NJsonSchema.dll" #>
<#@ assembly name="$(ProjectDir)\bin\debug\NJsonSchema.CodeGeneration.dll" #>
<#@ assembly name="$(ProjectDir)\bin\debug\NSwag.Core.dll" #>
<#@ assembly name="$(ProjectDir)\bin\debug\NSwag.CodeGeneration.dll" #>
<#@ assembly name="$(ProjectDir)\bin\debug\NSwag.AssemblyLoader.dll" #>
<#@ assembly name="$(ProjectDir)\bin\debug\NSwag.Annotations.dll" #>


<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System.IO" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="Microsoft.CSharp" #>

<#@ import namespace="NJsonSchema.CodeGeneration.CSharp" #>
<#@ import namespace="NSwag.CodeGeneration" #>
<#@ import namespace="NSwag.CodeGeneration.SwaggerGenerators.WebApi" #>
<#@ import namespace="NSwag.CodeGeneration.CodeGenerators" #>
<#@ import namespace="NSwag.CodeGeneration.CodeGenerators.CSharp" #>

....

var generator = new WebApiAssemblyToSwaggerGenerator(new WebApiAssemblyToSwaggerGeneratorSettings
    {
        AssemblyPaths = assemblyPaths.Select(a => Path.GetFullPath(Path.GetDirectoryName(Host.TemplateFile) + a)).ToArray(),
        DefaultUrlTemplate = defaultUrlTemplate                     
    }); 

// It fails here:
generator.GetControllerClasses()




ERROR:


Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'NSwag.CodeGeneration, Version=7.0.6156.29526, Culture=neutral, PublicKeyToken=c2d88086e098d109' or one of its dependencies. The system cannot find the file specified.
File name: 'NSwag.CodeGeneration, Version=7.0.6156.29526, Culture=neutral, PublicKeyToken=c2d88086e098d109'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at NSwag.CodeGeneration.Infrastructure.AppDomainIsolation`1..ctor(String assemblyDirectory, String assemblyConfiguration) in C:\projects\nswag\src\NSwag.AssemblyLoader\Infrastructure\AppDomainIsolation.cs:line 32
   at NSwag.CodeGeneration.SwaggerGenerators.WebApi.WebApiAssemblyToSwaggerGenerator.GetControllerClasses() in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\SwaggerGenerators\WebApi\WebApiAssemblyToSwaggerGenerator.cs:line 40
   at Microsoft.VisualStudio.TextTemplating0E04CCD20955CE11529A2F3B257C1216E2BBC526104C14E8A9A89E74D632C4F513E9F97AE1A739F163E4724F9C1F6FB26D0B11DB98DF48EC951E25ABA56B8B10.GeneratedTextTransformation.TransformText()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].	Beeline.Services.Clients	C:\Users\simoneau_p\Documents\Visual Studio 2015\Projects\ApiService\ServiceClients\ServiceGenerator.tt	1

**Comment by rsuter** [comment]
Can you try to add the packages directory (ie where the missing dll can be found) path to the ReferencePaths setting?

**Comment by rsuter** [comment]
And i think you cannot use the nuget package... Try downloading the zip archive with all required dlls and reference these dlls in your t4 tpl...

**Comment by rsuter** [comment]
Please try again with v7.6

**Comment by mkenyon2** [comment]
Just tried again today, got this message:
Severity	Code	Tool	Description	Project	File	Line	Suppression State
Error			Compiling transformation: 'WebApiAssemblyToSwaggerGenerator' does not contain a definition for 'GenerateForController' and no extension method 'GenerateForController' accepting a first argument of type 'WebApiAssemblyToSwaggerGenerator' could be found (are you missing a using directive or an assembly reference?)		C:\Users\mkenyon\Source\Repos\Clark Chains\Clark.Chains.Web\Infrastructure\ApiClients\Account\..\GenerateClient.tt	51

**Comment by mkenyon2** [comment]
Okay, figured that out. Needed to use `GenerateForControllers(IEnumerable<string> controllers)`. (Perhaps could have a `GenerateForController(string controllerName) { GenerateForControllers(new List<string>{controllerName});}

Doesn't work while debugging. It's saying:
>Running transformation: System.IO.FileNotFoundException: Could not load file or assembly 'NJsonSchema, Version=5.19.6171.28316, Culture=neutral, PublicKeyToken=c2f9c3bdfae56102' or one of its dependencies. The system cannot find the file specified.
File name: 'NJsonSchema, Version=5.19.6171.28316, Culture=neutral, 

The NJsonSchema File version is: 5.20.6175.31167

**Comment by mkenyon2** [comment]
Okay, got the correct version of that in place.

Also added a reference to NSwag.Commands.

This runs and generates my file when I choose 'Debug T4' and generates my file. It does NOT generate my file when I use 'Run Custom Tool', but I get no errors.
