### ISSUE TITLE
Referenced assembly 'NSwag.AspNet.Owin, ...' does not have a strong name

### ISSUE THREAD

**Issue by dcbroad3** [NSwag/NSwag#359]
On building a signed project, I am getting the error:
`Referenced assembly 'NSwag.AspNet.Owin, Version=6.11.6129.25107, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

It looks like NSwag.Core is strongly signed but NSwag.AspNet.Owin and NSwag.CodeGeneration are not. Is there a reason for this, or a known workaround other than manually signing them?

**Comment by dcbroad3** [comment]
This is using the NuGet packages, by the way. It looks like a NSwag.snk file exists as part of this repo, but is not included on some of the projects. I'd suggest adding the .snk file to all the projects unless there's a good reason not to.

**Comment by rsuter** [comment]
I think there was a request a longer time ago to sign the assemblies... and for the new ones I forget to sign them... but I have to check this. Maybe there is a reason that only some dlls are signed...

**Comment by rsuter** [comment]
Otherwise it's fine for me to sign all assemblies...

**Comment by rsuter** [comment]
Will be released as v6.12

**Comment by rsuter** [comment]
Please try again with v6.13

**Comment by dcbroad3** [comment]
Does work with 6.16 (just got around to checking)
