### ISSUE TITLE
SerializationException when passing in controllerClassNames as IEnumerable from LINQ Where

### ISSUE THREAD

**Issue by voxoid0** [NSwag/NSwag#36]
line 64 of WebApiAssemblyToSwaggerGenerator throws SerializationException because it tries to directly serialize the IEnumerable. Maybe convert to array or list first?

**Comment by rsuter** [comment]
Can you post some sample code to reproduce the exception?

**Comment by rsuter** [comment]
Closed due to not reproducible...
