### ISSUE TITLE
ObservableCollection<T> becomes ObservableCollectionT

### ISSUE THREAD

**Issue by lciocci** [NSwag/NSwag#364]
Visual Studio 2015

We use NSwag command line to generate our client proxies from post build events when building our micro services. The first generation of the client proxies comes out fine - collections (such as List<T>) become ObservableCollection<T>. We have another layer of micro services (aggregates) that consume these proxies, and in turn this layer of micro services generate their own proxies. 

What we see is that collections that were defined as ObservableCollection<T> (where T can either be a primitive or some class object) becomes an ObservableCollectionOf[Class], with no discernible properties. The [Class] is generated in the proxy code, but the collection of that class (ObservableCollectionOf[Class]) is does not make any reference to that class.

NSwag has been great so far and we'd like to continue using it. Any thoughts as to how to get around this?

**Comment by rsuter** [comment]
It seems that NSwag does not handle ObservableCollection<T> as array but generic classes... I think this should be easy to fix...

**Comment by lciocci** [comment]
Sounds good. We're currently in the development phase of our project. Any idea as to when this would be addressed? If this isn't able to be addressed relatively soon, might there be a workaround we could employ in the meantime?

**Comment by rsuter** [comment]
Cant you use list instead of obscollection (arraytype setting in cs gen)?

**Comment by lciocci** [comment]
Yes - I just tried this and my collections are now of type List[T]. I'll get with the other developers to check if this works. Thank you for your help.

**Comment by rsuter** [comment]
Fixed: https://github.com/NJsonSchema/NJsonSchema/commit/fe577cd860f09fa21133721a5933f2204310244f

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/db1bbe9b348831dd939488683dea0197045d2378

**Comment by rsuter** [comment]
You can now use the CI artifacts .msi with the fix: https://ci.appveyor.com/project/rsuter/nswag-25x6o

**Comment by rsuter** [comment]
Ok i broke the build, will fix it later today..
