### ISSUE TITLE
Route/Param Case Sensitivity

### ISSUE THREAD

**Issue by dcbroad3** [NSwag/NSwag#368]
Working on a Web API assembly that included something like the following:

```
        /// <summary>
        /// Retrieve a thing.
        /// </summary>
        /// <param name="webId">
        /// The ID of the thing.
        /// </param>
        [HttpGet, Route("things/{webid}", Name = "GetThing")]
        [ResponseType(typeof(ThingDTO))]
        public HttpResponseMessage Get(string webId)
        {
            ...
        }
```

NSwag sees that there is a parameter passed in called "webId", and checks the route path to see if it's included. However, in WebApiToSwaggerGenerator.GenerateForController, when constructing the SwaggerOperationDescription, it checks for a case sensitive match for the parameter in the route. When it doesn't see a case sensitive match (since it's incorrectly "webid" in the route), it records the Path as "things" instead of "things/{webid}". Then, incidentally, it fails because there is already a "things" route. 

Obviously we should fix our routes so that the case matches, but since the Web API action actually works without a case sensitive match, could NSwag do a case insensitive match here?

**Comment by rsuter** [comment]
Will be available in v8.0, please test with latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts
