### ISSUE TITLE
Error Calling method that returns byte[]

### ISSUE THREAD

**Issue by himalpatel81** [NSwag/NSwag#37]
If a method returns file content/byte[] the return type of the client side method is set to object. and While deserialzing the string response of the API to object, it errors out. 
Here is the Server side method code. 

	HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);
	response.Content= new ByteArrayContent(btResult); ;
	response.Content.Headers.ContentDisposition = new System.Net.Http.Headers.ContentDispositionHeaderValue("attachment");
	response.Content.Headers.ContentDisposition.FileName = strFileName;
	return response;

	
And here is the method code generated

	public async Task<Object> Documents_GetDocumentContentAsync(long fileid, CancellationToken cancellationToken)
	{
		var url = string.Format("{0}/{1}?", BaseUrl, "api/Documents/{fileid}/Content/");

		url = url.Replace("{DocumentID}", fileid.ToString());

		var client = new HttpClient();
		PrepareRequest(client);

		var response = await client.GetAsync(url, cancellationToken).ConfigureAwait(false);
		ProcessResponse(client, response);

		var responseData = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
		var status = ((int)response.StatusCode).ToString();

		if (status == "200")
		{
			var result = default(Object);

			try
			{
				if (!string.IsNullOrEmpty(responseData))
					result = JsonConvert.DeserializeObject<Object>(responseData);
				return result;
			}
			catch (Exception exception)
			{
				throw new SwaggerException("Could not deserialize the response body.", response.StatusCode, exception);
			}
		}
		else
		{
		}

		throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response.StatusCode + ").", response.StatusCode, null);
	}            

It errors out on line 

	result = JsonConvert.DeserializeObject<Object>(responseData);

How can I access these methods ?

**Comment by rsuter** [comment]
At the moment, non-JSON results are not supported... What do you expect as result? A byte[] array?

**Comment by himalpatel81** [comment]
Yes, I have few methods which returns byte[], string and Data Table (
http://stackoverflow.com/questions/14571927/net-webapi-datatable).

All those methods are failing.

Do I need to make pure http for those methods or is there any work around ?

Thanks,
Himal

**Comment by rsuter** [comment]
Can you post a sample Web API controller and a class showing how the client interface should look like?

**Comment by rsuter** [comment]
I've added support for `file` responses in v1.35: https://github.com/NSwag/NSwag/commit/228523b1f9eca35b2b1b43c0a7871203ce7346ce

I also updated the documentation (chapter "Specify the response type"): https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator

**Comment by rsuter** [comment]
Is the output as expected?

**Comment by himalpatel81** [comment]
Thanks Rico!
