### ISSUE TITLE
ResponseType typeof(List<...>) returns Inline Model in Swagger results

### ISSUE THREAD

**Issue by mkenyon2** [NSwag/NSwag#370]
I'm trying to write an API to return a list of a custom type. I define it like this:

    [HttpGet]
    [Route("api/categories/top")]
    [ResponseType("200", typeof(List<MyCustomType>)), ResponseType("500", typeof(Exception))]
    public async Task<IHttpActionResult> GetMyListAsync()
    {
        var myList = new MyCustomType();
        //... code to populate
        foreach (var myType in myList)
        {
            myType.ChildType = (await _myService.GetChildTypeAsync(myType.myTypeId));
        }

        return Ok(myType);
    }

I get this in the Swagger Spec:

>Response Class (Status 200)
>Model
Inline Model [
 Inline Model 1
]Inline Model 1 {
subcategories (Array[MyChildType], optional)
}MyChildType {
childId (integer),
name (string, optional)
}

My problem is, if I do List< MyCustomType >, I do not see MyCustomType specified. You notice, it lists Inline Model, but never displays anything about MyCustomType. 

I would normally define it as IList<> or in other cases IEnumerable<>. Is this possible? Should/could I describe this better?

**Comment by rsuter** [comment]
Sorry, can you post the generated Swagger spec and the expected result? I don't understand your problem yet...

**Comment by mkenyon2** [comment]
Updated my original post. Spec was pasted there the first time.

If I do List<MyCustomType> NSwag/Swagger does not list MyCustomType.

**Comment by rsuter** [comment]
Just tried this. I have this controller: 

    public class TestController : ApiController
    {
        public class Foo
        {
            public string Bar { get; set; }
        }

        [NSwag.Annotations.ResponseType("200", typeof(List<Foo>))]
        public HttpResponseMessage GetPersons()
        {
            return Request.CreateResponse(HttpStatusCode.OK, new[] { new Foo { Bar = "Test" } });
        }
    }

And this produces this (correct) spec: 

```
{
  "swagger": "2.0",
  "info": {
    "title": "Web API Swagger specification",
    "version": "1.0.0"
  },
  "schemes": [],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/Test/GetPersons": {
      "get": {
        "tags": [
          "TestController"
        ],
        "operationId": "Test_GetPersons",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Foo"
              }
            },
            "x-nullable": true
          }
        }
      }
    }
  },
  "definitions": {
    "Foo": {
      "type": "object",
      "x-typeName": "Foo",
      "additionalProperties": false,
      "properties": {
        "Bar": {
          "type": "string"
        }
      }
    }
  },
  "responses": {},
  "securityDefinitions": {}
}
```

**Comment by mkenyon2** [comment]
Where do you see that Spec generated?

**Comment by rsuter** [comment]
You can use NSwagStudio: https://github.com/NSwag/NSwag/wiki/NSwagStudio

**Comment by rsuter** [comment]
How did you generate the spec?

**Comment by mkenyon2** [comment]
I go to the swagger page: localhost:####/swagger (#### = our port #).

It seems that if my controller action returns List<MyCustomType> I get Inline Model. But if I do a wrapper type (MyWrapperType) with a property of List<MyCustomType> it gets defined correctly. When I look at `operation.Responses["200"].Schema.SchemaReference.TypeNameRaw` I get MyWrapperOfListOfMyCustomType.

I can work with that.

**Comment by rsuter** [comment]
You can directly access the spec by copying the url on top of the swagger ui and accessing it directly in the browser...

The ui is provided by swagger ui - it may not support all features of the swagger spec.. see http://swagger.io/swagger-ui/

**Comment by mkenyon2** [comment]
Okay, thank you for your patience... I'm learning a lot.

So I edited my controller to have 2 methods, one returns `ResponseWrapper<List<MyCustomType>>` and the other returns `List<MyCustomType>`. Here's the spec:

	"paths" : {
		"/api/categories/top" : {
			"get" : {
				"tags" : ["CategoryController"],
				"operationId" : "Category_GetTopCategories",
				"parameters" : [],
				"responses" : {
					"200" : {
						"description" : "",
						"schema" : {
							"$ref" : "#/definitions/ResponseObjectOfListOfMyCustomType"
						},
						"x-nullable" : true
					},
					"500" : {
						"description" : "",
						"schema" : {
							"$ref" : "#/definitions/Exception"
						},
						"x-nullable" : true
					}
				}
			}
		},
		"/api/categories/topper" : {
			"get" : {
				"tags" : ["CategoryController"],
				"operationId" : "Category_GetTopCategoriesTopper",
				"parameters" : [],
				"responses" : {
					"200" : {
						"description" : "",
						"schema" : {
							"type" : "array",
							"items" : {
								"$ref" : "#/definitions/MyCustomType"
							}
						},
						"x-nullable" : true
					},
					"500" : {
						"description" : "",
						"schema" : {
							"$ref" : "#/definitions/Exception"
						},
						"x-nullable" : true
					}
				}
			}
		}

You'll notice that the second one, `List<MyCustomType>` says type:array, but doesn't specify `List` or `Enumerable`. Maybe this isn't a bug, and I just need to understand it better. We are working around it with our ResponseWrapper object for now.

**Comment by rsuter** [comment]
I think its correct as is. Currently swagger and json schema do not support generics (only for arrays) and thus all generic types are expanded to non-generic/specific types... altough the models should be correct but you may end up with lots of classes...

An enhancement for supporting generics is planned but this will be not compliant with swagger and only work with nswag... (No support in swagger ui)

**Comment by rsuter** [comment]
If you have problems with Swagger UI, you should check the page of the Swagger UI project: http://swagger.io/swagger-ui/

**Comment by mkenyon2** [comment]
Okay, that makes sense. I just didn't know definitively. Thank you.
