### ISSUE TITLE
Need to pass parameters to HttpClient in generated client

### ISSUE THREAD

**Issue by cbordeman** [NSwag/NSwag#371]
`client_ = new HttpClient()`

is generated.  Can you create a virtual method CreateHttpClient() so I can pass parameters and change your code to:

`client_ = CreateHttpClient()`

The problem is there is no way to set handlers on an already created httpclient object.  They must be set in its constructor.  I have handlers to setup auth and retry logic that work far better within the httpclient.

**Comment by rsuter** [comment]
This is already possible with the UseHttpClientCreationMethod setting: https://github.com/NSwag/NSwag/wiki/SwaggerToCSharpClientGeneratorSettings

**Comment by cbordeman** [comment]
How is this exposed in the NSwagStudio UI?  I don't see it.

**Comment by cbordeman** [comment]
Ah, I see you have to give a Base class name then you get the option.  Cool thanks.
