### ISSUE TITLE
Add support for disable swagger validator

### ISSUE THREAD

**Issue by bingebong** [NSwag/NSwag#373]
If swagger document in webapi-solution is not publicly available the built in swagger validation shows a red "Error..." in swagger ui.

I suggest adding a setting in SwaggerUiOwinSettings: 'ShowValidator' that defaults to true.
Add 'validatorUrl : null' in SwaggerUI's index.html when 'ShowValidator=False'   
```
window.swaggerUi = new SwaggerUi({ 
         url: url, 
         dom_id: "swagger-ui-container", 
         validatorUrl : null,
```

**Comment by rsuter** [comment]
But even if the red "error" is shown, you cannot use Swagger UI because the JSON cannot be accessed? Why don't you completely disable the middleware if the JSON is not allowed to access?

**Comment by bingebong** [comment]
What I mean by 'publicly' is that the webapi is password protected. After authentication you can use swagger ui as normal, its only the validator function that does not work.

Since the validator function just makes a restcall to 'online.swagger.io' with the URL to my swagger-document, this validator service then tries to download the swagger document unauthenticated, without success. Hence: red "error".
