### ISSUE TITLE
Add GeneratedCode Attribute to internal c# classes as well

### ISSUE THREAD

**Issue by rangp** [NSwag/NSwag#374]
Code Analysis is in my current setup throwing errors because parameters were not validated in internal c# classes generated by the CSharpClientGenerator.  This is because internal classes lack the `[GeneratedCode]` attribute. Could you please add this attribute to internal classes as well to get rid of the errors?`I wouldn't like to disable Code Analysis in my project.

**Comment by rsuter** [comment]
And https://github.com/NJsonSchema/NJsonSchema/commit/ad4b9fbd5a190bcafa476edceeb2c22ec19eed04
