### ISSUE TITLE
C# Compiler Error When Using Custom Return Types for HTTP 500 Response

### ISSUE THREAD

**Issue by rangp** [NSwag/NSwag#375]
Hi,

we are using custom return types for HTTP 500 responses in swagger. The swagger.json looks like this:

    "responses": {
					"200": {
						"description": "Success",
						"schema": {
							"$ref": "#/definitions/Response[Contract]"
						}
					},
					"500": {
						"description": "Server Error",
						"schema": {
							"$ref": "#/definitions/ServerErrorResponse"
						}
					}
				}

Where `ServerErrorResponse` ist just a plain object definition. The generated c# client recognizes the custom return type and contains the following generated code to handle a HTTP 500 status:

            if (status_ == "500") 
            {
                var result_ = default(ServerErrorResponse); 
                try
                {
                    if (responseData_.Length > 0)
                        result_ = JsonConvert.DeserializeObject<ServerErrorResponse>(Encoding.UTF8.GetString(responseData_, 0, responseData_.Length), new JsonConverter[] { new JsonExceptionConverter() });                                
                } 
                catch (Exception exception) 
                {
                    throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, exception);
                }
                if (result_ == null)
                    result_ = new ServerErrorResponse();
                result_.Data.Add("HttpStatus", status_);
                result_.Data.Add("ResponseData", Encoding.UTF8.GetString(responseData_, 0, responseData_.Length));
                /* Compiler error here -> */ throw new SwaggerException<ServerErrorResponse>("A server side error occurred.", status_, responseData_, result_, result_); 
            }
    
Now the second to last line is causing the compiler error, since the last Parameter for the constructor of `SwaggerException<TResult>` is `innerException` and must be of type Exception. Yet `ServerErrorResponse` is not an exception type, it's just a regular object (that has also been generated by NSwag).

I see two possible fixes for this issue: Either a return type for a HTTP 500 response must always be an Exception type or the `innerException` parameter could just be null when custom return types are used.

Thanks for helping
 
NSwag is a great tool, btw!

**Comment by rsuter** [comment]
I'd say we set the inner exception to null...

**Comment by rangp** [comment]
No problem wit that. The service response is already contained in the `response` parameter, so no information loss.

**Comment by rsuter** [comment]
There is already a check whether the response type is an exception. In your scenario this check is broken: 

![image](https://cloud.githubusercontent.com/assets/2603405/19479469/2b24193c-9547-11e6-9e42-1d5f49fb5e85.png)

Can you post a full swagger spec so that I can reproduce your issue and fix this?

**Comment by rangp** [comment]
[swagger.json.txt](https://github.com/NSwag/NSwag/files/536483/swagger.json.txt)

I stripped it down to the essential parts. I'm calling the generator from within a dotnet core console application. The installed version of NSwag is: "6.4.6122.16182"

Thank you!

**Comment by rangp** [comment]
Whoa. I just updated to "6.12.6130.41018" to see if that helps but the update introduced another compiler error that wasn't there before. `FileParameter` cannot be found anymore. Is this known?

**Comment by rsuter** [comment]
Before, the class FileParameter was always rendered. Now it is only rendered if any operation parameter is of type "file"... is this the case?

**Comment by rsuter** [comment]
Do you reference the class even if it is not used in your client?

**Comment by rangp** [comment]
No the class `FileParameter` is referenced in the internal (generated) class `JsonExceptionConverter`

Here's the generated code

    [GeneratedCode("NSwag", "6.4.6122.16182")]
    internal class JsonExceptionConverter : JsonConverter
    {
        private readonly DefaultContractResolver _defaultContractResolver = new DefaultContractResolver();
        private readonly IDictionary<string, Assembly> _searchedNamespaces;
        private readonly bool _hideStackTrace = false;
    
        public JsonExceptionConverter()
        {
            _searchedNamespaces = new Dictionary<string, Assembly> { { typeof(FileParameter).Namespace, typeof(ServiceException).GetTypeInfo().Assembly } };
        }

Just that `FileParameter` itself is not generated. I'm not using any file operation parameters.

**Comment by rsuter** [comment]
Yes, this was a bug (just fixed).

**Comment by rsuter** [comment]
Ok, I think both problems are fixed... Can you try with the latest CI artifacts (i.e. with NSwagStudio): https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

If everything is fine, I will release the .NET Core version... or is this not possible in your setup?

**Comment by rangp** [comment]
Should be possible, I'm on it right now. I'll keep you posted

**Comment by rangp** [comment]
Perfect. Compiler errors are gone. Works with my setup.
Thanks for the quick fixes!

**Comment by rsuter** [comment]
Ok thx for checking. Ill release v6.13 today...
