### ISSUE TITLE
C# Generator: Support for Optional Object Properties

### ISSUE THREAD

**Issue by rangp** [NSwag/NSwag#377]
Hi, it's me again,

I just realized that the C# client generator with the default settings always adds the following attribute above the properties of generated objects.

     [JsonProperty("createdAt", Required = Required.DisallowNull, NullValueHandling =     NullValueHandling.Ignore)]
        public DateTime CreatedAt
    ...

Although there are some properties that are optional. This results in runtime errors, when the property is `null`. 

The JSON Schema definition used by swagger states that all object properties are treated as optional, unless they are included in the `required` section. Cf. below

    {
      "type": "object",
      "required": [
       "name"
      ],
      "properties": {
        "name": {
          "type": "string"
         },
         "address": {
           "$ref": "#/definitions/Address"
         },
         "age": {
           "type": "integer",
           "format": "int32",
           "minimum": 0
         }
      }
    }

Is there a way to enable optional properties? 
If not: Are you planning on supporting them?

Cheers
Peter

**Comment by rsuter** [comment]
I just tried this swagger spec: 

```json
{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": ""
  },
  "schemes": [],
  "paths": {},
  "definitions": {
    "MyType": {
      "type": "object",
      "x-typeName": "MyType",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "integer",
          "format": "int32",
          "minimum": 0.0
        }
      }
    }
  },
  "responses": {},
  "securityDefinitions": {}
}
```

The output looks correct to me: 

```cs
    [JsonObject(MemberSerialization.OptIn)]
    [GeneratedCode("NJsonSchema", "5.2.6135.25892")]
    public partial class MyType 
    {
    
        [JsonProperty("name", Required = Required.Always)]
        [Required]
        public string Name { get; set; }
    
        [JsonProperty("age", Required = Required.Default, NullValueHandling = NullValueHandling.Ignore)]
        public int? Age { get; set; }
    
        public string ToJson() 
        {
            return JsonConvert.SerializeObject(this);
        }
        
        public static MyType FromJson(string data)
        {
            return JsonConvert.DeserializeObject<MyType>(data);
        }
    }
```

**Comment by rangp** [comment]
I just realized that it seems to be a dotnet core specific problem.  When I run the same specification from within a dotnet core application I get the following output:

        [JsonProperty("name", Required = Required.Always)]
        [Required]
        public string Name
        {
            get { return _name; }
            set 
            {
                if (_name != value)
                {
                    _name = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        [JsonProperty("age", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public int Age
        {
            get { return _age; }
            set 
            {
                if (_age != value)
                {
                    _age = value; 
                    RaisePropertyChanged();
                }
            }
        }

`Required.DisallowNull` is the critical difference. Also Datetimes are not generated as nullables in a dotnet core context.

The NSwagStudio generates the code properly, like you posted above, but unfortunately I cannot use it in my toolchain.

**Comment by rangp** [comment]
I think I found the root cause of the problem. Whenever I use `CSharpGeneratorSettings` (no matter what settings I actually use) the code generation is faulty. Then I removed the `CSharpGeneratorSettings` completely from my `SwaggerToCSharpClientGeneratorSettings`  and it suddenly works as expected.

I have no clue why..

**Comment by rsuter** [comment]
The difference is the NullHandling setting which is set to Swagger when creating a new SwaggerToCSharpGeneratorSettings: 

https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration/CodeGenerators/CSharp/SwaggerToCSharpGeneratorSettings.cs

**Comment by rsuter** [comment]
I just tried this code in my .NET Core application: 

```
            var service = SwaggerService.FromJson(@"{
  ""swagger"": ""2.0"",
  ""info"": {
    ""title"": """",
    ""version"": """"
  },
  ""schemes"": [],
  ""paths"": {},
  ""definitions"": {
    ""MyType"": {
      ""type"": ""object"",
      ""x-typeName"": ""MyType"",
      ""required"": [
        ""name""
      ],
      ""properties"": {
        ""name"": {
          ""type"": ""string""
        },
        ""age"": {
          ""type"": ""integer"",
          ""format"": ""int32"",
          ""minimum"": 0.0
        }
      }
    }
  },
  ""responses"": {},
  ""securityDefinitions"": {}
}");
            var settings = new SwaggerToCSharpClientGeneratorSettings();
            var generator = new SwaggerToCSharpClientGenerator(service, settings);
            var code = generator.GenerateFile();
```

And the age is still `public int? Age { get; set; }`...

Can you provide a sample project?

**Comment by rangp** [comment]
https://github.com/rangp/NSwag_Test_Application

I just hacked it down.. I set the NullValueHandling to JsonSchema but it made no difference.
Client.cs is the generated class.

Let me know if you need anything else

**Comment by rsuter** [comment]
Ah, I see, just use Swagger for NullHandling: 

                var settings = new SwaggerToCSharpClientGeneratorSettings
                {
                    ClassName = "Client",
                    CSharpGeneratorSettings = new CSharpGeneratorSettings
                    {
                        NullHandling = NJsonSchema.NullHandling.Swagger,
                        Namespace = "Namespace1",
                    },
                    UseHttpRequestMessageCreationMethod = true
                };

The problem is, because you create a new instance of CSharpGeneratorSettings the Swagger default is removed and the JSON Schema default is used... I need to find a solution for this so that always Swagger is used when the input is a swagger spec...
