### ISSUE TITLE
RefClass generated and Enum naming

### ISSUE THREAD

**Issue by cluen** [NSwag/NSwag#379]
With the latest version of nswag studio i get some errors:

1. There is a generated Ref class? What is this? 
` 
public partial class Ref_5c2fc86d_a70e_4466_b823_71692804053a : INotifyPropertyChanged
    {
    
        public event PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return JsonConvert.SerializeObject(this);
        }
        
        public static Ref_5c2fc86d_a70e_4466_b823_71692804053a FromJson(string data)
        {
            return JsonConvert.DeserializeObject<Ref_5c2fc86d_a70e_4466_b823_71692804053a>(data);
        }
        
        protected virtual void RaisePropertyChanged([CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    } 
`
2. The request parameter of a post method isn't generated if 'Assembly is using ASP.NET Core' is checked
3. Enum naming with enum handling as integer get's names like this:
` public enum StatusAsInteger
    {
        Unplaned = 0,
        Planed = 1,
    } `

**Comment by rsuter** [comment]
3. Fixed: https://github.com/NJsonSchema/NJsonSchema/commit/9d970d353de3fc5015b20408d2cdfa0c73845a70

**Comment by rsuter** [comment]
1: Can you provide a sample model class where I can reproduce this?
2: For ASP.NET Core you need to apply the [FromBody] attribute I think

**Comment by rsuter** [comment]
1: Should be fixed with this: https://github.com/NJsonSchema/NJsonSchema/pull/230
