### ISSUE TITLE
Poll: Remove all constructors from CSharp client template?

### ISSUE THREAD

**Issue by rsuter** [NSwag/NSwag#381]
My idea was to remove ~~all~~ some constructors from the generated C# client code ~~and also the configuration setting (which generates an additional ctor with a configuration parameter)~~.

You can then add your own ctors via a partial class, so everything is still possible. 

The idea behind this is, that you can have exactly the ctors you need and no ctors are generated which (in your scenario) may not be allowed. Also this is better for DI frameworks as you can enforce a specific ctor by not having a default ctor. 

**What do you think?**
**Is there a scenario we could not support with this change?**

**Scenario: Default BaseUrl is provided by the spec**

Currently, we have these ctors: 

```
[GeneratedCode("NSwag", "6.14.6138.28998")]
public partial class GeoClient 
{
    public GeoClient() : this("http://localhost:13452") { }

    public GeoClient(string baseUrl)
    {
        BaseUrl = baseUrl; 
    }

    public string BaseUrl { get; set; }
```

The new output would be: 

```
[GeneratedCode("NSwag", "6.14.6138.28998")]
public partial class GeoClient 
{
    public string BaseUrl { get; set; } = "http://localhost:13452"; 
```

**Scenario: Configuration class is set** 

When the configuration class setting is set we generate a single ctor (the BaseUrl can/must be set in the base class' ctor using the config object): 

```
public partial class ConsumersClient : ClientBase, IConsumersClient
{
    public ConsumersClient(ClientBaseConfig config) : base(config)
    {
    } 

    public string BaseUrl { get; set; }
```

**Scenario: No BaseUrl is provided by the spec** 

When no default BaseUrl is available we still generate a ctor but only if the configuration class is not set (in this case the BaseUrl must be set in the base class with the configuration object...): 

```
[GeneratedCode("NSwag", "6.14.6138.28998")]
public partial class GeoClient 
{
    public GeoClient(string baseUrl)
    {
        BaseUrl = baseUrl; 
    }

    public string BaseUrl { get; set; } 
```

**Comment by cpx** [comment]
It makes sense to me. If the generated ctors only assign properties that could be moved out as in your example.
