### ISSUE TITLE
Client handling of error status codes.

### ISSUE THREAD

**Issue by cnash** [NSwag/NSwag#382]
I have a REST API endpoint that returns a list of records and supports paging. If there are no records found, it returns 404. This is configured as an expected response in the Swagger. I used NSwagStudio to generate client-side code.  This appears in the client-side code:

```
            if (status_ == "404") 
            {
                throw new SwaggerException("A server side error occurred.", status_, responseData_, null);
            }
```

1) Is this configurable?
2) 404 is, by definition, a client-side error, not a server-side error (as are all [4xx HTTP status codes](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4))

**Comment by rsuter** [comment]
Can you post the swagger spec?

**Comment by cnash** [comment]
I can't post mine, but I'll try to recreate with minimal example and post that.

**Comment by rsuter** [comment]
No, its ok... what do you expect from the generator? Another exception message? Is this message defined in your spec and in which property?

**Comment by cnash** [comment]
Here's my controller:
```
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.SwaggerGen.Annotations;

namespace SandboxApi.Controllers
{
    [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        [HttpGet]
        [SwaggerOperation("GetValueList")]
        [SwaggerResponse(200, type: typeof(IEnumerable<string>))]
        [SwaggerResponse(404)]
        public virtual IActionResult Get()
        {
            return Ok(new string[] { "value1", "value2" });
        }
    }
}
```

Here's the swagger.json:
```
{
	"swagger" : "2.0",
	"info" : {
		"version" : "v1",
		"title" : "API V1"
	},
	"basePath" : "/",
	"paths" : {
		"/api/Values" : {
			"get" : {
				"tags" : ["Values"],
				"operationId" : "GetValueList",
				"consumes" : [],
				"produces" : [],
				"responses" : {
					"204" : {
						"description" : "No Content"
					},
					"200" : {
						"description" : "OK",
						"schema" : {
							"type" : "array",
							"items" : {
								"type" : "string"
							}
						}
					},
					"404" : {
						"description" : "NotFound"
					}
				},
				"deprecated" : false
			}
		}
	},
	"definitions" : {},
	"securityDefinitions" : {}
}
```

**Comment by cnash** [comment]
At the least, I'd expect an exception from a client-side error to say "client-side" rather than "server-side". It would probably do better to pull the message from the "description" field in the swagger.

**Comment by rsuter** [comment]
Please retry with the latest build artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by cnash** [comment]
Looks good. :)

**Comment by skironDotNet** [comment]
I'm late with my comment but NotFound means null on the server side, so I would expect the client to return null instead of throwing, It's better to do null check to know it was not found than to do try catch.

**Comment by jeremyVignelles** [comment]
@skironDotNet Sorry, but null means 204 by default on the server side. There is an in-famous issue about the bad handling of generated code (200 vs 204). If you want "NotFound" to return null, you'll have to override the template

**Comment by skironDotNet** [comment]
@jeremyVignelles would you be able to point me to "the template" where and how to override? Do you mean fork it on github and modify something, or is there a built in mechanism I could configure or override? What would be the file name or class name?
Thank you
