### ISSUE TITLE
Documentation needed for Calling generated client for Typescript 

### ISSUE THREAD

**Issue by sankp** [NSwag/NSwag#385]
Hello,

I am able to generate the typescript code for WebAPI calls and able to call them as well. I am not sure i am calling it right or wrong way from my angular2 component .ts file
After getting data i am getting many internal errors.
Is there proper documentation available for this which can show how to utilize client.ts proper way.
My client.ts have all generated output for Typescript using nswag windows tool.
I have app.component.ts file from where i am calling client.ts function call getMembers();
I am able to get all data from the web api but it is giving some internal errors later. one of them is every property in returned json in _body is not defined.

![image](https://cloud.githubusercontent.com/assets/9613276/19781272/35d7db1c-9c4e-11e6-9c1b-6ceedb151702.png)

**Comment by rsuter** [comment]
The names are converted to js style, try `firstName` in your html (lower camel case)

**Comment by rsuter** [comment]
Could you solve your problem?

**Comment by sankp** [comment]
Yes I was able to solve the problem. Thanks...
