### ISSUE TITLE
Error after upgrading to v6.17

### ISSUE THREAD

**Issue by vdecristofaro** [NSwag/NSwag#392]
Hi,
I am getting this error in the latest build. I dont have the same error in my compilation log. 
Probably is due to code in my trunk but can you help with finding the reason of the error?

Also could you please validate that the new parameter `basePath` is correctly evaluated?

```

D:\github>D:\webtools\nswag\nswag webapi2swagger /assembly:D:\VisualStudio\MyProject\MyProject.WebAPI\bin\MyProject.WebAPI.dll /controller:MyProject.WebAPI.Controllers.Api.MyController /output:
.\restapi\cp_swagger.json /infotitle:"My Project" /infodescription:"Documentation of My Project API module" /infoversion:1.0 /serviceschemes:https /servicehost:api.myserver.com /servicebasepath:/

NSwag command line: NSwag toolchain v6.17.6146.29531 (NJsonSchema v5.7.6142.39228) (x64)
Visit http://NSwag.org for more information.

```

Here is the Exception

`System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'double' to 'decimal?'. An explicit conversion exists (are you missing a cast?)
`
I can provide you with the full stack trace if needed.

**Comment by rsuter** [comment]
I think we had a fix for this in NJsonSchema v5.9, but NSwag 6.17 is running with NJsonSchema v5.7... I will update and release...

**Comment by rsuter** [comment]
Try again with v6.18, released in 5 mins (servicebasepath is working for me when set in the UI)

**Comment by vdecristofaro** [comment]
yes. I confirm that v6.18 solves the problem
Thanks
