### ISSUE TITLE
typescript client generator with Date Time Type momentJS

### ISSUE THREAD

**Issue by ismcagdas** [NSwag/NSwag#394]
Hi,

We are generating typescript anguylar2 service proxies with NSwag and it's working great for us.
But if we choose MomentJS as Date Time Type, Nswag does not import moment in generated output.
Because of that, we get an error "cannot find namespace moment".

If we add an import line like this, error goes away.
`import * as moment from "moment";` 

I'm not sure this is the correct way or not ? Can you advise ?
If this is the right way, can you add this line to generated output ?

Thanks.

**Comment by rsuter** [comment]
The current code requires you to use momentjs as global module with global typings. But you can add your import with extension code. Just create a new file "service.extensions.ts" and paste your import there. Then use the option `/extensionCode:service.extensions.ts` of the command line and the import should be inserted at the top of your generated script.

See
- https://github.com/NJsonSchema/NJsonSchema/wiki/TypeScriptGenerator#extended-classes-and-extension-code
- https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code

**Comment by rsuter** [comment]
Just made a fix for this scenario, use v6.19

**Comment by ismcagdas** [comment]
Thanks, I will try this soon.
