### ISSUE TITLE
Question, angular2, how to customize API_BASE_URL of several clients

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#395]
Hi,

This might not be directly related to NSwag, but you might be able to explain me how to use this feature as you support it.

Let's say I have generated 2 clients which looks like this : 
```

export const API_BASE_URL = new OpaqueToken('API_BASE_URL');
export const JSON_PARSE_REVIVER = new OpaqueToken('JSON_PARSE_REVIVER');

@Injectable()
export class ClientA {
    private http: Http = null;
    private baseUrl: string = undefined;
    private jsonParseReviver: (key: string, value: any) => any = undefined;

    constructor(@Inject(Http) http: Http, @Optional() @Inject(API_BASE_URL) baseUrl?: string, @Optional() @Inject(JSON_PARSE_REVIVER) jsonParseReviver?: (key: string, value: any) => any) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "http://dev.A.test.com/api/frontend";
        this.jsonParseReviver = jsonParseReviver;
    }
...
}
```

and
```

export const API_BASE_URL = new OpaqueToken('API_BASE_URL');
export const JSON_PARSE_REVIVER = new OpaqueToken('JSON_PARSE_REVIVER');

@Injectable()
export class ClientB {
    private http: Http = null;
    private baseUrl: string = undefined;
    private jsonParseReviver: (key: string, value: any) => any = undefined;

    constructor(@Inject(Http) http: Http, @Optional() @Inject(API_BASE_URL) baseUrl?: string, @Optional() @Inject(JSON_PARSE_REVIVER) jsonParseReviver?: (key: string, value: any) => any) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "http://dev.B.test.com/api/frontend";
        this.jsonParseReviver = jsonParseReviver;
    }
...
}
```

Now let's says this is the dev config, and I want to change the urls for prod config
`http://dev.A.test.com/api/frontend` => `http://A.test.com/api/frontend`
and
`http://dev.B.test.com/api/frontend` => `http://B.test.com/api/frontend`

How can I inject both services but each with a different API_BASE_URL ? 

Thanks a lot

**Comment by rsuter** [comment]
I haven't used this feature yet, but I think this article describes how to use it: http://blog.thoughtram.io/angular/2016/05/23/opaque-tokens-in-angular-2.html

**Comment by no-more** [comment]
Hi,

Thanks, I was on this link too, but I don't know if it works when tokens have the same final. I will try using import as syntax and check if this works.

Thanks.

**Comment by rsuter** [comment]
Could you find a solution?

**Comment by no-more** [comment]
Hi,

Sorry I forget to response, Yes it worked!!! I was worried about name conflict but it's a non issue.

Thanks.
