### ISSUE TITLE
application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by marticrespi** [NSwag/NSwag#398]
Hi,

It's possible to change the content-type of a request to the urlencoded? Define for certain methods are json and some as urlencoded. Or add it in the Parameter content type dropdown.

I know that I can set up a consumes list in PostService, but is added to all methods!

Thanks.

**Comment by rsuter** [comment]
How are you using nswag? If you're using it with the middleware you can write an OperationProcessor and change the request type there...

**Comment by rsuter** [comment]
In this processor you can change the parameter types to FormData..

**Comment by marticrespi** [comment]
Hi rsuter,

Yes, I using with the middleware.

**Startup.cs**

            app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiOwinSettings
            {
                DefaultPropertyNameHandling = PropertyNameHandling.CamelCase,
                PostProcess = service =>
                {
                    service.Info.Title = "Rest Api Net Core Specification";
                    service.Info.Description = "Web methods to manage users and products.";
                    service.Info.Version = "v 1.0";
                    service.Consumes.Add("application/x-www-form-urlencoded");
                }
                //, OperationProcessors = new 
                
            });

If I add to Consumes List (by default there is json already), It shows me two content types in all methods in the controller. For example, I want only urlencoded in Account/Login but in Product/Create only json.

How can I implement this?

Many thanks.

**Comment by rsuter** [comment]
Here is a sample operation processor implementation: 

https://github.com/NSwag/NSwag/blob/305db1d4afcd4179fec2b0ea70127af631cfe4b5/src/NSwag.CodeGeneration/SwaggerGenerators/WebApi/Processors/OperationSecurityScopeAppender.cs

Just check the operation name and set the parameters or produces to "FormData" or "application/x-www-form-urlencoded"

**Comment by marticrespi** [comment]
Hi @rsuter 

Thanks for your help!
