### ISSUE TITLE
Support ASP.NET Core

### ISSUE THREAD

**Issue by dgee2** [NSwag/NSwag#40]
Hi is here any support for this in Asp.net Core (dnx/dotnet)?

**Comment by rsuter** [comment]
The WebApiAssemblyToSwaggerGenerator currently does not support .NET Core because I had problem loading the assemblies (ie reflection exceptions). But this is definitely on the wish list...

**Comment by rsuter** [comment]
Do you know how to compile so that all necessary dlls are in the output directory?

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/pull/46

**Comment by rsuter** [comment]
Swagger spec can be generated for .NET Core with the new ReferencePaths options. Read here for more information: https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator

**Comment by rsuter** [comment]
Moved documentation to: https://github.com/NSwag/NSwag/wiki/WebApiAssemblyToSwaggerGenerator
