### ISSUE TITLE
Swagger tags (as opposed to operation tags)

### ISSUE THREAD

**Issue by vdecristofaro** [NSwag/NSwag#403]
The SwaggerTags attribute does it's job by leveraging operation tags.
What about the tags section in the Schema Object defined in the spec which is an Array Of [Tag Object](http://swagger.io/specification/#tagObject)?

As this section in most cases is a summary of operations tags, shall this be defined by using an extended version Of the SwaggerTags attribute? E.g. A SwaggerTags which also leverage a description field.

What is your opinion on this topic?

**Comment by rsuter** [comment]
Options: 

- Add new attribute: `SwaggerTag("MyTag", "MyDescription")` 
    - How to define the External Documentation Object? Is it needed?
- Add new constructor: SwaggerTags(params SwaggerTag[] tags)
    - Question: Is this even possible in an attribute (i.e. is it allowed to `new` new instances in an attribute ctor)?
    - Should we reference `NSwag.Core` in `NSwag.Annotations` (ugly, dependency should be avoided) or copy the classes (also ugly)

What do you think?

**Comment by vdecristofaro** [comment]
I would go with the first option.
The pluralized versions can be left as a quick way to specify multiple tags or deprecated.
Second option cannot be done because of impossibility to new objects in attribute ctors.

**Comment by rsuter** [comment]
Is this ok?

https://github.com/NSwag/NSwag/blob/78e58ae639ae7043325f6f7d34fea12154feb7e1/src/NSwag.CodeGeneration.Tests/WebApi/Attributes/TagsTests.cs

**Comment by vdecristofaro** [comment]
It seems ok to me.

If I am not getting wrong however, document tags can be added by using one of the two attributes at the controller level while adding these to action methods leverages operation tags.

I would have done something more: that is, adding a tag at action method level would add those tags also at document level by merging these with properly defined ones. Example:
```
[SwaggerTag( "Basic", "Basic usage notes" )]
[SwaggerTag( "Advanced", "Advanced usage notes" )]
public async Task<HttpResponseMessage> Create( InputViewModel model ) {
    [...]
}
```

would produce the following swagger

```
{
  "swagger": "2.0",
  "info": {
    "title": "xxxx",
    "description": "xxxxx module",
    "version": "1.0"
  },
  "host": "api.myserver.com",
  "basePath": "/",
  "tags": [
    { "Basic", "Basic usage notes" },
    { "Advanced", "Advanced usage notes" }
  ],
  [...]
  "paths": {
    "/cp": {
      "post": {
        "tags": [
          "Basic", "Advanced"
        ],
      }
    }
}

``` 

This is because most of the times the tags at operation level are used to group operations in the generated docs while the referring group is elsewhere defined (document level).

This should only impact the generations phase where you it should be taken care of merging the resulting tags. Do you see any drawback in this?

**Comment by rsuter** [comment]
The only problem: When operation tags are automatically added to the document tags, then you cannot add tags only to operations (which may be a use case). 

What about if we support the SwaggerTagAttribute on operations and add an option "AddToDocument" (default: false) so that you can specify if it should also be added to the document?

**Comment by vdecristofaro** [comment]
Yes. That will be great.

**Comment by rsuter** [comment]
Check the tests: https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration.Tests/WebApi/Attributes/TagsTests.cs

Is this as expected?
