### ISSUE TITLE
.net core/.net standard port

### ISSUE THREAD

**Issue by mikehaas763** [NSwag/NSwag#404]
Would you be interested in porting the portion of the codebase that can "interpret an Open API spec json file and output to client code" to .net core?

The reason I ask is because NSwag seems to be best at what it does assuming a combination of features/quality/popularity. However, it only runs on windows as a command tool. A first stop gap could be to port that portion to .net standard and publish it as a CLI that can run on win/macos/linux. The next step could then be to write bindings for other popular platforms such as node so that it can be used programmatically. I'm not sure if there's a story yet for writing bindings to .net core libs yet, but it's something that's bound to happen and would be an interesting exercise.

Also, I'm willing to help out with this where I can.

**Comment by rsuter** [comment]
The .NET Core command line tool has just been released (experimental): 

- https://www.nuget.org/packages/NSwag.ConsoleCore/ 
- (https://www.nuget.org/packages/NSwag.AssemblyLoaderCore/)

Its currently packaged as NuGet (NSwag.ConsoleCore) but can be run with `dotnet nswag.dll`
I don't know yet how to distribute the .NET Core command line tools...

**Comment by mikehaas763** [comment]
That's great! Yeah ideally I think it'd be nice to have it published to any popular package manager repos. NPM probably being the first most obvious one. Any idea if .net core currently has a way to build with the runtime embedded for all platforms (linux, macos, and win) so that a single npm package can be used?

I believe in the past when compiling .net core tooling it generated a bash script and a win script alongside that figured out the appropriate way to bootstrap the CLI no matter the OS. So if that's true that would make it easy.

**Comment by rsuter** [comment]
I dont know yet :-) just finished the .net core command line support. Are you interested in looking into this? I have no experience with creating npm modules...

**Comment by mikehaas763** [comment]
Yes, I'll definitely look into it.

**Comment by rsuter** [comment]
https://m.reddit.com/r/dotnet/comments/42s6rt/distributing_net_core_console_applications/

**Comment by rsuter** [comment]
I just tried to create "self-contained deployments" for all platforms: https://github.com/NSwag/NSwag/commit/c5d456926a6bcfabb4c70c4e43a8572fca320f5e

You can run `src\NSwag.ConsoleCore\Publish.bat` which creates an `Output` directory.

This directory contains self-contained binaries for all platforms... We just have to create an NPM package which calls the correct binary depending on the OS. The problem: The output takes approx. 900 megabytes... Maybe we have to package the runtime dependent binaries and add .NET Core as dependency to the NPM module (if this is possible) or as prerequisite to use the module (i.e. show a message that it has to be installed, or install it automatically?). 

See https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/

**Comment by rsuter** [comment]
A runtime dependent publish takes 1.2 mb...

**Comment by mikehaas763** [comment]
Wow, I didn't realize it would take that much space. I figured it would strip out anything that's not needed. I guess it's not the worst thing, could just make it a prerequisite to have .net core installed which is would just be specified in the readme for the npm package.

**Comment by rsuter** [comment]
I think I already have a solution for NPM :)

**Comment by rsuter** [comment]
Yes, it works for me: 
https://www.npmjs.com/package/nswag

**Comment by rsuter** [comment]
I think we should also package the full .NET Framework console app, and run this if the full .NET framework is available...

**Comment by rsuter** [comment]
Ive added the check for .net full. The npm cli pkg now runs either the full cli or .net core cli...

With the next nswag release i will set the npm version to the same as the other packages..

Ill close this issue and we should create specific issues if there are any problems with the .net core cli or npm cli...
