### ISSUE TITLE
Net Core SwaggerUI explanations

### ISSUE THREAD

**Issue by marticrespi** [NSwag/NSwag#405]
Hi, Is there any way to decorate a controller function in net core like this?

    /// <summary>
    /// Creates a TodoItem.
    /// </summary>
    /// <remarks>
    /// Note that the key is a GUID and not an integer.
    ///  
    ///     POST /Todo 
    ///     {
    ///        "key": "0e7ad584-7788-4ab1-95a6-ca0a5b444cbb",
    ///        "name": "Item1",
    ///        "isComplete": true
    ///     }
    /// 
    /// </remarks>
    /// <param name="item"></param>
    /// <returns>New Created Todo Item</returns>
    /// <response code="201">Returns the newly created item</response>
    /// <response code="400">If the item is null</response>
    [HttpPost]
    [ProducesResponseType(typeof(TodoItem), 201)]
    [ProducesResponseType(typeof(TodoItem), 400)]
    public IActionResult Create([FromBody, Required] TodoItem item)

I have tried to explain every method but dont work. The first time the summary tag prints ok into swagguer ui, but then I take it off and always print on every solution execution. Remarks and returns tags never has been displayed, and produces response dont show any description, only the code.

From https://docs.asp.net/en/latest/tutorials/web-api-help-pages-using-swagger.html

I have installed Nswag vía Nuget.

Is not possible with this syntax? If not, I think I should use NSwag.CodeGeneration, any full example to view all possible operations? I have been searching but only I have found ResponseType and Ignore examples.

Thanks.

**Comment by marticrespi** [comment]
I have found an example from Annotations, but with this code:

        /// <summary>
        /// Register an user into the system.
        /// </summary>
        /// <param name="model">Register User object</param>
        /// <returns>HttpStatusCode 200 when is successful.</returns>
        [HttpPost]
        [ResponseType("200", typeof(IActionResult), Description = "Succesfully registered. The next is logging into the system to can obtain the access_token.")]
        [ResponseType("400", typeof(IActionResult), Description = "Bad Request.")]
        [ResponseType("500", typeof(IActionResult), Description = "Internal Server Error.")]

I can't see on ui the summary, explanation register user param, and returns explanation. All the other instructions are ok.

Thanks.

**Comment by rsuter** [comment]
How and in what type of project are you using NSwag? If your using the .NET Core middlewares, maybe you need to install the following NuGet packages: https://github.com/NJsonSchema/NJsonSchema/wiki/XML-Documentation

**Comment by rsuter** [comment]
I just tried to create "self-contained deployments" for all platforms: https://github.com/NSwag/NSwag/commit/c5d456926a6bcfabb4c70c4e43a8572fca320f5e

You can run `src\NSwag.ConsoleCore\Publish.bat` which creates an `Output` directory.
This directory contains self-contained binaries for all platforms... We just have to create an NPM package which calls the correct binary depending on the OS. The problem: The output takes approx. 900 megabytes... Maybe we have to package the runtime dependent binaries and add .NET Core as dependency to the NPM module (if this is possible) or as prerequisite to use the module (i.e. show a message that it has to be installed, or install it automatically?). 

See https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/

**Comment by marticrespi** [comment]
Thanks. I thought this library was implicitly in Nswag package as dependency from Nuget!

**Comment by rsuter** [comment]
Yes, I have to check whether I can do this... So your using the "NSwag.AspNetCore" package? I have to check whether I can add the required dependencies so that you don't have to add them manually...

**Comment by marticrespi** [comment]
Hi!

Yes, I'm on NSwag.AspNetCore 6.21.0! Thanks for your wonderful work!

Kind regards!

**Comment by rsuter** [comment]
The deps are declared: 
https://github.com/NSwag/NSwag/blob/master/src/NSwag.AspNetCore/project.json

Maybe they are nit referenced because they are under .net std 1.6

**Comment by marticrespi** [comment]
Maybe that's why not downloaded when main package is installed!

Thanks again!

**Comment by rsuter** [comment]
Processing remarks tags is still open: https://github.com/NSwag/NSwag/issues/292
