### ISSUE TITLE
Question: How to retrieve server error code and error message?

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#408]
Hi,

I was wondering how can I get server error code without specifying all of them in the swagger definition.
I might be wrong but I would expect that undefined error code would be converted to an error based on the response status code.
Or is there any way to retrieve additional information about the server response in order to be able to handle several answers type ? 
Currently when the status is not defined in the swagger, I only have a generic error `error_no_callback_for_the_received_http_status`

Thanks.

**Comment by rsuter** [comment]
You can use "default" instead a specific http code. The default response will be used for all undefined http codes...

**Comment by rsuter** [comment]
http://swagger.io/specification/#responsesObject

**Comment by no-more** [comment]
Thanks that's what I needed. I wasn't able to find if it's possible to do some wildcard or regexp matches ? like "5*" or /^[45]\d{2}$/
Do you know if such a think is possible with swagger ?

**Comment by rsuter** [comment]
You have to read the spec. But I think this is not possible. It is definitely not supported by NSwag though...

**Comment by no-more** [comment]
Thanks,

I couldn't find such a think in the docs.
