### ISSUE TITLE
NSwag Download

### ISSUE THREAD

**Issue by dgee2** [NSwag/NSwag#41]
Hi,

I'm trying to get hold of NSwag but none of the download links appear to be working for the zip downloads (both from the links on GitHub and AppVeyor)

**Comment by rsuter** [comment]
It works for me... I can download the artifacts here: 
https://ci.appveyor.com/project/rsuter/nswag/build/artifacts

**Comment by dgee2** [comment]
Ok it may be the work proxy having fun again... Any chance you could up load a release into GitHub?

**Comment by dgee2** [comment]
P.S. this is the url that I end up with for the download of the zip. Would be interested to know if that url works for you.
https://storage.googleapis.com/appveyor-artifacts/rsuter-25659/nswag/321/ucwac4uosltiiefk/src/NSwagStudio/bin/NSwag.zip?GoogleAccessId=646512516365-bidt3t59mctt8vti6cffe2sbq65pnmb1@developer.gserviceaccount.com&Expires=1455798401&Signature=M4jb4xJTphLmTwaXBVVcaeqLaxZnCYiFjsnKKFCAWbzhFgFNc%2bj8atms7NoKZYSO65qBrh%2bS2NyFZipY2qMwhoyePGBvZkRKNJPv5xnTQFJQfKpJK8bue%2fiX%2f2ywv6JZ0fXk4hMVY1ZcDHGLCXLTxdgNv5uObTDaAl%2fz4IAtLs%2fVmbez5kpEhDqubNl6WCy4KllQPZITRU4z7ApQzXQRuC5PtFRLzRd8z2iQvOi8l8DSJGbu3eh0GCSJJT5OiZQo2%2fOrYr%2f2HKq44vYmDhQIZl9Z5x35jKeLe6xSa%2bqrn6bGHhEjnVIp5QZJMt2fgAfLwzompqLk5R%2fdq7HGLt%2fAvg%3d%3d

**Comment by rsuter** [comment]
This is the proxy generated URL?

**Comment by rsuter** [comment]
Ok, builds are now automatically pushed to releases page: https://github.com/NSwag/NSwag/releases

**Comment by dgee2** [comment]
Thankyou!
