### ISSUE TITLE
C# Generator: Prefix reserved keywords

### ISSUE THREAD

**Issue by arnederuwe** [NSwag/NSwag#411]
Consider the following WEB API method:

`public IHttpActionResult Get(bool @override = false)`

The generated C# client doesn't take the @ into account, therefore producing invalid code.
There should be a check on all reserved keywords when generating properties and fields, prefixing them with an @
The following resource can be used as a list: https://msdn.microsoft.com/nl-be/library/x53a06bb.aspx

**Comment by rsuter** [comment]
Fixed: https://github.com/NSwag/NSwag/commit/87eff0b10e1fc952673ee3c0d3c49a6dd3286bc9
