### ISSUE TITLE
Serialize $type with Type.FullName in toJS(data?: any) TypeScript method template

### ISSUE THREAD

**Issue by faramos** [NSwag/NSwag#412]
I´m using NSwagStudio and have some polymorphic types. At server, I need to receive the $type value in order to recognize the instance´s Type. Is it possible to add this value into the toJS(data?: any) TypeScript method (Angular2 client)
Thanks in advance

**Comment by rsuter** [comment]
Have you checked this page?
https://github.com/NJsonSchema/NJsonSchema/wiki/Inheritance

**Comment by faramos** [comment]
I didn't know. Thank you!
