### ISSUE TITLE
nswag.exe missing in installer and zipped version

### ISSUE THREAD

**Issue by crazyfx1** [NSwag/NSwag#416]
I tried to use the NSwag command line tool but I noticed the nswag.exe is missing in the MSI-installer (it's not installed in C:\Program Files (x86)\Rico Suter\NSwagStudio) and is also missing in the zip. 

It was included in the 6.21 version though, was it removed on purpose?

**Comment by rsuter** [comment]
This is a bug and not on purpose...

**Comment by rsuter** [comment]
Will fix this today or tomorrow with v7.1

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/b67be888185fc4478c996704de697ac12a8ec8cb

**Comment by rsuter** [comment]
v7.1
