### ISSUE TITLE
Load assembly in NSwagSudio

### ISSUE THREAD

**Issue by sbonello** [NSwag/NSwag#42]
I'm trying to load a WebAPI project DLL in NSwagStudio and keep receiving this error:

```
Could not load file or assembly 'System.Web.Http, Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest 
definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by rsuter** [comment]
Can you provide sample DLLs to reproduce the error?

**Comment by rsuter** [comment]
What .NET version has your web project? Do you select the DLL from the location where all required, dependent DLLs are located?

**Comment by sbonello** [comment]
Version 4.5.

Yes I am selecting the DLL from the bin folder of the web api.

Simon

**Comment by sbonello** [comment]
Will try and generate a stripped down version of the web api which I can
pass over.

**Comment by rsuter** [comment]
Can you try again with v2.1. It is now using .NET 4.6 and you can specify additional DLL paths...

**Comment by rsuter** [comment]
Close because it is not reproducible...
