### ISSUE TITLE
Configuration dependency injection

### ISSUE THREAD

**Issue by lciocci** [NSwag/NSwag#422]
We're using NSwag to generate our service's client proxies. Our client proxies are derived from a base class that's responsible for generating the Bearer token in the proxy's HttpClient Authorization header (using the CreateHttpClientAsync method). The Bearer token is built using entries defined in the application's configuration file (app.config or web.config).

Our applications run in Microsoft Azure. Those applications consist of Azure API/Web API apps and Service Fabric apps. Service Fabric applications store their application configuration information far differently than that of Azure API/Web API apps.

We're looking to use a dependency injection pattern to handle configuration values from different source types. Might there be something that can be used in NSwag when generating the base class and/or CreateHttpClientAsync method that would let us inject our own configuration information?

**Comment by rsuter** [comment]
Either you create your own constructor for DI in a partial class or you define a configuration class: https://github.com/NSwag/NSwag/wiki/SwaggerToCSharpClientGeneratorSettings

In this ctor you take a dependeny and assign it to a class field which then can be used in the other methods...

**Comment by lciocci** [comment]
Great stuff, rsuter. Looking forward to trying this out.

**Comment by rsuter** [comment]
Also see https://github.com/NSwag/NSwag/wiki/SwaggerToCSharpClientGenerator

**Comment by rsuter** [comment]
Did you find out how to do config DI?

**Comment by lciocci** [comment]
Yes - it worked perfectly. Thank you for your help.

Regards,
Louis Ciocci
________________________________

**Comment by rm-code** [comment]
I've been trying to inject a custom configuration object, but it fails on the DI:

`InvalidOperationException: A suitable constructor for type 'WebUi.Services.Backend.BackendClient' could not be located.`

According to the [wiki](https://github.com/RicoSuter/NSwag/wiki/CSharpClientGenerator#provide-configuration-object) the generated client should have three constructors, but in my case it only has one:

```csharp
public partial class BackendClient : BaseClient, IBackendClient
{
	private string _baseUrl = "";
	private System.Lazy<System.Text.Json.JsonSerializerOptions> _settings;

	public BackendClient(IBaseClientConfiguration configuration) : base(configuration)
	{
		_settings = new System.Lazy<System.Text.Json.JsonSerializerOptions>(CreateSerializerSettings);
	}
	...
```

This is my DI configuration in `Program.cs`:

```csharp
builder.Services.AddScoped<IBaseClientConfiguration, BaseClientConfiguration>();
builder.Services.AddHttpClient<IBackendClient, BackendClient>(client =>
{
  client.BaseAddress = new Uri("<snip>");
});
```

@RicoSuter Any ideas?
