### ISSUE TITLE
[TypeScript] Feature request, configure the casing for generating a typescript class constructor

### ISSUE THREAD

**Issue by arnederuwe** [NSwag/NSwag#426]
Hi,

I'm generating an Aurelia fetch client from a Web API. First I generate a swagger def file from the assembly, and then I use that file to generate a client in TypeScript.
We configured our Web API  to return JSON with camelCasing instead of PascalCasing, and this presents an issue with the generated TypeScript client, as the constructor is using data["PropertyName"] where it should be looking for "propertyName" instead.
Could it be an option to make this configurable as a command line parameter? It's not a big deal for us as we are building our API from scratch, but I can imagine it being an issue where the API is already being consumed by existing apps.

**Comment by rsuter** [comment]
You need to set `DefaultPropertyNameHandling` to `CamelCase`: 
https://github.com/NJsonSchema/NJsonSchema/wiki/JsonSchemaGeneratorSettings

I recommend to use NSwagStudio to create an .nswag file and execute this via command line... In the UI you see all available options...

**Comment by rsuter** [comment]
You can see all available settings in this class: https://github.com/NSwag/NSwag/blob/master/src/NSwag.Commands/Commands/WebApiToSwaggerCommandBase.cs

**Comment by rsuter** [comment]
Or just run "nswag help" and check the WebApiToSwagger command parameters

**Comment by arnederuwe** [comment]
Great, missed that apparently..
 thanks for the quick reply!
