### ISSUE TITLE
TypeScript Code Generation incorrect parameter names

### ISSUE THREAD

**Issue by DDtMM** [NSwag/NSwag#427]
I have parameters with the names $top, $skip, and $orderby.  The json that is generated is correct, for example $top looks like this:
```
{  
  "name":"$top",
  "in":"query",
  "description":"Optional number of records to be returned",
  "required":false,
  "type":"integer"
},
```
The issue is that TypeScript Code Generation removes the $from the parameter name when creating the querystring parameter.

The code generated:
`url_ += "orderby=" + encodeURIComponent("" + orderby) + "&";`

Should read:
`url_ += "$orderby=" + encodeURIComponent("" + orderby) + "&";`

**Comment by rsuter** [comment]
Please test with the CI artifacts as soon as the build is ready: 
https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by rsuter** [comment]
Is the issue fixed for your scenario?

**Comment by DDtMM** [comment]
This was fixed.  Thank you.
