### ISSUE TITLE
Need to be able to generate interfaces with optional properties

### ISSUE THREAD

**Issue by simeyla** [NSwag/NSwag#428]
I desperately need to be able to generate interfaces for typescript with optional ? properties.

This is exactly how interfaces are described in the typescript documentation : 

> Not all properties of an interface may be required. Some exist under certain conditions or may not be there at all. These optional properties are popular when creating patterns like “option bags” where you pass an object to a function that only has a couple of properties filled in.
https://www.typescriptlang.org/docs/handbook/interfaces.html

I often pass an 'option bag' to my server where all parameters aren't required..

I saw some previous discussion on the subject that just didn't make sense to me. I should be able to decide what is optional but cannot see any way to do that.

For instance I may have a 'SearchOptions' object with various optional properties:

   export interface SearchOptions
   {
      int? maxItems;
      string? orderID;
      string? name;
   }

This is basically a 'property bag'. Unfortunately there is no way to create this interface with NSwag and it is very important to me to be able to create do so.

I don't understand why there is no option to do this - unless I am missing it.

Currently I am manually having to create some interfaces that have optional properties, which is kind of a pain.

**Comment by rsuter** [comment]
Can you provide a sample C# class and the generated TypeScript interface as well as the expected TypeScript interface?

**Comment by rsuter** [comment]
Reference: https://github.com/NJsonSchema/NJsonSchema/issues/119#issuecomment-261678401

Maybe we should add an option "GenerateOptionalProperties" so that you can enable this for your scenario...

**Comment by simeyla** [comment]
Hi Rico,
Yes that would be really great. Right now I am just passing undefined which really doesn't work well. 
Thanks for the fast response,
-Simon



		_____________________________

**Comment by rsuter** [comment]
Added GenerateOptionalProperties (default: false) setting: https://github.com/NJsonSchema/NJsonSchema/commit/7bfa8b3d5a609db70403310bc510434e7eac1828

**Comment by rsuter** [comment]
Setting "MarkOptionalProperties" also available in command line and UI

**Comment by MelvLee** [comment]
Is this setting not available in NSwagStudio for C#?

**Comment by RicoSuter** [comment]
It has been renamed to MarkOptionalProperties and this should be available in the UI
https://github.com/RicoSuter/NJsonSchema/commit/2edd83aa131c0e6a031147ee8969b18522f527a8

> Mark optional properties with ?

**Comment by MelvLee** [comment]
I can't find it in the settings tab for the CSharp Client and CSharp Controller. I did find it in the Settings tab for the TypeScript Client

**Comment by RicoSuter** [comment]
It is TypeScript only as c# does not support ? yet

**Comment by MelvLee** [comment]
OK. Can you tell me how should I specify for example an optional integer property in openapi? The c# code for an integer marked as required looks the same as an integer not marked as required. Below is the specification that I have used:

    Resource:
      type: object
      required:
      - num1
      properties:
        num1:
          type: integer
        num2:
          type: integer

**Comment by RicoSuter** [comment]
`Nullable<int>`?

**Comment by MelvLee** [comment]
Yes. Is it possible to use a setting so that NSwagStudio generates Nullable<int> for a optional integer property in openapi?

**Comment by shivanaru** [comment]
@RicoSuter - Is there a way to mark ALL properties as optional with the TypeScript client? I know there is - "Mark optional properties with ?". But looking for all properties regardless.
