### ISSUE TITLE
Breaking change in header parameters

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#429]
Hi,

I was previously using v7.0 but now in 7.1 I have a found a breaking change in the way parameters are handled.
For example :
```
          {
            "type": "string",
            "name": "language-code",
            "in": "header",
            "required": false
          },
```
is now converted to `"language_code": language_code,`
instead of `"language-code": language_code,`

Thanks.

**Comment by rsuter** [comment]
I think https://github.com/NSwag/NSwag/commit/8309e7108f6dcd0178d553fed778494bd6dbd3c4 fixes your problem... 

Can you try with the latest CI build? 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by no-more** [comment]
Hi,

Thanks but this new release does not work at all. After installation 503 errors generate new type of error messages more like an exception.
And for opened swagger that are accessible (normal case of course) the generate button does nothing. No error and no output.

**Comment by rsuter** [comment]
Can you provide more information about the problems? All my integration tests and unit tests still works...

**Comment by rsuter** [comment]
What do you mean with "openend swagger" file? An .nswag file? Can you provide the nswag file so I can inspect it?

**Comment by rsuter** [comment]
Can you also test with the latest CI? https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

Should have no changes to your installed CI build..

**Comment by no-more** [comment]
Sorry for late response I didn't get the email notification.

Here is a screenshot of the new error message

![err](https://cloud.githubusercontent.com/assets/3856871/20465239/5f92e500-af72-11e6-82d5-d6c07ad4d5d0.jpg)

Before this update the error message was a clean warning saying 503.

**Comment by no-more** [comment]
But this error is only for some unreachable host. Which is not very important.

My issue is with other services which are working. I correctly get the swagger definition. but generation does absolutely nothing. I have no error but also no output in any tabs.

Thanks.

**Comment by rsuter** [comment]
Can you connect with me via skype: rico.suter
I wanted to create a release today, but this makes me nervous...

**Comment by no-more** [comment]
ok, I have tried to write to you but skype shows me several contact. did you get my message ?

**Comment by rsuter** [comment]
No, haven't received anything...
