### ISSUE TITLE
Custom serializers

### ISSUE THREAD

**Issue by SebastianStehle** [NSwag/NSwag#435]
I have a set of classes with custom json serializers, e.g. Money, Language and so on. How would I handle them in NSwag? At the moment I see their properties in my output.

**Comment by rsuter** [comment]
Add a type mapper: https://github.com/NJsonSchema/NJsonSchema/wiki/Type-Mappers

Or use the json schema attribute: https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema/Annotations/JsonSchemaAttribute.cs

... to specify the type of the class

**Comment by rsuter** [comment]
See https://github.com/NJsonSchema/NJsonSchema/wiki/JsonSchemaGenerator#custom-type-and-format-for-class

**Comment by SebastianStehle** [comment]
Thanks a lot, looks very good :)

**Comment by rsuter** [comment]
Can we close this issue?

**Comment by SebastianStehle** [comment]
Yes
