### ISSUE TITLE
Error in new Release

### ISSUE THREAD

**Issue by pemola** [NSwag/NSwag#436]
Hello, 

Since this morning when I Try to add NSwag.CodeGeneration from Nuget console in Visual Studio I get an Error that doesn´t let me work.

![image](https://cloud.githubusercontent.com/assets/17745708/20520032/8aec01d0-b0a5-11e6-8fa4-0689e4509fcf.png)

Do you know how could I install previous versión with Nuget console?

Thank you!

**Comment by rsuter** [comment]
Try add

    <#@ import namespace="System.Linq" #>

On top of your T4 template

**Comment by DDtMM** [comment]
I got the same error.  There was an import namespace="System.Linq" already in the .tt file so that wasn't it.

**Comment by rsuter** [comment]
What about 

      <#@ assembly name="System.Core" #>

?

**Comment by rsuter** [comment]
Can you post your T4 template so that i can reproduce the error? (or better: a sample project?)

**Comment by DDtMM** [comment]
I actually have two error that show up.  I am using 7.6.6171.30839.  Both are Compiling Transformation errors:
* The name 'Model' does not exist in the current context [Line 1]
* The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)  [Line 3]

This is a .Net 4.6.2 console application with no additional references than what comes in normally with a new console project and what comes when I get the NSwag CodeGeneration project.  

*Template Attached:* [RequestUrlTemplate.tt.txt](https://github.com/NSwag/NSwag/files/609862/RequestUrlTemplate.tt.txt)

**Comment by rsuter** [comment]
Do you reference the nswag project via nuget or source code/project reference?

**Comment by rsuter** [comment]
It seems that in some way the "RequestUrlTemplate.Extensions.cs" file is missing (where the Model property is defined): 

![image](https://cloud.githubusercontent.com/assets/2603405/20578083/c7237cf2-b1c5-11e6-869b-b4318cdc29ff.png)

My problem is, that I don't understand how you use the project... If you use the DLLs the tpls are already compiled into the assembly and you shouldn't get these errors.

**Comment by pemola** [comment]
I have tried with previous version and it works.
I'm not authorized to post my t4 template, but the error occurs when you add the Nswag.CodeGeneration library via Nuget and then compile the project.
My project uses Entity Framework 6 and it's connected to an Oracle Database.

**Comment by rsuter** [comment]
Ah I see, just delete the created CodeGenerators directory in your project...
