### ISSUE TITLE
Command line: webapi2swagger does not work unless controller parameter is provided

### ISSUE THREAD

**Issue by ta-stott-oe** [NSwag/NSwag#439]
The following commands result in an unhandled exception:
`nswag.exe webapi2swagger /assembly:MyAssembly.dll /controllers:Controller1,Controller2 /output:swagger.json`
`nswag.exe webapi2swagger /assembly:MyAssembly.dll /output:swagger.json`

> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Property Get method was not found.
>     at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
>     at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
>     at NConsole.ArgumentAttribute.GetValue(IConsoleHost consoleHost, String[] args, PropertyInfo  property, IConsoleCommand command, Object input)
>     at NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()

I think it's because, as of [this commit](https://github.com/NSwag/NSwag/commit/ed61968863bd32961b5c6c858df600831dbe381c#diff-56f3fd3641289595e32ee0dadd645bb2), `WebApiToSwaggerCommandBase.ControllerName` no longer has a getter and NConsole is unhappy about this.

A workaround is to supply the `controller` parameter with an empty value:
`nswag.exe webapi2swagger /assembly:MyAssembly.dll /controller: /output:swagger.json`

Nice library by the way, thanks!

**Comment by rsuter** [comment]
fixed in v7.5, released just now
