### ISSUE TITLE
Question: URL prefix

### ISSUE THREAD

**Issue by SebastianStehle** [NSwag/NSwag#441]
Hi, I am running my API in Asp.net core under a prefix with app.MapPath. Therefore all my URLs are wrong. Is there a setting for it, I don't see?

**Comment by rsuter** [comment]
You can set the MiddlewareBasePath: https://github.com/NSwag/NSwag/wiki/OwinGlobalAsax

**Comment by SebastianStehle** [comment]
This works for me to host the middleware with app.MapPath, but the urls of the API operations are still wrong

**Comment by rsuter** [comment]
You can set the BasePath with the PostProcess action setting or transform all urls in a document processor. Or what is your suggestion?

**Comment by SebastianStehle** [comment]
Works perfectly. Thank you.
