### ISSUE TITLE
New lines in remarks.

### ISSUE THREAD

**Issue by SebastianStehle** [NSwag/NSwag#442]
I try to create some new lines in the remarks. According to the specification I need to create either

* \n\n
* <br>

I tried everything, e.g.

    <remarks>
		Gets all configured client keys for the app with the specified name.
		<para />
		Required Role: Owner
	</remarks>
	
or 

	<remarks>
		Gets all configured client keys for the app with the specified name.
		<br />
		Required Role: Owner
	</remarks>
	
or 

	<remarks>
		Gets all configured client keys for the app with the specified name.
		
		Required Role: Owner
	</remarks>
	
or 

	<remarks>
		Gets all configured client keys for the app with the specified name.

		
		Required Role: Owner
	</remarks>
	
But my result always looks like this:

"description": "Gets all configured client keys for the app with the specified name.\nRequired Role: Owner",

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/570e8b4c08364953be9b4681a48320687e074558
