### ISSUE TITLE
Inaccessible due to its protection level

### ISSUE THREAD

**Issue by kvanover** [NSwag/NSwag#444]
I have a problem when running the NSwag.ConsoleCore in a aspcore project with "dotnet nswag" to generate the swagger.json:

"postcompile": [
      "dotnet nswag webapi2swagger /assembly:%compile:OutputFile% /output:swagger.json"
    ]

First of all, it works in the "NSwag.Console", but it doesn't in the "NSwag.ConsoleCore"

**Exception: 'NJsonSchema.Infrastructure.DynamicApis.PathGetDirectoryName(string)' is inaccessible due to its protection level**

If I look at the NSwagCommandProcessor, Line 43, it excecutes 
var binDirectory = DynamicApis.PathGetDirectoryName(((dynamic)typeof(NSwagCommandProcessor).GetTypeInfo().Assembly).CodeBase.Replace("file:///", string.Empty));

DynamicApis is internal and I have looked at the NJsonSchema for the InternalsVisibleTo, what seems to be there, but apparently it doesn't work with  netcoreapp1.0.

**Comment by kvanover** [comment]
Perfect, I will test it

**Comment by rsuter** [comment]
Can only be tested after release... please wait.

**Comment by rsuter** [comment]
Ok, v7.6 is released, please try with this version...
