### ISSUE TITLE
Typescript Template

### ISSUE THREAD

**Issue by BringerOD** [NSwag/NSwag#447]
First of all thanks for all of your hard work.

I am attempting to use the TypeScript Fetch generated code.

I guess I am a confused on whether the generated code is design to be edited after the fact and never be generated again or not.  

The API call below produces a CompanyUser object when everything goes right and a list of errors ( string[] ) when its a bad request or status 400.  The promise on the template is of typed to return a  CompanyUser regardless of its an string[] or not .  Is this by design?  I guess I am not sure how to deal with it.  

Was the idea with the template generation that we should generate it and then the modify it?  I was hoping to generate it every time the API changes instead of generating it once then modify it.  

One way to solve this would be to return a object with the response object and all the object results,  something like this.  

```javascript
    class GetUserResult {
      response: Response
      result200: CompanyUser;
      result400: string[];
    }
```

then the function declaration could be.
```javascript
getUser(companyId: string, id: string):  Promise<GetUserResult > {}
```

This would allow the developer to import this code and then deal with all of the response types.

Here is the typescript that is produced and the json swagger below.
```javascript
  getUser(companyId: string, id: string):  Promise<CompanyUser> {
        let url_ = this.baseUrl + "/api/companies/{companyId}/users/{id}"; 
        if (companyId === undefined || companyId === null)
            throw new Error("The parameter 'companyId' must be defined.");
        url_ = url_.replace("{companyId}", encodeURIComponent("" + companyId)); 
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));

        return this.http.fetch(url_, {
            method: "GET",
            headers: {
                "Content-Type": "application/json; charset=UTF-8"
            }
        }).then((response) => {
            return this.processGetUser(response);
        });
    }

    private processGetUser(response: Response) {
        return response.text().then((data) => {
            const status = response.status.toString(); 

            if (status === "204") {
            }
            else
            if (status === "200") {
                let result200: CompanyUser = null; 
                let resultData200 = data === "" ? null : JSON.parse(data, this.jsonParseReviver);
                result200 = resultData200 ? CompanyUser.fromJS(resultData200) : new CompanyUser();
                return result200; 
            }
            else
            if (status === "400") {
                let result400: string[] = null; 
                let resultData400 = data === "" ? null : JSON.parse(data, this.jsonParseReviver);
                if (resultData400 && resultData400.constructor === Array) {
                    result400 = [];
                    for (let item of resultData400)
                        result400.push(item);
                }
                throw result400; 
            }
            else
            if (status === "404") {
            }
            else
            if (status === "500") {
            }
            else
            {
                throw new Error("error_no_callback_for_the_received_http_status"); 
            }
        });
    }

    /**
```
Here is the swagger json 
```javascript
"/api/companies/{companyId}/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "GetUser",
        "consumes": [],
        "produces": [],
        "parameters": [
          {
            "name": "companyId",
            "in": "path",
            "required": true,
            "type": "string",
            "format": "uuid"
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "format": "uuid"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/CompanyUser"
            }
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "NotFound"
          },
          "500": {
            "description": "InternalServerError"
          }
        },
        "deprecated": false
      },
```

**Comment by rsuter** [comment]
**The golden rule of code generation:** Never manually change generated code; use one of the extensions points to modify it (i.e. partial classes or extension code) or change the generators input. 

In your sample, everything is correct. And I think you cannot implement this better yourself... You can use this like that: 

```
var client = new Client();
client.getUser("myCompany", 5).then(user => {
    // Success: Process user
}).catch(exception => {
    // Fail: Bad HTTP code
    if (Array.isArray(exception)) {
        // Process error string array
    }
});

The problem is, that the type of a promise only specifies the success type, the rejected type cannot be specified (this is not possible because the fail type can be of any type). 

I'm thinking about an option to wrap all exception with an exception object so that you can access the HTTP status code and type information.

**Comment by rsuter** [comment]
Another problem I saw in your Swagger spec is that the 404 and 500 errors do not throw because they have no return type. I think in this case we should throw a generic exception so that the promise is rejected in these cases....

**Comment by BringerOD** [comment]
Thanks for the quick reply. 

Yes, the 404 and 500 do not have any data by design.  

Is there a way you can return the status code or maybe even the entire response object.  I have a requirement that specifies when the request is not successful I show a different message per status code 400, 404, 500,  etc.  With the current implementation there is no way for me to do this.

If I cannot get the response object,  the original status code would do.

**Comment by rsuter** [comment]
The newest change generates the following code...

    private processGetUser(response: Response) {
        return response.text().then((data) => {
            const status = response.status.toString(); 

            if (status === "204") {
            }
            else
            if (status === "200") {
                let result200: CompanyUser = null; 
                let resultData200 = data === "" ? null : JSON.parse(data, this.jsonParseReviver);
                result200 = resultData200 ? CompanyUser.fromJS(resultData200) : new CompanyUser();
                return result200; 
            }
            else
            if (status === "400") {
                let result400: string[] = null; 
                let resultData400 = data === "" ? null : JSON.parse(data, this.jsonParseReviver);
                if (resultData400 && resultData400.constructor === Array) {
                    result400 = [];
                    for (let item of resultData400)
                        result400.push(item);
                }
                throw result400; 
            }
            else
            if (status === "404") {
                throw new Error("error_http_status_404"); 
            }
            else
            if (status === "500") {
                throw new Error("error_http_status_500"); 
            }
            else
            {
                throw new Error("error_no_callback_for_the_received_http_status"); 
            }
        });
    }

I'll create a release with this change... And then I'll start changing the output to use a SwaggerException class with StatusCode property...

**Comment by BringerOD** [comment]
Again, thanks for the quick turn around and the help.   

I think I will have to wait for the exception changes.  

When the swagger exception code implementation occurs,  will I be able to discern the 400 status code from the 404 or 500?  Will they all be thrown as exceptions?

The 400 has an array of strings, for my situation at least, and I don't think check if its a an array is a good idea?  It needs to be clearer that that. 

I guess I am not sure why you would not send back the response so the developer can work with it?   You can't code all possible scenarios.

**Comment by rsuter** [comment]
In the next version SwaggerException objects (with status, response and result properties) are thrown. The default is that http codes with models are directly thrown, but you can choose to always wrap the result in a SwaggerException (WrapExceptions setting). All http codes which are not success (ie 200 or 204) are thrown because a promise can only have one success type. 

How do you use NSwag? Via command line or NSwagStudio? A test version will be available soon.

**Comment by rsuter** [comment]
You can download the latest msi installer from here: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

The described behavior and setting is available in this latest version.

Is this working for you?

**Comment by BringerOD** [comment]
Awesome!  Again thanks for the help.

I tried it out and I am getting this error.  I am using typescript 2.1.  That might be the problem.

```javascript

ERROR
api.ts(951,12): error TS2322: Type 'Promise<Response>' is not assignable to type 'Promise<string>'.


  /**
   * @return OK
   */
  apiCompaniesByIdGet(id: number): Promise<string> {
    let url_ = this.baseUrl + "/api/Companies/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));

    return this.http.fetch(url_, {                  ////  ERROR HERE
      method: "GET",
      headers: {
        "Content-Type": "application/json; charset=UTF-8"
      }
    }).then((response) => {
      return this.processApiCompaniesByIdGet(response);
    });
  }

  private processApiCompaniesByIdGet(response: Response) {
    return response.text().then((responseText) => {
      const status = response.status;

      if (status === 200) {
        let result200: string = null;
        let resultData200 = responseText === "" ? null : JSON.parse(responseText, this.jsonParseReviver);
        result200 = resultData200 !== undefined ? resultData200 : null;
        return result200;
      } else if (status !== 200 && status !== 204) {
        return this.throwException("An unexpected server error occurred.", status, responseText);
      }
      return null;
    });
  }

```

**Comment by rsuter** [comment]
With the latest release, I removed the return statements of the throwException calls. But I don't think this solves the problem...

Can you tell me, how to change the code so that it compiles? As I see it, in this line

      return this.processApiCompaniesByIdGet(response);

the response seems to be of type string but the API requires a Response object... Maybe you are using the wrong d.ts files? Are you using these?:

https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#fetch

Or what d.ts files are you using?

**Comment by BringerOD** [comment]
Changing the return time to match works.  Not sure why though.  

From

```javascript
  private processApiCompaniesByIdGet(response: Response)  {
```

To

```javascript
private processApiCompaniesByIdGet(response: Response) :Promise<string> {
```
```javascript


Full code
  /**
   * @return OK
   */
  apiCompaniesByIdGet(id: number): Promise<string> {
    let url_ = this.baseUrl + "/api/Companies/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));

    return this.http.fetch(url_, {
      method: "GET",
      headers: {
        "Content-Type": "application/json; charset=UTF-8"
      }
    }).then((response) => {
      return this.processApiCompaniesByIdGet(response);
    });
  }

  private processApiCompaniesByIdGet(response: Response) :Promise<string> {
    return response.text().then((responseText) => {
      const status = response.status;

      if (status === 200) {
        let result200: string = null;
        let resultData200 = responseText === "" ? null : JSON.parse(responseText, this.jsonParseReviver);
        result200 = resultData200 !== undefined ? resultData200 : null;
        return result200;
      } else if (status !== 200 && status !== 204) {
        return this.throwException("An unexpected server error occurred.", status, responseText);
      }
      return null;
    });
  }

```

**Comment by rsuter** [comment]
Yes had this problem too, latest version add any to the process methods...

**Comment by BringerOD** [comment]
Adding "any" does not work for the code above.  

It has to be the same type as the "apiCompaniesByIdGet" call.

```javascript
private processApiCompaniesByIdGet(response: Response) :Promise<string> {
```

**Comment by rsuter** [comment]
Strange.. but ok, will change that tomorrow

**Comment by BringerOD** [comment]
It is strange, when I switch back to typescript 2.0 its fine,  its just 2.1 that has the issue.  The new version is inferring the types a lot more.

**Comment by rsuter** [comment]
More type inferencing is good... can you try again with the latest build?

**Comment by grovesNL** [comment]
The latest seems to work correctly for me with TypeScript 2.1.1 with the newest whatwg-fetch typings. If you still have issues with the latest build, could you verify your version of whatwg-fetch typings and create a gist of a full generated class so we could reproduce the issue?

**Comment by BringerOD** [comment]
Compiles, and I am sure it works.  I will integrate and test later today and confirm.

Thanks again.

**Comment by BringerOD** [comment]
All good.  Thanks again.

**Comment by rsuter** [comment]
The option is now called WrapDtoExceptions...

@grovesnl and @no-more: Do you want to do more tests with the latest version? 

I think the breaking change in the exception handling is acceptable for v7.8... What do you think?

**Comment by grovesNL** [comment]
@rsuter: It looks good to me. I can't see any functionality changes so it appears fine to release.

I think it's ok for v7.8 because the previous behavior is not very useful except for logging.

**Comment by rsuter** [comment]
Version v8.0 (some breaking changes) will be ready soon, please test again with the latest CI build

**Comment by grovesNL** [comment]
@rsuter: The latest CI build seems to work fine for me.
