### ISSUE TITLE
[FromUri] complex type parameter produces invalid function signature

### ISSUE THREAD

**Issue by mkjeff** [NSwag/NSwag#45]
C# WebAPI:
``
..  Get([FromUri] ComplexType request) { ...}
``
typescript :
``
Get(req.prop1: req.prop1, req.prop2: req.prop2, ...) { ... }  //  invalid syntax
``

**Comment by rsuter** [comment]
Complex types in the query string are currently not supported and generated as string parameter.

**Comment by rsuter** [comment]
Added FromUri complex type support (adds first level of properties as query parameters). 

    public class RequestParameterTestController : ApiController
    {
        public class GeoPoint
        {
            public double Latitude { get; set; }

            public double Longitude { get; set; }
        }

        public void FromBodyTest([FromBody] GeoPoint location)
        {

        }

        public void FromUriTest([FromUri] GeoPoint location)
        {

        }
    }

Output: 

    {
      "swagger": "2.0",
      "info": {
        "title": "",
        "version": ""
      },
      "schemes": [],
      "paths": {
        "api/RequestParameterTest/FromBodyTest": {
          "Post": {
            "tags": [],
            "operationId": "FromBodyTest",
            "parameters": [
              {
                "name": "location",
                "in": "body",
                "schema": {
                  "type": [
                    "null",
                    "object"
                  ],
                  "$ref": "#/definitions/GeoPoint"
                }
              }
            ],
            "responses": {
              "204": {}
            }
          }
        },
        "api/RequestParameterTest/FromUriTest": {
          "Post": {
            "tags": [],
            "operationId": "FromUriTest",
            "parameters": [
              {
                "name": "Latitude",
                "in": "query",
                "type": "number",
                "description": ""
              },
              {
                "name": "Longitude",
                "in": "query",
                "type": "number",
                "description": ""
              }
            ],
            "responses": {
              "204": {}
            }
          }
        }
      },
      "definitions": {
        "GeoPoint": {
          "typeName": "GeoPoint",
          "additionalProperties": false,
          "type": "object",
          "properties": {
            "Latitude": {
              "type": "number"
            },
            "Longitude": {
              "type": "number"
            }
          }
        }
      },
      "responses": {},
      "securityDefinitions": {}
    }

**Comment by rsuter** [comment]
Commit https://github.com/NSwag/NSwag/commit/4264a5adcef910ad56fd43e00eb49d3ee714097c and https://github.com/NSwag/NSwag/commit/46c4f7fc85745b396b087fab5363acd7f44891da, NuGet v1.38
