### ISSUE TITLE
`response.status.toString()` in fetch client

### ISSUE THREAD

**Issue by grovesNL** [NSwag/NSwag#450]
Is there a reason it is necessary to perform the cast [`response.status.toString()`](https://github.com/NSwag/NSwag/blob/d05c0791cc440d74ed429dd507b9af78121962f5/src/NSwag.CodeGeneration/CodeGenerators/TypeScript/Templates/FetchClientTemplate.tt#L82) in the fetch client ([example of a generated script](https://github.com/NSwag/NSwag/blob/d05c0791cc440d74ed429dd507b9af78121962f5/src/NSwag.Integration.TypeScriptWeb/scripts/serviceClientsFetch.ts#L170))? Could we just compare directly against the response status code?

It's trivial but I am curious whether there was a reason for this.

**Comment by rsuter** [comment]
In the swagger spec the http status is a string ( eg can be "default" ) the left part is a string (to be safe) and thus i have to call tostring..

Another question: can you connect with me via skype "rico.suter" (switzerland), id like to discuss a breaking change in the ts tpls exception handling

**Comment by grovesNL** [comment]
I see - makes sense, thanks!

Will do.
