### ISSUE TITLE
Custom type name for subtypes

### ISSUE THREAD

**Issue by SebastianStehle** [NSwag/NSwag#455]
Hi, I use the following approach for subtypes. 

Can you extend the system to support custom names? E.g. a custom Attribute would be helpful:

      [KnownNamedType(typeof(CatModel), "Cat")]

I have two problems with the current approach:

* My models have a suffix because I don't want to have naming conflicts with business objects, e.g. Cat and CatDto or CatModel
* I would like to use a reserved for my type name, e.g. String or Boolean.

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/088188e3c4e149008ccb0ff9a2d78bbdfbb302aa

**Comment by SebastianStehle** [comment]
Wow, this is awesome :)

**Comment by rsuter** [comment]
Will be available in NSwag v8.0, please test using the latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by SebastianStehle** [comment]
Sorry for the delay 

I tested it but it failes with:

	System.MissingMethodException: Method not found: 'System.String NJsonSchema.JsonSchema4.GetTypeName(NJsonSchema.ITypeNameGenerator, System.String)'.
	   at NSwag.SwaggerSchemaResolver.AppendSchema(JsonSchema4 schema, String typeNameHint)
	   at NJsonSchema.JsonSchemaResolver.AddSchema(Type type, Boolean isIntegerEnumeration, JsonSchema4 schema) in C:\projects\njsonschema\src\NJsonSchema\JsonSchemaResolver.cs:line 59

**Comment by rsuter** [comment]
What version of NSwag and NJsonSchema are you using?

**Comment by SebastianStehle** [comment]
Sorry, 8.0 from Nuget for .NET Core ... I try to install the packages from a local folder at the moment.

**Comment by rsuter** [comment]
the problem is, that you are using a newer version of NJsonSchema than NSwag v8.0 requires

**Comment by SebastianStehle** [comment]
I installed the version from the nuspec and it works...awesome :)

**Comment by rsuter** [comment]
this is de facto a bug, because NJsonSchema has a breaking change in a minor version change, but this will be fixed in the next nswag release...

**Comment by SebastianStehle** [comment]
I just thought the same ;) ... is there a nuget feed to your build server?

**Comment by rsuter** [comment]
Nope there isn't... but i think ill release now...

**Comment by rsuter** [comment]
Please try again with v8.1

**Comment by SebastianStehle** [comment]
Hi, I realized that it does not work (have only tested the swagger generation so far).

The problem is, that the JsonInheritanceConverter does not handle the schema name correctly. The bugfix is to change the IsKnownTypeTargetType to:

	private bool IsKnwonTypeTargetType(dynamic attribute, string discriminator)
	{
		Type type = attribute.Type;

		if (type == null)
		{
			return false;
		}

		var typeName =
			type.GetTypeInfo().GetCustomAttribute<JsonSchemaAttribute>()?.Name ?? type.Name;

		return typeName == discriminator;
	}

But besides that I would prefer that the schema generation is indepenent of how I serialize and deserialize the json.
