### ISSUE TITLE
Mocks for TypeScript generated Client

### ISSUE THREAD

**Issue by sankp** [NSwag/NSwag#456]
Hello I am trying to create mocks in angular 2 for type script generated client.
But it is not working for me.
Do you have any way to create mock classes and methods of type script generated client ?
in spec.ts

I am using TestBed

**Comment by rsuter** [comment]
How would a nock client class look like?

**Comment by sankp** [comment]
Hello,

I am able to make this working now.
By mistake this generated client was added into provider of component so that's why it was always taking that instead of mock class.
