### ISSUE TITLE
NSwag generator is generating stange types

### ISSUE THREAD

**Issue by chapas** [NSwag/NSwag#458]
Hi,
I'm using this code to generate the Swagger file:
```
private static readonly Lazy<NSwag.SwaggerDocument> _swagger = new Lazy<NSwag.SwaggerDocument>(() =>
        {
            IHttpRoute defaultRoute = new HttpRoute();
            GlobalConfiguration.Configuration.Routes.TryGetValue("DefaultApi", out defaultRoute);
            var settings = new WebApiToSwaggerGeneratorSettings
            {
                DefaultUrlTemplate = (defaultRoute == null ? "DefaultApi" : defaultRoute.RouteTemplate),
                IsAspNetCore = false,
                Title = "VBPISAPI",
                Description = "Business level API from APIS",
                Version = Assembly.GetExecutingAssembly().GetName().Version.ToString()
        };
var generator = new WebApiToSwaggerGenerator(settings);

            List<Type> derivedTypes = VType.GetDerivedTypes(typeof(ApiController), Assembly.GetExecutingAssembly());

            return generator.GenerateForControllers(derivedTypes);
        });
        public static void GenerateSwaggerFile()
        {
            string strJson = JsonConvert.SerializeObject(_swagger.Value, Formatting.Indented);

            File.WriteAllText(AppDomain.CurrentDomain.BaseDirectory + @"vbpisapi-swagger.json", strJson);
        }
````

The file gets generated and somewhere in the definitions I find this:

```
"definitions": {
    "AssessmentStatus": {
      "type": "integer",
      "x-typeName": "AssessmentStatus",
      "x-enumNames": [
        "HIT",
        "NO_HIT",
        "ERROR"
      ],
      "enum": [
        0,
        1,
        2
      ],
      "description": ""
    },
...... more definitions in between ....
    "ref_62c1b6ef_5b69_4574_be54_d9c177526403": {
      "type": "string",
      "x-typeName": "AssessmentStatus",
      "x-enumNames": [
        "HIT",
        "NO_HIT",
        "ERROR"
      ],
      "enum": [
        "HIT",
        "NO_HIT",
        "ERROR"
      ],
      "description": ""
    },
```

Where did this "ref_" came from?

**Comment by rsuter** [comment]
Can you try with the latest CI build? https://ci.appveyor.com/project/rsuter/nswag-25x6o
This is the next version which may solve this problem.

**Comment by rsuter** [comment]
Can you try this with v8.0. This version contains some major schema resolving changes and may fix this issue... otherwise, can you provide a full sample swagger spec to reproduce this?

**Comment by chapas** [comment]
I haven't find the time on my project to test it. Thanks for yours. Will test as soon as I can.

On Dec 11, 2016 18:33, "Rico Suter" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you try this with v8.0. This version contains some major schema resolving changes and may fix this issue... otherwise, can you provide a full sample swagger spec to reproduce this?

**Comment by chapas** [comment]
Got the time (and the need) to test it; checked out commit f89a56ed from master and compiled it locally on VS2015:

This bug is solved, the 'strange types' went away.

But now I'm left with duplicate enum types:

```
 "definitions": {
    "FlightDirection": {
      "type": "integer",
      "x-enumNames": [
        "INBOUND",
        "OUTBOUND"
      ],
      "enum": [
        0,
        1
      ],
      "description": ""
    },
  ...... more definitions in between ....
    "FlightDirection2": {
      "type": "string",
      "x-enumNames": [
        "INBOUND",
        "OUTBOUND"
      ],
      "enum": [
        "INBOUND",
        "OUTBOUND"
      ],
      "description": ""
    },
```

Any hint on this?

**Comment by rsuter** [comment]
Strange, i thought that this is fixed... can you provide sample classes where I can reproduce this?

**Comment by rsuter** [comment]
Ah sorry, this is intentional: Just see the types of these enums, one is integer and the other is string... It seems that you serialize your enums to ints and strings in another place... This is why the generator has to generate two enum definitions.

**Comment by rsuter** [comment]
Just use StringEnumConverter for all enum properties or as a global converter (and enable global string enum handling in nswag)
