### ISSUE TITLE
Typescript camelCase issue

### ISSUE THREAD

**Issue by phinett** [NSwag/NSwag#459]
I am using NSwag to generate both a C# client and a Typescript client, the C# client is working great and using Pascel Casing as i would like it to.

But i'm having an issue with the Typescript output, have a look at this:

```export class CategoryDto { 
    id: number; 
    name: string; 
    isPublished: boolean; 
    parentId: number;

    constructor(data?: any) {
        if (data !== undefined) {
            this.id = data["Id"] !== undefined ? data["Id"] : null;
            this.name = data["Name"] !== undefined ? data["Name"] : null;
            this.isPublished = data["IsPublished"] !== undefined ? data["IsPublished"] : null;
            this.parentId = data["ParentId"] !== undefined ? data["ParentId"] : null;
        }
    }

    static fromJS(data: any): CategoryDto {
        return new CategoryDto(data);
    }

    toJS(data?: any) {
        data = data === undefined ? {} : data;
        data["Id"] = this.id !== undefined ? this.id : null;
        data["Name"] = this.name !== undefined ? this.name : null;
        data["IsPublished"] = this.isPublished !== undefined ? this.isPublished : null;
        data["ParentId"] = this.parentId !== undefined ? this.parentId : null;
        return data; 
    }

    toJSON() {
        return JSON.stringify(this.toJS());
    }

    clone() {
        var json = this.toJSON();
        return new CategoryDto(JSON.parse(json));
    }
}
```

this.id = data["Id"] !== undefined ? data["Id"] : null;

My Asp.Net Core project is returning camelCase properties in json for my Typescript Client, but the typescript client is trying to use Pascel Casing. I can't see anywhere to correct this from the NSwag studio?

Not sure if this is a bug, or I am thinking about this in the wrong way?

**Comment by rsuter** [comment]
You can change the settings in the input tab to use camelcase

**Comment by rsuter** [comment]
![image](https://cloud.githubusercontent.com/assets/2603405/20760164/78f3d856-b71f-11e6-9bd1-b95fc3b1d4e8.png)

**Comment by rsuter** [comment]
Did this work for you?

**Comment by phinett** [comment]
Sorry yes it did.

I wish github would e-mail me when i get a reply!

Thanks.
