### ISSUE TITLE
Namepsace collision

### ISSUE THREAD

**Issue by BenTheBest69** [NSwag/NSwag#464]
I encounter an issue using the T4 script to process my swagger file, after the code was generated I had to replace some code by new version of class name to include the namespace:

code = code.Replace("Required.Default", "Newtonsoft.Json.Required.Default");
code = code.Replace("CancellationToken.None", "System.Threading.CancellationToken.None");
code = code.Replace("CancellationToken cancellationToken", "System.Threading.CancellationToken cancellationToken");

You should consider using full qualify class name with their namespace in order to avoid this.

Hope this help.

**Comment by rsuter** [comment]
I think using full type names is the right way to do this in the future...

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/6432729a2bdae438f79fabce50ad4e2e0db6762d

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/116f337deb92db67a703ce940a72c0bd765e301d

**Comment by rsuter** [comment]
I think everything is fine... please try latest CI build and report any broken code.
