### ISSUE TITLE
Expose the Http Request in PostProcess

### ISSUE THREAD

**Issue by HakanL** [NSwag/NSwag#466]
We're dealing with a set up that includes a reverse proxy (Azure Service Fabric) so the hostname for the Swagger requests are coming in as localhost and a port-number. That's not the real URL/hostname that users are accessing (because it goes through the proxy). The proxy adds headers to track the real/original hostname, so my plan was to use the SwaggerUiOwinSettings.PostProcess to set the doc.Host to the original hostname, but I can't access the headers in that method.
My suggestion is to add the original http request object (or just headers) to the SwaggerDocument that is passed to PostProcess.

**Comment by rsuter** [comment]
I think in this scenario you should remove the hostname and schemes so that the client must specify the hostname. I think Swagger UI uses the current hostname when no hostname is specified in the spec.

**Comment by rsuter** [comment]
You cannot acces a HTTP request because the generator/Swagger spec is static and cannot change for every request. 

Of course you could write your own Swagger serving middleware which generates the spec for each request... But this is not how you should do this.

**Comment by HakanL** [comment]
Thanks for the information, very helpful. I assume the hostname on the document is set based on the current request though, so even if this would only be called once (since it's static) it would still be helpful to have the headers available (because the hostname is incorrectly set).

**Comment by rsuter** [comment]
It is not static per se - with the nswag libraries you can generate it on the fly and add the headers/set the hostname. But the Swaggerdocument is meant as static description of your api. This is why you should set the host to the host which is externally visible or empty if the client has to decide.

**Comment by HakanL** [comment]
Ok, but the issue is that I don't know what the host is (in PostProcess) without the headers, the code in NSwag detects it incorrectly (in my case because of the reverse proxy in Azure Service Fabric). I realize I can leave it empty, but I like the option to specify it in the swagger file.
Another option would be to expose a "host detection callback" in the settings, so we don't have to modify the SwaggerDocument (which I agree isn't very clean).

**Comment by rsuter** [comment]
You can use this method without lazy: https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator#serve-the-swagger-specification-from-a-web-api-action

This way the spec is generated for each request and you have access to the headers...

**Comment by Eneuman** [comment]
@HakanL Did you get NSwag to work behind the revers Proxy in Service Fabric?

**Comment by HakanL** [comment]
I was able to get it to work, but I can't remember how, too long ago :)

**Comment by Asshiah** [comment]
I am in the same situation that @HakanL was previously where my api is behind a proxy that forwards the url (for instance, from [](https://localhost:12345/basepath) externally to [](http://localhost) on the api server).
I am getting the original scheme, port and basepath in custom headers for each requests on the api.
I would have liked to be able access these headers in an extensionpoint that allows me to define these elements globally for the swagger document and swagger UI.
The enduser should not know the local url of the api on its hosting server but only the externally exposed url. Swagger UI should also display and use this externally exposed url for the url forwarded requests to work.
I can't define these elements statically as the api is deployed in a Azure Kubernetes Cluster where each pod uses a different port and basepath so I must handle this dynamically.
I don't know if this is possible.
