### ISSUE TITLE
Feature: remove unused definitions

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#469]
Hi,

In typescript code generation I often have several unused classes (mainly model_1, model_2 ...) which are empty (no properties) and aren't used at all.
Of course I suspect this is related to my swagger generation tool, but I was wondering if it would be possible to add a 'cleanup' feature to automatically remove all those empty and unused definitions.
Of course this should be an option in order to not affect any case where they might be required (I don't see in my case, but might be used by others).

Once again, thanks a lot!

**Comment by rsuter** [comment]
Can you provide a sample Swagger spec or Web API controller classes?

**Comment by no-more** [comment]
Hi,

Can I send you the definition with skype ?

Thanks.

**Comment by rsuter** [comment]
Yes, please send it via skype
