### ISSUE TITLE
Referenced assembly 'NSwag.AspNetCore, ...' does not have a strong name

### ISSUE THREAD

**Issue by alphaleonis** [NSwag/NSwag#470]
Similar issue to #359, but for the NSwag.AspNetCore assembly. It is missing a strong name in the latest NuGet package as of version 7.7.0.

**Comment by rsuter** [comment]
I think .NET Core assembly cannot have a strong name (i.e. they cannot be signed)...

**Comment by alphaleonis** [comment]
Targetting .NET framework they definitely can anyway. I will submit a pull request.

**Comment by alphaleonis** [comment]
Thanks! :) Any chance we can get a new Nuget-package pushed with this change?

**Comment by rsuter** [comment]
v8.0 will be released in 20 min

**Comment by alphaleonis** [comment]
Ah, great work! =) Thank you so very much!

**Comment by rsuter** [comment]
ok v8.0 is released, please check if it works...

**Comment by alphaleonis** [comment]
Yep, it seems to work just like the doctor ordered. :) Thank you very much!
