### ISSUE TITLE
Question: enum name generation

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#473]
Hi,

I'm not sure, maybe it's an issue with the swagger generator I'm using, but currently when I have an enum inside of an element, the definition is directly included in the element and not as an external definition.
Then when I generate the typescript code, the enum is prefixed with the element name.
For example enum "ContactType" in my Contact element is named "ContactContactType".
I suppose this prevent name collision but is there any way to disable this ? 
More over when I'm using the same ContactType definition in another element A, I have an other definition named "AContactType".

Do you think it's an issue with the swagger definition tool I'm using ? or could this be handled in nSwag ? 

Thanks a lot.

**Comment by rsuter** [comment]
The problem is that because the enum is not referenced from the "definitions" section, no type name can be inferred... and thus the parent class name + property name is used... When using NSwag as assembly, you can provide an own ITypeNameGenerator (ie implement own class which inherits from DefaultTypeNameGenerator) and selectively change type names...

**Comment by no-more** [comment]
Hi,

Ok thanks I'll try to have a look on this. I'll first try to check if it's possible to change the generated swagger definition but I'm not sure about it.

Thanks.

**Comment by rsuter** [comment]
In the best case, every special type (object, enums) should be referenced in the "definitions" section, so that the type name is defined... however there are some cases where this is not possible (https://github.com/NSwag/NSwag/issues/328)

**Comment by no-more** [comment]
I have submitted a PR to the project which generate the swagger definition. It's now working as I would expect. Thanks.

**Comment by rsuter** [comment]
What project are you using? Swashbuckle?

**Comment by no-more** [comment]
I'm using Happi-swagger (https://github.com/glennjones/hapi-swagger)
