### ISSUE TITLE
CommandLine run config.nswag don't work

### ISSUE THREAD

**Issue by w0nderw0man** [NSwag/NSwag#474]
I have create a config.nswag.
I execute 

> nswag run config.nswag
It's >Done.

after webapi2swagger command and swagger2tsclient command, my .ts file it's loaded.
But I have a .ts with Jquery configuration dans not AngularJS

> template: "AngularJS"

I have test with other terms 

> template: "foobar"
end error appears. This is proof that the file is read correctly.
Bug?
Thanks you.

my configuration swag file :
```
{
  "swaggerGenerator": {
    "webApiToSwagger": {
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 2.0,
      "template": "AngularJS",
      "promiseType": "Promise",
      "dateTimeType": "Date",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": false,
      "typeStyle": "Class",
      "generateDefaultValues": true,
      "output": null
    },
    "swaggerToCSharpClient": {
      "exceptionClass": "SwaggerException",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateDtoTypes": true,
      "useHttpClientCreationMethod": false,
      "useHttpRequestMessageCreationMethod": false,
      "generateContractsOutput": false,
      "className": "{controller}Client",
      "namespace": "MyNamespace",
      "requiredPropertiesMustBeDefined": true,
      "dateType": "DateTime",
      "dateTimeType": "DateTime",
      "timeType": "TimeSpan",
      "timeSpanType": "TimeSpan",
      "arrayType": "ObservableCollection",
      "dictionaryType": "Dictionary",
      "classStyle": "Inpc",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "generateDefaultValues": true,
      "output": null
    },
    "swaggerToCSharpController": {
      "className": "{controller}",
      "namespace": "MyNamespace",
      "additionalNamespaceUsages": [
        "System.Web.Http"
      ],
      "requiredPropertiesMustBeDefined": true,
      "dateType": "DateTime",
      "dateTimeType": "DateTime",
      "timeType": "TimeSpan",
      "timeSpanType": "TimeSpan",
      "arrayType": "IEnumerable",
      "dictionaryType": "Dictionary",
      "classStyle": "Inpc",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "generateDefaultValues": true,
      "output": null
    }
  }
}
```

**Comment by rsuter** [comment]
This nswag document does nothing when executed with the "run" command. You need to: 

- Specify some more settings for the "webApiToSwagger" generator
- Define the "output" path of at least one code generator (only code generators with "output" path produce a file output)

If you use a .nswag file, you don't need to run the "webapi2swagger" command or "swagger2tsclient" command as these are described and executed with the .nswag file... I recommend to create the .nswag file with NSwagStudio

**Comment by w0nderw0man** [comment]
I used NSwag Studio to generate the configuration file.

I have : 
`"swaggerGenerator": {
        "webApiToSwagger": {
      "assemblyPaths": [
        "E:/Repos/Chausson.Web.Front.Elearning/Chausson.Web.Front.Elearning/bin/Chausson.Web.Front.Elearning.dll"
      ],
      "referencePaths": [],
      "isAspNetCore": false,
      "controllerNames": [
        "Chausson.Web.Front.Elearning.Controllers.Api.ElearningApiController"
      ],
      "defaultUrlTemplate": "api/{controller}/{id}",
      "defaultPropertyNameHandling": "Default",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "addMissingPathParameters": false,
      "infoTitle": "Web API Swagger specification",
      "infoVersion": "1.0.0",
      "output": "xxxxx/xxxxx/xxxxx.ts"
    }
  },`

I want to automate the generation of my .ts file.
In the .csproj I have add:
`  <Target Name="AfterBuild">
    <Exec Command="$(NSwagExe) run nswagConfig.nswag" />
    <Exec Command="$(NSwagExe) webapi2swagger /assembly:bin\/xxx.dll /controller:xxx.xxx.Api.xxxController/output:swaggerWebService.json" />
    <Exec Command="$(NSwagExe) swagger2tsclient /input:swaggerWebService.json /output:Scripts\/ApiClient\/xxxxApiClient.ts" />
  </Target>`

What command should be used ?
**thank you in advance**

**Comment by rsuter** [comment]
When using an .nswag document, you just need 

    <Exec Command="$(NSwagExe) run nswagConfig.nswag" />

the `run` command executes `webapi2swagger` and `swagger2tsclient` with the parameters from the document, just define an "output" for the client generators so that the output file is created...

**Comment by w0nderw0man** [comment]
It works thank you very much 👍 

I did not understand that the run was enough to indicate the file outputs. I try to use the commands `webapi2swagger` and `swagger2tsclient` in the `.csproj` of my project.
