### ISSUE TITLE
Add "version" command to nswag to detect installed version

### ISSUE THREAD

**Issue by andylowry** [NSwag/NSwag#475]
I'm working on a command-line integration of NSwag into other tooling, and I'd like to have a good way of checking up front that the installed NSwag version meets my requirements. I don't see a good way of getting that version by running the command line. There's a sort of crummy way, which is to invoke a bogus command like "nswag version", detect the nonzero exit status, and parse the "toolchain" version from the console output. It'd be nicer if there could actually be a "version" or "about" command or something like that, which would print version and other useful info in a format that's easy to parse.

**Comment by rsuter** [comment]
We can add the "version" command but the header and execution time will stay.. is this an issue?

**Comment by andylowry** [comment]
@rsuter asked:
> header and execution time will stay.. is this an issue?

No, especially if I can count on blank lines before and after the main output. Seems to be a pattern with the existing commands.

**Comment by rsuter** [comment]
![image](https://cloud.githubusercontent.com/assets/2603405/21080801/c02b8d6c-bfb8-11e6-89e8-5d20a979a769.png)
