### ISSUE TITLE
Multiple same-named parameters in a Swagger operation generates invalid C#

### ISSUE THREAD

**Issue by andylowry** [NSwag/NSwag#476]
In Swagger, an operation can have multiple parameters with the same name, so long as they all have different "in" values. NSwag apparently uses those names as-is, which can result in e.g. controller method signatures that contain multiple parameters with the same name, which is invalid C#.

It would seem ideal to use the incoming names whenever possible, but if there are conflicts, some sort of disambiguating rename would be required for all but the "highest priority" use of the name, where "highest priority" might mean first of [path, query, form, body, header] or some such...

**Comment by rsuter** [comment]
Thanks for reporting this bug, I'll look into this...
