### ISSUE TITLE
C# Codegen: HttpClients are not disposed

### ISSUE THREAD

**Issue by drake7707** [NSwag/NSwag#479]
A HttpClient implements the IDisposable interface, so .Dispose() should be called.

Even though there are many people that say it isn't required (e.g. http://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed) that's only the case if you reuse the same HttpClient later on. In the current implementation a new HttpClient is created on each request (which is probably required as they request can be run async).

I can imagine doing a lot of requests and not disposing them could exhaust the max. number of socket handles.

Suggested fix, change:
```
   var client_ = new HttpClient();
   ...
```

to

```
   using(var client_ = new HttpClient()) {
      ...
    }
```

**Comment by rsuter** [comment]
Thanks submitting the issue... please test with the latest CI build: 
https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by gitfool** [comment]
Current thinking is this should be a single static instance per process.

References:
- https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/
- https://github.com/mspnp/performance-optimization/blob/master/ImproperInstantiation/docs/ImproperInstantiation.md

**Comment by rsuter** [comment]
For this change, we need to drop UseHttpClientCreationMethod support

**Comment by drake7707** [comment]
Please make it a static ThreadLocal<HttpClient> then, otherwise you'll be blocking parallel execution.

**Comment by gitfool** [comment]
Huh? Don't do that. `HttpClient` is thread-safe.

**Comment by rsuter** [comment]
Aren't there security considerations when using a global HttpClient per client class? The problem is, this is a breaking change in the generated code. I think some users use the HttpClient creation method to set headers, but if it is global, then the headers must be set on the request message... correct?

**Comment by gitfool** [comment]
The best approach might be to allow `HttpClient` to be passed to the client proxy ctor, with other ctors defaulting to passing `new HttpClient` (or calling an initializer for whatever it does now). That way existing behavior is preserved, but it opens up the option to inject / pass your own `HttpClient` instance. If injected then the IoC container would control the lifetime scope of the `HttpClient`, whether it be a singleton (per process), per unit of work, or otherwise, and that could be determined independently at container registration-time.

**Comment by drake7707** [comment]
@gitfool Oh yeah, sorry. I mixed it up with WebClient which isn't.

**Comment by rsuter** [comment]
v8.2 now uses using() for the HttpClients... but it seems that we need to find a better solution...

**Comment by rsuter** [comment]
My biggest concern is security: What if the clients are used in a Web API for different users and some URLs are cached because the HttpClient is reused?

**Comment by gitfool** [comment]
The best way to address your concerns would be through configuration and backwards compatible default behaviour.

That said, the simplest case is actually to depend on `HttpClient` via the ctor. This implies ownership (and lifetime) is controlled elsewhere, so the library should just interact with it but never call `Dispose`, either directly or indirectly via a `using` or `finally` block.

From there we're layering on complexity in order to "simplify" using the client library for users that don't care about that level of control. What is the expected default behaviour for such users? If it's internally newing up `HttpClient` (via a default ctor) then, based on your concerns above, it should track that it owns the instance and call `Dispose` in a `finally` block.

Make sense?

**Comment by rsuter** [comment]
Yes, i think this is the way to go...

**Comment by lciocci** [comment]
Our applications are running into intermittent socket exhaustion exceptions when creating the HttpClient in our client proxies. We upgraded NSwag to 8.6.0, and see that HttpClients are created with the 'using' statement.  My questions are - are these HttpClients disposed of properly if they're created in a 'using' statement and an exception is thrown?  Does this require a try/catch/finally code pattern to ensure that resources are being disposed of properly?

**Comment by rsuter** [comment]
The "using" keyword is the same as "try ... finally": https://msdn.microsoft.com/en-us/library/yh598w02.aspx

**Comment by rsuter** [comment]
I just added the InjectHttpClient setting, so that you can fully control its lifecycle from outside if you need to. Please test this feature with the latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

If everything is fine, I'll create a release...

**Comment by lciocci** [comment]
We use NSwag.MSBuild.8.6.0 in our toolchain. What would it take for us to incorporate this new package into NSwag.MSBuild?

**Comment by rsuter** [comment]
You can download the CI nuget packages into a local directory, then add this directory as NuGet repo: 

![image](https://cloud.githubusercontent.com/assets/2603405/21991136/b39fe974-dc11-11e6-8465-89e52363145a.png)

Then you can update to the latest CI version. If everything is fine you can downgrade and wait for the release, or later directly upgrade to v8.7

**Comment by lciocci** [comment]
I downloaded the package as instructed, but ran into an issue building a client proxy with this version: 

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The method 'Get' on path '/api/v1/Values/{id}' is registered multiple times.

I then rolled back to version 8.5.0, and this exception does not occur in this version. The signatures and decorations for the 'Get' methods in this controller are as follows (see below). I've rolled back to 8.5.0 for now.

        [SwaggerOperation("GetAllDevices")]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(IEnumerable<DeviceList>))]
        public IEnumerable<DeviceList> Get(string SortCriteria = "", int page = 1, int pagesize = 10)

        [SwaggerOperation("GetDeviceById")]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof (Device))]
        [SwaggerResponse(HttpStatusCode.NotFound)]
        public Device Get(string id)

**Comment by rsuter** [comment]
Can you post the full controller code so that i can reproduce the issue?

**Comment by lciocci** [comment]
I'm not permitted to copy/paste the actual code, but can include the controller's skeleton. I've not built this so it may contain errors.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Web.Http;
using Swashbuckle.Swagger.Annotations;

using System.Threading.Tasks;

namespace devicesvc_api.Controllers
{
	public class DeviceList
	{
		public Guid Id { get; set; }
	}
	
	public class Device : DeviceList
	{
		public string Name { get; set; }
	}
	
    public class ValuesController : ApiController
    {
        [SwaggerOperation("GetAllDevices")]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(IEnumerable<DeviceList>))]
        public IEnumerable<DeviceList> Get(string SortCriteria = "", int page = 1, int pagesize = 10)
        {
            try
            {
                var devices = new List<DeviceList>();

                return devices.Skip(Skip).Take(pagesize);
            }
            catch (System.Exception err)
            {
                throw;
            }
        }

        [SwaggerOperation("GetDeviceById")]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof (Device))]
        [SwaggerResponse(HttpStatusCode.NotFound)]
        public Device Get(string id)
        {
            try
            {
                return new Device();
            }
            catch (System.Exception err)
            {
                throw;
            }
        }

        [SwaggerOperation("CreateDevice")]
        [SwaggerResponse(HttpStatusCode.Created)]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof (Device))]
        public async Task<Device> Post([FromBody] Device value)
        {
            try
            {
                return new Device();
            }
            catch (System.Exception err)
            {
                throw;
            }
        }

        [SwaggerOperation("UpdateDevice")]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof(Device))]
        [SwaggerResponse(HttpStatusCode.NotFound)]
        [SwaggerResponse(HttpStatusCode.Conflict, Type = typeof(HttpResponseException))]

        public async Task<Device> Put(string id, [FromBody] Device value)
        {
            try
            {
                return new Device ();
            }
            catch (System.Exception err)
            {
                throw;
            }
        }

        [SwaggerOperation("DeleteDevice")]
        [SwaggerResponse(HttpStatusCode.OK, Type = typeof (bool))]
        [SwaggerResponse(HttpStatusCode.NotFound)]
        public async Task <bool> Delete(string id)
        {
            try
            {
                var deleted = true;

                return deleted;
            }
            catch (System.Exception err)
            {
                throw;
            }
        }
    }
}

**Comment by rsuter** [comment]
We changed the default of the setting AddMissingPathParameters to true, this causes this problem. Just change this to false and it should work. But I'll look into how we can fix this.

**Comment by lciocci** [comment]
Very good. I'll give this setting a try. Thank you for your help.

**Comment by rsuter** [comment]
I changed the default back to false, this should now work out of the box

**Comment by rsuter** [comment]
Can you test again with the latest CI build? There are some major (internal) changes to the generated code. Can you provide feedback for the newly generated code?

**Comment by lciocci** [comment]
Hello Rico,

I’m not in a position to test the latest CI build at the moment. We have a push to deliver an interim build. I’ll have to come back to this later on, possibly sometime next week.

Regards,
Louis Ciocci

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/44b0295c5a20765c55ed5a8056e4cb980d4f5988

**Comment by rsuter** [comment]
I think its fine now: 

- Client is disposed (when not injected and result is not FileResponse)
- Request is always disposed
- Response is disposed when result is not FileResponse

FileResponse disposes client (when not injected) and response => caller of method must use FileResponse with using().
