### ISSUE TITLE
Support RouteAttribute inheritance in Web API generator

### ISSUE THREAD

**Issue by mkjeff** [NSwag/NSwag#48]
Web API 2.2 supported indeed(http://stackoverflow.com/a/19989344)

Is possible support this as well?

**Comment by rsuter** [comment]
Supporting inherited attributes should be easy... The custom routing is not possible because the routing works at runtime and cannot be determined from an assemblies metadata (i.e. reflection).

**Comment by rsuter** [comment]
Does only the `RouteAttribute` support inheritance?

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration.Tests/WebApiToSwaggerGenerator/Attributes/RouteInheritanceTests.cs

**Comment by rsuter** [comment]
Also add a setting to enable route inheritance (default: Off).

**Comment by rsuter** [comment]
Why did you close this one? It is not implemented yet...

**Comment by rsuter** [comment]
Inheritance is now supported: https://github.com/NSwag/NSwag/commit/4d2db5907281a169fe779d431923d7bc98abf465
