### ISSUE TITLE
Support for additionalProperties with specified schema

### ISSUE THREAD

**Issue by tedepstein** [NSwag/NSwag#483]
I tried modifying the PetStore example, adding `additionalProperties` to the `Pet` schema definition, in accordance with the Swagger–OpenAPI spec:

```
    "Pet": {
      "type": "object",
      "required": [
        "name",
        "photoUrls"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "category": {
          "$ref": "#/definitions/Category"
        },
        ... (other properties)
      },
      "additionalProperties": {
        "type": "string"
      },
      "xml": {
        "name": "Pet"
      }
    }
````

The NSwag-generated C# client and server classes don't seem to have any provision for this additional collection of string properties. 

I created this example in NSwag studio using "Create Local Copy" from http://petstore.swagger.io/v2/swagger.json.  Then I modified the schema a shown above, saved the .nswag file, and clicked Generate Outputs.  I'm new to NSwag, so if I missed a step, or I'm misreading the output, please let me know.

What I expected was something like an `_additionalProperties` property, whose value is an `IDictionary<String, String>`.  I guess this would need some special Newtonsoft attributes to make it serialize as part of the containing class.  Or, maybe the class itself should inherit from `Dictionary`.

 Note that there are some limitations with additionalProperties support in Swagger's core Java libraries.  I've documented these in detail [here](https://support.reprezen.com/support/solutions/articles/6000162892-support-for-additionalproperties-in-swagger-2-0-schemas).   In particular, Swagger doesn't really seem to support additionalProperties with a boolean `true` or `false` value.  You have to specify a schema as the value.  

So that's the level of support I'm looking for, if it exists or can be added: `additionalProperties` with an embedded sub-schema or referenced schema specified as its value.

**Comment by rsuter** [comment]
This should actually generate an additional property: 

        [JsonExtensionData]
        public IDictionary<string, object> ExtensionData { get; set; }

With the value type of the schema. 

This is an NJsonSchema issue and must be implemented there...

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/6263b3fcd6f5f19edeef8ed402ab2549efb03d31

**Comment by tedepstein** [comment]
Thank you for the fast turnaround, @rsuter!  What is the best way for me to test this new feature?

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/01c803d2f21e405d15a4045398249eda90aa8e2c

**Comment by rsuter** [comment]
You can test with the latest CI build artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by tedepstein** [comment]
Generated code looks good.  Thanks again!
