### ISSUE TITLE
Ignore Properties marked with JsonIgnore-Attribute or especially ignore Indexer Property 

### ISSUE THREAD

**Issue by cluen** [NSwag/NSwag#486]
Hi, 

have a problem with a simple Indexer Property marked with JsonIgnore-Attribute but it's still generated to client. My Problem: The generated indexer property isn't useful for me at client side, so i've my own implementation copied from serverside object to a partial class extending the generated client code.

So it would be very helpful to just don't generate properties marked with Json Ignore or especially don't generate Indexer Properties.

Maybe these code snipets will help you:
`
if (propertyInfo.GetIndexParameters().Length > 0)
{
    // Property is an indexer
}
`

`        public Dictionary<string, object> DynamicValues { get; set; }

        /// <summary>
        /// Gets a DynamicValue if key exists otherwise null
        /// </summary>
        /// <param name="key"></param>
        /// <returns></returns>
        [JsonIgnore]
        public object this[string key]
        {
            get
            {
                if (!string.IsNullOrEmpty(key) && DynamicValues.ContainsKey(key.ToLower()))
                {
                    return DynamicValues[key.ToLower()];
                }

                return null;
            }
        }`

**Comment by rsuter** [comment]
From

        public class Foo
        {
            public Dictionary<string, object> DynamicValues { get; set; }

            [JsonIgnore]
            public object this[string key]
            {
                get
                {
                    if (!string.IsNullOrEmpty(key) && DynamicValues.ContainsKey(key.ToLower()))
                    {
                        return DynamicValues[key.ToLower()];
                    }

                    return null;
                }
            }

            public string Bar { get; set; }
        }

        [TestMethod]
        public void When_indexer_property_has_ignore_attribute_then_it_is_ignored()
        {
            //// Arrange
            var schema = JsonSchema4.FromType<Foo>();

            //// Act
            var json = schema.ToJson();

            //// Assert
            Assert.IsTrue(json.Contains("DynamicValues"));
        }

I get: 
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Foo",
  "additionalProperties": false,
  "properties": {
    "DynamicValues": {
      "type": [
        "null",
        "object"
      ],
      "additionalProperties": {}
    },
    "Bar": {
      "type": [
        "null",
        "string"
      ]
    }
  }
}
```
Which is correct... What do you expect?

**Comment by cluen** [comment]
NSwag Version: 8.1.6192.40777
NJsonSchema Version 6.6.6192.39835

Yeah, that looks great but I get:

For Swagger Output:
`
"Foo": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",        
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "dynamicValues": {
          "type": "object",
          "additionalProperties": {}
        },
        **"item": {}**
      }
`
For CSharp Client:
`
[Newtonsoft.Json.JsonObject(Newtonsoft.Json.MemberSerialization.OptIn)]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "6.6.6192.39835")]
    public partial class Foo : System.ComponentModel.INotifyPropertyChanged
    { 
        private int _Id; 
        private System.Collections.Generic.Dictionary<string, object> _dynamicValues; 
        private object _item;
    
        [Newtonsoft.Json.JsonProperty("Id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Id
        {
            get { return _Id; }
            set 
            {
                if (_Id != value)
                {
                    _Id = value; 
                    RaisePropertyChanged();
                }
            }
        }
      
        [Newtonsoft.Json.JsonProperty("dynamicValues", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.Dictionary<string, object> DynamicValues
        {
            get { return _dynamicValues; }
            set 
            {
                if (_dynamicValues != value)
                {
                    _dynamicValues = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        [Newtonsoft.Json.JsonProperty("item", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object Item
        {
            get { return _item; }
            set 
            {
                if (_item != value)
                {
                    _item = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static Foo FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Foo>(data);
        }
        
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
`

**Comment by rsuter** [comment]
This is your input class?

**Comment by cluen** [comment]
No that's the output by NSwag Studio.

Input class:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace XXX.XXX.Core.Settings
{
    [Serializable]
    public class Foo
    {
        public int Id { get; set; }

        public Dictionary<string, object> DynamicValues { get; set; }

        [JsonIgnore]
        public object this[string key]
        {
            get
            {
                if (!string.IsNullOrEmpty(key) && DynamicValues.ContainsKey(key.ToLower()))
                {
                    return DynamicValues[key.ToLower()];
                }

                return null;
            }
        }

        public Foo()
        {
            DynamicValues = new Dictionary<string, object>();
        }
    }
}
```

**Comment by rsuter** [comment]
The problem is

      "item": {}

I have to investigate where it comes from...

**Comment by cluen** [comment]
item is the default Name for the indexer property.

PropertyInfo.GetIndexParameters-Methode (System.Reflection) 
https://msdn.microsoft.com/de-de/library/system.reflection.propertyinfo.getindexparameters(v=vs.110).aspx

**Comment by cluen** [comment]
http://stackoverflow.com/q/5110403

**Comment by rsuter** [comment]
For me, the property is correctly ignored... Can you provide a sample project where i can reproduce this? Or can you retry with v8.2?

**Comment by RSuter** [comment]
I think this was a problem with the assembly loader and not matching assembly versions, see https://github.com/NSwag/NSwag/issues/738

Please test with latest NSwag version and reopen the issue if you sill have this issue...
