### ISSUE TITLE
Using npm NSwag with DotNetCore 1.1.0 on a mac is not supported out-of-the-box

### ISSUE THREAD

**Issue by PabloZaiden** [NSwag/NSwag#491]
Right now, nswag from npm with dotnet core 1.1.0 (current version) doesn't work out-of-the-box.
It says it requieres dotnet core 1.0.1, but the current version is 1.1.0.

A quick workaround is, after (globally) installing nswag, you can edit the file `/usr/local/lib/node_modules/nswag/bin/binaries/core/dotnet-nswag.runtimeconfig.json` and change the framework version to "1.1.0"

Doing that, the tool "just works", but it would be great if it required a minimum version, and not an exact version.

**Comment by rsuter** [comment]
You can install .net core 1.0.1 first and it should work out of the box... But we should update to v1.1

**Comment by rsuter** [comment]
How can i change to project.json to achieve that?

https://github.com/NSwag/NSwag/tree/master/src/NSwag.Npm

**Comment by PabloZaiden** [comment]
What?

**Comment by rsuter** [comment]
>  if it required a minimum version, and not an exact version.

Can we define that in a .NET Core project?

**Comment by PabloZaiden** [comment]
Mmm... no idea how to achieve the "minimum version" thing. Will call for help on twitter

**Comment by rsuter** [comment]
We can change the project to: 

![image](https://cloud.githubusercontent.com/assets/2603405/21526733/b2facd62-cd26-11e6-9784-d823807304a3.png)

But the generated "dotnet-nswag.runtimeconfig.json" still uses the version "1.1.0" (ie the newest version on build time), and thus requires exactly this version...

**Comment by PabloZaiden** [comment]
And would it be possible to replace the `1.1.0` in `dotnet-nswag.runtimeconfig.json` for `1.*` after the file generation?

**Comment by rsuter** [comment]
Maybe, can you try this on your machine?

**Comment by PabloZaiden** [comment]
Just checked and it doesn't work :(

When you update the app to use the 1.1.x releases, add ` "applyPatches": true` to the runtimeconfig.json file, so at least, it will continue working just fine when the X is updated

**Comment by rsuter** [comment]
The question is: How can I add this to the runtimeconfig.json, it is generated by the C# compiler... is there a way to define this in project.json?

**Comment by rsuter** [comment]
Can you confirm that v8.3 now works with .net core 1.1?

**Comment by PabloZaiden** [comment]
Working! Thanks
