### ISSUE TITLE
Enable binding a complex object with an array element to WebApi2

### ISSUE THREAD

**Issue by aelbatal** [NSwag/NSwag#492]
I need to modify the TypeScript template for angular2 to be able to send a complex object (that has an array element) in the Get method via URI. so, instead of this generated code:
```
    if (filter_Filters !== undefined)
        filter_Filters.forEach(item => { url_ += "Filter.Filters=" + encodeURIComponent("" + item) + "&"; });
```
I want it to be:
```
if (filter_Filters !== undefined)
    filter_Filters.forEach((item, index) => {
        for (let attr in item) {
            url_ += "Filter.Filters[" + index + "]." + attr + "=" + encodeURIComponent("" + item[attr]) + "&";
        }
    });
```
how can i do this?

**Comment by aelbatal** [comment]
@rsuter 
Thank you for applying my edit. hope to find it soon in the next release.

**Comment by rsuter** [comment]
The problem with this PR: It is not allowed to set the "schema" of a query/path parameter, and thus your will never be used for a valid Swagger specification... Where do you get a Swagger spec where a query/path parameter has a "schema"?

    public bool IsObjectArray => IsArray && Schema.Item?.Type == JsonObjectType.Object;

**Comment by rsuter** [comment]
See http://swagger.io/specification/#parameterObject

**Comment by rsuter** [comment]
"schema" is only allowed for body parameters

**Comment by aelbatal** [comment]
It's very reasonable though,
1. I need to pass a _DataSourceRequest_ object to the _get_ method's URL
`public DataSourceResult<UserDTO> Get([FromQuery]DataSourceRequest dataSourceRequest)`
so that it contains the paging, sort and filter paramters
```
public class DataSourceRequest
{
    public int Take { get; set; }
    public int Skip { get; set; }
    public IEnumerable<Sort> Sort { get; set; }
    public Filter Filter { get; set; }
}
```
2. the Filter property may be nested
```
public class Filter
{
    public string Field { get; set; }
    public string Operator { get; set; }
    public string Value { get; set; }
    public string Logic { get; set; }
    public IEnumerable<Filter> Filters { get; set; }
}
```
3. MVC allows this type of binding
http://stackoverflow.com/questions/17578878/using-fromuri-attribute-bind-complex-object-with-nested-array
http://stackoverflow.com/questions/31376560/complex-parameter-binding-array-of-nested-class-in-web-api
4. The Swashbuckle's Swagger spec (as this [sample](https://github.com/NSwag/NSwag/files/678791/Swagger.Swashbuckle.txt)) gives the required specifications for this case.


all what I'm missing is to get NSwag handles this type of binding. and I don't care much if this handling happens in the TypeScript side or the T4 template side.

**Comment by rsuter** [comment]
In the sample spec, your DataSourceRequest and Filter are flat parameters. Your PR will not work with that spec - we have to merge these parameters into a complex parameter first... and then decompose the instances in the client method (similar to your PR)

**Comment by aelbatal** [comment]
I appreciate your insistence of making this in the T4 side. I'm just a little afraid about the time needed to do so. It was easier for me to do it in the TypeScript side.

**Comment by aelbatal** [comment]
Honestly, I didn't test the latest commit locally before pushing it. but I did now and it worked only when I changed the _IsObjectArray_ condition to accept _None_ object types:
```
public bool IsObjectArray =>
    IsArray &&
    (Schema.Item?.Type == JsonObjectType.Object ||
    Schema.Item?.Type == JsonObjectType.None);
```
Is it suitable to do so? or whould break something else?

**Comment by rsuter** [comment]
I think its better to use: 

        public bool IsObjectArray => IsArray && (Schema.Item?.Type == JsonObjectType.Object || Schema.Item?.IsAnyType == true);

**Comment by rsuter** [comment]
Is the correct code generated with this change?

**Comment by aelbatal** [comment]
Yes. and didn't try your suggestion yet.

**Comment by rsuter** [comment]
Any can be any object, primitive types (like string and integer) must be defined... so its fine internally

**Comment by aelbatal** [comment]
I got the latest release today and enjoyed my issue fixed. :+1:  Thanks a lot. :handshake: 
note that I discovered the same problem [here](https://github.com/swagger-api/swagger-codegen/tree/master/modules/swagger-codegen/src/main/resources/typescript-angular2) but I'm fine with NSwag now :wink:

**Comment by rsuter** [comment]
:+1 enjoy

**Comment by rsuter** [comment]
According to http://swagger.io/specification/#itemsObject complex array items are not supported and your code will never be called for a valid Swagger spec:

> The value MUST be one of "string", "number", "integer", "boolean", or "array".

... and thus the type is never "object" or empty (any type)
