### ISSUE TITLE
"run" command doesn't understand absolute paths on linux

### ISSUE THREAD

**Issue by andylowry** [NSwag/NSwag#495]
If I say, e.g. `nswag run /tmp/nswag.json` on Linux, nswag appears to completely ignore the path I've provided. If I say `nswag run ../../tmp/nswag.json` then all works fine (when my current directory is `/home/andy`). I imagine that nswag is silently ignoring the path because it looks like an option (using windows command line syntax conventions) and is not a recognized option. A good approach might be to permit the file path in the `run` command to be specified as the value of an `/input` option, which would allow arbitrary linux-style paths to be specified without requiring nswag to understand linux command line conventions. I.e. `nswag run /input:/tmp/nswag.json`. Explicit use of `/input` could be optional, and only required for cases where the path looks syntactically like an option.

**Comment by rsuter** [comment]
Fixed in https://github.com/NConsole/NConsole/commit/4839b8c950caae8d59f03381f83c2a497a34ef83

**Comment by andylowry** [comment]
Thanks @rsuter. This is now working correctly for me.
