### ISSUE TITLE
Import momentjs automatically when needed

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#497]
Hi,

I have just switched to moment for dates in angular2 generation and I have to add the import in my extension code. Maybe this could be automatically added?

On my side I added `import moment from 'moment';` at the beginning of my extension code file.

Thanks a lot.

**Comment by rsuter** [comment]
Some people may use it as a global module (no import needed). Maybe we should leave it as is so that all scenarios are possible... Or maybe we need some "dependencies" setting to manage all required dependencies and their imports...

**Comment by RSuter** [comment]
This has been implemented with the ImportRequiredTypes setting (default: true)
