### ISSUE TITLE
NSwag or a dependency improperly using collectionformat

### ISSUE THREAD

**Issue by ryanackley** [NSwag/NSwag#500]
I have 

`[FromUri]string[] currentStates` 

as a parameter in a function in my WepAPI controller. The Swagger type ends up as string and the collectionformat ends up as multi when I run it through NSwag. This is not correct. The description of collectionformat from the OpenAPI specification, 

> 	Determines the format of the array if type array is used.

http://swagger.io/specification/#parameterCollectionFormat

When viewed in swagger-ui, it appears as a single value field which will work but will always serialize as an array of length 1. If the Swagger type was array and the collectionformat multi instead, swagger-ui would let me enter multiple values and make a request that would allow web api to serialize it into an array.

**Comment by rsuter** [comment]
Please test with the latest CI build/artifacts...

**Comment by ryanackley** [comment]
Tried testing it but ran into a problem. I get 

`The type 'HttpStatusCode' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Net.Primitives, Version=3.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

when I try to build my asp.net webforms project. I get the same problem when I try to get the latest from Nuget. 

Seems like a local issue but if you have any ideas I would be grateful. The assembly is installed somewhere because NSwag builds with no issues on my local computer. 6.13.6135.32131 on Nuget worked fine for me before this.

**Comment by ryanackley** [comment]
Ok, got it working by manually adding the missing dependencies to the web.config. 

It works now but I found another bug. #504
