### ISSUE TITLE
NSwag.ConsoleCore 8.3.0: `dotnet nswag` fails with FileLoadException

### ISSUE THREAD

**Issue by mclark1129** [NSwag/NSwag#501]
I'm trying to use the `NSwag.ConsoleCore` library with my .NET Core application so that it can be integrated in our CI pipeline.  I'm receiving the following message when running `dotnet nswag` from my project directory

> Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'NSwag.AssemblyLoaderCore, Version=8.3.6208.29157, Culture=neutral, PublicKeyToken=c2d88086e098d109'. The located assembly's manifest definition does not m
atch the assembly reference. (Exception from HRESULT: 0x80131040)
   at NSwag.Program.Main(String[] args)

**Steps to reproduce**
1) I've installed the latest SDK of .NET Core 1.1 to my machine
2) Added `"NSwag.ConsoleCore": "8.3.0"` to the `tools` section of my project.json file
3) From within the API directory ran `dotnet nswag`

Is there a different version I should reference or a different way I should set up this tooling?

**Comment by rsuter** [comment]
Yes, I think v8.3 broke the .NET Core console app, I've changed the used framework version back to v1.0 until I've figured out how to have the broadest support... Please try again with v8.4, available in some minutes

**Comment by rsuter** [comment]
Just tried this again, v8.4.1 now supports .NET Core 1.0.1 and 1.1.0... It works now on my machine.
