### ISSUE TITLE
Can NSwag generate client code for Web API actions with complex FromBody parameters?

### ISSUE THREAD

**Issue by devingoble** [NSwag/NSwag#502]
I have an Action that takes a complex type (a few `int`s and `string`s wrapped into a single object) and the swagger definition seems correct. However, the generated client does not pass the parameter when calling the API.

```
    get(filter: FilterParameter): Promise<any> {
        let url_ = this.baseUrl + "/api/Personnel";

        return this.http.fetch(url_, {
            method: "GET",
            headers: {
                "Content-Type": "application/json; charset=UTF-8"
            }
        }).then((response) => {
            return this.processGet(response);
        });
    }
```

Could I be missing something? I had this problem in 8.2, and I just updated to 8.3, but have the same issue.

**Comment by rsuter** [comment]
Can you post the swagger spec?

**Comment by rsuter** [comment]
The problem is that GET cannot have a body parameter...

**Comment by devingoble** [comment]
Ok, I'll flatten the object to query string parameters and go from there.

**Comment by devingoble** [comment]
Huh, it looks like it's not. It compiles, and doesn't throw any errors at runtime. Somebody has been using it. I bet it's not working as they expect though.
