### ISSUE TITLE
long data type not supported by swagger

### ISSUE THREAD

**Issue by bpstiles** [NSwag/NSwag#503]
According to the swagger spec (http://swagger.io/specification/), if you have a "long" data type, the format should be specified as "int64" in the swagger definition. (currently NSwag outputs "long" as the format)

Example:
"BatchNumber": {
          "type": "integer",
          "format": "long"
        }

Should be:
"BatchNumber": {
          "type": "integer",
          "format": "int64"
        }

Not sure that it matters, but as a side note: I'm not using the full NSwag toolchain. I am using NSwag to read my existing WebApi and output the Swagger json definition file.

**Comment by rsuter** [comment]
If this is in the spec, then we should change it...

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/611af0968c3bee9fe8418ff68f830f0b5bdcbef0
