### ISSUE TITLE
How do you invoke a client method that needs bearer token in header (TypeScript client)?

### ISSUE THREAD

**Issue by Kitcheone** [NSwag/NSwag#512]
Very similar to #365 - I'd like to do this in a TypeScript client, using swagger2tsclient.

Is this possible?

I should mention I'm currently generating the client using the command line, using the angular2 template:

```
nswag swagger2tsclient /input:... /output:... /template:angular2
```

**Comment by Kitcheone** [comment]
Managed to get this working with the following options:

```
nswag swagger2tsclient /input:... /output:... /template:angular2 /ClientBaseClass:BaseClient /ExtensionCode:....baseclient.ts /UseTransformOptionsMethod:true
```

And having an appropriate base class defined in `baseclient.ts`, with a `transformOptions()` method that appends the Authorization header to the `RequestOptions`

**Comment by rsuter** [comment]
Yes this is one way, you can also add an intercepter to the injected http service...

**Comment by rsuter** [comment]
... but i think extension code is more flexible and also the logic is more encapsulated in the clients.

**Comment by paddyfink** [comment]
Hi @Kitcheone, how did you implement the transformoptions methods? I'm not sure how to do it ( cf #643 )
