### ISSUE TITLE
Complex path parameters

### ISSUE THREAD

**Issue by kvanover** [NSwag/NSwag#513]
I have a problem when I use complex parameters with [FromRoute] to generate the swagger file.

Code:

[HttpGet]
[Route("Filter/{title}")]
[SwaggerOperation("Filter")]
public Todo Filter(ComplexGetRequest model)
{
}

public class ComplexGetRequest
{
        [Required]
        [FromRoute]
        public string Title { get; set; }
}

The output should be: "in" : "path", but I can only receive body and query.
if you set IsAspNetCore = true, it is query, false it markes it as query.

**Comment by rsuter** [comment]
This construct (route parameter from complex model) is only available in ASP..NET Core, correct?

**Comment by rsuter** [comment]
With the fix I have this: 

![image](https://cloud.githubusercontent.com/assets/2603405/21811100/a5931c74-d74e-11e6-90d7-36b29fc72b9a.png)

And this Swagger UI: 

![image](https://cloud.githubusercontent.com/assets/2603405/21811109/aeb89e6e-d74e-11e6-8820-1601b6f34489.png)

Is this correct?

**Comment by kvanover** [comment]
That's perfect

Thanks

**Comment by kvanover** [comment]
Quick question: When is the next release?

Thanks,

Koen

**Comment by rsuter** [comment]
I can release today..

**Comment by kvanover** [comment]
Thanks,

another question. Can we ignore a property? JSonIngnore doens't work and SwaggerIgnore cannot be set on a property.

Thanks,

Koen

**Comment by rsuter** [comment]
How does Web API handle that? Is JsonIgnoreAttribute working?

**Comment by kvanover** [comment]
With the webApi, the JsonIgnoreAttribute is working. but Nswag is not checking this. SwaggerIgnore is also fine. Just need to option to ignore properties.

And if you are editing :): There is also an FromHeader attribute in aspnetcore, this should be => "in": "header".

Thanks,

Koen

**Comment by kvanover** [comment]
Hey,

I forked it to make the change myself, but I saw that you have already done it. Thanks for this.

Can you tell me when you will release the next version.

Thanks a lot for the quick response.

**Comment by rsuter** [comment]
See this: https://github.com/NSwag/NSwag/commit/62e6aac641a9733b5764ecd3de4c716b5939edc4

**Comment by rsuter** [comment]
Can you test the changes with the latest CI artifacts? https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

I'm waiting for feedback on other issues, then I'll create a new release. I think it will be this week.

**Comment by kvanover** [comment]
It works perfect on our side
