### ISSUE TITLE
C# Client: response of type byte[] or string

### ISSUE THREAD

**Issue by rangp** [NSwag/NSwag#514]
I'm trying to integrate a web-service that generates pdf files, hence my response is in binary format. I have seen that the generated c# client reads the content as byte[] but then tries to do the following:

    Newtonsoft.Json.JsonConvert.DeserializeObject<byte[]>(System.Text.Encoding.UTF8.GetString(responseData_, 0, responseData_.Length));

Which obviously fails. My workaround for the moment is that I encode the byte[] as base64 string and put the whole chunk into an object that has one property - the binary. The json deserialization works that way but it's definitely much of an overhead (especially for large files) and it would be much nicer if the c# client could recognize the binary response type and skip the deserialization and string conversion.

Also each client generator should recognize plain string responses and skip the json deserialization for strings. It would make many of my interfaces much cleaner if I could return a string directly rather than wrapping the string into an object that has one property.

**Comment by rsuter** [comment]
Can you post a Web API action or Swagger spec operation?

I think there are two tasks to fix this: 

1. Web API to Swagger: Correctly set the "produces" of the response to the correct mime-type (or "application/octet-stream") for type "file"
2. Swagger to CSharp/TypeScript: When "produces" != "application/json" then return Stream and do not get or deserialize byte[]

**Comment by rangp** [comment]
Oh, right. The produces section in my swagger.json still contains 'application/json' as a possibility. I'll just fix this and then I'll get back to you.

**Comment by rangp** [comment]
Alright, my bad. Without `application/json` in my produces section the client is returning a byte[] as expected. However a stream would certainly be nicer, also for responses of type `plain/text` etc. 

Thanks and cheers

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/c0f5217fd100bd0c1a0374f256c6abb32c408d77

**Comment by rsuter** [comment]
//// Arrange

            var geoClient = new GeoClient(new HttpClient()) { BaseUrl = "http://localhost:13452" };



            //// Act

            using (var response = await geoClient.GetUploadedFileAsync(1, true))

            {

                //// Assert

                Assert.AreEqual(1, response.Stream.ReadByte());

                Assert.AreEqual(2, response.Stream.ReadByte());

                Assert.AreEqual(3, response.Stream.ReadByte());

            }

**Comment by rsuter** [comment]
Please test with the latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by rsuter** [comment]
v8.7
