### ISSUE TITLE
Generate RoutePrefix attribute for SwaggerToCSharpWebApiControllerGenerator

### ISSUE THREAD

**Issue by paulomorgado** [NSwag/NSwag#515]
Allow an option for the generated controller code to have the RoutePrefix attribute.

**Comment by rsuter** [comment]
Do you mean using "basePath" from the Swagger spec as RoutePrefix?

**Comment by paulomorgado** [comment]
Something like that or a configurable property for someone to just get the stub a put it up without having to define any routes or do more configurations.

**Comment by rsuter** [comment]
Is RoutePrefix("") allowed?

**Comment by paulomorgado** [comment]
It's working for me:

```
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "8.5.6214.25340")]
    [RoutePrefix("DocumentReader")]
    public partial class DocumentReaderController : ApiController 
```

By the way, the attributes applied to the actions are not fully qualified and need a using directive for `System.Web.Http`. If I add a list of additional namespace usages, I need to add the `System.Web.Http` namespace to the list. It would be better if those attributes where generated with fully qualified name.

**Comment by rsuter** [comment]
yes, if fixed that too... available in NSwag v8.6 now!

**Comment by paulomorgado** [comment]
Got this after upgrading:

       HResult=-2147467261
       Message=Object reference not set to an instance of an object.
       Source=NSwag.CodeGeneration
       StackTrace:
            at NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpWebApiControllerGenerator.GenerateClientClass(String controllerName, String controllerClassName, IList`1 operations, ClientGeneratorOutputType outputType)
            at NSwag.CodeGeneration.CodeGenerators.ClientGeneratorBase.GenerateFile(SwaggerDocument document, ClientGeneratorOutputType type)
            at NSwag.CodeGeneration.CodeGenerators.CSharp.SwaggerToCSharpWebApiControllerGenerator.GenerateFile()

**Comment by rsuter** [comment]
This is because no BasePath is defined in the Swagger spec. Please set a basePath (even "" is ok) until the next version...

**Comment by paulomorgado** [comment]
Hum! It would be a good option if there was a `BasePath` override in `SwaggerToCSharpWebApiControllerGeneratorSettings`.

Now that you're at it, it would also be nice to have the basePath in the url of the generated client.

And you missed the `System.Net.Http` in `ApiController`.
