### ISSUE TITLE
Web API Controller generator: Return Response<T> object

### ISSUE THREAD

**Issue by rsuter** [NSwag/NSwag#521]
Instead of 

       Task<DocumentCaptureRequest> StartCaptureAsync(DocumentCaptureRequest captureRequest);

we need something like

       Task<Response<DocumentCaptureRequest>> StartCaptureAsync(DocumentCaptureRequest captureRequest);

so that you can define headers, status code, etc. on the Response\<T\> object

See https://github.com/NSwag/NSwag/issues/516

**Comment by Egorikas** [comment]
Hello. I'd like to help with this one. Because I really want to jump-in and like this project. Can I grab it?

**Comment by rsuter** [comment]
Thank you for your help. We could implement this the same way as for the C# clients. Here the settings: 

https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpClientGeneratorSettings.cs#L38

Maybe we move the three setting properties down to SwaggerToCSharpGeneratorSettings: 

https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/SwaggerToCSharpGeneratorSettings.cs

... and use them also for the C# controller generation.

**Comment by Egorikas** [comment]
Ok. I'll watch all the stuff today and start to implement it

**Comment by rsuter** [comment]
Have you seen my review notes?

**Comment by Egorikas** [comment]
@rsuter yep, we discussed them in pr

**Comment by rsuter** [comment]
Thank you, please try the generator with the latest CI artifacts

**Comment by Egorikas** [comment]
@rsuter You are welcome) I'll definitely do this. Thank you for merged pr. Can I help with something else?
