### ISSUE TITLE
ConsoleCore 8.6.0: Support relative paths for the Assembly parameter

### ISSUE THREAD

**Issue by mclark1129** [NSwag/NSwag#522]
I'm attempting to use the ConsoleCore tool in a `postpublish` script in `project.json`.  I use the following command in my script:

```dotnet nswag webapi2swagger /Assembly:%publish:OutputPath%/MyAssembly.dll /Output:%publish:OutputPath%/docs/swagger.json```

This works fine when running `dotnet publish` with the default arguments.  However, when if I specify an output with a relative path using `-o` the command fails with the message 

> Absolute path information is required.
> Parameter name: assemblyPath

We use relative paths when generating artifact outputs in our CI builds, so it would be helpful if the tool could just automatically append the working directory of the command if it is provided a relative path.

**Comment by rsuter** [comment]
I think relative paths are supported (I fixed that a while ago). But here we have placeholders like "%publish:OutputPath%". Are the replaced before the cmd line tool is called?

**Comment by mclark1129** [comment]
These placeholders are replaced before the command is called.  You can test this by adding an `echo` script to `postpublish` as well. 

```
  "scripts": {
    "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%",
      "echo %publish:OutputPath%",
      "dotnet nswag webapi2swagger /Assembly:%publish:OutputPath%/MyAssembly.dll /Output:%publish:OutputPath%/docs/swagger.json"
    ]
  }
```

If you run `dotnet publish` with no arguments, OutputPath resolves to the absolute path of the release binaries for that project, and the `nswag` command succeeds.

If you run `dotnet publish -o ./someoutputfolder` then OutputPath resolves to `./someoutputfolder`, and the `nswag` command fails.

**Comment by rsuter** [comment]
It seems that AssemblyLoadContext.LoadFromAssemblyPath does not work with relative paths.

**Comment by mclark1129** [comment]
@ruster Seems that way, that's why I wonder if it's possible to convert a relative path input to an absolute path, using the command's working directory.

**Comment by rsuter** [comment]
Can you test with these NuGet packages?

[Packages.zip](https://github.com/NSwag/NSwag/files/705557/Packages.zip)

Commit: https://github.com/NSwag/NSwag/commit/63c6c19e3c7c6cd7a154c0e01e5d4b38f6e759a4

**Comment by rsuter** [comment]
New addition: Enfore .NET Core host in NPM package (--core)

**Comment by mclark1129** [comment]
@rsuter Seems like that did the trick!  Document deployed to a relative path with no issues.

**Comment by rsuter** [comment]
Ok, very good. I'm waiting for feedback for other issues, and if everything is fine, I'll release a new version.
