### ISSUE TITLE
Add Content-Type for Swagger UI (.NET Core)

### ISSUE THREAD

**Issue by georgeonofrei** [NSwag/NSwag#525]
Hello,

Can you fix the issue related to two html tags being generated?

![image](https://cloud.githubusercontent.com/assets/15815781/21924580/79c2406c-d982-11e6-8bca-6eaa44909a37.png)

Thanks,
George

**Comment by rsuter** [comment]
The first tag specifies the doctype and is not a html tag. Removing it is not correct. What exactly is the problem with it?

**Comment by georgeonofrei** [comment]
Hi,

Sorry for the confusion. My Chrome (and someone else's) is not rendering /swagger as HTML and I was under the impression that there should not be a double html tag (one with DOCTYPE and the other without). Had a fast look on the HTML standard and the two are coming together nicely.

Still don't know why Chrome keeps rendering plain text HTML instead of web site.

Thanks,
George

**Comment by rsuter** [comment]
Are you using the latest NSwag version? Can you post a screenshot of the HTTP headers from the Chrome dev tools?

**Comment by georgeonofrei** [comment]
I am running on NSwag 8.5.0.

Request looks like:
![image](https://cloud.githubusercontent.com/assets/15815781/21929080/3c539806-d997-11e6-9053-7f31b91f0c0e.png)

I see that content-type is missing still, I thought the fix was included in the latest. 
Is the content-type missing on your side also? I've had NuGet cache issues before, so I will also look at that.

Thanks,
George

**Comment by rsuter** [comment]
I added the Content-Type only for NSwag.AspNet.Owin, not for .NET Core... Are you running on ASP.NET Core?

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/blob/master/src/NSwag.AspNet.Owin/SwaggerUiIndexMiddleware.cs

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/blob/master/src/NSwag.AspNetCore/SwaggerUiIndexMiddleware.cs

**Comment by georgeonofrei** [comment]
Yes, I am using .NET Core.

**Comment by rsuter** [comment]
Ok, then i think this is the problem... We just have to add the missing header in the middleware.

**Comment by rsuter** [comment]
Can you test it with these packages?

[Packages.zip](https://github.com/NSwag/NSwag/files/705563/Packages.zip)

**Comment by munafk** [comment]
@RSuter Is this resolved? 
Sorry to bring it up after a long time. I am trying to use NSwag and just want to know if this has been resolved before getting my hands dirty? Your one liner will help!

**Comment by RSuter** [comment]
According to the closing commit, the Content-Type header is now correctly added...
