### ISSUE TITLE
AssemblyTypeToSwaggerGenerator fails when providing class names in particular order

### ISSUE THREAD

**Issue by grovesNL** [NSwag/NSwag#527]
If a class references another, the order of which the class names are provided to `AssemblyTypeToSwaggerGenerator` may cause it to fail.

For example, using the `types2swagger` command with the following classes:
```
namespace A
{
    public class B { public C C { get; set; } }

    public class C { }
}
```
`nswag types2swagger /assembly:A.dll /classnames:A.C,A.B /output:A.json` will succeed.

Note the order of the class names (`A.C` then `A.B`). If the order is reversed (`A.B` then `A.C),

`nswag types2swagger /assembly:A.dll /classnames:A.B,A.C /output:A.json` will fail with the exception:

> System.InvalidOperationException: Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema.
> 
> Server stack trace:
>    at NJsonSchema.JsonPathUtilities.GetJsonPath(Object rootObject, Object searchedObject) in C:\projects\njsonschema\src\NJsonSchema\JsonPathUtilities.cs:line 34

This appears to be a regression from the previous behavior. I had a look at the history but it's not obvious when the regression was introduced (somewhere between 7.7.6173.30628 and 8.6.6221.23504). I noticed the error in version 8.6.6221.23504.

**Comment by rsuter** [comment]
I had to change some significant changes because ToJson() had side effects. I will look into this tomorrow.

**Comment by grovesNL** [comment]
@rsuter: Thanks! No problem, let me know if I can help.

**Comment by rsuter** [comment]
Can you test with the CI artifacts? https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by grovesNL** [comment]
@rsuter: Latest CI artifacts work great!

**Comment by grovesNL** [comment]
@rsuter: Thanks for the quick response, when do you plan to publish to NuGet next?

**Comment by rsuter** [comment]
There is another regression (https://github.com/NSwag/NSwag/issues/479) i have to solve, but then ill release. I think by the end of the week.

**Comment by grovesNL** [comment]
@rsuter Ok perfect

**Comment by danielreuterwall** [comment]
Is this fix included in v9.6?

**Comment by rsuter** [comment]
Yes.

**Comment by danielreuterwall** [comment]
Ok, maybe we got another issue then. In the generated swagger.json the type definitions seems to be ordered by appearance in the API methods. This leads to a parent type being defined after a child type for us. This should be ok but we get compilation error in webpack and the typescript editor. Anyway around this?

**Comment by rsuter** [comment]
Can you create a new issue with samples?

**Comment by danielreuterwall** [comment]
My bad, we forgot to update one of the clients. With the fresh assembly everything works as expected. Big thanks and great work @rsuter!
