### ISSUE TITLE
Nullabel Enums

### ISSUE THREAD

**Issue by phinett** [NSwag/NSwag#531]
My nullable enums are being converted to Non-nullable for my c# client code.

**Comment by rsuter** [comment]
Can you post a sample controller?

**Comment by rsuter** [comment]
Is this an issue with an action method parameter or model property?

**Comment by phinett** [comment]
Sorry about the delay, it's a model property, i'm not sure how/why but it has now generated the correct result.

I have another issue though with attributes on enums not being carried over...i'll create a separate issue.
