### ISSUE TITLE
Don't throw a System.Aggregate exception if it's only wrapping a single exception

### ISSUE THREAD

**Issue by ryanackley** [NSwag/NSwag#533]
The C# API that NSwag generates will always throw a System.Aggregate exception on an error code returned from the WebAPI. It's essentially a wrapper around the actual exception. 

It would make it easier for end-users of the NSwag-generated API if the API would just throw the wrapped exception instead of an aggregate exception.

**Comment by rsuter** [comment]
Where is this happening?

**Comment by ryanackley** [comment]
woops, my bad. It's the runtime doing it because my tests are waiting for the async client to run.
