### ISSUE TITLE
Command "swagger2cscontroller" is generating "return" statement for void methods

### ISSUE THREAD

**Issue by anilktalla** [NSwag/NSwag#536]
I tried to generate code from swagger template for PetStore and found there is a 'return' statement added to void method.

<Target Name="BeforeBuild">
 <Exec Command="$(NSwagExe) swagger2cscontroller /input:swagger.json /output:Generated/PetStoreController.cs />
</Target>

Output:
     /// <summary>Updated user</summary>
        /// <param name="username">name that need to be updated</param>
        /// <param name="body">Updated user object</param>
        [System.Web.Http.HttpPut, System.Web.Http.Route("user/{username}")]
        public void UpdateUser(string username, User body)
        {
            **## return** _implementation.UpdateUserAsync(username, body);
        }

**Error**:
Since PetStoreController.DeleteUser(String,User) returns void, a return keyword must not be followed by the object expression.

**Comment by rsuter** [comment]
Please test with the latest CI artifacts: https://ci.appveyor.com/project/rsuter/nswag-25x6o
