### ISSUE TITLE
Class-Level Swagger Responses not showing in generated swagger doc

### ISSUE THREAD

**Issue by ogoodwin** [NSwag/NSwag#538]
It appears class-level swagger responses or not recognized by the the nswag command line generator. The only responses that appear in the generated swagger appear to be the ones defined on the endpoints themselves.

Steps to reproduce:
1) Create a new dotnet core project
2) Annotate a class with the below attribute.
3) Use the command line generator to create a swagger doc. Notice the response is not recognized.

[SwaggerResponse(HttpStatusCode.Forbidden, "The user is not authorized")]

Thanks

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/3ee465214d83f3a2a05292a6592b0a1a92eb4ec0
