### ISSUE TITLE
Generated code for swagger2csclient only returns first response

### ISSUE THREAD

**Issue by fcsobel** [NSwag/NSwag#541]
For the code generated by swagger2csclient if you have more than one response only the first response block gets a generated `return result_; ` 

For example:

```json
"responses": {
"200": {"description": "OK", "schema": { "$ref": "#/definitions/Booking" } },
"201": {"description": "Created", "schema": { "$ref": "#/definitions/Booking" } },
```
Generates this for the 200:

```csharp
if (status_ == "200") 
{
	var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
	var result_ = default(Response); 
	try
	{
		result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Response>(responseData_);                                
		return result_;
	} 
	catch (System.Exception exception) 
	{
		 ...	
```

And this for the 201

```csharp
if (status_ == "201") 
{
	var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
	var result_ = default(Response); 
	try
	{
		result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Response>(responseData_);                                
	} 
	catch (System.Exception exception) 
	{
		 ...	
```
_result is returned for 200 while 201 generates an exception.  Is this expected behavior?

**Comment by rsuter** [comment]
We need a mechanism which merges 2xx responses with the same response schema, so that this problem can be avoided...

**Comment by fcsobel** [comment]
Thanks,  we can work around by catching any exception that returns a booking:

```csharp
//catch 201 code and return response data instead of exception
catch (SwaggerException<Booking> e)
{
	return e.Response;
}
```
Thought it was a matter of generating the missing `return result_;` for all 2xx responses but I see they could be different return types...

**Comment by rsuter** [comment]
Yes, all such bugs at this stage of the project are not that simple to solve... :-)

**Comment by rsuter** [comment]
I think this is now properly supported (if success responses 2xx have the same type, then they are returned instead of only one and the others thrown). Please test this with the latest CI artifacts.

**Comment by Reza-Noei** [comment]
@RicoSuter Are you sure that its been resolved ?
I got the same issue on ``.NetCore 6.0`` and ``Swagger 6.2.3``.
