### ISSUE TITLE
When wrapping success responses, consider configuration for SwaggerResponse

### ISSUE THREAD

**Issue by paulomorgado** [NSwag/NSwag#543]
Like for exception classes, there should be a configurations for the response class.

Consider adding `ResponseClass` and `GenerateResponseClasses` configurations.

**Comment by rsuter** [comment]
I think this is the WrapSuccessResponses setting, check out CI artifacts

**Comment by paulomorgado** [comment]
`WrapSuccessResponses` is a Boolean setting. I found no way to use my own classes and not generate ones like for exceptions.

**Comment by rsuter** [comment]
Can you use your own class for exceptions? So you want to specify a Response class name?

**Comment by paulomorgado** [comment]
> Can you use your own class for exceptions?

Yes! `SwaggerToCSharpClientGeneratorSettings.ExceptionClass`

And the code template uses it like this:

    throw new <#=Model.ExceptionClass#>(...);

See [this](/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration/CodeGenerators/CSharp/Templates/ClientTemplate.tt#L222).

**Comment by rsuter** [comment]
Yes, but the exception class is still generated, even it is renamed...

**Comment by paulomorgado** [comment]
Not if I set `SwaggerToCSharpClientGeneratorSettings.GenerateExceptionClasses` to `false`.

**Comment by BlackGad** [comment]
Same issue here. It would be pleasant to see similar to exception classes implementation.
* Wrap or not : bool
* Wrap class name : string

**Comment by rsuter** [comment]
Now we have 

- WrapSuccessResponses => Whether to wrap responses
- GenerateResponseClasses => Whether to generate response classes (only needed when WrapSuccessResponses = true)
- ResponseClass => The name of the response classes

**Comment by rsuter** [comment]
Please test with latest CI artifacts or MyGet feed: https://www.myget.org/gallery/nswag-ci

**Comment by BlackGad** [comment]
Almost good. U forget to rename SwaggerResponse ctor :)

current result when I set ResponseClass = "Response"

` [System.CodeDom.Compiler.GeneratedCode("NSwag", "8.8.6242.22354")]
    public class Response
    {
        public string StatusCode { get; private set; }

        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public SwaggerResponse(string statusCode, System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> headers)
        {
            StatusCode = statusCode;
            Headers = headers;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "8.8.6242.22354")]
    public class Response<TResult> : Response
    {
        public TResult Result { get; private set; }

        public SwaggerResponse(string statusCode, System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result) 
            : base(statusCode, headers)
        {
            Result = result;
        }
    }`
