### ISSUE TITLE
Default parameters and CSharp

### ISSUE THREAD

**Issue by BlackGad** [NSwag/NSwag#545]
Is it possible to add default operation argument values into generated client code in CSharp?

1) Add option to SwaggerToCSharpClientGeneratorSettings 
2) React in the CSharp\Templates\ClientTemplate.tt (Line 84) (method with out Cancellation token)
3) Swagger respond with requirement flag for params... If if is possible sort optional params to method end and fill with default values. Required properties left as is.

Example: 

**Was:**
`public System.Threading.Tasks.Task<PagedItemsData> ListAsync(int? take, int? skip)`

**Become:**
`public System.Threading.Tasks.Task<PagedItemsData> ListAsync(int? take = default(int?), int? skip = default(int?))`

**Implementation**

rsuter: I think we should: 

- Add a setting "ReorderAndGenerateDefaultParameters" (default: false, to avoid breaking changes)
- Reorder parameters by IsOptional (i.e. required first, then optional), in the required/optional groups the order should be stable
- Generate default value for optional parameters

**Comment by rsuter** [comment]
I think it's better to create overloads of the method in an own partial class.

**Comment by BlackGad** [comment]
The main reason of using client code generation for me is to exclude manual code writing :) 

Overall description of my case:
1) Dev writes custom ApiController covered with swagger
2) Enable automatic client code generation with checkbox(msbuild instruction etc)
3) Nuget package with client code and contracts published for clients

**Comment by rsuter** [comment]
I think reordering is not an option because it would break existing users, and I think this also might cause other problems. Adding default parameters for nullable parameters should be possible

**Comment by BlackGad** [comment]
Reordering is not necessary. Just code sugar... It will be enought to add default values (value and reference types). 
`public System.Threading.Tasks.Task<PagedItemsData> ListAsync(int? take = default(int?), int? skip = default(int?), Guid? belongsToUser = default(Guid?), int foo = default(int))`

then in client app u could use 
`client.ListAsync(foo: 2);` 
Other params will be default

**Comment by rsuter** [comment]
I think we should: 

- Add a setting "ReorderAndGenerateDefaultParameters"
- Reorder parameters by IsOptional (i.e. required first, then optional), in the required/optional groups the order should be stable
- Generate default value for optional parameters

**Comment by BlackGad** [comment]
Exactly what i need. Thank you a lot!

This project is awesome :)

**Comment by rsuter** [comment]
Please test with the latest CI nugets: 

https://www.myget.org/gallery/nswag-ci

or CI artifacts: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/1862

**Comment by mkrasser** [comment]
I just tried out this change using v12.0.2 and adding the new setting "reorderAndGenerateDefaultParameters" : true to my Configuration.nswag and the client still did not generate default values.  Am I doing something wrong?
