### ISSUE TITLE
Custom ParameterBindingAttribute: More than one body parameter

### ISSUE THREAD

**Issue by domenichelfenstein** [NSwag/NSwag#546]
I have a very simple T4 in which I just want to write the swagger output in a file using the NSwag.AssemblyLoader (see attached file).
In my WebApi I created a custom ParameterBindingAttribute (the reason is not of interest here).
NSwag seems to have a problem with this scenario because of the way it is implemented:
It searches for Query-Bindings and assumes that every other binding has to be a body parameter binding. And because there can only be one body parameter it refuses work correct when bindings of other types were found.
My proposal is to specifically search for body/query parameters and ignore all parameters that are not of the Type FromBodyAttribute or FromQueryAttribute.
[nswag.txt](https://github.com/NSwag/NSwag/files/737449/nswag.txt)

**Comment by rsuter** [comment]
With the referenced commit, you can now add SwaggerIgnoreAttribute to the parameter so that is ignored, you can also inherit from SwaggerIgnoreAttribute in your custom attribute so that it is always ignored (just create a class SwaggerIgnoreAttribute in your project and inherit from it).

**Comment by rsuter** [comment]
Is this fine for you?

**Comment by domenichelfenstein** [comment]
Thanks! This works for me as well. As long as I can run NSwag without throwing Exceptions I'm fine with it.

**Comment by domenichelfenstein** [comment]
Will there be a preview build available in nuget that enables me to use this improvement?

**Comment by rsuter** [comment]
The CI feed is here: https://www.myget.org/gallery/nswag-ci

**Comment by domenichelfenstein** [comment]
perfect, thanks!

**Comment by rsuter** [comment]
Can you close the issue when it's working for you?
