### ISSUE TITLE
Set custom IOperationNameGenerator for client code generation (CSharp)

### ISSUE THREAD

**Issue by BlackGad** [NSwag/NSwag#551]
It would be very nice if you will allow to setup custom IOperationNameGenerator.
For now it is possible to setup only one of 3 available schemes (from OperationGenerationMode enumeration)

Could you make public OperationNameGenerator with set parameter? for custom OperationNameGenerator provide OperationGenerationMode.Custom value.

**Comment by BlackGad** [comment]
Hi again! 
You added this feature to vNext release, thank you!. 
So want to ask you approximate release dates :) (days/weeks/months). It will help me in my milestone(decision to wait or to hack for now)

**Comment by rsuter** [comment]
You can now test with the CI nuget packages... I hope the release will be next week. I plan to do some more refactorings and release a major version (because there are some breaking changes).

**Comment by BlackGad** [comment]
Works like a charm! Thank you!

**Comment by bpred754** [comment]
Hi there,

I would like to implement my own IOperationNameGenerator. Can you describe how I would do this or maybe point me to some documentation?
