### ISSUE TITLE
How to setup NSwag in ASP.NET Core + Xaml project

### ISSUE THREAD

**Issue by weitzhandler** [NSwag/NSwag#553]
Hi,

I have a solution that contains an ASP.NET Core Web API data end, and a Xamarin Portable XAML app (with Prism).

I'm looking at the manuals, but it's still hard for me to decide what way to take in generating my client entities. I want to have both `HttpClient`s and reflecting entities (with INPC) generated into the portable app Models folder.

I followed [this](../wiki/Middlewares#integrate-with-aspnet-core) manual by adding `app.UseSwaggerUi` to my code, and looks like the UI works fine and fetches the controllers and stuff.

Anyway, I'm unsure what approach to take in order to automate the client generation process so that whenever I rebuild the Web API it should regenerate the client entities and REST clients. Is it the T4 templates I should use?

**Comment by rsuter** [comment]
If this must be fully automated, I recommend the following: 

- With NSwagStudio you create an .nswag file with all your setting, reading a built .NET Core app: https://github.com/NSwag/NSwag/wiki/WebApiAssemblyToSwaggerGenerator#net-core
- In your build server, build and publish your ASP.NET Core app so that you can run the .nswag file on its output
- Run the file with "nswag run nswag.json"
- Then build your client project with the updated generated sources

Important: Save the .nswag file in your repo so that the input and output paths are relative...

**Comment by rsuter** [comment]
I think I should write a blog post about this, because it is not that simple - ASP.NET Core projects make this process even more complicated...

The other way is to expose the swagger spec via middleware, but to load the spec, the web server must be running - which may not be possible on the build server... If its an option to start the ASP.NET Core project, you can also use the URL to the spec as input for the code generator (the other steps are the same)

**Comment by weitzhandler** [comment]
@rsuter Thank you so much for your detailed response.
Oh hey, I haven't said thanks for the entire project! You're awesome!!

Anyway, do you plan on migrating the studio into a VSIX?

**Comment by weitzhandler** [comment]
@rsuter 
In my case it's a small project that I'll be running on my own machine off team or build server.
Since it's a project I have to get up and running quickly I don't want to run it over and over. Just build and get the entities generated right to client project.
Let me install the studio and see what it's all about. I normally don't like installing external software, I believe there are other people like me, that's also why I suggest going the vsix path. Besides it'll give you more flexibility on current project solution and control many options in the box. Visual Studio Extensibility Tools offers great options.

**Comment by rsuter** [comment]
I think usually you setup your build script (via NSwag NPM or MSBuild or whatever) or use NSwagStudio to create a config file... then you'll run the config file or command line script via cmd line :-) everytime you need to update the clients... 

The inputs of the generator can be a Web API DLL or the spec URL (ie the project must be started and the NSwag middleware must serve the spec)

**Comment by weitzhandler** [comment]
> The inputs of the generator can be a Web API DLL or the spec URL (ie the project must be started and the NSwag middleware must serve the spec)

So I can then add the cmd to post build or are there better ways?

**Comment by rsuter** [comment]
The idea is to run the script after all dlls are compiled, i think a simple build does not create all required DLLs. I'm not sure, but I think you need to build and publish (to a local directory) the project and run the script "after publish"... read the doc, there you can see what paths/outputs must be available to scan a .NET Core dll

**Comment by weitzhandler** [comment]
The truth is the the publish emits an exe file, not a dll

**Comment by rsuter** [comment]
Running "dotnet build" and "dotnet publish": 

![image](https://cloud.githubusercontent.com/assets/2603405/22489943/8a9d5380-e81a-11e6-94c1-81f2ac5d5e80.png)

Gives: 

![image](https://cloud.githubusercontent.com/assets/2603405/22489951/94fc985e-e81a-11e6-9d03-53cffb0394cc.png)

Then choose the DLL: 

![image](https://cloud.githubusercontent.com/assets/2603405/22489964/a898cee6-e81a-11e6-9e25-68e0a525a94d.png)

And generate code... (works for me)

**Comment by weitzhandler** [comment]
it doesn't output a dll, but i managed to find my controller from the exe file.
Anyway, i get this error (see [stacktrace](http://pastebin.com/rJcjXdqy):

> The JSON property 'item' is defined multiple times on type 'System.ComponentModel.ComponentCollection'.

**Comment by rsuter** [comment]
Are you using .net core v1.0? I think this changed in v1.1...

Can you post the controller or dto class where collection is used?

**Comment by rsuter** [comment]
If this is a but youll have to use list instead of collection until this is fixed

**Comment by weitzhandler** [comment]
I'm on 1.1.1
But I got around it anyway. Maybe I was on the wrong tab before (.NET Assembly).

> If this is a but youll have to use list instead of collection until this is fixed
What's but? I didn't understand what you mean

**Comment by rsuter** [comment]
.net assembly is just for dto classes, you need to use web api assembly

**Comment by weitzhandler** [comment]
The output looks overall just fine, I'm gonna have to mess with it some more to find out more.
I notice a different funny thing tho, I have inherited generic classes that gets some funny name containing all type parameters instead of just the finalized class name.

**Comment by rsuter** [comment]
Can you post a sample input/output?

**Comment by weitzhandler** [comment]
Input:

    public class ApplicationUser : IdentityUser<int, ApplicationUserLogin, ApplicationUserRole, ApplicationUserClaim>, IValidatableObject

Output:

    public partial class IdentityUserOfInt32AndApplicationUserLoginAndApplicationUserRoleAndApplicationUserClaim : System.ComponentModel.INotifyPropertyChanged

**Comment by weitzhandler** [comment]
Found it down the file.
It all looks well.
Thank a lot
