### ISSUE TITLE
swagger2csclient specify additional using directives (or fully qualified dto class name)?

### ISSUE THREAD

**Issue by pragmat1c** [NSwag/NSwag#554]
Is it possible with swagger2csclient to specify additional using directives? 

I don't want the DTO's generated for me, I already have a project with those. However, I'm trying to figure out how to either A) tell swagger2csclient to namespace (fully qualify) those dto's correctly inline or b) add a using directive automatically so it can resolve the dto class names.

Is any of that possible?

My command line (build even in VS) for reference:
$(NSwagExe) swagger2csclient /input:swagger-public.json /classname:FooClient /namespace:Foo /GenerateDtoTypes:false /output:$(ProjectDir)FooClientGen.cs

**Comment by rsuter** [comment]
You can use the AdditionalNamespaceUsages setting for that

**Comment by pragmat1c** [comment]
@rsuter Thank you very much. 

For anyone else that needs to use this from the command line, this worked for me:

`$(NSwagExe) swagger2csclient /input:swagger-public.json /classname:FooClient /namespace:Foo /GenerateDtoTypes:false /AdditionalNamespaceUsages:Foo.DTO /output:$(ProjectDir)FooClientGen.cs`
