### ISSUE TITLE
Feature: add option in the gui to replace null values with undefined

### ISSUE THREAD

**Issue by no-more** [NSwag/NSwag#556]
Hi,

would it be possible to add this option to the NSwagStudio please : https://github.com/NJsonSchema/NJsonSchema/issues/256

Thanks.

**Comment by rsuter** [comment]
This is already implemented but not released yet: 

![image](https://cloud.githubusercontent.com/assets/2603405/22505127/1bf755a6-e87a-11e6-9491-973ac15896fb.png)

Try CI build
