### ISSUE TITLE
NSwagStudio does not add ApiKey header when generating client code

### ISSUE THREAD

**Issue by stamo** [NSwag/NSwag#557]
Hi, Thank you for the great tool. I realy enjoy it. But have an issue that is preventing me from using it.

I use authorization through ApiKey in header. So every call needs to send custom header X-apiKey to the API.

So i have this code in my SwaggerUIOwinSettings
```
DocumentProcessors =
                {
                    new SecurityDefinitionAppender("apikey", new SwaggerSecurityScheme
                    {
                        Type = SwaggerSecuritySchemeType.ApiKey,
                        Name = "X-apiKey",
                        In = SwaggerSecurityApiKeyLocation.Header
                    })
                }
```
And it works like a charm for SwaggerUI. I have Authorise button and I can put down my Api Key.
And I can see it in the JSON

```
"securityDefinitions": {
    "apikey": {
      "type": "apiKey",
      "name": "X-apiKey",
      "in": "header"
    }
  }
```
Unfortunately when generating client with NSwagStudio (NSwag Version: 8.8.6231.36137, NJsonSchema Version: 7.7.6231.35489), both, C# client and TypeScript client does not have X-apiKey header

**Comment by rsuter** [comment]
You need to manually add authentication headers. 

In C# use a base class and enable UseHttpRequestMessageCreationMethod
In TypeScript use a base class and enable UseTransformOptionsMethod and add header in transformOptions

**Comment by fcsobel** [comment]
For the c# client we had success using the PrepareRequest method in a partial class: 
```csharp
partial void PrepareRequest(System.Net.Http.HttpClient request, ref string url)
{
	request.DefaultRequestHeaders.Add("X-APIKey", ConnectSettings.ApiKey);
}
```

**Comment by stamo** [comment]
@rsuter Thank you very much. This solved the problem

**Comment by codymullins** [comment]
@rsuter I've enabled those two things and am able to have the clients in Typescript reference a base class. Is there any way to ensure an import statement or something is at the top of the file for the location of the base class so I don't need to manually add it each time?

**Comment by codymullins** [comment]
@rsuter is there a way when using base class generation for the typescript file to be able to add a reference/import statement automatically?

**Comment by rsuter** [comment]
You need to use the ExtensionCode setting and reference a .ts file with the required imports there...

**Comment by codymullins** [comment]
I'm sorry I'm not quite sure I understand. I'm using the nswag config to launch the generator. So do I add something like this to the json doc: `"extensionCode": "ClientImports.ts"`? Would that file only contain the import statement? I only need to make sure the base class is imported otherwise there are typescript compile errors....

**Comment by rsuter** [comment]
Yes that file should contain only the imports and then added to the output file...

**Comment by frank-digirati** [comment]
I added it at the builder service level in Program.cs

` builder.Services.AddHttpClient<IOtherApi, OtherApi((provider, client) =>
    {
      client.DefaultRequestHeaders.Add"x-headname", "some-key");
    }).AddHeaderPropagation();`

**Comment by JonasBenz** [comment]
> You need to manually add authentication headers.
> 
> In C# use a base class and enable UseHttpRequestMessageCreationMethod In TypeScript use a base class and enable UseTransformOptionsMethod and add header in transformOptions

@RicoSuter What I don't like about this solution is, that you have to hold the header as state in the client (in a field or property) for something which should just be part of the current request and not influence any other requests.

Or at least I don't know how you can provide a header value to a request of a generated C# client directly when doing the request without setting it before the actual request which forces you to keep it as state.
