### ISSUE TITLE
$(NSwagExe) is available in Pre-build event command line but not Post-build event command line in Visual Studio 2015

### ISSUE THREAD

**Issue by pragmat1c** [NSwag/NSwag#558]
When I have this in the Pre-Build event command line, it works:

`$(NSwagExe) webapi2swagger /assembly:$(TargetPath) /output:swagger.json`

However when i try to use that in the Post-build event line, the macro $(NSwagExe) doesn't seem to be registered?

I get this error.
`The command " webapi2swagger /assembly:C:\Work\code\Fenix\Fenix.WebApi\bin\Debug\Fenix.WebApi.dll /output:swagger.json" exited with code 9009.	`

I can probably switch this to the MSBuild config, but using it in pre and post build make it much more accessible, and others on the team can more easily see that there is a something going on pre/post build without digging into the csproj file.

Am I doing something wrong, or is this a known limitation?

Attachment showing pre and post build fields:

![image](https://cloud.githubusercontent.com/assets/1749623/22517754/d03fa56e-e86f-11e6-99ae-53190dcc137c.png)

**Comment by pragmat1c** [comment]
Here is another example:

`echo NSwagExe is $(NSwagExe) `

`1>  NSwagExe is `

![image](https://cloud.githubusercontent.com/assets/1749623/22518335/d71521c8-e871-11e6-8e5c-149a191a9cf1.png)

**Comment by fcsobel** [comment]
We ran into a similar problem.  To fix manaully edit the project file and make sure your PreBuildEvent and PostBuildEvent sections are after the nswag settings.  Happens every time we update the package but it's easy to fix.

Here is what ours looks like:

```xml
  <Import Project="..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets" Condition="Exists('..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>.....</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\NSwag.MSBuild.8.6.0\build\NSwag.MSBuild.targets'))" />
  </Target>

  <PropertyGroup>
    <PreBuildEvent>"$(NSwagExe)" swagger2csclient:...</PreBuildEvent>
  </PropertyGroup>
```

**Comment by BlackGad** [comment]
for @rsuter ... Rename NSwag.MSBuild.targets to NSwag.MSBuild.props. VS places all targets in the bottom of msbuild file and props files in the top (before all PropertyGroups)

**Comment by rsuter** [comment]
Can you test this with the CI artifacts?

**Comment by pragmat1c** [comment]
@fcsobel Thanks, your work around fixes the issue.

For refence this was causing the issue:

```
<PropertyGroup>
    <PostBuildEvent>
    </PostBuildEvent>
  </PropertyGroup>
  <Import Project="..\packages\NSwag.MSBuild.8.8.0\build\NSwag.MSBuild.targets" Condition="Exists('..\packages\NSwag.MSBuild.8.8.0\build\NSwag.MSBuild.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\NSwag.MSBuild.8.8.0\build\NSwag.MSBuild.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\NSwag.MSBuild.8.8.0\build\NSwag.MSBuild.targets'))" />
  </Target>
  <PropertyGroup>
    <PreBuildEvent>echo NSwagExe is $(NSwagExe)</PreBuildEvent>
  </PropertyGroup>
```

Notice the  <PostBuildEvent> is before NSwag entries.

**Comment by rsuter** [comment]
Fixed. Can you test with the CI nuget feed? https://www.myget.org/gallery/nswag-ci

**Comment by rsuter** [comment]
Can we close this?

**Comment by pragmat1c** [comment]
Closing.
