### ISSUE TITLE
C# Controller Code Generation and optional query parameters

### ISSUE THREAD

**Issue by anilktalla** [NSwag/NSwag#562]
Hi NSwag Team,

We tried to generate C# Controller classes for Swagger and observed that optional query parameters are not marked as nullable in the method definitions. 

Can you please fix it or let us know a workaround?

Thanks

**Comment by anilktalla** [comment]
Swagger.json

"parameters": [
          {
            "name": "foo",
            "in": "query",           
            "required": false,
            "type": "string",
            "x-nullable": true 
          },
          {
            "name": "bar",
            "in": "path",
            "required": true,
            "type": "string",
            "x-nullable": true 
          }
        ],

Generated code:

public X DoThat(string foo, string bar)

**Comment by anilktalla** [comment]
Can this be changed to the following for nullable parameters?

public X DoThat(string foo = null, string bar =null)

**Comment by rsuter** [comment]
Same as this issue but for controllers: https://github.com/NSwag/NSwag/issues/545

**Comment by rsuter** [comment]
Please test with the latest CI nugets: 

https://www.myget.org/gallery/nswag-ci

or CI artifacts: 

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/1862
