### ISSUE TITLE
FileResponse omits Content Headers

### ISSUE THREAD

**Issue by JesseEdwardThompson** [NSwag/NSwag#564]
**To Repro**

1. Create a new endpoint that returns a file w/ Content-Type and Content-Disposition headers.
2. Generate api clients.

**Expected**

    var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h => h.Key, h => h.Value);
    // Include content headers
    foreach (var h in response_.Content.Headers)
    {
        headers_.Add(h.Key, h.Value);
    }

**Actual**

Content headers are lost in translation.

**Comment by rsuter** [comment]
This would nearly work: 

    var headers_ = System.Linq.Enumerable.ToDictionary(System.Linq.Enumerable.Concat(response_.Headers, response_.Content.Headers), h => h.Key, h => h.Value);

... but throws an exception when a header is defined in both collections...

**Comment by JesseEdwardThompson** [comment]
Sorry,

    foreach (var h in response_.Content.Headers)
    {
        headers_.Add(h.Key, h.Value);
    }

**Comment by JesseEdwardThompson** [comment]
In what scenario would there ever be duplicates? I don't think there is one.

**Comment by JesseEdwardThompson** [comment]
However, you could of course use a .ContainsKey(), then .Add(), pattern to be sure.

**Comment by rsuter** [comment]
"Add" also throws, it is: 

    headers_[h.Key] = h.Value;

**Comment by JesseEdwardThompson** [comment]
I'm aware, yes. Sorry, you've had about a quarter of my attention up until now. My honest opinion is that there will NEVER be duplicate keys in this scenario because all content headers will be under the response_.Content.Headers dictionary. If you are concerned that there could be, for some very exotic scenario then I can submit something for you that is more robust. I was really just trying to get the issue on someone's radar because I'm currently manually updating the generated output to get it to work for us.

**Comment by JesseEdwardThompson** [comment]
We rely on these headers for file downloads and for viewing in the browser (ex PDFs)

**Comment by JesseEdwardThompson** [comment]
THANK YOU!!! :)

**Comment by rsuter** [comment]
Ok, thanks for reporting, will be available in v9.0 soon

**Comment by rsuter** [comment]
... or use the CI nuget feed or artifacts
