### ISSUE TITLE
FileResponse class generation

### ISSUE THREAD

**Issue by kimpenhaus** [NSwag/NSwag#565]
Hi all,

this is more like a question cause I am not sure if its a bug or just wrong usage by myself.

We do have a CSharp Client generated from a json specification. It is using a byte[] as return type. We had generated this with NSwag Studio 8.5 before and it gave us a byte[]. With new version 8.8 we are getting a FileResponse as return type. I saw in the commits during the release 8.6 -> 8.8 that it was changed.

But with the new version of NSwag Studio I can't get the FileResponse class to be generated. Do I need to have a special checkbox activated?

Our settings are as follows:

![nswag](https://cloud.githubusercontent.com/assets/575109/22639047/51d708b2-ec4c-11e6-8a09-7fe96365edee.png)

NSwag Studio version info:

![nswag-studio-version](https://cloud.githubusercontent.com/assets/575109/22639172/ee3dacec-ec4c-11e6-8bb4-62f44fd08c6a.png)

cheers,
m.

**Comment by rsuter** [comment]
If FileResponse is used in the API then the class should be automatically generated. I think this is a bug where this usage detection is not working properly. Can you provide a swagger spec to reproduce this?

**Comment by kimpenhaus** [comment]
I tried to bundle a sample into a NSwag Studio project file.

[file_response.zip](https://github.com/NSwag/NSwag/files/754002/file_response.zip)

**Comment by rsuter** [comment]
I just tested this and I think it is fixed in the latest CI build: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

Can you verify? Release of v9.0 will be soon

**Comment by kimpenhaus** [comment]
Awesome!
Works perfect - thanks for the quick fix!

**Comment by rsuter** [comment]
It was already fixed :-)... The next release will be someday this week
