### ISSUE TITLE
[Bug]: output parameter for webApiToSwagger seems to be ignored

### ISSUE THREAD

**Issue by empedia** [NSwag/NSwag#568]
Steps to reproduce:

Use NSwag studio to configure WebAPI Assembly to Swagger. Click on Generate Outputs - Swagger output is generated in the UI.

Save the configuration as an nswag file and open it to edit it. Output parameter for webApiToSwagger is null.

Set Output parameter to point to a file e.g. swagger.json (either relative or absolute (need to use / or \\  as path separator otherwise there is a crash)).

Use nswag run to run the nswag file.

Expected result - swagger.json will be created in the appropriate location.
Actual result - there  is no file is generated.

**Comment by rsuter** [comment]
I think this is fixed with https://github.com/NSwag/NSwag/commit/18bc433b3b50080132332ba53e08990737d5b554

Can you test this with the latest CI artifacts?
