### ISSUE TITLE
AngularJS Generator toJS problem

### ISSUE THREAD

**Issue by Rui90** [NSwag/NSwag#574]
I don't know why this is happening, but when I generate to use AngularJS for all the methods a .ToJS is used

for instance:

```
    AuthClient.prototype.registerNewUser = function (registerUser) {
        var _this = this;
        var url_ = this.baseUrl + "/api/v1/auth/register";
        var content_ = JSON.stringify(registerUser ? registerUser.toJS() : null);
        return this.http({
            url: url_,
            method: "POST",
            data: content_,
            transformResponse: [],
            headers: {
                "Content-Type": "application/json; charset=UTF-8",
                "Accept": "application/json; charset=UTF-8"
            }
        }).then(function (response) {
            return _this.processRegisterNewUser(response);
        }, function (response) {
            if (response.status)
                return _this.processRegisterNewUser(response);
            throw response;
        });
    };
```

Here it is:         `var content_ = JSON.stringify(registerUser ? registerUser.toJS() : null);`

The problem is I am getting always the error that toJS() is not a function. I already tried to remove toJS() and the client works great without it. So here is my question, what does the toJS() does, why is it not a function, is there anyway to make it a function or to avoid using it on code automatic generation?

**Comment by rsuter** [comment]
The generator also generated a User class, you need to pass an instance of this to the registerNewUser function, otherwise you need to switch to DTO interfaces instead of DTO classes

**Comment by Rui90** [comment]
@rsuter  yes I believe you must be right... Could you help me chose the best approach for building the interface? Maybe this one?

[](blob:http://imgur.com/63bda89f-e7a0-44cf-b377-6e1383e4e528)

**Comment by Rui90** [comment]
it did! fixed thank you 👍
