### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Rui90** [NSwag/NSwag#575]
In the Swagger Code Generation there is a few exports that are being added to the code on compile. Like this one for instance:

`exports.AuthClient = AuthClient;`

I have no idea what this exports is doing, I just know that I am having a problem with it: 

`Uncaught ReferenceError: exports is not defined`

Anyone could explain me what is the exports for and why am I getting that error and how to fix/avoid it?

**Comment by rsuter** [comment]
I think in your tsconfig.json you have selected the wrong module system... i think this is a TypeScript issue and not an NSwag issue

**Comment by Rui90** [comment]
@rsuter  yes I believe you must be right... Could you help me chose the best approach for building the interface? Maybe this one?

[](blob:http://imgur.com/63bda89f-e7a0-44cf-b377-6e1383e4e528)

**Comment by rsuter** [comment]
The link is not working... The problem is that the tooling is not correctly working in your JS project

**Comment by Rui90** [comment]
@rsuter  http://imgur.com/a/be80L

**Comment by rsuter** [comment]
I always use class in my project, because it converts to properties to lower case (JS-style) and also correctly converts date objects correctly. But you cannot use duck-typing - you need to pass instances of the expected classes. 

And yes, you can choose "Interface" as Type Style, this way you just have to provide an object which satisfies the interface...

**Comment by Rui90** [comment]
but the problem with exports remains

**Comment by rsuter** [comment]
Yes, this is a problem with your TypeScript compiler settings in your project... I think it is configured to compile to AMD modules but your module loader cannot use this

**Comment by Rui90** [comment]
what can I do then? I'm kinda newbie with this, I have no idea

**Comment by Rui90** [comment]
swagger specification:

```
{
  "swaggerGenerator": {
    "webApiToSwagger": {
      "assemblyPaths": [
        "AppBackend/AppBackend/bin/AppBackend.dll"
      ],
      "referencePaths": [],
      "isAspNetCore": false,
      "controllerNames": [
        "AppBackend.Controllers.AuthController",
        "AppBackend.Controllers.LessorController",
        "AppBackend.Controllers.UserController"
      ],
      "defaultUrlTemplate": "api/{controller}/{id}",
      "defaultPropertyNameHandling": "Default",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateXmlObjects": false,
      "addMissingPathParameters": false,
      "infoTitle": "Web API Swagger specification",
      "infoVersion": "1.0.0",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 1.8,
      "template": "AngularJS",
      "promiseType": "Promise",
      "dateTimeType": "Date",
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "wrapDtoExceptions": false,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "typeStyle": "Interface",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "output": "RenterLogApiBackendClient.ts"
    },
    "swaggerToCSharpClient": {
      "exceptionClass": "SwaggerException",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateDtoTypes": true,
      "injectHttpClient": false,
      "wrapSuccessResponses": false,
      "useHttpClientCreationMethod": false,
      "useHttpRequestMessageCreationMethod": false,
      "generateExceptionClasses": true,
      "generateContractsOutput": false,
      "className": "{controller}Client",
      "namespace": "MyNamespace",
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTime",
      "dateTimeType": "System.DateTime",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.ObjectModel.ObservableCollection",
      "dictionaryType": "System.Collections.Generic.Dictionary",
      "classStyle": "Inpc",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "output": null
    },
    "swaggerToCSharpController": {
      "className": "{controller}",
      "namespace": "MyNamespace",
      "additionalNamespaceUsages": [
        "System.Web.Http"
      ],
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTime",
      "dateTimeType": "System.DateTime",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.Generic.IEnumerable",
      "dictionaryType": "System.Collections.Generic.Dictionary",
      "classStyle": "Inpc",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "output": null
    }
  }
}
```

**Comment by Rui90** [comment]
is there anyway to typescript does not generate the exports?

**Comment by rsuter** [comment]
What module loader are you using in your AngJS project?

**Comment by Rui90** [comment]
@rsuter I am affraid I don't know, so I will just show you everything xD

this the module:

```
angular.module('indexApp', [
    'indexApp.directives',
    'ngRoute', 'satellizer'
])
```

**Comment by Rui90** [comment]
@rsuter Angular DI.

**Comment by rsuter** [comment]
Then myabe you have to define None in the module parameter: 

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by Rui90** [comment]
@rsuter think that is the problem... unfortunately can't compile with none :/

tsc typescriptclient.ts --module None
typescriptclient.ts(9,18): error TS1148: Cannot use imports, exports, or module augmentations when '--module' is 'none'.

**Comment by Rui90** [comment]
Any more suggestions?

**Comment by rsuter** [comment]
Maybe try: 

https://www.npmjs.com/package/typescript-bundle

this generates a JS bundle which you can directly import and use without a module loader...

**Comment by umesh190690** [comment]
https://github.com/Microsoft/TypeScript/issues/6319 "Solved finally" follow this ..i was also getting same error i changed module:"commonjs"  to "module": "es6", because targeting ES5 remove the import/export statements, so these tools cannot remove unused exports.

**Comment by Rui90** [comment]
@umesh190690  where do I change that? In compilation?

`tsc typescriptclient.ts --module es6` ?

**Comment by RSuter** [comment]
Closed because this is a TS tooling issue and not an nswag issue...
