### ISSUE TITLE
Typescript/Fetch template issue for file upload endpoint.

### ISSUE THREAD

**Issue by offbeatful** [NSwag/NSwag#579]
I have the following spec:
/api/system/data/legacy: {
    post: {
        tags: [
            "System"
        ],
        operationId: "ApiSystemDataLegacyPost",
        consumes: [
            "application/form-data"
        ],
        produces: [
            "text/plain",
            "application/json",
            "text/json"
        ],
        parameters: [
            {
                name: "file",
                in: "formData",
                description: "Uplaod Zip",
                required: true,
                type: "file"
            }
        ],
        responses: {
            200: {
                description: "Success",
                schema: {
                    $ref: "#/definitions/ApplicationData"
                }
            },
            500: {
                description: "Internal Server Error",
                schema: {
                    $ref: "#/definitions/ExceptionDto"
                }
            }
        },
        deprecated: false
    }
},

It leads to the following client generation:
  apiSystemDataLegacyPost(file: FileParameter): Promise<ApplicationData> {
        let url_ = this.baseUrl + "/api/system/data/legacy";

        const content_ = new FormData();
        if (file === null)
            throw new Error("The parameter 'file' cannot be null.");
        else
            content_.append("file", file.data, file.fileName ? file.fileName : "file");

        let options_ = <RequestInit>{
            body: content_,
            method: "POST",
            headers: {
                'Content-Type': **<string>undefined**
            }
        };

        return this.http.fetch(url_, options_).then((response) => {
            return this.processApiSystemDataLegacyPost(response);
        });
    }

Problematic place is marked in bold.

Version: 9.0.0 (also experienced in 8.x)
Command: nswag swagger2tsclient /Input:http://localhost:5000/swagger/v2/swagger.json /Output:app/api/ApiClient.generated.ts /TypeScriptVersion:2.0 /Template:Fetch /WrapDtoExceptions:true /TypeStyle:Interface /GenerateClientInterfaces:true /DateTimeType:MomentJS /ExtensionCode:app/api/ApiClient.imports.ts

My workaround is to remove Content-Type completely for file upload endpoint. Is there any other way to fix this problem?

**Comment by rsuter** [comment]
So no content-type is not the same as undefined content-type? We need to remove the assignment in this case?

**Comment by offbeatful** [comment]
Yep, I think this should be removed completely in case of undefined.

**Comment by nbickel** [comment]
I have the same issue with the Angular 2 Client. Removing of Content-Type: undefined also solved the problem.

**Comment by nbickel** [comment]
Should i create a new issue for the angular template?

**Comment by rsuter** [comment]
yes please
