### ISSUE TITLE
'GenerateOptionalParameters' doesn't treat enums as i would expect.

### ISSUE THREAD

**Issue by davidshorter** [NSwag/NSwag#583]
Using the option `GenerateOptionalParameters` with Enum paramaters does not make them nullable so the client will not compile. I have written two failing tests [here](https://github.com/davidshorter/NSwag/commit/ed567dbe3b2f4e15723420486109f02d4f2e1ab4)

Screen shot of generated client.
![image](https://cloud.githubusercontent.com/assets/13352856/22805060/aa916aba-ef80-11e6-8075-bcb367a61c44.png)

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/9f0588372030ca6a1fdbddb849a10a25068e97e3

**Comment by rsuter** [comment]
Try CI artifacts

**Comment by davidshorter** [comment]
Perfect, thankyou !
