### ISSUE TITLE
Missing assemblies on NSwag.MSBuild

### ISSUE THREAD

**Issue by SvyatSlav** [NSwag/NSwag#584]
**Error:** 

> The command "NSwag.MSBuild.9.2.0\build\NSwag.exe  webapi2swagger /assembly:$(OutDir)/Category.dll /output:swagger.json" exited with code -532462766

**Output:**

> System.IO.FileNotFoundException: Could not load file or assembly "NSwag.CodeGeneration.CSharp, Version=9.2.6249.28921, Culture=neutral, PublicKeyToken=c2d88086e098d109" or one of its dependencies. The system cannot find the file specified.
1>     в NSwag.Commands.NSwagCommandProcessor.Process(String[] args)
1>     в NSwag.Program.Main(String[] args)
1>  NSwag command line tool for .NET 4.6+, 

**Workaround:**
Add assemblies to NSwag.MSbuild Folder:

> NSwag.CodeGeneration.CSharp.dll
NSwag.SwaggerGeneration.dll
NSwag.SwaggerGeneration.WebApi.dll

**Possible solution:**
Add to [.nuspec file](https://github.com/NSwag/NSwag/blob/master/src/NSwag.MSBuild/NSwag.MSBuild.nuspec) direct link to these assemblies

**Comment by rsuter** [comment]
I totally missed that... will fix that ASAP

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/07ec2ae4482e2bae7cfe91d1d5ce23f46627a1e5

**Comment by rsuter** [comment]
Try NSwag.MSBuild 9.2.1 on NuGet

**Comment by SvyatSlav** [comment]
Everything is OK! Thanks!
