### ISSUE TITLE
@odata.context and resulting variable and property names in CSharp generated code.

### ISSUE THREAD

**Issue by iAlexanderMoon** [NSwag/NSwag#586]
The swagger document of the 3rd party API I am trying to consume uses Swashbuckle.OData and generates a property name @odata.context. Unfortunately I am unable to supply file due to restrictions from the 3rd party...

Example:

	"Swashbuckle.OData.ODataResponse[System.Collections.Generic.List[Model]]": {
      "type": "object",
      "properties": {
        "@odata.context": { "type": "string" },
        "value": {
          "type": "array",
          "items": { "$ref": "#/definitions/Model" }
        }
      }
    }, 

The CSharp code generator tries to use _@odata.context as a private variable and @odata.context as the property names. Should the private variable and property remove all reserved characters? 

Not sure if this is the case for all swagger files coming with Swashbuckle.OData.

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/38bcd7869eedc401303d9059d8cc4d820971115a
