### ISSUE TITLE
Per operation template extensibility

### ISSUE THREAD

**Issue by cortex93** [NSwag/NSwag#587]
Hi,

As an enhancement, it would nice to have a per operation Template with the actual logic as default.

I have some operations that receive parameters to filter, sort, page output results. Those parameters are string representations due to wire constraints but I would like my interface and client implementation to expose those parameters as custom arguments like IQueryable<T>.

The idea is that calling myClient.GetAllProduct(query => query.Where(p => p.ID = 2)) would be translated to an HttpRequestMessage with a parameter $filter=ID eq 2 (in an odata style).
And the swagger definition will contains a $filter parameter.

For now, I use tags on SwaggerOperation to branch the logic but it implies to keep merging change in ClientTemplate.tt.

I wonder if it would be possible to try calling TemplateFactory for a custom Template and if none, use actual logic as default.

**Comment by rsuter** [comment]
Isnt it possible to check the operation name and call the default impl only when its not your special operation?

**Comment by rsuter** [comment]
Other idea: Theres a new option ProtectedMethods to make a method protected so that you can implement a "better" version of the operation in a partial method and call the protected one

**Comment by cortex93** [comment]
yes, I like this idea.

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/fadf35cba1cd3d958bc0de1cc8ebee0def84a0bc

**Comment by cortex93** [comment]
Fantastic
