### ISSUE TITLE
NSwagStudio generated C# code doesn't compile

### ISSUE THREAD

**Issue by doubret** [NSwag/NSwag#590]
Hi,
I tried to generate c# client code using bitbucket and teamcity swagger files.

Both output code that doesn't compile.
For bitbucket, there's a problem with an enum. Here's the swagger file : https://bitbucket.org/api/swagger.json

For teamcity, this is a problem with an invalid class name.
I don't have a link to the swagger file at hand. Tell me if you need it, i'll find a link to it.

Thanks.

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/0f92023de692fb50c3c165677c75e14a21435b74
