### ISSUE TITLE
How to remove some of the Generated attributes?

### ISSUE THREAD

**Issue by galvesribeiro** [NSwag/NSwag#595]
I can't find an option to remove from the generated code attributes like:

`[System.ComponentModel.DataAnnotations.Required]`

Is there a way to do it from the GUI or CLI?

Thank you

**Comment by rsuter** [comment]
Try the option RequiredPropertiesMustBeDefined = false

**Comment by rsuter** [comment]
Theres a new option GenerateDataAnnotations, try ci builds


https://github.com/NSwag/NSwag/commit/85a802083fad8833f5daf9e0a2d1626307c19633
