### ISSUE TITLE
NSwagStudio output window has both Generate Outputs and Generate Files

### ISSUE THREAD

**Issue by steveculshaw** [NSwag/NSwag#598]
The NSwagStudio [wiki](https://github.com/NSwag/NSwag/wiki/NSwagStudio) page shows only a Generate Outputs option for the output window, but current release has both Generate Outputs and Generate Files

And the Generate Files doesn't do anything?

**Comment by rsuter** [comment]
Yes, I know, these are just screenshots... I don't have the time to update them for each release.
"Generate Files" generates the output files if you have specified an output path in one of the Code Generators.

**Comment by steveculshaw** [comment]
Ah, missed that entry at the very bottom ... empty: no file output 

Thanks for the (very quick) response
