### ISSUE TITLE
Respect the DataMember(Name) Attribute

### ISSUE THREAD

**Issue by Swellenator** [NSwag/NSwag#6]
Hi

When generating the TypeScript definitions, the property names are appearing verbatim. I am using the DataMember attribute but it does not appear in the output. I can see in the NJsonSchema that each property does respect the attribute, so I'm not sure what is going wrong. 

Here is a sample class:

    [DataContract]
    public class InformationData
    {
        [DataMember(Name = "a")]
        public string Code { get; set; }

        [DataMember(Name = "b")]
        public string InfoText { get; set; }

        [DataMember(Name = "c")]
        public DateTime ModifiedDate { get; set; }
    }

**Comment by rsuter** [comment]
Currently only the `JsonPropertyAttribute` is used for generating the property name...

**Comment by Swellenator** [comment]
Ok that's fine, we have the DataMember stuff so it is compatible with WCF and XML serialisation. Can you please point me in the direction of which file has this code in it so I can have a look at it myself? Thanks!

**Comment by rsuter** [comment]
The property name resolution is implemented in the NJsonSchema library: I've updated the library so that it acts the same as Json.NET: 
1. JsonPropertyAttribute 
2. DataMemberAttribute
3. Property name (reflection)
Just try again with the latest NSwag release... (v0.16.5778.39280)

**Comment by Swellenator** [comment]
Great! You are a master.
