### ISSUE TITLE
Anonymous class generation

### ISSUE THREAD

**Issue by frankkoenigstein** [NSwag/NSwag#603]
This might be more a forum entry but I don't know were to put it. Maybe stackoverflow?

Based on this c# class hierachy:
```c#
//Tour
public interface ITour
public class Tour : ITour
public interface ITourExtend : ITour
public class TourExtend : Tour, ITourExtend

//Tourstopp
public interface ITourstopp
public class Tourstopp : ITourstopp
public interface ITourstoppExtend : ITourstopp
public class TourstoppExtend : Tourstopp, ITourstoppExtend
```

The following typescript hierachy is generated:

```typescript
// Tour
export class Anonymous
export class TourExtend extends Anonymous
export class Tour
export class ITour
export class ITourExtend

// Tourstopp
export class ITourstopp
export class ITourstoppExtend
export class Tourstopp
export class TourstoppExtend extends Tourstopp
```

I wonder why an Anonymous class is generated for Tour where as there is no Anonymous class for Tourstopp. I would expect a similar hierachy in typescript as in c#.

**Comment by rsuter** [comment]
Can you post the plain c# classes so that i can reproduce this?

**Comment by frankkoenigstein** [comment]
I created a minimal sample: https://github.com/frankkoenigstein/nswag-603. It uses the nswag npm module.
There is one reference to Tour in **ATourRelation**. It looks like that generation depends on alphabetical order. If **ATourRelation** is renamed to **ZTourRelation** no anonymous class is generated.

**Comment by rsuter** [comment]
Should hopefully be fixed with: https://github.com/NJsonSchema/NJsonSchema/commit/f12ef7e26f793c63fa89f1195d8654072e6e9c0a

**Comment by rsuter** [comment]
Can you try with these binaries?
[NSwg_with_inheritance_fix.zip](https://github.com/NSwag/NSwag/files/788286/NSwg_with_inheritance_fix.zip)

**Comment by frankkoenigstein** [comment]
That looks fine. Thank you. Please update your npm module.

Where can I find some informationabout how to configure about with [DataContract], [DataMemeber], etc.?

**Comment by rsuter** [comment]
What is your problem with it?

**Comment by frankkoenigstein** [comment]
Just don't know anything about it. And wonder how I can influence NSwag with it.

**Comment by rsuter** [comment]
I think there are currently no settings to change the behavior for DataContract attribute handling... Please create a new issue for that
