### ISSUE TITLE
Custom JSON serializer

### ISSUE THREAD

**Issue by danielreuterwall** [NSwag/NSwag#609]
We have implemented a custom contract resolver for our WebAPI defined in `Application_Start` like this:
```config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CustomContractResolver();```

It works great for the WebAPI but it's not respected by Swagger. Looking at the `SwaggerUiOwinSettings` we use to inject Swagger into the project, we can only set a fixed set of contract resolvers defined in `NJsonSchema.PropertyNameHandling` using the config parameter `DefaultPropertyNameHandling`.

Is it possible to configure Swagger to use our custom contract resolver or any other way around this?

**Comment by rsuter** [comment]
Currently not possible, but we should refactor to use JsonContract for generation: https://github.com/NJsonSchema/NJsonSchema/issues/321

**Comment by rsuter** [comment]
What exactly did you customize in the contract resolver?

**Comment by danielreuterwall** [comment]
We have swedish characters in our internal models that we need to escape for the Typescript generator to work. The contract resolver takes care of that.

**Comment by danielreuterwall** [comment]
Ideally we might not have Swedish characters in our models. However if the WebAPI is set up to use a custom contract resolver this should be respected by Swagger.

**Comment by rsuter** [comment]
Where do you have Swedish characters? In the property names?

**Comment by danielreuterwall** [comment]
Yep, property and type names.

**Comment by rsuter** [comment]
Can you give some samples, i think this is just a fix in the property name generator

**Comment by danielreuterwall** [comment]
Sure thing!
Let's say we have a model with swedish characters
```
[DataContract]
public class ModelWithÅÄÖ {
  [DataMember]
  public string PropertyWithÅÄÖ { get; set; }
}
´´´

Then we have our custom contract resolver that escapes the Swedish characters like this
```
protected override string ResolvePropertyName(string propertyName)
  {
    var escapedPropertyName = propertyName
      .Replace('å', 'a')
      .Replace('ä', 'a')
      .Replace('ö', 'o')
      .Replace('Å', 'A')
      .Replace('Ä', 'A')
      .Replace('Ö', 'O');

  return escapedPropertyName ;
}
´´´

For the type names we have another issue as that's not part of the contract resolver.

**Comment by RSuter** [comment]
v11 of NSwag has the new ContractResolver-based implementation... You can now provide your resolver so that your serialization logic is used...

**Comment by RSuter** [comment]
Please test with the CI artifacts and report and problems...
