### ISSUE TITLE
NSwagStudio possibly generating false expected responses for actions

### ISSUE THREAD

**Issue by zuckerthoben** [NSwag/NSwag#611]
I am using NSwagStudio with my ASP.NET Web API project and want to use the client implimentation provided by NSwag in Xamarin.Forms. 
My problem is that the HTTP responses that the client expects are always 200 or 204, for all actions. Example: 
EmployeesController.cs:

    [ResponseType(typeof(Employee))]
        public async Task<IHttpActionResult> PostEmployee(Employee employee)
        {
            if (!this.ModelState.IsValid)
            {
                return this.BadRequest(this.ModelState);
            }

            this.db.Employees.Add(employee);

            try
            {
                await this.db.SaveChangesAsync();
            }
            catch (DbUpdateException)
            {
                if (this.EmployeeExists(employee.Id))
                {
                    return this.Conflict();
                }
                else
                {
                    throw;
                }
            }

            return this.CreatedAtRoute("DefaultApi", new { id = employee.Id }, employee);
        }

I would expect that the client generated for this action would expect the Created (201) and throw exceptions for 409 (Conflict), 400 (Bad Request) and 500 (Internal Server Error). Instead it expects 200 or 204.

NSwagStudio generated Method: 
   
    public async System.Threading.Tasks.Task<Employee> PostEmployeeAsync(Employee employee,     System.Threading.CancellationToken cancellationToken)
        {
            var url_ = string.Format("{0}/{1}", BaseUrl, "api/Employees");

            var client_ = _httpClient;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    PrepareRequest(client_, ref url_);
                    var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(employee));
                    content_.Headers.ContentType.MediaType = "application/json";
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                    request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h => h.Key, h => h.Value);
                        foreach (var item in response_.Content.Headers)
                            headers_[item.Key] = item.Value;

                        ProcessResponse(client_, response_);

                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200")
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            var result_ = default(Employee);
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<Employee>(responseData_);
                                return result_;
                            }
                            catch (System.Exception exception)
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                        }
                        else
                        if (status_ != "200" && status_ != "204")
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
                        }

                        return default(Employee);
                    }
                    finally
                    {
                        if (response_ != null)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
            }
        }

Do I have to decorate all my actions in all my controllers with the SwaggerResponse attribute or do I have to integrate the Swagger middleware to get correct Swagger specs? Shouldn't NSwag create this the way I thought it would?

**Comment by rsuter** [comment]
NSwag uses reflection to generate a Swagger spec. It only sees the method signature - and not its implementation. This is why it cannot find out all possible status code. You have to specify them with SwaggerResponse attributes.

**Comment by zuckerthoben** [comment]
Ok, thank you for your quick response. Do you have a complete guide for using SwaggerResponse or sample projects?

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator#working-with-http-status-codes-and-exceptions
