### ISSUE TITLE
C# Client generator : verbatim string not supported inside RegularExpression Attribute

### ISSUE THREAD

**Issue by sviluppoRobyone** [NSwag/NSwag#612]
From this type in my c# web api project (please note the **@** charater at the beginning of the pattern)

```

public class Foo {
       
        [Required]
        [RegularExpression(@"/^(?:[B-DF-HJ-NP-TV-Z](?:[AEIOU]{2}|[AEIOU]X)|[AEIOU]{2}X|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[1256LMRS][\dLMNP-V])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[\dLMNP-V][1-9MNP-V]|[1-9MNP-V][0L]))[A-Z]$/")]
        public string Bar { get; set; }      
}
```

i got this in the generated client code

```
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "8.5.6255.20253")]
public partial class Foo {
  
        [Newtonsoft.Json.JsonProperty("CodiceFiscale", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.RegularExpression("/^(?:[B-DF-HJ-NP-TV-Z](?:[AEIOU]{2}|[AEIOU]X)|[AEIOU]{2}X|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[1256LMRS][\dLMNP-V])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[\dLMNP-V][1-9MNP-V]|[1-9MNP-V][0L]))[A-Z]$/")]
        public string Bar { get; set; }
}
```

The **@** charater is missing and it won't compile because it is considered a syntax error

**Comment by rsuter** [comment]
Do you think generating `@"<pattern.Replace("\"", "\"\"")>"` is fine?

**Comment by rsuter** [comment]
https://github.com/NJsonSchema/NJsonSchema/commit/ced5d068124fe4ad8a96505f3f0ce38461938ac5

**Comment by sviluppoRobyone** [comment]
yes it should work, doing it manually on the generated code solve the problem

thank you

**Comment by rsuter** [comment]
Can you verify the fix with the CI artifacts? https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by Liero** [comment]
Its quite difficult to include those artefacts in local solution since they are not exposed in any nuget feed. I've tried to copy the packaged into local folder and set the folder as package source, but I was not able to restore the packages then.

It would be totally awesome if you tried some prerelese release or private nuget feed for CI build like the .net core team does: https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

**Comment by rsuter** [comment]
CI feed: https://www.myget.org/gallery/nswag-ci

**Comment by rsuter** [comment]
But without .net core packages
