### ISSUE TITLE
TypeScript --noUnusedParameters and --noUnusedLocals flags

### ISSUE THREAD

**Issue by adzhiljano** [NSwag/NSwag#615]
Hello, I am currently using tslint as a linter for my ts files and I was ignoring the ts file, generated by your awesome lib.
Now, tslint started to deprecate the unused varuable flag ([Start to deprecate no-unused-variable rule](https://github.com/palantir/tslint/issues/1481)) , because in newer versions of Typescript `noUnusedParameters `and `noUnusedLocals` flags have been added ([Flag unused declarations with --noUnusedParameters and --noUnusedLocals](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals))
If you set them to true and try to compile the ts file, generated by NSwag you will get **_at least_**:
- error TS6133: 'caught' is declared but never used, when setting `noUnusedParameters `to true (caused by [this](https://github.com/NSwag/NSwag/blob/c9211140b4db4d4aa509d16bbf32cf067a5e2824/src/NSwag.CodeGeneration.TypeScript/Templates/Angular2ClientTemplate.tt#L88))
- error TS6133: 'RequestOptionsArgs' is declared but never used, when setting `noUnusedLocals ` to true (caused by [this](https://github.com/NSwag/NSwag/blob/1fa71dc52a48497fb0f34fda9e29e4eca4c32538/src/NSwag.CodeGeneration.TypeScript/Templates/FileTemplate.tt#L16))

As far as I can see the latest is caused, because it is used in the `TransformOptionsMethod` [here](https://github.com/NSwag/NSwag/blob/c9211140b4db4d4aa509d16bbf32cf067a5e2824/src/NSwag.CodeGeneration.TypeScript/Templates/Angular2ClientTemplate.tt#L36)

There might be some other errors, those are the onse I stumbled upon.
Thank you!

**Comment by rsuter** [comment]
Good find, is there a way to completely disable validation for a .ts document (there is already a comment for TSLint)?

**Comment by grovesNL** [comment]
@rsuter You can't disable validation currently because it's at the TypeScript compiler level.

I have some changes in a branch to solve the particular issues here, but I couldn't send a PR last night because of the [diff problem](https://github.com/NSwag/NSwag/pull/618).

We'll probably want to go through the other clients besides Angular 2 and check those as well.

**Comment by rsuter** [comment]
Yes, we should fix all tpls

**Comment by adzhiljano** [comment]
@rsuter Yes, you can skip the validation with TSLint for some files, but you shouldn't bother with TSLint, mostly because its usage is optional and the usage of the TS compiler is required : ) 

As @grovesNL said, those flags [are now part](https://www.typescriptlang.org/docs/handbook/compiler-options.html) of the Typescript compiler itself. You can disasble the validation if you set them to false(the default values), but you can't [disable them for some files](https://github.com/Microsoft/TypeScript/issues/12913). So It's either on or off for all of your ts files. As I said, and as @grovesNL pointed out, there might be some other problems (due to some other flags in the TS compiler config) and in other TS templates from(I posted this issue just for the Angular2 template).

We could start with min NSwag configuration, generate all of the possible TS templates and then run them with through the TS compiler with max _strictness_ options. Something like:
``` 
"compilerOptions": {
...
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
...
  }
```

**Comment by grovesNL** [comment]
I'll try to look at this soon. #563 is related to `noImplicitAny` too.

**Comment by rsuter** [comment]
Maybe we should also improve the integration tests so that the generated TS outputs are compiled and linted... Currently I regenerate the integration svcs and only check the diff...

**Comment by rsuter** [comment]
Can we close this one?

**Comment by adzhiljano** [comment]
Very good job, @rsuter , @grovesNL . Thank you very much!

This issue is resolved, so you can close it now : )
