### ISSUE TITLE
Configure SupportedSubmitMethods when using Middlewares

### ISSUE THREAD

**Issue by ThumNet** [NSwag/NSwag#617]
Hi,

I'd like to know if there is a way to configure the Swagger UI setting SupportedSubmitMethods?

From the Swagger UI docs:
*An array of of the HTTP operations that will have the 'Try it out!' option. An empty array disables all operations. This does not filter the operations from the display.*

My project is based on OWIN Web API.
```
app.UseSwaggerUi(typeof(Startup).Assembly, new SwaggerUiOwinSettings());
```
Any help is welcome!

**Comment by rsuter** [comment]
This is currently not exposed as setting. 

You could add the Swagger UI manually in your project and point it to the NSwag generated Swagger spec.

**Task:** Add the missing settings to the settings class and process it in the Swagger UI html file (in the NSwag Swagger UI middleware for ASP.NET and ASP.NET Core).

**Comment by rsuter** [comment]
Thank you for the PR...
Please test your changes with the latest CI build. NuGet feed (no .net core packages): https://www.myget.org/gallery/nswag-ci

**Comment by ThumNet** [comment]
Thanks for excepting the PR :) 
I see the changes already made it into the official nuget repository, great! And working as expected!
