### ISSUE TITLE
Detecting proper SwaggerParameterKind from multiple custom parameter binders.

### ISSUE THREAD

**Issue by Cephei** [NSwag/NSwag#621]
I'm running into complications due to `OperationParameterProcessor.EnsureSingleBodyParameter`. Unfortunately, aside from `[FromBody]`, `[FromUri]` etc, it's difficult to determine whether a custom parameter binder will read from the body unless you have an instance of it and check the `HttpParameterBinding.WillReadBody`.

Example Problem:
```
public Task<HttpResponseMessage> PostRevision(
            string documentId, 
            [MaybeMultipart]DocumentRevisionDto revisionDto,
            [DocumentCreationSource]DocumentCreationSource source = null,
            string sourceId = null, 
            string transactionId = null)
```

Here, `[MaybeMultipart]` create a custom parameter binder that reads from the body. `[DocumentCreationSource]`, however, does *not* read from the body, but is a custom parameter binder.

One option could be to create a dummy attribute, something like `[NonBodyAttribute]`:
```
public Task<HttpResponseMessage> PostRevision(
            string documentId, 
            [MaybeMultipart]DocumentRevisionDto revisionDto,
            [DocumentCreationSource][NonBody]DocumentCreationSource source = null,
            string sourceId = null, 
            string transactionId = null)
```

Then in `OperationParameterProcessor.ProcessAsync` add a new check:
```
dynamic nonBodyAttribute = parameterAttributes.SingleOrDefault(a => a.GetType().Name == "NonBodyAttribute");
```
... and update the conditional.

Other than that, or removing the `EnsureSingleBodyParameter` validation , I'm at a loss of ideas. This will break for all custom parameter binders.

**Comment by rsuter** [comment]
I think you actually have an instance of the attribute and you can check HttpParameterBinding.WillReadBody (but you have to do it via reflection).

**Comment by rsuter** [comment]
Sorry, posted in wrong issue :)

**Comment by Cephei** [comment]
Unfortunately that won't work. `HttpParameterBinding.WillReadBody` is on the actual binding. The attribute has no such property; it just acts as a factory method to create the binding.

**Comment by Cephei** [comment]
I also can't remove `EnsureSingleBodyParameter` like earlier suggested. In our API we have multiple custom binders/attributes. Some read from the body, others not. It's unfortunate Microsoft didn't move WillReadBody to the attribute. The only thing I can think of now is to create a new attribute like suggested above.
