### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by Cephei** [NSwag/NSwag#625]
I'm trying to fork this repo and contribute to several bug fixes but as soon as git checks-out all the files, there's about 14-24 files that always report as changed. It's due to line endings but I can't find a solution. A git reset --hard doesn't fix the problem.

I'm building from a Windows environment.

**Comment by Cephei** [comment]
Most of the files "changed" are .config and .bat.

**Comment by rsuter** [comment]
Yes, I had some problems with line endings (mostly because .tt files require crlf). Please get the latest commit and report if this is still a problem

**Comment by grovesNL** [comment]
@rsuter I think we may want to normalize all line endings to match the changes to .gitattributes, i.e. https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

**Comment by Cephei** [comment]
Re-forked and worked perfectly! Thanks!

**Comment by rsuter** [comment]
@grovesNL thanks, will do that soon...

**Comment by rsuter** [comment]
Ok, it should be fine now...

https://github.com/NSwag/NSwag/commit/84ea8fc86fb9e0d9b74948a76560208527de23af

**Comment by Cephei** [comment]
This is still a major issue. I'm having all kinds of problems with .ts, .tt, .csproj.

**Comment by Cephei** [comment]
Also, anything generated by .tt should most likely not be checked into the repo. It should be ignored by git. I'm running build.bat to test integration and then it shows me all the files to be checked in.

**Comment by rsuter** [comment]
Please try to delete the local repo and clone it again...

**Comment by Cephei** [comment]
I just created an entirely new fork. Deleted all files prior. Still shows files changed.

**Comment by rsuter** [comment]
Had the same problem, commited the changes: https://github.com/NSwag/NSwag/commit/34effb4a68c526592dc1c1ca986770e2c5859a59

Does this fix your problem?

**Comment by Cephei** [comment]
unsure ... I ran `git rm --cached -r .` and then `git reset --hard`. It seemed to help.

**Comment by grovesNL** [comment]
I noticed this yesterday too. It seems as though some files were skipped in the correction (https://github.com/NSwag/NSwag/commit/84ea8fc86fb9e0d9b74948a76560208527de23af) for some reason.

Fortunately after all the files have the correct line endings (i.e. matching .gitattributes rules) we shouldn't have this problem again. We just have to make sure any existing branches run `git rm --cached -r .` and `git reset --hard` as @Cephei said.

**Comment by grovesNL** [comment]
If I create a clone master and run `git rm --cached -r . && git reset --hard` it seems there are still some files that have line ending diffs. Do you see the same?

**Comment by Cephei** [comment]
<img width="324" alt="screen shot 2017-02-26 at 4 49 57 pm" src="https://cloud.githubusercontent.com/assets/1054639/23344058/ae169d84-fc43-11e6-8e94-61d4d3c2c30e.png">


These files must be getting generated from Demo.Web. Keeps asking me to check them in after a build. Going to disable that project (locally) for now.
