### ISSUE TITLE
Updating TypeScriptTools to latest...

### ISSUE THREAD

**Issue by Cephei** [NSwag/NSwag#631]
<img width="509" alt="screen shot 2017-02-26 at 4 23 38 pm" src="https://cloud.githubusercontent.com/assets/1054639/23343853/0ea09fdc-fc40-11e6-88eb-5587fca4f1be.png">

Not sure if it's possible for us to update to the latest. I had issues finding the version you're currently using so I've been disabling working with the TypeScript project

**Comment by rsuter** [comment]
Had the same problem...

@grovesNL Can you check this please?

**Comment by Cephei** [comment]
eleases
TypeScript 2.2.1 for Visual Studio 2015 — February 22, 2017 (release notes)[Download]
TypeScript 2.2.0 RC for Visual Studio 2015 — February 2, 2017 (release notes)[Download]
TypeScript 2.1.5 for Visual Studio 2015 — January 11, 2017 (release notes)[Download]
TypeScript 2.1.4 for Visual Studio 2015 — December 7, 2016 (release notes)[Download]
TypeScript 2.0.6 for Visual Studio 2015 — October 24, 2016 (release notes)[Download]
TypeScript 2.0.3 for Visual Studio 2015 — September 22, 2016 (release notes)[Download]
TypeScript 2.0.2 RC for Visual Studio 2015 — August 30, 2016 (release notes)[Download]
TypeScript 2.0.0 Beta for Visual Studio 2015 — July 11, 2016 (release notes)[Download]
TypeScript 1.8.6 for Visual Studio 2015 — March 1, 2016 (release notes)[Download]
TypeScript 1.8.4 for Visual Studio 2015 — February 22, 2016 (release notes)[Download]
TypeScript 1.8.1 Beta for Visual Studio 2015 — January 28, 2016 (release notes)[Download]
TypeScript 1.7.6 for Visual Studio 2015 — December 14, 2015 [Download]
TypeScript 1.7.4 for Visual Studio 2015 — November 30, 2015 (release notes) [Download]
TypeScript 1.6.3 for Visual Studio 2015 — September 16, 2015 (release notes) [Download]
TypeScript 1.6.0 Beta for Visual Studio 2015 — September 2, 2015 (release notes) [Download]
TypeScript 1.5.4 for Visual Studio 2015 — August 6, 2015 (release notes) [Download]
TypeScript 1.5.3 for Visual Studio 2015

**Comment by Cephei** [comment]
I suppose I can try installing an older version. I'm guessing it's currently using 2.0.0 Beta?

**Comment by grovesNL** [comment]
@rsuter I think we should update to the latest. I must have had an older version installed.
