### ISSUE TITLE
RoutePrefix with optional parameter causes invalid Paths

### ISSUE THREAD

**Issue by Cephei** [NSwag/NSwag#639]
Example:
```
[Route, RoutePrefix("users/{userId?}")]
public class UsersController : ApiController
{
    private readonly IUserManager _UserManager;

    public UsersController(IUserManager userManager)
    {
        _UserManager = userManager;
    }

    public Task<HttpResponseMessage> PostUser(UserDetailsDto userDto)
    {
        return _UserManager.CreateUser(userDto)
            .AwaitToHttpResponseMessageAsync(Request, HttpStatusCode.Created);
    }

    [Route("devices")]
    [AcceptVerbs("POST")]
    public Task<HttpResponseMessage> PostUserDeviceId(string userId, UserDeviceDto userDevice)
    {
        return _UserManager.AddUserDeviceId(userDevice.DeviceId, userDevice.Platform)
            .AwaitToHttpResponseMessageAsync(Request);
    }
}
```

swaggerDocument.Paths contains three paths.

**Comment by rsuter** [comment]
There are still problems with optional path parameters...

**Comment by rsuter** [comment]
So this was fixed with the route PR?

**Comment by Cephei** [comment]
All my routing is working properly now but I'm slowly enabling swagger generation for more controllers endpoints as I document them. Only am working with two controllers now as I refine my documentation approach (not using xml or attribute annotations).

**Comment by rsuter** [comment]
Ok thanks for your work here... I hope i can release next week. This will be a major version because we have some minor breaking changes... Do you see other important changes we should include in this release?
