### ISSUE TITLE
Is there a strategy to share DTOs across several clients?

### ISSUE THREAD

**Issue by paulomorgado** [NSwag/NSwag#640]
I have several clients that I want to generate for my project.

They are all under the same namespace.

Because they share DTO type names (and specifications), multiple class declarations are generated.

Is there a strategy to share DTOs across several clients?

**Comment by rsuter** [comment]
You can exclude types in the config and add namespaces to the missing types

**Comment by paulomorgado** [comment]
@rsuter, that's what I'm doing now, but that implies that I have to know, beforehand, what is on those swagger definitions.

I was wondering if there was some kind of bundle generator where only one type for each name would be generated.

**Comment by rsuter** [comment]
Can you just generate the DTOs (ie GenerateClients = false) and only the clients in two separate steps and then import the DTOs wherever you need them?

**Comment by paulomorgado** [comment]
Yes, I can. But then I'll have to know beforehand which ones to exclude from which.

I'll probably try to figure out if I can keep a list of already generated types.

**Comment by rsuter** [comment]
I'm planning to change the output process to work per class and then you can filter them in an output step... but this is a bigger task...
