### ISSUE TITLE
NSwagStudio generates incorrectly byte to a byte array

### ISSUE THREAD

**Issue by ericvb** [NSwag/NSwag#649]
From some legacy tables, I get following model
`public virtual byte? Cell { get; set; }`
This is translated by NSwagStudio to
```
[Newtonsoft.Json.JsonProperty("cell", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public byte[] Cell { get; set; }
```
causing an serializing exception _Could not deserialize the response body. Unexpected character encountered while parsing value:0. Path 'model[0].cell', line 1, position 49_  when getting for example 0 as value
It should generate for a normal System.Byte type:
```
[Newtonsoft.Json.JsonProperty("cell", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public byte? Cell { get; set; }
```
or if not nullable
```
[Newtonsoft.Json.JsonProperty("cell", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public byte Cell { get; set; }
```

**Comment by rsuter** [comment]
JSON Schema does not know a format string for a single byte (only "byte", a byte array). We could extend NJsonSchema with "singlebyte" format...

How is this property serialized? As integer?

**Comment by rsuter** [comment]
If the JSON Schema is generated by NJsonSchema, then it works for me: https://github.com/NJsonSchema/NJsonSchema/commit/12b14b961eb7651aaf2ad5245f5c3949e7ec71ea

**Comment by rsuter** [comment]
Can you post your JSON Schema?

**Comment by ericvb** [comment]
I'm new to NSwagStudio, even to the use of the Swagger project, so I think you are talking about the input tab 'JSON Schema'. Didn't use that because I don't even know how to use it (yet :-) )
Searched now quickly through the wiki here, but didn't find directly something about it...

Because of bug #641 (System.IndexOutOfRangeException: Index was outside the bounds of the array), I'm using the output swagger.json generated by Swashbuckle.
In this file I see for the Cell field :
```
    "Organigram": {
      "type": "object",
      "properties": {
        "id": {
          "format": "int32",
          "type": "integer"
        },
        "upperUnit": {
          "format": "int32",
          "type": "integer"
        },
        "cell": {
          "format": "byte",
          "type": "string"
        },
        "unitInitials": {
          "type": "string"
        }
      }
    },
```
In the legacy tables, there are effectivily several fields with the SQL datatype byte and used as a single byte integer. So yes, used as integer value.

So a solution can be to extend the NJSONSchema or another solution is that I adapt my exposed datamodel to use a normal int32 and that I do some conversion in my business layer from byte to int32 and viceversa before going to the database.

What do you think? Nowadays, with our tera bytes sql servers, nobody is using anymore the single byte type to save some space if your number exceeds not the 8 bits.
I have no idea about the amount of work, to extend the json schema with the single byte integer...

**Comment by rsuter** [comment]
According to the swagger spec (data types) 

http://swagger.io/specification/

"byte" describes a base64 byte array. There is no format string to describe a single byte. As i said, we can introduce a new format string in njs (eg singlebyte) but this would only work if you generate the spec with nswag. I will look into your exception soon..

**Comment by rsuter** [comment]
I just tried this once again... **If** you use NSwag/NJsonSchema to generate the spec and you have a byte property: 

    public byte MyByte { get; set; }

then the schema looks like: 

```
{
    "type": "integer", 
    "format": "byte"
}
```

which correctly generates a byte array when generating the client. 

It seems that Swashbuckle generates: 

```
{
    "type": "string", 
    "format": "byte"
}
```

which I think is wrong because according to the Swagger spec this denotes a base64 string which should be a byte[] in the generated client... With the latest fix (other issue, IndexOutOfRange) you can use NSwag for the swagger generation...

**Comment by ericvb** [comment]
Ok, thanks.
What is the roadmap planning for a new nuget package of NSwag?

If it's soon,  I will wait for the new nuget package, otherwise I will  download the code, built it and replace the original nswag dll's by the new build ones.

**Comment by rsuter** [comment]
I'm just releasing...

**Comment by rsuter** [comment]
Ok, v9.8 is released...

**Comment by ericvb** [comment]
I can't try it for the moment in our solution, because I stumbled on another problem, see #655
