### ISSUE TITLE
Load Swagger specification using http/https

### ISSUE THREAD

**Issue by pontusr** [NSwag/NSwag#65]
Hi,

It would be great to be able to input a URL (for example: https://example.com/api/swagger/docs) in the Swagger specification input text area and load the specification from that endpoint.

Thanks for a great tool

**Comment by rsuter** [comment]
Yes, I thought about this too... should be simple to implement. Thanks for using NSwag and submitting an issue.

**Comment by rsuter** [comment]
Added commit: https://github.com/NSwag/NSwag/commit/fde8cf1f48f9c51536e38c127d7d0b6369bc1893
