### ISSUE TITLE
TypeScript client generation: toJSON methods break JSON.stringify

### ISSUE THREAD

**Issue by jtheisen** [NSwag/NSwag#650]
The generated objects all have a `toJSON` method defined, which returns a json string.

`JSON.stringify`, however, uses that method and expects something to be stringified instead.

From mozilla.org:

> Instead of the object being serialized, the value returned by the toJSON() method when called will be serialized.

In other words, those objects all serialize to strings.

**Comment by jtheisen** [comment]
Weird, I find the serialization code that's generated for me...

    toJSON() {
        return JSON.stringify(this.toJS());
    }

...only in a directory call `NSwag.Integration.TypeScriptWeb\scripts` in NSwag's sources, ie. tests.

**Comment by grovesNL** [comment]
The client transformation code is generated in [NJsonSchema](https://github.com/NJsonSchema/NJsonSchema) which is a dependency of NSwag.

I'm not sure, but I believe this stringify behavior is intentional. What would you expect the output to be if not a `string`?

**Comment by rsuter** [comment]
Yes, DTOs are generated in NJsonSchema.CodeGeneration.TypeScript...

**Comment by jtheisen** [comment]
@grovesNL The output should be a string, yes, but it's a json-encoded string string, ie. something like this:

"\"{ ... }\""

The generated client itself calls `JSON.stringify` on the `toJS`-ed plain object, which is why this is usually not an issue. It would be nice though if one could still call `JSON.stringify` on the generated types' objects themselves.

I have a number of other issues with the generated code though (I'd really prefer plain objects defined with interfaces - that's going to play nicer with a state management library I use, mobx) and so will probably need to go with a customized generation anyway.

**Comment by rsuter** [comment]
You can generate interfaces instead of classes, theres an option for that

**Comment by rsuter** [comment]
... and you should not serialize the generated classes externally because it would not serialze correctly (the properties may be renamed)

**Comment by jtheisen** [comment]
I see. You could make it serialize correctly as `JSON.stringify`'s behavior can be configured by defining `toJSON` on the to be serialized objects (which nswag does, just not in a way that fits). I realize now that it had hardly any benefit though, especially since I don't think `JSON.parse` can be similarly configured.

The best suggestion I could make in this topic is that perhaps a `JSON.stringify` on the generated types should throw an exception as a heads-up to the programmer.

This issue should probably be closed then.

**Comment by rsuter** [comment]
Maye we should rename toJS to toJSON and toJSON to JSONstringify so that the behavior is as expected...
