### ISSUE TITLE
TypeScript API_BASE_URL with distinct name

### ISSUE THREAD

**Issue by marc-mueller** [NSwag/NSwag#661]
We have currently multiple micro services implemented and each service accessed by a distinct url. We generate for each service a client with NSwag which is then distributed as npm package. The current solution does not use any namespaces. 

If we now import multiple client packages, we have a naming conflict with API_BASE_URL. Our workaround currently is a rename of the field after the client creation in a post-generator action. If the name of this field could be set by a parameter in the settings, that would be great.

**Comment by rsuter** [comment]
Can't import the token with an alias?

    import { API_BASE_URL as PERSON_URL } from "person.client";

Nevertheless, we should provide this as option ("BaseUrlTokenName")...

**Comment by marc-mueller** [comment]
Thanks for the quick extension!
