### ISSUE TITLE
Error in TypeScript interface parameter name ">"

### ISSUE THREAD

**Issue by marc-mueller** [NSwag/NSwag#662]
The current version of the TypeScript generator has a wrong character withing the parameter name for the interfaces in TypeScript.

```
export interface IxxxxClient {
    /**
     * @return Success
     */
    getxxxDatas(id>: string): Observable<PublicKeyData[]>;
}
```

As you can see, there is a ">" behind each method parameter name.

**Comment by rsuter** [comment]
v9.10
