### ISSUE TITLE
Return jQueryXHR in jQueryCallbacks template to enable cancellation

### ISSUE THREAD

**Issue by nerfpops** [NSwag/NSwag#670]
ES6 and jQuery promises doesn't support cancellation, but jQueryXHR can be aborted. Instead of returning void, you could:

    let jqXhr = jQuery.ajax(...)
    jqXhr.done((...) => this.processWithCallbacks(...).fail(...)
    return jqXhr

Until someone agrees on how promises can be cancelled, this would be a quick fix to make it possible to cancel an xhr via NSwag generated code.

**Comment by nerfpops** [comment]
You rock 👍

**Comment by rsuter** [comment]
Thanks, but this was an easy one :)
