### ISSUE TITLE
Nswag use for Typescript generates duplicated client

### ISSUE THREAD

**Issue by sankp** [NSwag/NSwag#671]
Hello,

I am using Swagger UI for generating API clients in typescript.
I have multiple routes defined with two handlers.
Because of this when i run this
http://localhost/code_api/swagger/ui/index

I get multiple routes like this.
![image](https://cloud.githubusercontent.com/assets/9613276/23837354/ce55feac-0754-11e7-868e-d338c22801c8.png)

Because of this when i use nswag.exe tool for generating typescript clients, I get duplicated routes and also all classes are getting duplicated. eg. User, User1 something like this.

Is there a way to fix this ?

**Comment by rsuter** [comment]
You have to manually filter the scanned assemblies/selected controllers... In Startup.cs you can pass the exact controller types, in nswag.json you can specify the controller names (supports wildcards).

**Comment by sankp** [comment]
Hello,

i was able to fix this issue by filters.
