### ISSUE TITLE
Latest nswag 9.10 command line still fails on Linux due to line endings

### ISSUE THREAD

**Issue by empedia** [NSwag/NSwag#674]
As per #613 can confirm that the same problem is still happening for 9.10. This might only be when installing nswag using npm on Linux but the line ending for the nswag.js file is still set to Windows. 

This might be a useful reference - https://github.com/npm/npm/issues/2097 #613

**Comment by rsuter** [comment]
Can you try with v9.11?

**Comment by rsuter** [comment]
After installing on my system, I had a correct js file only with LFs...
