### ISSUE TITLE
Suggestion: Improved pattern for TypeScript field initializers

### ISSUE THREAD

**Issue by datumgeek** [NSwag/NSwag#679]
Amazing stuff here with ***NSwag***...  thought I'd suggest this pattern for initializing the TypeScript objects in the generated client code...

[TypeScript Field Initializers](http://stackoverflow.com/a/37682352/7085047) 📓 
================

[Typescript 2.1 introduces Mapped Types](https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/) and provides `Partial<T>`, which allows you to do this....

```javascript
    class Person {
        public name: string = "default"
        public address: string = "default"
        public age: number = 0;
    
    public constructor(init?:Partial<Person>) {
            Object.assign(this, init);
        }
    }
    
    let persons = [
        new Person(),
        new Person({}),
        new Person({name:"John"}),
        new Person({address:"Earth"}),    
        new Person({age:20, address:"Earth", name:"John"}),
    ];
```

**Comment by rsuter** [comment]
This won't work because the properties of the received object may be renamed to lower case (JS style)...

**Comment by datumgeek** [comment]
gotcha - thanks - and again - NSwag is amazing 😄

**Comment by rsuter** [comment]
Thanks for the idea and for using NSwag! :)
