### ISSUE TITLE
BASE URL in swagger spec not set for APIs under virtual dirs when using the WebAPI+OWIN middleware config

### ISSUE THREAD

**Issue by Grendel** [NSwag/NSwag#680]
I'm setting up a web api and trying to get my security middleware and the NSwag OWIN middleware config working side by side. 

I have it working in so far that the security middleware is triggered for actual API end point calls, whilst the /swagger end point remains open for discovery. 

The issue is that when the OWIN spec is generated by the OWIN NSwag configuration it has an empty 'context.Request.PathBase' in the OwenContext. This results in an empty BASE URL served up to the Swagger UI.

I've tested the same configuration using your SampleOwinWebApiWithSwaggerUi config sample and have observed the same behaviour. If you run it under the default localhost you are fine, but if you run it under a virtual directory the generated BASE URL is empty so the path for the individual end points is not fully configured.

Screen shot highlighted the issue:

![owin_api-under_virtual_directory](https://cloud.githubusercontent.com/assets/35219/23999379/2539aa54-0a50-11e7-911f-d2958f4b4cb8.png)

The local IIS config:

![owin_api-under_virtual_directory_iis_setup](https://cloud.githubusercontent.com/assets/35219/23999391/33dee2fe-0a50-11e7-8019-13867bb2e269.png)

Interestingly I can get the virtual directly working correctly if I use the Global.asax based config approach, but then I can't get the security middleware working because you need to disable the default OWIN startup discovery.

Will continue to work through this myself but am not an expert in the OWIN pipeline/lifecycle.

Kind regards,

Edward

**Comment by Grendel** [comment]
Okay - so I _think_ I have a better idea why the base path is not being populated.

This:

`document.BasePath = context.Request.PathBase.Value?.Substring(0, context.Request.PathBase.Value.Length - _settings.MiddlewareBasePath?.Length ?? 0) ?? "";`

Is using context.Request which will not be populated on 'Startup' because this runs once on app startup not in the context of a web request.

Would HostingEnvironment.ApplicationVirtualPath be a better option although this pulls in a dependency on System.Web into the NSwag.AspNet.Owin project.

**Comment by rsuter** [comment]
What about manually setting the base url with PostProcess in the settings?

**Comment by gnjack** [comment]
The BasePath is also not automatically set for us when using the Owin middleware, it seems like this line of GenerateSwaggerAsync isn't functioning as intended for some reason: https://github.com/NSwag/NSwag/blob/master/src/NSwag.AspNet.Owin/SwaggerMiddleware.cs#L71
```
document.BasePath = context.Request.PathBase.Value?.Substring(0, context.Request.PathBase.Value.Length - _settings.MiddlewareBasePath?.Length ?? 0) ?? "";
```

As @rsuter mentioned, it is easy enough work around by manually setting in PostProcess:
```
app.UseSwaggerUi(
	typeof(Startup).Assembly,
	new SwaggerUiOwinSettings
	{
		PostProcess = document =>
		{
			document.BasePath = "/SampleOwinWebApiWithSwaggerUi";
		}
	});
```

**Comment by Grendel** [comment]
Hey guys. Thanks - that seems to do the trick.
