### ISSUE TITLE
types2swagger Property default value ignored

### ISSUE THREAD

**Issue by frankkoenigstein** [NSwag/NSwag#688]
In the follwinig code Method has the defaut value "login":
```c#
    [DataContract]
    public class LoginRequest
    {
        [DataMember(IsRequired = true)]
        public string Method { get; set; } = "login";
    }
```

But this default value is not written in generated swagger configuration:
```json
{
"LoginRequest": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "method"
      ],
      "properties": {
        "method": {
          "type": "string"
        }
      }
    }
}
```

Generation should result in:

```json
{
"LoginRequest": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "method"
      ],
      "properties": {
        "method": {
          "type": "string",
          "default": "login"
        }
      }
    }
}
```

```ts
export class LoginRequest {
    method: string = "login";

    constructor(data?: any) {
        super(data);
        if (data !== undefined) {
            this.method = data["method"] !== undefined ? data["method"] : "login";
        }
    }

    static fromJS(data: any): LoginRequest {
        return new LoginRequest(data);
    }

    toJS(data?: any) {
        data = data === undefined ? {} : data;
        data["method"] = this.method !== undefined ? this.method : "login";
        return data; 
    }

    toJSON() {
        return JSON.stringify(this.toJS());
    }

    clone() {
        const json = this.toJSON();
        return new LoginRequest(JSON.parse(json));
    }
}
```
Please have a look.
Is there another way to specify default value in c#?

**Comment by rsuter** [comment]
You need to specify the default value with the DefaultValueAttribute (https://msdn.microsoft.com/en-us/library/system.componentmodel.defaultvalueattribute(v=vs.110).aspx) because `= "login"` is just syntactical sugar for an assignment in the ctor and this default value cannot be read via reflection...

**Comment by frankkoenigstein** [comment]
Thanks.

Could you please document how those Annotations influnce nswag generation?
I also don't know how to annotate static members in c# so that they are added to swagger configuration.

Please help.

**Comment by rsuter** [comment]
See https://github.com/NJsonSchema/NJsonSchema/wiki/JsonSchemaGenerator

**Comment by rsuter** [comment]
> I also don't know how to annotate static members in c# so that they are added to swagger configuration.

Can you post an example?

**Comment by rsuter** [comment]
Please create a new issue
