### ISSUE TITLE
Configurable HttpCompletionOption for generated c# Client 

### ISSUE THREAD

**Issue by jonnybi** [NSwag/NSwag#697]
We have a problem with file uploads when using .net core and docker.

The response content cannot be read when using file upload because of  
https://github.com/dotnet/corefx/issues/16259

We should be able to change the `HttpCompletionOption` to `ResponseContentRead`
in `client_.SendAsync(...)`.

I think this might be usefull in other scenarios too.

**Comment by rsuter** [comment]
Oh, this is bad... Will this be fixed?

**Comment by jonnybi** [comment]
I hope so...

I think a easy solution could be to prevent the generation of a client operation if 
it is allredy implemented in the base class or via an attribute. 
Therefore we are aple provide custom implementations for certain methods.

**Comment by rsuter** [comment]
You can hide methods with the ProtectedMethods setting

**Comment by jonnybi** [comment]
ah ok thanks
