### ISSUE TITLE
[TypeScript] [Aurelia] Check if the response was already read

### ISSUE THREAD

**Issue by arnederuwe** [NSwag/NSwag#699]
Hi,

When a TypeScript client is generated with the Aurelia template, the response is processed like this:
`return response.text().then((responseText) => {...`
This makes it impossible to work with interceptors that read the response before this code is executed. Because the promise is already resolved, the generated code will give an 'Uncaught TypeError: Already read' error.
There is a property available on the Response object that you can check to see if the response is already read, see: https://developer.mozilla.org/en-US/docs/Web/API/Body/bodyUsed
Would it be possible to perform this check in the process methods before performing 'text()' and acting accordingly when the response was already read?

**Comment by rsuter** [comment]
Can you show a sample output?

**Comment by arnederuwe** [comment]
You can close this, I did some research on how to read the result from a fetch twice and apparently it's not possible at the moment..
I managed to work around the issue in my interceptor method by cloning the response object before doing text(), so when it hit's your code, the original response still isn't read. Perhaps you could put this info somewhere in your docs?

**Comment by rsuter** [comment]
Hmm, can you create a PR with this docs change?

**Comment by arnederuwe** [comment]
Sure! You can expect it next week

**Comment by arnederuwe** [comment]
Sorry for the delay, apparently creating a pull request for wiki pages isn't possible, soI'll include it here. I would include this info [here](https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#aurelia-based-on-fetch):

Template for Aurelia using the HttpClient from aurelia-fetch-client. By using the HttpClient via dependency injection you can add global interceptors and other global configurations.
When using a global response interceptor, beware that the generated TypeScript code calls the [.text()](https://developer.mozilla.org/en-US/docs/Web/API/Body/text) method to read the response. Because the response of a fetch call can only be read once, you cannot call arrayBuffer(), blob(), json(), text() or formData() on the response object yourself or the generated TypeScript code will throw an exception. If you need to read the response in your interceptor, you should clone the response first and perform the text() function or equivalent on the cloned response, like this: `response.clone().text()`

**Comment by rsuter** [comment]
Thank youi for the wiki change, I've updated the wiki: https://github.com/NSwag/NSwag/wiki/SwaggerToTypeScriptClientGenerator#aurelia-based-on-fetch

It seems that GitHub does not support PRs for wikis: http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by rsuter** [comment]
Maybe I should allow wiki Edits, but I'm a bit afraid of bad changes (ie bots, etc.)

**Comment by rsuter** [comment]
Ok the wiki is now public, we'll see if this is a problem :)
