### ISSUE TITLE
Visual Studio 2015 Integration / Post Build ?

### ISSUE THREAD

**Issue by CastleSoft** [NSwag/NSwag#70]
What is the recommended way to integrate the Command Line for NSwag into a Webapi project ?

Currently I build the WebAPI and either switch to the GUI or command line.

But it would be nice to compile and automatically have the NSwag TS files generated.

Is this something that could be done using Nuget ? Or is it best via Post Build commands ?

LIke Arebis does ? You can then reference a .../Client/MyWebapi.js   containing the wrapper ?

http://www.codeproject.com/Articles/872033/ASP-NET-Web-API-Javascript-Clients

https://www.nuget.org/packages/Arebis.AspNet.WebApi.JsClients.cs/

**Comment by rsuter** [comment]
Currently there is no NSwag build target / NuGet package with build targets available. I think the best option is to add a post compile target/task and execute the command line tool...

**Comment by rsuter** [comment]
Use NSwag.MSBuild

**Comment by rsuter** [comment]
See https://github.com/NSwag/NSwag/wiki/MSBuild
