### ISSUE TITLE
CSharp client code GenerateOptionalParameters and optional issue

### ISSUE THREAD

**Issue by BlackGad** [NSwag/NSwag#702]
If u are using optional path operation parameter Generator correctly generates optional default value.
But then first line of code will be 
` if (<param> == null) new System.ArgumentNullException("<param>");`

Example:
Swagger parameter definition:
```
  "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Item identifier. UUID.",
            "required": false,
            "type": "string"
          }
        ]
```
Generated .cs code
```
public async System.Threading.Tasks.Task<Response> RenderPageAsync(string id = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
{
    if (id == null) throw new System.ArgumentNullException("id");
...
}
```

**Comment by rsuter** [comment]
According to the specification (http://swagger.io/specification/#parameterObject), a Path parameter must be required: 

> required = Determines whether this parameter is mandatory. If the parameter is in "path", this property is required and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

**Comment by BlackGad** [comment]
Ok, then argument in function must be required too i guess

**Comment by rsuter** [comment]
Yes its inconsistent, but this spec is not valid. Maybe we can still inofficially support this case...

**Comment by rsuter** [comment]
Please test with latest CI artifacts

**Comment by BlackGad** [comment]
I common case path is required. But in my case not. It would be nice if add some kind of option to support this or at least to tell generator do not generate null reference check

**Comment by rsuter** [comment]
See my latest commit
