### ISSUE TITLE
NSwag.CodeGeneration.CSharp model naming, dealing with not unique naming

### ISSUE THREAD

**Issue by molszews** [NSwag/NSwag#703]
For the following swagger doc:
```
{
    "paths": {
        "/api/book/add": {
            "post": {
                "consumes":(..),
                "operationId": "Book_Add",
                "parameters": [
                    {
                        "in": "body",
                        "name": "model",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/features.book.addbook.command"
                        }
                    }
                ],
                "produces": (..),
                "responses": (..)
            }
        },
        "/api/book/update": {
            "post": {
                "consumes":(..),
                "operationId": "Book_Update",
                "parameters": [
                    {
                        "in": "body",
                        "name": "model",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/features.book.updatebook.command"
                        }
                    }
                ],
                "produces": (..),
                "responses": (..)
            }
        }
(..)
    }
}
```
C# client code will have classes with names `Command1`, `Command2`, etc.
Is there a chance to use the name form `$ref` (in case of having non unique names), so they become e.g. `AddbookCommand` and `UpdatebookCommand`? Right now I have to deal with `Command23`, etc. I think the swagger doc knows the best what should be the names of models, so they should be retrieved from `definitions` part of swagger doc (in fact entries in `definitions` are unique already).

**Comment by rsuter** [comment]
You can provide an own ITypeNameGenerator via the settings object...

**Comment by molszews** [comment]
@rsuter You're right, haven't noticed that. Is it possible then to pass it somehow when I execute nswag.exe?

**Comment by rsuter** [comment]
This is currently not possible - you have to write your own command line app (should be simple). I hope to add this functionality (e.g. define TypeNameGenerator in nswag.json and load it from an assembly).

**Comment by rsuter** [comment]
Otherwise, you can create two nswag.json files (ie swaggerGen.nswag and codeGen.nswag) then run 1. swaggerGen.nswag (with Swagger spec output), 2. transform swagger spec, 3. run codeGen.nswag based on transformed spec

**Comment by molszews** [comment]
okay, I hoped I could just reference `NSwag.MSBuild` in my api client project, but that's fine, I think we can close the issue now

**Comment by rsuter** [comment]
Yes, I also try to avoid code extensions and only use the provided settings. But sometimes more tweaks are required...

**Comment by molszews** [comment]
@rsuter quick question: not sure if this will be the same issue or a different one. When I generate swagger doc from webapi assembly then `Command1`, `Command2`, etc. are in output swagger json file. I tried to play with `WebApiAssemblyToSwaggerGeneratorSettings` but despite having `TypeNameGenerator` and `SchemaNameGenerator` set to custom ones, they seems to be never used by swagger doc generator. Is there a way to enhance the swagger doc generation process itself?

**Comment by rsuter** [comment]
This is very strange... can you provide a sample project with your custom TypeNameGenerator and sample controllers?

**Comment by molszews** [comment]
@rsuter here it is
[TestNSwag.zip](https://github.com/NSwag/NSwag/files/890006/TestNSwag.zip)

**Comment by rsuter** [comment]
Hmm, both generators are not even called...

**Comment by rsuter** [comment]
Ah, you cannot use WebApiAssemblyGenreator classes (these have the same limitations as the cmd line, because they use a new AppDomain and extension classes cannot be passed to this domain)... you need to use WebApiToSwaggerGenerator:

**Comment by rsuter** [comment]
[TestNSwag.zip](https://github.com/NSwag/NSwag/files/890092/TestNSwag.zip)

**Comment by molszews** [comment]
@rsuter btw: why swagger doc generated that way differs from the one available at http://localhost:57174/swagger/docs/v1 ?

**Comment by rsuter** [comment]
When you use the NSwag middlewares, you can use the TypeNameGenerators, etc... because the spec is not generated in a separate AppDomain...

**Comment by molszews** [comment]
What I meant is that NSwag generates different swagger doc than Swashbuckle, but I understand that there are no strict rules of how the result file should look like (at least in terms of naming)

**Comment by rsuter** [comment]
Yes this makes sense. Do you see any discrepancies which have to be fixed? Btw: NSwag is a replacement for Swashbuckle and also provides middlewares to serve the spec and SwaggerUI.
