### ISSUE TITLE
JsonSchema attribute ignored when generating from the command line

### ISSUE THREAD

**Issue by javicrespo** [NSwag/NSwag#706]
I'm trying to use the JsonSchema attribute to convert a complex type to a swagger/json schema string type.

```csharp
 public class Foo
    {
        [NJsonSchema.Annotations.JsonSchema(JsonObjectType.String)]
        public Bar Bar { get; set; }
    }
```

When I generate with nswag.exe webapi2swagger I get the following swagger output:

```json
"bar": {
          "$ref": "#/definitions/Bar"
        }
```
But I was expecting:

```json
"bar": {
          "type": "string"
        }
```

So it seems that the attribute is ignored by the generator.
If I do the same thing with the asp.net core swagger runtime generator (configured with SwaggerUiOwinSettings) then I get the expected result.

Am I missing something?

**Comment by rsuter** [comment]
I think 

    [NJsonSchema.Annotations.JsonSchema(JsonObjectType.String)]

Must be defined as class attribute on Bar

**Comment by javicrespo** [comment]
I just tried with a class attribute, no luck.
At runtime (asp.net core) it works in both cases (class or property attribute)

**Comment by rsuter** [comment]
Have you tried to run `dotnet publish` before running nswag in the cmd line?

**Comment by javicrespo** [comment]
I'm using asp.net core with Windows .net fwk. Tried publishing the site but it didn't make a difference.
I quickly created a project that shows the issue
https://github.com/javicrespo/NSwagCustomSchema
If you execute the command line nswag as described in this file it doesn't work https://github.com/javicrespo/NSwagCustomSchema/blob/master/NSwagCustomSchema/GenerateCommandLine.txt
But if you run the website you'll see the expected result.
Let me know if that helps

**Comment by rsuter** [comment]
With v10 (just released) it works for me: 

![image](https://cloud.githubusercontent.com/assets/2603405/24815690/57bba2f6-1bd6-11e7-8ec1-bc1aecceb973.png)

Maybe this was because you were using a newer version of NJsonSchema than the released version of NSwag (v9.12)?

**Comment by javicrespo** [comment]
Ok, we're getting close :)

The nswag.exe that I'm using outputs the following version info:
NSwag command line tool for .NET 4.6+, toolchain v9.12.6284.27589 (NJsonSchema
8.11.6284.26855) (x64)

I downloaded nswag.exe tooling earlier today from here: http://rsuter.com/Projects/NSwagStudio/archive.php

The asp.net core project references nswag 10.0
<PackageReference Include="NSwag.AspNetCore" Version="10.0.0" />

Do I need to update nswag.exe? Where can I download it?

**Comment by rsuter** [comment]
See  https://github.com/NSwag/NSwag/wiki/CommandLine

**Comment by rsuter** [comment]
I recommend 

npm i -g nswag

**Comment by javicrespo** [comment]
Ok, that did the trick.
In order to work, the NSwag.AspNetCore package used in the target project and the NSwag.exe command line utility need to reference the same NJsonSchema.dll version (where the attribute is defined).
