### ISSUE TITLE
PrepareRequest/ProcessResponse signatures

### ISSUE THREAD

**Issue by molszews** [NSwag/NSwag#707]
For now they looks like:
```
        partial void PrepareRequest(System.Net.Http.HttpClient request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient request, System.Net.Http.HttpResponseMessage response);
```
However it would make much more sense if `PrepareRequest` would accept `HttpRequestMessage` as a parameter. Having single `partial void PrepareRequest(System.Net.Http.HttpClient httpClient, System.Net.Http.HttpRequestMessage request);` executed right before `SendAsync` would be sufficient. (So I could easily append http headers or change request uri).
Btw: I think `HttpClient` type variable should be called simply `httpClient`, and not `request` as it is now.

Btw2: I am not sure but maybe adding an option to generate these classes as partial/required in base class would be a good idea. I could then use a common base class for all services that will for example add custom header to each sent message.

**Comment by rsuter** [comment]
You should use

![image](https://cloud.githubusercontent.com/assets/2603405/24804547/0f1169ea-1baf-11e7-8dd9-32c005e94976.png)
