### ISSUE TITLE
NSwag 10.0 not "noImplicitAny"-friendly anymore

### ISSUE THREAD

**Issue by TimLariviere** [NSwag/NSwag#711]
Hi,
When generating a TypeScript file from a swagger definition with NSwagStudio 10.0, it now produces a function named "blobToText" which has an implicitly-typed any parameter.
```
function blobToText(blob: Blob): Observable<string> {
    return new Observable((observer) => { 
        let reader = new FileReader(); 
        reader.onload = function() { 
            observer.next(this.result);
            observer.complete();
        }
        reader.readAsText(blob); 
    });
}
```
When compiling TypeScript with the "noImplicitAny" flag, it fails due to this missing type.
> TS7006: Parameter 'observer' implicitly has an 'any' type.

In my case, this function is not even used.

I've attached a sample nswag file reproducing this issue.
[test.zip](https://github.com/NSwag/NSwag/files/910085/test.zip)

**Comment by rsuter** [comment]
Should be fixed with v10.1 (if the function is not used, it should be tree-shaked away from angular)
