### ISSUE TITLE
TypeError: _response.text is not a function (wrong code generated)

### ISSUE THREAD

**Issue by sviluppoRobyone** [NSwag/NSwag#712]
Hi,
after last update (v10.0)  there is an error in angular js code generation here [https://github.com/NSwag/NSwag/blob/5bfb3ab6f64dd22f7913e6e6091f71b21a213022/src/NSwag.CodeGeneration.TypeScript/Templates/ProcessResponseTemplate.tt#L23-L24](https://github.com/NSwag/NSwag/blob/5bfb3ab6f64dd22f7913e6e6091f71b21a213022/src/NSwag.CodeGeneration.TypeScript/Templates/ProcessResponseTemplate.tt#L23-L24).

It's seems to be the code for "Fetch" template instead of AngularJS (i don't know a method named .text() for IHttpPromiseCallback).

This is the full command:
`nswag swagger2tsclient /input:http://localhost:59633/swagger/docs/v1 /modulename:myapp /classname:Client /OperationGenerationMode:SingleClientFromOperationId /TypeStyle:Interface /Template:AngularJS /ImportRequiredTypes:false /output:./Scripts/Models/api.ts`

Thank you for your help

**Comment by rsuter** [comment]
Should be fixed with v10.1
