### ISSUE TITLE
Generating swagger from non-WEB API assembly

### ISSUE THREAD

**Issue by PaulDotNet** [NSwag/NSwag#715]
**WebApiToSwaggerGenerator** looks for classes inheriting **ApiController** when generating swagger spec. Is it possible to generate swagger from the class that does not inherit from **ApiController**? There does not seem to be anything that **WebApiToSwaggerGenerator** needs from **ApiController** base class anyway.

**Comment by rsuter** [comment]
WebApiToSwaggerGenerator needs a way to identify controller classes and this is by looking for ApiController or Controller inheriting classes. But you can manually define the classes to generate...

**Comment by PaulDotNet** [comment]
This is great. From documentation I got the impression that ASP.NET classes were necessary to generate swagger for methods.

**Comment by rsuter** [comment]
No, you need asp.net classses, but you can manually select them...

**Comment by PaulDotNet** [comment]
I just called **WebApiToSwaggerGenerator.GenerateForControllerAsync < T >** specified abstract class and got nice swagger specification back. Project had references to System.Web.Http and System.Net.Http but no classes inheriting **ApiController**.  If this is a bug then please do not fix it.

**Comment by rsuter** [comment]
No this is a feature... If you do not specify a controller then it guesses the controllers but only classes which are probably controllers are selected... otherwise you can specify any class and it tries to generate.

**Comment by rsuter** [comment]
Btw: selecting specific controllers works also via cmd line, nswag.json and nswagstuidio
