### ISSUE TITLE
TypeScript command Template description proposes incorrect 'Angular 2' option 

### ISSUE THREAD

**Issue by dan-dekel** [NSwag/NSwag#719]
Typescript Client Template Command (SwaggerToTypeScriptClientCommand.cs) suggest 'Angular2' as an option. Should be 'Angular' as per en um TypeScriptTemplate. When running the CLI, If 'Angular2' is selected as an option for the 'Template' argument, the cli throws an error: 'Requested value 'Angular2' was not found'

**Comment by rsuter** [comment]
Yes, this has been renamed to "Angular"
