### ISSUE TITLE
Required nullable<primitive types> could be transformed into non-nullable primitive types

### ISSUE THREAD

**Issue by molszews** [NSwag/NSwag#720]
When you write webapi and you require to pass primitive type, e.g. `int` then you have to put in your model `[Required] public int? my_property {get; set;}`. Could be such properties represented in generated client class simply as `public int my_property {get;set;}`, because null value is not allowed to be passed there anyway?
The other case is when you reuse that model in action that returns entities. These properties are populated there for sure however for the client they are still nullables (because they are declared as nullables in the first place), however generator knows that they are also `[Required]` so there is no chance for it to be nullable.

**Comment by rsuter** [comment]
This is already working as described: https://github.com/NJsonSchema/NJsonSchema/commit/09e8148fbbefbf66e555aba6f019cafb85748352

Can you provide a specific sample?

**Comment by molszews** [comment]
mea culpa - in that particular model I was using `FluentValidation`, indeed this mechanism is already in place and it is working correctly
