### ISSUE TITLE
Configuration to not wrapping results with Observable.of in TypeScript / Angular

### ISSUE THREAD

**Issue by faramos** [NSwag/NSwag#721]
Is there any way to configure results to not be wrapped with like return Observable.of(result200);?
I just want it like in previous version (v9.12.6284.27589)
Anyway, where can I download an old version of NSwagStudio?
Great tool!
Thank you very much!

**Comment by rsuter** [comment]
You can download old versions here: https://github.com/NSwag/NSwag/releases

What exactly is the problem? I think they were wrapped before too? How did it look like (diff?)?

**Comment by faramos** [comment]
Thanks Rico.

The main difference is at "return result200" vs "return Observable.of(result200)"

Before:

`    protected processEntityTypeProperties(response: Response): QueryablePropertyInfo[] {
        const responseText = response.text();
        const status = response.status; 

        if (status === 200) {
            let result200: QueryablePropertyInfo[] | null = null;
            let resultData200 = responseText === "" ? null : JSON.parse(responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [];
                for (let item of resultData200)
                    result200.push(QueryablePropertyInfo.fromJS(item));
            }
            return result200;
        } else if (status !== 200 && status !== 204) {
            this.throwException("An unexpected server error occurred.", status, responseText);
        }
        return null;
    }`

After:

`    protected processEntityTypeProperties(_response: Response): Observable<QueryablePropertyInfo[] | null> {
        const _status = _response.status; 

        if (_status === 200) {
            const _responseText = _response.text();
            let result200: QueryablePropertyInfo[] | null = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [];
                for (let item of resultData200)
                    result200.push(QueryablePropertyInfo.fromJS(item));
            }
            return Observable.of(result200);
        } else if (_status !== 200 && _status !== 204) {
            const _responseText = _response.text();
            return throwException("An unexpected server error occurred.", _status, _responseText);
        }
        return Observable.of(null);
    }
`

**Comment by rsuter** [comment]
Ah ok. And why is this a problem? The public api hasnt changed and you could transform the result with map()

**Comment by faramos** [comment]
Sure, I know it, but these way you must transform every result with map() before using safely. If I send a FromArrayObservable instance to lodash, I get some side effects, like getting null as argument at some iteration functions.

**Comment by rsuter** [comment]
I think you can generate a sync transform method,... Check the settings.

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/SwaggerToTypeScriptClientGeneratorSettings.cs#L60

**Comment by faramos** [comment]
I´ll try it. Thanks!

**Comment by nbickel** [comment]
I try to update to the new version and have same issue and i don't understand why you are saying that the public api hasnt changed. it has changed. In this example instead of QueryablePropertyInfo[] a Observable (ScalarObservable) gets returned instead of the Array QueryablePropertyInfo[]. I can not iterate with for..of over the result return from the Client.

**Comment by rsuter** [comment]
Ok the protected API has changed - I agree. But this had to be done to support blob results... 

I still dont understand why you can't transform the result with `return observable.map(p => TRANSFORM(p));` instead of `return TRANSFORM(p);` in a overridden method?

**Comment by nbickel** [comment]
The protected method returns Observable and map does wrap the result in an observable too, there are different behaviors
Normal case returns: Observable<Observable<T>>
Error case (catch Response) returns: Observable<T>

**Comment by rsuter** [comment]
Is this a problem with this issue? https://github.com/NSwag/NSwag/issues/733

**Comment by nbickel** [comment]
yes, i will test the flatmap solution tomorrow
