### ISSUE TITLE
C# code generator and Head requests

### ISSUE THREAD

**Issue by BlackGad** [NSwag/NSwag#722]
There is issue in generated client code for head requests:
Part 1:
```
var content_ = new System.Net.Http.StringContent(string.Empty);
request_.Content = content_;
request_.Method = new System.Net.Http.HttpMethod("HEAD");
```
Head request cannot contain any kind of content. This code produce:
```
Exception thrown: 'System.Net.ProtocolViolationException' in System.dll
Additional information: Cannot send a content-body with this verb-type.
```

Part 2:
```
request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
```
Related to part 1... response also cannot contain body so any Accept headers must be skipped.

Part 3:
```
if (status_ == "400")
{
var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
throw new ResponseException("Bad Request", status_, responseData_, headers_, null);
}
```
Same here... Content is absent.

**Comment by BlackGad** [comment]
Also there is no possibility to actually skip this even with partial client implementation.

Please add additional partial method 
```
PrepareRequest(client_, request_);
```
just before send. It will allow to fix a lot of user specific stuff.

**Comment by rsuter** [comment]
v10.2

**Comment by BlackGad** [comment]
Works as expected. Also thank you for additional feature implementation(PrepareRequest)
