### ISSUE TITLE
Optional disposing HttpClient

### ISSUE THREAD

**Issue by molszews** [NSwag/NSwag#723]
Inside client class I am using `CreateHttpRequestMessageAsync()` to get `HttpClient` from client base class. Inside that base class I am creating `HttpClient` instance once with hope to reuse it across subsequent requests (see e.g. [this article](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) ). Is there any option to not dispose `HttpClient` object after sending a request (with `InjectHttpClient` set to false)?

**Comment by rsuter** [comment]
v10.2

**Comment by molszews** [comment]
thx!
