### ISSUE TITLE
Support cookies in FetchClientTemplate.tt

### ISSUE THREAD

**Issue by nerfpops** [NSwag/NSwag#725]
Without `credentials: /include|same-origin/` in RequestInit, eg.
<pre>
    let options_ = &lt;RequestInit&gt;{
        body: _content,
        method: "&lt;#=operation.HttpMethodUpper.ToUpperInvariant()#&gt;",
        headers: { .... },
        <b>credentials: "same-origin"</b>
    }
</pre>
it's impossible to send cookies to the server. This is of course bad practice and not supported in WebApi without hacks, so I wish the CMS I'm forced to use had alternatives to cookies. Unfortunately that's not the case, so I've resorted to search and replace the NSwag-output for all `headers: {` with `credentials: "same-origin", headers: {`. It's not pretty and perhaps it would be useful for others also, if it was possible to tell swagger2ts to set credentials to either `include` or `same-origin`.

**Comment by rsuter** [comment]
You can use the setting UseTransformOptionsMethod and BaseClassName to set this...

**Comment by nerfpops** [comment]
Of course! Thank you for such fast replies!

**Comment by rsuter** [comment]
... but because this is such a common scenario, maybe we should add this as option.

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/issues/734

**Comment by ZhaoRd** [comment]
what BaseClassName  can I use ?
