### ISSUE TITLE
Angular code generation not matching function signature

### ISSUE THREAD

**Issue by DDtMM** [NSwag/NSwag#733]
The Typescript Apis generated for Angular are not generating the proper return signature.  The explicitly stated type is `Observable<T[] | null>`.  What is actually getting returned is an `Observable<Observable<T[] | null>>`.  

The best way I can explain the issue is by the example below.  This is a sample of the generated output from  NSwag 10.4.6319.17519.  The main method calls `Http.request()` which returns an `Observable`, map still returns as an `Observable` of the transformed response.  The transformed response itself is changed from `T[]` to `Observable<T[]>` because `process<MethodName>` returns an observable due to the `observable.of`.

So either the `observable.of` needs to be dropped or the signature of the public function should be changed to `Observable<Observable<T[] | null>>`.

    apiWorkflowWorkflowsGet(): Observable<Workflow[] | null> { //<-- This isn't the correct type
        /* ... */
        return this.http.request(url_, options_).map((_response) => {
            return this.processApiWorkflowWorkflowsGet(_response); //<-- an Observable in an Observable.
        })
       /*... */
    }
    protected processApiWorkflowWorkflowsGet(response: Response): Observable<Workflow[] | null> {
        const status = response.status; 

        if (status === 200) {
            const responseText = response.text();
            let result200: Workflow[] | null = null;
            let resultData200 = responseText === "" ? null : JSON.parse(responseText, this.jsonParseReviver);
            if (resultData200 && resultData200.constructor === Array) {
                result200 = [];
                for (let item of resultData200)
                    result200.push(Workflow.fromJS(item));
            }
            return Observable.of(result200);
        } 
        /* ... */
    }

**Comment by rsuter** [comment]
Are you using v10.4 - this version uses flatMap() instead of map() and everything works for me...

**Comment by rsuter** [comment]
I see the problem now. Do you think replacing `map(` with `flatMap(` would solve the problem?

**Comment by rsuter** [comment]
Can you test with the latest CI artifacts and report if this fixes your problem?

**Comment by nbickel** [comment]
CI artifact works

**Comment by rsuter** [comment]
Ok, then i'll release today...

**Comment by rsuter** [comment]
v10.5

**Comment by ismcagdas** [comment]
Hi,

I have upgraded nswag from 8.1 to 10.6.
After that, I cannot use finally method after calling a generated proxy service method.
I get this error "Uncaught (in promise): TypeError: this._servicePRoxy.methodName(...).finally is not a function".

I have searched for a few hours but couldn't find anything useful.

I'm not %100 sure if my problem is related to this issue but I think it might be.
Maybe my usage is wrong, can you point me to right direction ? 

Thanks.

**Comment by ismcagdas** [comment]
adding below import statement fixed it for me.
`import 'rxjs/add/operator/finally';`

So it seems like it is not related to this issue.

Thanks.
