### ISSUE TITLE
Invalid left-hand side of assignment expression

### ISSUE THREAD

**Issue by nxtayi** [NSwag/NSwag#736]
**Must be** "HostFeatures" + "[" + index + "]." + **instead of**  "HostFeatures + "[" + index + "]." +

if (hostFeatures !== undefined)
            hostFeatures.forEach((item, index) => { 
                for (let attr in item)
                    url_ += "HostFeatures + "[" + index + "]." + attr + "=" + encodeURIComponent("" + item[attr]) + "&";
            });

"/api/services/app/Venue/GetVenues": {
"parameters": [
           {
            "name": "HostFeatures",
            "in": "modelbinding",
            "required": false,
            "type": "array",
            "items": {},
            "collectionFormat": "multi"
          },
...
]
...
}

**Comment by rsuter** [comment]
I think this has already been fixed in commit https://github.com/NSwag/NSwag/commit/94f05610

What version of NSwag are you using?
