### ISSUE TITLE
NSwag 9.12 generates if (data !== undefined) even with /nullvalue:null

### ISSUE THREAD

**Issue by SudhakarRao** [NSwag/NSwag#737]
Hi,

We are using NSwag 9.12 version. with this version and we are using /nullvalue:null post build action to generate the Angular 2 typescrypt file.

It is still generating the if condition checks with undefined.
In the below code if data is null then it throws an exception. Please let me know how can we fix this issue with 9.12 version.

export class CustomBackground {
    name?: string;
    enabled?: boolean;
    uRL?: string;

    constructor(data?: any) {
        if (data !== undefined) {
            this.name = data["Name"] !== undefined ? data["Name"] : null;
            this.enabled = data["Enabled"] !== undefined ? data["Enabled"] : null;
            this.uRL = data["URL"] !== undefined ? data["URL"] : null;
        }
    }

**Comment by rsuter** [comment]
This is by design - to ensure that no undefined properties exists if the received data is wrong...

Btw: We made some major improvements in the area of null checking (ie. strictNullChecks, etc) in v10.x.

**Comment by SudhakarRao** [comment]
Hi,

We upgraded to version:10.4.0, with this upgraded version my functionality is broken.
after an investigation, we saw the proxy is returning instead of collection an object which has a value property.
But we didn't expect this value property. Please let me know how can we fix this issue.

![samplecollectionobject](https://cloud.githubusercontent.com/assets/2643735/25299345/952fd67a-271b-11e7-9db2-c255664ed867.PNG)

**Comment by rsuter** [comment]
How exacly are you using the proxies? The publuc methods return rxjs observables and you ha e to subscribe or call toPromise() to get results...

**Comment by SudhakarRao** [comment]
Thanks for your response. We could finally fix the proxy deserialization issue.
Now we have a new Issue. All the properties are getting generated with Camelcase. This is breaking all our JS code as we used the same casing as our API.

We also used /modelPropertyNaming:original command without any success.
Is this command available in 10.5? 

Please let us know how we can fix the Property Naming issue. We would like to retain our original properties naming convention.

Thanks in advance.

**Comment by rsuter** [comment]
The simplest way to achieve this is by using interface instead of classes for DTOs (this way the properties stay as is). Otherwise you could implement a custom type name generator. I don't think there's an option called "modelPropertyNaming"

**Comment by RSuter** [comment]
There was never an option `/modelPropertyNaming:original ` 

If the nswag libs are called via C# (ie own cmd line tool) you can implement an own PropertyNameGenerator and provide it via the settings object...
