### ISSUE TITLE
StackOverflowException when using JRaw and Newtonsoft.Json other than v9

### ISSUE THREAD

**Issue by sandord** [NSwag/NSwag#738]
I have a project that references Newtonsoft.Json v10. I also have properties of type `JRaw` in my WebAPI models.

Generating the Json schema throws an `StackOverflowException`. This happens both using NSwagStudio and the `nswag` command line.

Debugging revealed this is caused by an infinite recursive loop caused by a property of `Newtonsoft.Json.Linq.JRaw` which refers to `JToken` (which is a base class of `JRaw`).

While NJsonSchema has explicit logic to deal with `JRaw` (preventing the endless recursion), it fails to detect type equality comparing `typeof(JToken)` from the v9 version of `Newtonsoft.Json.dll` (as referenced in both NSwag and NJsonSchema) against `typeof(JToken)` from the v10 version of `Newtonsoft.Json.dll`.

    // In my case, type is from Newtonsoft.Json v10 and typeof(JToken) from v9 and
    // type == typeof(JToken) results in false.
    if (type == typeof(JObject) || type == typeof(JToken) || type == typeof(object))

As it seems, two versions of Newtonsoft.Json are loaded simultaneously.

I'm not sure how this should be fixed (other than the obvious workaround of downgrading my project to Newtonsoft.Json v9).

Perhaps NJsonSchema should be updated to perform a version agnostic type comparison for `JToken` but on the other hand NSwag could perhaps mitigate this problem by making sure only one version of Newtonsoft.Json is loaded.

IMHO, there should by at the very least some sort of warning mechanism that detects the presence of multiple versions of Newtonsoft.Json.

Again, this could very well be something that belongs in the NJsonSchema project but I felt I should bring it up here first.

**Comment by rsuter** [comment]
This is very bad. The loader tries to use binding redirects, but it seems that it is not working... 

Until this is fixed, you should use the middlewares or create an own cmd line tool referencing your project (so that the assemblies can be loaded in the same AppDomain).

**Comment by sandord** [comment]
I've just tried to get this to work with Cake but to no avail. I get an `StackOverflowException` as well, which is unexpected since Cake.NSwag comes currently references NewstonSoft.Json 9.0.1.

**Comment by rsuter** [comment]
Try to uncomment the line where ConfigurationFile is initialized, https://github.com/NSwag/NSwag/blob/master/src/NSwag.AssemblyLoader/Infrastructure/AppDomainIsolation.cs

**Comment by rsuter** [comment]
I think this fixes the problem: https://github.com/NSwag/NSwag/commit/0def315be1d81c1cc25934c59d15a1b1af81be46

**Comment by rsuter** [comment]
Can you test with the latest CI artifacts? https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/2234/artifacts

Could this fix solve your problems?

**Comment by sandord** [comment]
I can confirm that this fixes the issue. Thanks! Are you going to deploy this package as a prerelease version?

**Comment by rsuter** [comment]
There is a CI feed for the .NET Full NuGet packages... Can you use this, or do you need an MSI/NPM/.NET Core package?

**Comment by rsuter** [comment]
I think I will release today or tomorrow...

I just added the loadFromRemoteSources option, can you retest with https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by sandord** [comment]
https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts works for me as well.

**Comment by sandord** [comment]
Until Cake.NSwag gets updated to include this release, I'm running NSwag from a Powershell script that calls the `nswag` command line. I guess I could install _NSwagStudio_ using Chocolatey from my Cake script to get access to `nswag` without requiring user intervention. Is there a CI feed for the _NSwagStudio_ choco package as well?

**Comment by rsuter** [comment]
No, there is only a feed for the .net full packages. Can't you just extract the latest CI zip into your env and call this nswag.exe in your ps script? However I will release soon, you shouldn't spend too much time on this...

**Comment by sandord** [comment]
Yeah, I'm going to wait.

**Comment by rsuter** [comment]
v10.6

**Comment by sandord** [comment]
👍
