### ISSUE TITLE
NSwagger 10.5 version, typescript proxy with class instaed of interface

### ISSUE THREAD

**Issue by SudhakarRao** [NSwag/NSwag#740]
Hi,

I am using NSwagger 10.5 version, with this version typescript client proxy by default its generating interfaces instead of classes, could you please help how to fix this issue.

Swagger generating as interface:
export interface IUserSearch {
    accountId: string;
    sortBy?: string;
    page?: number;
    pageSize?: number;
    searchText?: string;
}

my API original c# classes:

 public class UserSearch
    {
        public Guid AccountId;
        public string SortBy;
        public int? Page;
        public int? PageSize;
        public string SearchText = "";
    }

i don't want interface classes just it should be like my c# classes.

Thanks for Advance.

**Comment by rsuter** [comment]
You have to use "TypeStyle" "Class": 

![image](https://cloud.githubusercontent.com/assets/2603405/25420199/44d00378-2a57-11e7-812c-eddec332773c.png)

**Comment by SudhakarRao** [comment]
Yes, I am using type style property in my post build events even though it's generating interfaces.

/Template:Angular /NullValue:null /TypeStyle:Class

**Comment by rsuter** [comment]
It generates classes and interfaces, to disable the constructor interfaces, disable GenerateConstructorInterface: 

    /GenerateConstructorInterface:false

**Comment by RSuter** [comment]
Could i answer your question?
