### ISSUE TITLE
WebApiToSwaggerGenerator fails when Controller contains public static method

### ISSUE THREAD

**Issue by nerfpops** [NSwag/NSwag#741]
Steps to reproduce:

 - Create a WebApi Controller with a public static method
 - Use the command line tool or this example to trigger the exception:
```

using NSwag.SwaggerGeneration.WebApi;

class Program
{
    static void Main(string[] args)
    {
        var settings = new WebApiAssemblyToSwaggerGeneratorSettings();
        settings.AssemblyPaths = new[] { @"C:\my.dll" };
        var generator = new WebApiAssemblyToSwaggerGenerator(settings);
        generator.GenerateForControllersAsync(generator.GetControllerClasses()).GetAwaiter().GetResult();
    }
}
```

A very long stack trace is shown:

```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateKnownTypesAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateObjectAsync>d__15`1.MoveNext()
[...]
```

## The fix

Add a check for static methods in WebApiToSwaggerGenerator.GetActionMethods so the method below...

```
private static IEnumerable<MethodInfo> GetActionMethods(Type controllerType)
{
    var methods = controllerType.GetRuntimeMethods().Where(m => m.IsPublic);
    return methods.Where(m =>
        m.IsSpecialName == false && // avoid property methods
        m.DeclaringType != null &&
        m.DeclaringType != typeof(object) &&
        m.GetCustomAttributes().All(a => a.GetType().Name != "SwaggerIgnoreAttribute" && a.GetType().Name != "NonActionAttribute") &&
        m.DeclaringType.FullName.StartsWith("Microsoft.AspNet") == false && // .NET Core (Web API & MVC)
        m.DeclaringType.FullName != "System.Web.Http.ApiController" &&
        m.DeclaringType.FullName != "System.Web.Mvc.Controller")
        .Where(m =>
        {
            return m.GetCustomAttributes()
                .SingleOrDefault(a => a.GetType().Name == "ApiExplorerSettingsAttribute")?
                .TryGetPropertyValue("IgnoreApi", false) != true;
        });
}
```

.. becomes

<pre>
private static IEnumerable<MethodInfo> GetActionMethods(Type controllerType)
{
    var methods = controllerType.GetRuntimeMethods().Where(m => m.IsPublic);
    return methods.Where(m =>
        m.IsSpecialName == false && // avoid property methods
        m.DeclaringType != null &&
        <b>m.IsStatic == false &&</b>
        m.DeclaringType != typeof(object) &&
        m.GetCustomAttributes().All(a => a.GetType().Name != "SwaggerIgnoreAttribute" && a.GetType().Name != "NonActionAttribute") &&
        m.DeclaringType.FullName.StartsWith("Microsoft.AspNet") == false && // .NET Core (Web API & MVC)
        m.DeclaringType.FullName != "System.Web.Http.ApiController" &&
        m.DeclaringType.FullName != "System.Web.Mvc.Controller")
        .Where(m =>
        {
            return m.GetCustomAttributes()
                .SingleOrDefault(a => a.GetType().Name == "ApiExplorerSettingsAttribute")?
                .TryGetPropertyValue("IgnoreApi", false) != true;
        });
}
</pre>

**Comment by rsuter** [comment]
For now, just add the SwaggerIgnoreAttribute.

**Comment by Pandalien** [comment]
I still wish to have static methods included

**Comment by RSuter** [comment]
Why? Are they called?

**Comment by Pandalien** [comment]
@RSuter  I want to use it in a Azure function api. The azure functions are all static methods in static classes.
