### ISSUE TITLE
VS build/debug instructions

### ISSUE THREAD

**Issue by tdjastrzebski** [NSwag/NSwag#742]
Hi, how do I build and run the solution, preferably in VS, so it is debugable?
The solution simply opened in VS does not build. It seems like I am missing something.
I wanted to contribute some improvements.

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/wiki/SdkDevelopment

**Comment by rsuter** [comment]
Do you need more info?

**Comment by tdjastrzebski** [comment]
Thanks, it builds :)

**Comment by tdjastrzebski** [comment]
Maybe one more question: where do data model/entity classes actually get generated?

**Comment by rsuter** [comment]
The DTO generators are implemented in http://njsonschema.org

**Comment by rsuter** [comment]
Docs updated: https://github.com/NSwag/NSwag/wiki/SDK-Development
