### ISSUE TITLE
formData parameter doesn't register to HttpContent.

### ISSUE THREAD

**Issue by prakash-patel** [NSwag/NSwag#75]
I have added 3 formData parameter to new path called **Token** for Asp.net Web API.
```
parameters = new List<Parameter> {
                        new Parameter
                        {
                            type = "string",
                            name = "grant_type",
                            required = true,
                            @in = "formData",
                            description = "Grant Type is 'password'."
                        },
                        new Parameter
                        {
                            type = "string",
                            name = "username",
                            required = true,
                            @in = "formData"
                        },
                        new Parameter
                        {
                            type = "string",
                            name = "password",
                            required = true,
                            @in = "formData"
                        }
                    }
```

in _/swagger/docs/v2_ this how it's looks 
![image](https://cloud.githubusercontent.com/assets/938054/14928324/bae4d1d6-0e1c-11e6-92b1-ee0af482ffe1.png)

When i geneate the client code using **.tt** file. I am not able to see those three parameter being passed or used in `PostAsync()` method.
![image](https://cloud.githubusercontent.com/assets/938054/14928369/1bae5460-0e1d-11e6-8fbf-35e077373dd1.png)

As you see in below screen In Swagger api works fine. I can use this endpoint and geneate token.
![image](https://cloud.githubusercontent.com/assets/938054/14928494/ec2faaa8-0e1d-11e6-9560-de940d7b0540.png)

Could you please tell me what is the best way to fix this issue? Or am i doing something wrong here.?

**Comment by rsuter** [comment]
formData parameters are currently not supported. How would a formData parameter be transmitted with the http client? Can you show me some code?

**Comment by rsuter** [comment]
Like this: http://stackoverflow.com/a/19983672/876814 ?

**Comment by prakash-patel** [comment]
Thant meams i have to wite my own method in order to achive this. I won't be able to use generated code.

**Comment by rsuter** [comment]
Ill implement this soon... Will be simple.

**Comment by prakash-patel** [comment]
That would be great 👍. Thanks in advance.

**Comment by rsuter** [comment]
Same issue here: https://github.com/NSwag/NSwag/issues/21

**Comment by rsuter** [comment]
Implemented in commit: https://github.com/NSwag/NSwag/commit/17aa94027281c0623cb875873fd149c7c38faa53

Please try again with v2.18
