### ISSUE TITLE
Duplicate 'System.CodeDom.Compiler.GeneratedCode' attribute caused by multiple partial classes

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [NSwag/NSwag#754]
Using the C# client generator generates multiple partial classes and results in the following error:

`Duplicate 'System.CodeDom.Compiler.GeneratedCode' attribute`

The `OperationGenerationMode` property no longer appears to be in the SwaggerToCSharpGeneratorSettings so I can't figure out how to generate a single client to avoid this error message.

**Comment by rsuter** [comment]
The setting OperationGenerationMode is only available in the command line, in C# you can use the OperationNameGenerator setting and one of the available IOperationNameGenerator implementations

**Comment by blackbaud-GavinNicol** [comment]
Worked perfectly. Thanks

**Comment by peteraritchie** [comment]
Why have something that by default generated code that won't compile?
