### ISSUE TITLE
Operation order

### ISSUE THREAD

**Issue by sandord** [NSwag/NSwag#759]
Is it possible to change the operation order?

I'm providing my controller assembly to `app.UseSwaggerUi` and therefore I have no control over the order in which the controllers are processed.

I've tried to use `PostProcess` but the `Operations` property is a read only enumerable so I can't change the order.

**Comment by RSuter** [comment]
Operations is just a convenience method to access the operations in the Paths property. You have to reorder the operations in the Paths dictionary...

**Comment by sandord** [comment]
Thanks. I got it working like this:

```
PostProcess = document =>
{
	var paths = document.Paths.OrderBy(n => n.Key).ToList();
	document.Paths.Clear();

	foreach (var path in paths)
	{
		var operations = path.Value.ToList();
		path.Value.Clear();
		path.Value.AddRange(operations.OrderBy(n => n.Key).ToDictionary(n => n.Key, n => n.Value));

		document.Paths.Add(path);
	}
}
```
