### ISSUE TITLE
C# code generation for enum in response does not compile (type name mismatch).

### ISSUE THREAD

**Issue by Prooskalia** [NSwag/NSwag#76]
Hi All

When I generate an API with an enum field in a method response type (e.g. in my example the enum field called TestCase), a type, TestCase1 in the example, is generated in the C# code generated, but the C# code then refers to a type named TestCase which does not exist, so the code doesn't compile.  It's easy to fix-up the code by hand, but I thought I'd log it in case it affects anyone else.  Example below.

Many thanks for your application - it's invaluable!
Nx

* Example Swagger specification:
```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "SampleApi"
  },
  "host": "localhost:50332",
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/v1/Sample": {
      "get": {
        "tags": [
          "Sample"
        ],
        "operationId": "Sample_Get",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/MyTestClass"
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "MyTestClass": {
      "type": "object",
      "properties": {
        "TestCase": {
          "enum": [
            "HelloWorld",
            "GoodbyeCruelWorld"
          ],
          "type": "string"
        }
      }
    }
  }
}
```

* Generated code: attachment (search for text "TestCase")
[GeneratedCode.txt](https://github.com/NSwag/NSwag/files/244202/GeneratedCode.txt)

**Comment by rsuter** [comment]
Thanks for reporting, should be fixed soon... thanks for using NSwag.

**Comment by rsuter** [comment]
Fixed in https://github.com/NJsonSchema/NJsonSchema/commit/7c8fabb806cd7b9b6dab1bd713db65436d6035d3

**Comment by rsuter** [comment]
Fixed in NSwag v2.13

**Comment by Prooskalia** [comment]
Many thanks for the change - that works perfectly!

**Comment by rsuter** [comment]
Ok, thanks for reporting and using NSwag
