### ISSUE TITLE
Unused 'responseText' if return type is Promise<void>

### ISSUE THREAD

**Issue by snmed** [NSwag/NSwag#760]
Hi

If the typescript compiler  options `noUnusedLocals` is set to `true` and you have a WebApi method with void as return type, then services,ts can't be compiled due errors. NSwag generates code as follows
```
    protected processLogMessage(response: Response): Promise<void> {
        const status = response.status;
        if (status === 200) {
            return response.text().then((responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((responseText) => {
            return throwException("An unexpected server error occurred.", status, responseText);
            });
        }
        return Promise.resolve<void>(<any>null);
    }
```
I propose to change the t4 templates to use `_responseText` instead of `responseText` for all cases so you don't have to clutter up the template with additional if-statments.

Cheers,
Sandro

**Comment by grovesNL** [comment]
We did use `_responseText` temporarily, but @rsuter was recently working on some improvements to omit that argument when the response should not be processed.
