### ISSUE TITLE
Inheriting from 3rd party class, UnixDateTimeConverter JsonConverter

### ISSUE THREAD

**Issue by lciocci** [NSwag/NSwag#761]
I ran into an issue yesterday where I had attempted to inherit one of my classes from some DocumentDB elements (e.g. Resource). One of the date/time properties is decorated with the JsonConverter: UnixDateTimeConverter. Generating the client via NSwag did not decorate the property with the JsonConverter, and as a result deserialization failed on this property because the serialized value was numeric (e.g. not the expected serialized format for date/time).

**Source property:**
```
// Summary:
//     Gets the last modified timestamp associated with the resource from the Azure
//     DocumentDB database service.
[JsonConverter(typeof(UnixDateTimeConverter))]
[JsonProperty(PropertyName = "_ts")]
public virtual DateTime Timestamp { get; internal set; }
```

**Generated property:**
```
/// <summary>Gets the last modified timestamp associated with the resource from the Azure DocumentDB database service.</summary>
[Newtonsoft.Json.JsonProperty("_ts", Required = Newtonsoft.Json.Required.Always)]
[System.ComponentModel.DataAnnotations.Required]
public System.DateTime _ts
{
            get { return __ts; }
            set 
            {
                if (__ts != value)
                {
                    __ts = value; 
                    RaisePropertyChanged();
                }
            }
}
```

I was able to work around the issue but am understandably curious if the inclusion of the property's JsonConverter is something that's supported in NSwag.

**Comment by lciocci** [comment]
Additional info: I have a property in another class that's decorated with the JsonConverter: StringEnumConverter. Interestingly enough this JsonConverter is included with this property when generating the client:

**Source:**
```
public class MergeAction
{
        public enum DeliveryStateEnum
        {
            NA,
            Pending,
            Delivered,
            OnHold,
        };

        **[JsonConverter(typeof(StringEnumConverter))]
        public DeliveryStateEnum? DeliveryState { get; set; }** 

        public List<DeviceOperation> Operations { get; set; }

        public string Message { get; set; }                                    
}

```

**Generated client:**
```
[Newtonsoft.Json.JsonProperty("DeliveryState", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
**[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]**
public DeliveryStateEnum? DeliveryState
{
            get { return _deliveryState; }
            set 
            {
                if (_deliveryState != value)
                {
                    _deliveryState = value; 
                    RaisePropertyChanged();
                }
            }
}
```

**Comment by RSuter** [comment]
At the moment only StringEnumConverter is generated, but only if the enum is of type string... Swagger internally uses json schema to describe classes and i think json schema does not really support unix datetimes. Maybe we can add a custom string format for that...

**Comment by RSuter** [comment]
See https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/JsonFormatStrings.cs

**Comment by RSuter** [comment]
With the latest commit in NJsonSchema, you can implement a custom TypeMapper and generate a custom schema based on the given property type and/or property attributes...

**Comment by lciocci** [comment]
Very nice - ty RSuter :)
