### ISSUE TITLE
Collection of enum leads to enum renaming to "Anonymous"

### ISSUE THREAD

**Issue by nero777x** [NSwag/NSwag#765]
Creating an array (or list, etc) of an enum property on a class model leads to the enum being renamed to "Anonymous."

Additionally, if you have the same enum as an array in other places it creates a new "Anonymous" version of that enum even if the two arrays are in the same class.  The latter is already being addressed in NJsonSchema/NJsonSchema#17.

**Comment by RSuter** [comment]
Can you provide a sample to reproduce this?

**Comment by nero777x** [comment]
public enum SomeEnum { Thing1, Thing2 }

    public class SomeClass
    {
        public int SomeProperty { get; set; }
        public SomeEnum[] SomeEnums { get; set; }
    }

**Comment by RSuter** [comment]
I cannot reproduce the problem with NJsonSchema only: https://github.com/RSuter/NJsonSchema/commit/f5b2c0effe85f77fc65575835d46dbecc8eaa90f

Can you reproduce this with an NJsonSchema unit test?

**Comment by nero777x** [comment]
Unfortunately, I am pressed for time with a difficult work schedule and don't have the time to set up a project for unit testing.  If the unit test that you wrote doesn't fail because it doesn't produce the results I am getting then it must have done something wrong in the way I am generating my client.  I did notice something in the meantime, however.  I am generating a Swagger document as my first step using `SwaggerDocument.FromUrlAsync(...)` which, when examined for the portion that would contain my enum array, is rendered as `"someEnums":{"type":"array","items":{"enum":{"Thing1","Thing2"],"type":"string"}}` which explains why is coming up as anonymous enum.

**Comment by RSuter** [comment]
Enums only have a name when they are referenced... I thought you generated the spec with nswag.

**Comment by RSuter** [comment]
Can you provide a sample spec?

**Comment by nero777x** [comment]
I am using NSwag to generate the spec.  The `SwaggerDocument` object that I am using to generate it is in the NSwag namespace:

	var doc = await SwaggerDocument.FromUrlAsync(urlString);

	var settings = new SwaggerToCSharpClientGeneratorSettings()
	{
		GenerateClientClasses = true,
		GenerateDtoTypes = true,
		ClassName = "ConfigurationClient",
		OperationNameGenerator = new MultipleClientsFromOperationIdOperationNameGenerator()
	};
	
	var generator = new SwaggerToCSharpClientGenerator(doc, settings);
	var code = generator.GenerateFile();

	return code;

I hope this is enough of the spec:

	{  
	   "swagger":"2.0",
	   "info":{  
		  "version":"v1",
		  "title":"My Something or Other App v1"
	   },
	   "basePath":"/",
	   "paths":{  },
	   "definitions":{
		  ...
		  "SomeClass":{  
			 "type":"object",
			 "properties":{  
				"someEnums":{  
				   "type":"array",
				   "items":{  
					  "enum":[  
						 "Thing1",
						 "Thing2"
					  ],
					  "type":"string"
				   }
				}
			 }
		  },
		  ...
	   },
	   "securityDefinitions":{}
	}

**Comment by RSuter** [comment]
No, you are not generating a swagger spec with NSwag but only loading an existing spec from an URL... this is why the enums are not referenced and thus are named "Anonymous*"...

But you can provide a custom TypeNameGenerator (settings.CSharpGeneratorSettings.TypeNameGenerator) and return a custom class name for the enum schema (just inherit from the default implementation and return a different name for the enum schema).

**Comment by nero777x** [comment]
Ok, I see now.  Sorry for the confusion.  I will try out what you have suggested.  Thank you for your help.
