### ISSUE TITLE
How to set parameter descriptions?

### ISSUE THREAD

**Issue by jtheisen** [NSwag/NSwag#768]
The `WebApiToSwaggerGenerator` supports the `DescriptionAttribute` to describe actions, models and model properties, but apparently not parameters:

https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator

That's odd, as there definitely is a parameter description field defined in the Swagger specification, [see here](http://swagger.io/docs/specification/describing-parameters/).

The Swagger UI also expects it to be there:

![image](https://cloud.githubusercontent.com/assets/1516294/26131561/ef2a88e0-3a9a-11e7-9efc-5c9b002fbfe6.png)

**Comment by RSuter** [comment]
You can use xml docs to define params: https://github.com/RSuter/NJsonSchema/wiki/XML-Documentation

**Comment by jtheisen** [comment]
Well, that's good to hear and I will consider going that route (making it necessary to create the spec from assembly).

I don't see why it shouldn't work with attributes also though.

**Comment by RSuter** [comment]
Yes, we should add the feature...

**Comment by RSuter** [comment]
Attribute will work in v11

**Comment by jtheisen** [comment]
Great!

**Comment by unluckycode** [comment]
Hi, Can you give me an example of how to use the description in parameters?

**Comment by zyofeng** [comment]
As far as I can see Description attribute on model properties (parameters) still does not work.
The ones against controller method works. I am using 12.0.20

**Comment by zyofeng** [comment]
Sorry my fault it does seem to work.
To answer unluckycode's question:

In controller method:
public async Task<Response> Search(string term, [Description("Zero-based page index")]int currentPage, int pageSize = 50)
