### ISSUE TITLE
Nonsensical error messages when CLI's version matching fails

### ISSUE THREAD

**Issue by agc93** [NSwag/NSwag#769]
On some hosts (especially when using pre-built binaries), the `dotnet` Version string is either not set, or set to non-well-known values.

![screenshot from 2017-05-19 17-33-22](https://cloud.githubusercontent.com/assets/1369269/26237645/5efc032c-3cb9-11e7-9e98-d02d36ca57b6.png)

In that case, the version matching in the NPM CLI package (at [line 32 of nswag.js](https://github.com/NSwag/NSwag/blob/master/src/NSwag.Npm/bin/nswag.js#L32)) fails out, `cmd` is never updated, and you just get the help screen followed by a Node traceback.

The CLI should at least print a helpful error, or attempt a sensible default with a warning.

Related to #770

![screenshot from 2017-05-19 17-35-58](https://cloud.githubusercontent.com/assets/1369269/26237909/4b30f39c-3cba-11e7-99e0-b6be533efa65.png)

**Comment by RSuter** [comment]
Do you think this should fix your problem?
