### ISSUE TITLE
Support for overriding CLI version matching

### ISSUE THREAD

**Issue by agc93** [NSwag/NSwag#770]
The NPM CLI does rudimentary [version matching in `nswag.js`](https://github.com/NSwag/NSwag/blob/master/src/NSwag.Npm/bin/nswag.js#L32). When this fails (#769), the only way to actually use the CLI is to go in and manually edit `nswag.js` in `${PREFIX}/bin/nswag`.

The CLI should allow overriding the "detected" runtime version number. Providing the CLI option should also override the detection logic as it's possible for the runtime and SDK to be at different versions (especially on non-Windows).

**Comment by RSuter** [comment]
Can you create a pr to fix that?
