### ISSUE TITLE
WIP: Upgrade to .NET Standard v11

### ISSUE THREAD

**Issue by RSuter** [NSwag/NSwag#772]
- Migrate all projects to .NET Standard
- Update to NJsonSchema v9+ (many improvements)
- Release as v11.0.0

**Comment by LordJZ** [comment]
@RSuter hey, any plans to update the NSwag NuGet package to v11 any time soon? Want to try the new features and fixes, and https://github.com/RSuter/NJsonSchema/issues/370 too. Thanks!

**Comment by RSuter** [comment]
You can test with this feed: https://www.myget.org/gallery/nswag-ci

**Comment by RSuter** [comment]
Just FYI: All projects are now migrated to .NET Standard, but I have big problems with the assembly loader - NSwagStudio and the cmd line tool have problems loading many .NET Core project. It may take longer than expected...
