### ISSUE TITLE
Display message on Error

### ISSUE THREAD

**Issue by ranouf** [NSwag/NSwag#773]
Hi,

in Typescript client configuration, I added a base class. Every work correctly, I can now handle my error.
What I want now is to display a message when an error is handle using my snackBarService.
I added "SnackbarService" in Configuration class name, but of course it doesnt work like this, i need to add an import or maybe something else ...
How to configure NswagStudio to add External Service in the BaseConstructor?

Thank you,
Cedric

**Comment by RSuter** [comment]
You can achieve this by using a ConfigurationClass

**Comment by ranouf** [comment]
@RSuter Do you have an exemple?

I looked here for Nswag and Configuration:
https://github.com/NSwag/NSwag/issues/219
https://github.com/NSwag/NSwag/wiki/NSwag-Configuration-Document

Are you talking about something like this:
https://medium.com/@hasan.hameed/reading-configuration-files-in-angular-2-9d18b7a6aa4

Thanks for your help

**Comment by RSuter** [comment]
No, meant the option ConfigurationClass of nswag (also available in studio)

**Comment by RSuter** [comment]
See https://github.com/Picturepark/Picturepark.SDK.TypeScript/blob/master/src/picturepark-sdk-v1-ng2/src/picturepark.servicebase.ts

**Comment by ranouf** [comment]
Ok thank you, I will look on it soon and give an example for the next one who are looking for the solution :)
