### ISSUE TITLE
Support for aspnet versioning package?

### ISSUE THREAD

**Issue by vdecristofaro** [NSwag/NSwag#774]
As per the subject, is there any way to support the [Asp Net Api Versioning](https://github.com/microsoft/aspnet-api-versioning) package?

Actually, I have my endpoints using this package as per the following configuration example:

        [HttpPost]
        [Route( "v{version:apiVersion}/svc/create" )]
        public async Task<HttpResponseMessage> Create( CreateInput model ) {
        }

and using NSwag in the following way

```
nswag webapi2swagger /assembly:%LIB% /controller:%CONTROLLER%  /output:%OUTDIR% /infoversion:1.0 
```
produce a swagger path that is like the following:

```
/v/svc/create
```

It would be great to leave it at least as 

```
v{version:apiVersion}/svc/create
```

**Comment by RSuter** [comment]
See https://github.com/NSwag/NSwag/issues/655

**Comment by RSuter** [comment]
We could add a PathParameterReplacements (dict of path parameter name and replacement text). If a path parameter is in the dict then it is just replaced.

**Comment by vdecristofaro** [comment]
Do you mean to solve #776?
The solution explained in #655 is really powerful and it's ok for me to implement it like that. 
The only problem is #776, I did'nt had time to watch deeper but I suppose to have a look at it in a couple Of days.

**Comment by RSuter** [comment]
I added the ApiVersionProcessor to the default processors (it is active in NSwagStudio)
