### ISSUE TITLE
How to do custom binding?

### ISSUE THREAD

**Issue by jtheisen** [NSwag/NSwag#775]
Does NSwag support custom binding and if so, how?

### Background
Let's say I have this action method:

        public void DoSomethingWithAnEntity(MyEntity entity)
        {
        }

I also have a custom binding for the `MyEntity` class that looks for an `id` and then loads the entity from a database - that's one of the common scenarios for custom binding.

Obviously NSwag can't infer that from the custom binder because of the way custom binders are written. I would expect, however, NSwag to have a way to be told about the actual values to expect in a request.

I googled and searched here, but I found only [this test](https://github.com/NSwag/NSwag/blob/56d7b6174d8388a13505ffb3f6bcf70679a61362/src/NSwag.SwaggerGeneration.WebApi.Tests/Attributes/ComplexParametersTests.cs), but that only talks about whether the data ought to be in the body or not.

**Comment by RSuter** [comment]
Maybe you can do this with type mappers:

https://github.com/RSuter/NJsonSchema/wiki/Type-Mappers

**Comment by jtheisen** [comment]
Yes, that works. I can set the type mappers on the `WebApiAssemblyToSwaggerGeneratorSettings`.

**Comment by jtheisen** [comment]
On a second thought, there is one pain point with this:

You have to decide on type mappers at least on the controller level.

That means that if I have, as it extremely typical, on a controller two actions like this:

```
public MyEntity[] GetSome();
public void DoWith(MyEntity entity);
```

I can't have the first action returning the whole entity and the second one taking only a key.

I was thinking about using attributes to control that:

```
public void DoWith([ByKey] MyEntity entity);
```

This would require NSwag to specify type mappers based on those attributes though.

There's already logic to support `[FromBody]` in NSwag, which is someone related.

**Comment by RSuter** [comment]
In this case i think you should not implement a type mapper but a custom IOperationProcessor and transform the param if it has the attribute... (ie add a new schema to the definitions and reference this from all ByKey params of the same type)

**Comment by jtheisen** [comment]
Right, that looks promising. I'll have a look at how that goes.
