### ISSUE TITLE
Error while generating swagger

### ISSUE THREAD

**Issue by vdecristofaro** [NSwag/NSwag#776]
I was using NSwag to generate swagger files in the following version

`NSwag command line tool for .NET 4.6+, toolchain v10.2.6317.32053 (NJsonSchema v8.30.6304.31883) (x64)`

However as specified in the issue #655 I have implemented an IOperationProcessor and got the error 

> System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'MyProject.ApiVersionProcessor' does not contain a definition for 'Process'

Then I have updated the NSwag toolkit to latest version

`NSwag command line tool for .NET 4.6+, toolchain v10.6.6324.28497 (NJsonSchema v8.33.6323.36213) (x64)
`
and now I am getting the following error

> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Any suggestion?

**Comment by RSuter** [comment]
Related https://github.com/NSwag/NSwag/issues/762

**Comment by RSuter** [comment]
Can you try with the latest CI build?
I worked on the assembly loader and now it looks good for my projects...

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by vdecristofaro** [comment]
I think that something went wrong because in the NSwag.zip archive there is not the main executable nswag.exe.

**Comment by RSuter** [comment]
Sorry, I removed the reference to nswag.exe in NSwagStudio (the zip archive). Will fix it now...

**Comment by RSuter** [comment]
https://github.com/NSwag/NSwag/commit/0c9545420fd4b2792037f4ef5da4624d3135f20c

**Comment by RSuter** [comment]
![image](https://cloud.githubusercontent.com/assets/2603405/26762928/be8bcd02-494a-11e7-9a56-052f953e274d.png)

**Comment by RSuter** [comment]
If you still have problems, can you provide a sample output as zip?

**Comment by vdecristofaro** [comment]
Now this problem is solved. However I am still experiencing a problem with the ApiVersionProcessor class. 
I have implemented as in #655 and then added the SwaggerOperationProcessor attribute on a controller.

The system compile correctly but I still get 

> System.AggregateException: One or more errors occurred. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'MyProject.Common.WebApi.Swagger.ApiVersionProcessor' does not contain a definition for 'Process'

That is correct as my implementation, as in the sample, implements `IOperationProcessor` that has 

`public Task<bool> ProcessAsync( OperationProcessorContext context ) {`

Should I upgrade NJsonSchema library? Actually I am using

> NSwag command line tool for .NET 4.6+, toolchain v11.0.0.0 (NJsonSchema v9.1.4.0) (x64)

**Comment by RSuter** [comment]
As of now, the ApiVersionProcessor is integrated into NSwag (see https://github.com/NSwag/NSwag/issues/655) you can remove your version and test again...

**Comment by vdecristofaro** [comment]
Great! Tested and worked perfectly! 
Thanks.

Will this be partof the next release?

**Comment by RSuter** [comment]
Yes, i'm working on v11 (complete migration to .NET Standard, bug fixes, some enhancements)... I hope to release soon, but i have to do more integration tests. If possible, please verify if everything works as expected.

**Comment by RSuter** [comment]
Join https://gitter.im/NSwag/NSwag for the release announcements, etc...
