### ISSUE TITLE
cannot accept nullable enum property

### ISSUE THREAD

**Issue by limwesley** [NSwag/NSwag#778]
i have one method generate list of below classes 
```
public class class1
{
public Enum1 Enum1 { get; set; }
public Enum2? Enum2 { get; set; }
public string value { get; set; }
}
```
as Enum2 is nullable but when i generate, it throw me 

> 		"Cannot convert null value to class1.Enum2. Path '[0].Enum2', line 1, position 55

**Comment by RSuter** [comment]
Is this a json.net serializer exception?

**Comment by limwesley** [comment]
@RSuter yes it happened at this line of code 
`// at this point, it must be a model (json)
            try
            {
                return JsonConvert.DeserializeObject(response.Content, type, serializerSettings);
            }
            catch (Exception e)
            {
                throw new ApiException(500, e.Message);
            }`

**Comment by RSuter** [comment]
What content do you receive in `response.Content`?

**Comment by limwesley** [comment]
`[{"Enum1":"EnumA","Enum2":null,"value":null}]`
here is my response.Content

**Comment by RSuter** [comment]
The enum value must be in quotes. So this is invalid: 

    "Enum2":EnumA1

must be

    "Enum2":"EnumA1"

This test works for me: 

        public enum Enum1
        {
            EnumA,
            EnumB
        }

        public enum Enum2
        {
            EnumA1,
            EnumA2
        }

        public class class1
        {
            public Enum1 Enum1 { get; set; }
            public Enum2? Enum2 { get; set; }
            public string value { get; set; }
        }

        [TestMethod]
        public void When()
        {
            //// Arrange
            var json = @"[{""Enum1"":""EnumA"",""Enum2"":null,""value"":null}, " +
                @"{""Enum1"":""EnumA"",""Enum2"":""EnumA1"",""value"":null}]";

            //// Act
            var obj = JsonConvert.DeserializeObject<class1[]>(json);

            //// Assert
            Assert.IsNotNull(obj);
        }

**Comment by limwesley** [comment]
but when i try with swagger code gen purely from swashbuckle.core it give me null value without the quotation

**Comment by RSuter** [comment]
But without quotes it is not valid JSON, correct?

**Comment by RSuter** [comment]
The null value must be without quotes but the other values need quotes (if its a string enum)

**Comment by limwesley** [comment]
but it was generate from swashbuckle.core, could the nswag resolve this ? 
if not i will change to used swagger code gen, 
i think the string enum is accept enum as string but null value will remain as null not null string

**Comment by limwesley** [comment]
i have check it should be `null `instead of `"null"`
based on this https://stackoverflow.com/a/21121267

**Comment by RSuter** [comment]
The Problem is not the `null` but the `EnumA1` which does not have "
