### ISSUE TITLE
Generating CSharp client from swagger containing escaped quotes does not compile

### ISSUE THREAD

**Issue by backlune** [NSwag/NSwag#781]
Generating a CSharp Client (In NSwagStudio v10.6.6324.28497) based on a swagger containing the definition below does not compile.

```
"output1Item": {
  "required": [
    "Something \"some1\"",
    "Something \"some2\""
  ],
  "properties": {
    "Something \"some1\"": {
      "type": "number",
      "format": "double"
    },
    "Something \"some2\"": {
      "type": "number",
      "format": "double"
    }
  }
}
```

The CSharp client from http://editor.swagger.io/#/ seems to handle this. Would be great if NSwag could handle it as well.

**Comment by RSuter** [comment]
How do you expect that this should be handled?

**Comment by RSuter** [comment]
fixed in v11

**Comment by backlune** [comment]
Great job! Sorry I was not able to find the time to describe how I wanted it to be handled.
