### ISSUE TITLE
SwaggerToTypeScriptClient: Cannot find global type 'Array'

### ISSUE THREAD

**Issue by LeonidEfremov** [NSwag/NSwag#785]
After SwaggerToTypeScriptClient transformation got next errors:

- Cannot find global type 'Array'.
- Cannot find global type 'Boolean'.
- Cannot find global type 'Function'.
- Cannot find global type 'IArguments'.
- Cannot find global type 'Number'.
- Cannot find global type 'Object'.
- Cannot find global type 'RegExp'.
- Cannot find global type 'String'.

when try to use tsc (2.3.3) for js transformation. How i can avoid this?

- "target": "ES2015"
- "module": "es2015"

**Comment by RSuter** [comment]
Can you provide a sample project? Or at least some generated code?

**Comment by RSuter** [comment]
This is surely a TypeScript tooling issue and not a problem in NSwag

**Comment by LeonidEfremov** [comment]
Agree, this is not a bug, sorry.
