### ISSUE TITLE
Register the middleware step for .NET Core

### ISSUE THREAD

**Issue by dixonalex** [NSwag/NSwag#788]
[Link to wiki page](https://github.com/NSwag/NSwag/wiki/Middlewares)

Code snippet states `app.UseSwagger(typeof(Startup).Assembly, new SwaggerOwinSettings());`
However in my environment the following is requried: `app.UseSwagger(typeof(Startup).GetTypeInfo().Assembly, new SwaggerOwinSettings());`

Target framework: .NETCoreApp 1.1
Project Sdk: Microsoft.NET.Sdk.Web
NSwag.AspNetCore v 10.6.0

**Comment by RSuter** [comment]
Yes, this depends on the .NET framework used, in .NET full its without GetTypeInfo(). I've updated the wiki..
