### ISSUE TITLE
NSwag studio generates wrong HTTP Headers for IEnumerable collections

### ISSUE THREAD

**Issue by Boriszn** [NSwag/NSwag#789]
Hi Team.
 
I have Web API with action which have Http Header parameters with IEnumerable types, like:
`public IActionResult Get([FromHeader]List<string> idList)`

When I generate client, using NSwag studio (based on Swagger Json specification) 
it creates API methods with folowing code line: 

`
request_.Headers.TryAddWithoutValidation("idList", idList != null ? idList.ToString() : null);
`

Nswag supose that i passing string which is wrong.

Could someone suggest me how to fix it. 
(Probably, I'm doing something wrong with Nswag config) 

Thanks a lot in advance.

**Comment by RSuter** [comment]
This is currently not supported... 
What would be the expected output?

**Comment by Boriszn** [comment]
Thanks a lot for the quick answer. 
Expected output should be: 
`request_.Headers.Add("idList", idList);`

**Comment by RSuter** [comment]
Is it also ok to use

    request_.Headers.TryAddWithoutValidation("idList", idList);

?

**Comment by Boriszn** [comment]
Yeah, this one should be ok.
Thanks.

**Comment by Boriszn** [comment]
Sorry I have one more (probably stupid :) ) question: 
Should I expect this fixed in next version(s) of Nswag studio ?

Thanks.

**Comment by RSuter** [comment]
Yes, v11... released next week.
Until then you can use the latest CI builds:

**Comment by Boriszn** [comment]
Clear and Thank you so much ! 
You save my life :)

**Comment by RSuter** [comment]
You build something life-saving with NSwag? :-)

**Comment by Boriszn** [comment]
Yeah, almost :) (only my life and my colleagues :)) ) And not only life but time also !!!
We are building some complex, AR product (Unfortunately, I can't say now what exatly the name of product / company etc. (( ) 

Cheers !!

**Comment by RSuter** [comment]
Sounds interesting :-). Then I wish you success with your project!

**Comment by Boriszn** [comment]
Thanks man ;)

p.s
Totaly forgot that we have web site :)
https://www.re-flekt.com/

**Comment by RSuter** [comment]
Just FYI: v11 is released, v11.1 incoming ;-)

**Comment by Boriszn** [comment]
Thanks a lot for the update. ;-)
