### ISSUE TITLE
 System.InvalidOperationException: The method 'Delete'  on path  is registered multiple times 

### ISSUE THREAD

**Issue by osmidhun** [NSwag/NSwag#794]
Hi,

On our api definition, we have same route differenciated by "HttpPost" and "HttpDelete". When we try to generate swagger spec , NSwag Studio throws with following expecion 

System.InvalidOperationException: The method 'Delete' on path '/api/{carrierCode}/{dep}/{depDate}/{fltNum}/PaxJourney/{seqNum}/ChangeOfPaxDetails/Contact' is registered multiple times (check the DefaultUrlTemplate setting [default for Web API: 'api/{controller}/{id}'; for MVC projects: '{controller}/{action}/{id?}']).

Our sample Api Defintions as follows
  [Route("api/{carrierCode}/{dep}/{depDate}/{fltNum}/PaxJourney/{seqNum}/ChangeOfPaxDetails/Contact")]
        [HttpDelete]
        public async Task<PaxJourneyEntityModel.PaxContactEmergencyDeleteResponse> Delete(string carrierCode, string dep, string depDate, string fltNum, string seqNum)
   {
}
  [Route("api/{carrierCode}/{dep}/{depDate}/{fltNum}/PaxJourney/{seqNum}/ChangeOfPaxDetails/Contact")]
        [HttpPost]
        public async Task<HttpResponseMessage> Post(PaxJourneyEntityModel.PaxContactEmailMobileRequest contacts, 
            string carrierCode, string dep, string depDate, string fltNum, string seqNum)
        {
}

**Comment by Boriszn** [comment]
Hi, 

In most cases for delete operation you can use only one unique identificator (like int, guid, email etc)
Nevertheless, in this case you can try add or remove any param from Route (and from method)
then generate client.

**Comment by RSuter** [comment]
According to your posted controller, there must be another controller with the same route and HTTP method (DELETE)... Have you checked this?

**Comment by osmidhun** [comment]
Thank you, There was a duplicate route on my project
