### ISSUE TITLE
configurationClass property is not respected

### ISSUE THREAD

**Issue by cwoolum** [NSwag/NSwag#795]
I have a nswag configuraiton that is meant to render out a class for AngularJS using TypeScript >2 with a base class and a configuration passed in like

```
 "clientBaseClass": "ServiceBase",
 "configurationClass": "ServiceBaseConfig",
```
and the output being 
```
export classAutocompleteApiClient extends ServiceBase {
    private baseUrl: string | undefined = undefined; 
    private http: ng.IHttpService; 
    private q: ng.IQService; 
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor($http: ng.IHttpService, $q: ng.IQService, baseUrl?: string) {
        super();
        this.http = $http;
        this.q = $q;
        this.baseUrl = baseUrl ? baseUrl : "";
    }
}
```

The code that is output has the base class but ServiceBaseConfig is not passed into the constructor or the super().  As a small side item, it would be nice to include an import statement if TS >2.0 is selected so that the  class could be generated without any modifications.

**Comment by RSuter** [comment]
Configuration class was only supported for "Angular". I've added this feature to the other templates in the referenced commit...

**Comment by RSuter** [comment]
Can you test it?

https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by RSuter** [comment]
v11.1

**Comment by cwoolum** [comment]
Works great! Thanks!
