### ISSUE TITLE
Problems serializing an array of objects to JSON

### ISSUE THREAD

**Issue by lucassp** [NSwag/NSwag#799]
Hi guys,

Probably this question has been asked before but neither Google nor the search aren't helping me right now. I use classes generated by NSwag from swagger.json inside my app.

I have an array of objects:

```TypeScript
console.log(JSON.stringify([
        Dashboard.fromJS({
            code: "1212312",
            name: "tresads",
            description: "some description"
        }),
        Dashboard.fromJS({
            code: "1212312",
            name: "tresads",
            description: "some description"
        })
    ]));
```
which I'm trying to serialize to JSON using `JSON.stringify()`, but it throws an error when it calls the toJSON method of the objects: 
```
angular.js:14199 TypeError: Cannot create property 'code' on string '0'
    at Dashboard.toJSON (App/models/api.js:785:34)
    at JSON.stringify (<anonymous>)
```
If I'm manually calling the `toJSON()` method of each object, everything is fine. Is this the behavior of `JSON.stringify` when elements of an array have a  `toJSON()` method? Is there a way to avoid the extra boilerplate of calling `myArr = myArr.map(dash => dash.toJSON())`?

Thanks!

**Comment by RSuter** [comment]
Can you post the code of Dashboard?

**Comment by RSuter** [comment]
I think i know where the problem is... This is a completely undocumented "feature" of stringify: It calls toJSON() with an argument... It just needs a small fix. Coming soon...

**Comment by lucassp** [comment]
I also got an answer on stackoverflow about that: https://stackoverflow.com/questions/44588013/strange-error-when-serializing-to-json-an-array-of-objects-which-have-a-tojson-m/44589300#44589300

Yeap, a small fix should do it :)

**Comment by RSuter** [comment]
This problem has already been fixed. Your code has: 

        data = data ? data : {};

but the latest verison of NJS/NSwag generates: 

    data = typeof data === 'object' ? data : {};

Which prevents this issue...
