### ISSUE TITLE
Empty Base class leaves an extra :

### ISSUE THREAD

**Issue by tkwpfo** [NSwag/NSwag#8]
If I omit the /baseclassname: parameter in the commandline utility the generated class gets an class definition with an extra : 

like 
public partial class myservice : 
{

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/378e1e02053ec376ea9df53c690d6b0495ad0195

**Comment by rsuter** [comment]
Fixed in v1.1
