### ISSUE TITLE
Generate array code from just a simple array schema

### ISSUE THREAD

**Issue by hmeijer2** [NSwag/NSwag#800]
Is NSwag able to generate any C# code, be it array or collection, from this simple array schema below?
Or does the array schema need to be within an object schema (and if so, why)? Thanks.

{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": ""
  },
  "schemes": [],
  "paths": {},
  "definitions": {
    "Hotels": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "hotelName": {
            "type": "string"
          }
        }
      }
    }
  },
  "parameters": {},
  "responses": {},
  "securityDefinitions": {}
}

**Comment by hmeijer2** [comment]
I find it strange that it just generate an empty namespace.

**Comment by RSuter** [comment]
The problem is that classes which inherit from array are not supported. Try something like: 

```json
{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": ""
  },
  "schemes": [],
  "paths": {},
  "definitions": {
  	"Container": {
  		"type": "object",
  		"properties": {
  			"hotels": {
  				"type": "array", 
  				"items": {
  					  				"$ref": "#/definitions/Hotel"
  				}
  			}
  		}
  	},
    "Hotel": {
        "type": "object",
        "properties": {
          "hotelName": {
            "type": "string"
          }
        }
    }
  },
  "parameters": {},
  "responses": {},
  "securityDefinitions": {}
}
```

**Comment by hmeijer2** [comment]
That works. Great. Thanks very much for that.
