### ISSUE TITLE
[Moq integration] generate interface or virtual method

### ISSUE THREAD

**Issue by torejx** [NSwag/NSwag#806]
Hi,

is it possible to generate a Client Interface or to create virtual method? I need to mock some method with Moq, but I have this problem: https://stackoverflow.com/questions/1962010/moq-invalid-setup-on-a-non-overridable-member-x-x-getbytitleasdf

Thanks

**Comment by RSuter** [comment]
Yes there is the option GenerateClientInterfaces

**Comment by torejx** [comment]
Ouch, didn't see the flag, sorry!

Thanks
