### ISSUE TITLE
NSwag studio v.11 fails when trying to load .net core dll

### ISSUE THREAD

**Issue by ctokareff** [NSwag/NSwag#807]
following exception occurs when I'm trying to load my .net core web api dll into NSwag studio 11.1.1

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Note: my project references System.Runtime 4.3.0.0

Note: NSwag studio 10 works just fine with exactly the same dll

**Comment by RSuter** [comment]
We switched to .NET Standard and we may have some unresolved assembly loading problems...

Try creating a `web.config` file somewhere with: 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <loadFromRemoteSources enabled="true"/>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="9.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.3.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

and select this file: 

![image](https://user-images.githubusercontent.com/2603405/27318951-3c5dd770-558f-11e7-8c60-527306218cb5.png)

Is this working?

**Comment by RSuter** [comment]
Or if you have selected a web.config, try leaving this field empty..

**Comment by RSuter** [comment]
The simplest solution is to use the ASP.NET Core middlewares to generate/serve the spec from the asp.net core process and import this url in NSwagStudio: 

https://github.com/NSwag/NSwag/wiki/Middlewares

**Comment by Farshidgolkarihagh** [comment]
I just referenced 

C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Runtime.dll

and it worked.

**Comment by ctokareff** [comment]
Sorry guys, I do not need workarounds simply because studio v10 works just fine - I'm stick with it for now.

@RSuter I'm using swagger web api middleware (and UI) for testing, but NSwag generates very different type script classes out of it. I prefer one that comes from assembly.

@Farshidgolkarihagh I'm talking about .net core web api project and there is no direct reference on system.runtime in it

**Comment by RSuter** [comment]
@ctokareff This is probably because the middleware uses the correct defaults for .NET Core (UseAspNetCore = true) and in NSwagStudio/cmd line you have to manually set this...

Can you provide a sample project where I can reproduce this issue?

**Comment by ctokareff** [comment]
I think I can - will do it tomorrow (quite busy now)

**Comment by ctokareff** [comment]
here is a sample project https://www.dropbox.com/s/a7286q4ceuxw064/WebApplication1.zip?dl=0
again: v10.* works fine with it
v11.* crashes with error (see first message)

**Comment by RSuter** [comment]
If I publish the application: 

    WebApplication1>dotnet publish -c Release

and use the correct path of the DLL: 

    bin/Release/netcoreapp1.1/WebApplication1.dll

.nswag: 

```
{
  "swaggerGenerator": {
    "webApiToSwagger": {
      "assemblyPaths": [
        "bin/Release/netcoreapp1.1/WebApplication1.dll"
      ],
      "referencePaths": [],
      "isAspNetCore": false,
      "controllerNames": [],
      "defaultUrlTemplate": "api/{controller}/{id?}",
      "defaultPropertyNameHandling": "Default",
      "defaultEnumHandling": "Integer",
      "flattenInheritanceHierarchy": false,
      "generateKnownTypes": true,
      "generateXmlObjects": false,
      "addMissingPathParameters": false,
      "infoTitle": "Web API Swagger specification",
      "infoVersion": "1.0.0",
      "output": null
    }
  },
  "codeGenerators": {}
}
```

it works for me

![image](https://user-images.githubusercontent.com/2603405/27376210-c39123c2-5671-11e7-8b73-91bbf4377fe9.png)

**Comment by ctokareff** [comment]
@RSuter I'm publishing from VS2017 into PublishOutput
and as I said version 10 works just fine for me
if you don't want to find out what is the difference between v10 and v11 then I'll just sit in v10 and will not bother you )

**Comment by ctokareff** [comment]
@RSuter BTW if I use 'dotnet publish -c Release' and then try to open dll from '\bin\Release\netcoreapp1.1\publish' then error appears again

**Comment by RSuter** [comment]
You have to select the dll from `WebApplication1\WebApplication1\bin\Release\netcoreapp1.1`

But yes this is very strange - why is VS publish and dotnet publish not the same?

**Comment by RSuter** [comment]
If i upgrade NSwagStudio to .net 4.6.2 and install System.Runtime 4.3.0 it works: 

[nswag.zip](https://github.com/NSwag/NSwag/files/1091051/nswag.zip)

**Comment by ctokareff** [comment]
my main point is: v10 works fine w/o any additional actions from my side

**Comment by RSuter** [comment]
I understand your point. And I also know where this issue comes from: The migration to .NET Standard - this is not a just a single line of change and we will also not be rolling back. Because .NET Standard is the future... The only way is to solve this problem in the current codebase...

**Comment by RSuter** [comment]
https://github.com/NSwag/NSwag/commit/1348698596d6c066c052ad002923685665990ba1

**Comment by RSuter** [comment]
Can you test with the latest CI artifacts?

**Comment by ctokareff** [comment]
I see 3 days old build here:
https://ci.appveyor.com/project/rsuter/nswag 
is it correct place?

**Comment by RSuter** [comment]
This: https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts

**Comment by ctokareff** [comment]
it works fine now, great!

**Comment by RSuter** [comment]
v11.2.0
