### ISSUE TITLE
Naming convention of parameters (underscores)

### ISSUE THREAD

**Issue by hmvs** [NSwag/NSwag#808]
I would like to change the way how parameters names are generated for specific cases. 
For example: I have header attribute names like that `X-Related-Data` that will results in 
`string x_Related_Data`. But I would like to have just xRelatedData.
Is there any option/extension point where I can do it?

**Comment by hmvs** [comment]
Thanks a ton. Would be nice to have it in updated package.

**Comment by RSuter** [comment]
Is this working for you?
Release will be soon

**Comment by hmvs** [comment]
Yep, for me it's absolutely fine. Thanks a lot. 
Hoping for release :)

**Comment by RSuter** [comment]
v11.1.2
