### ISSUE TITLE
Excluding a controller from an Assembly

### ISSUE THREAD

**Issue by lucassp** [NSwag/NSwag#810]
Is there a way to exclude a controller from a specific assembly when generating the swagger specification JSON file inside the MSBuild target?

```
<Exec Command="$(NSwagExe) webapi2swagger /assembly:$(OutDir)/Service.exe /output:api.json" />
```

Thanks!

**Comment by RSuter** [comment]
No, there is no option to exclude a specific controller. There is only a setting to define the included controllers: 

    /controllers:MyNamespace.Controllers.**
