### ISSUE TITLE
Generated typescript code for dictionary does not compile

### ISSUE THREAD

**Issue by terkill** [NSwag/NSwag#811]
```
"responses": {
    "200": {
        "schema": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/myItem"
            }
        }
    }
 }
```

The response above, from this [swagger document](https://github.com/terkill/nswag-typescript-dictionary-repro/blob/master/swagger-doc.json), will result in incorrectly generated TypeScirpt code.

```
result200[key] = resultData200[key] ? MyItem.fromJS(resultData200[key]) : {};
```

`result200` is of the type ` { [key: string]: MyItem; } | null` and `{}` is not conform to the `MyItem` type

----

Based on my investigation the issue is in ConvertToClassTemplate (line  [25](https://github.com/RSuter/NJsonSchema/blob/658853fa83313006b99f5f86c55fb39313ba51f6/src/NJsonSchema.CodeGeneration.TypeScript/Templates/ConvertToClassTemplate.tt#L25)) in the JSonSchema repo. As it uses the default value of `Model`, i.e. the dictionary and not the default value of the item.

If I'm correct then [this patch](https://github.com/terkill/nswag-typescript-dictionary-repro/blob/master/dict.patch) should fix the issue

**Comment by RSuter** [comment]
https://github.com/RSuter/NJsonSchema/commit/121091576486d6a99d0772f8e90314706dde0c41
