### ISSUE TITLE
How to avoid adding authorization header to the generated c# code

### ISSUE THREAD

**Issue by andrecarlucci** [NSwag/NSwag#817]
Hi guys,
Is it possible to avoid adding the authorization header to every method of the client?
I'm using JWT and I want to add the headers myself only once on a base class.

Also, how can I set the name of the generated class?

Tks!

**Comment by RSuter** [comment]
You can set the name of the clients with the ClassName setting: 

![image](https://user-images.githubusercontent.com/2603405/27530389-bf04e10a-5a58-11e7-8776-537b7ddd387a.png)

At the moment there is no option to exclude parameters from being generated... You have to first transform the document and remove the unwanted parameters.

**Comment by andrecarlucci** [comment]
@RSuter Thanks (name).
About the authorization header option, is this a feature you would like to have on NSwag?

**Comment by RSuter** [comment]
To understand you correctly: Your swagger spec specifies an authorization header parameter for each operation and you would like to omit this and implement this once in a base class?

**Comment by andrecarlucci** [comment]
Never mind. NSwag is working just fine. There was some code injecting these headers as parameters on the SwaggerUI page, so other developers could test the web services using different credentials. That's why they were appearing on NSwag generated code as well. I commented the code before using the tool and everything is fine now.
Thanks a lot.

**Comment by GreenMooseWork** [comment]
>To understand you correctly: Your swagger spec specifies an authorization header parameter for each operation and you would like to omit this and implement this once in a base class?

I am after this exact functionality, is this possible somehow?

**Comment by RSuter** [comment]
Some sort of setting to exclude some parameters from being generated?

**Comment by GreenMooseWork** [comment]
Yes. I.e. I have a base class for the API client which injects the authorization header, so I don't want to require it on all operations as parameters.

**Comment by RSuter** [comment]
No, there is no such functionality at the moment. ATM, you need to preprocess the swagger spec before feeding it into the code generator - should be really simple to write a simple command line tool with NSwag.Core to transform the spec... 

But maybe we should think about adding a DocumentProcessors preprocessors setting to the code generator settings so that you can transform the spec as part of the generation process...

**Comment by GreenMooseWork** [comment]
> No, there is no such functionality at the moment. ATM, you need to preprocess the swagger spec before feeding it into the code generator

Thanks, that was easy enough :)
![image](https://user-images.githubusercontent.com/31244330/37763893-94e3faf0-2dc0-11e8-9995-937d234eab7b.png)

**Comment by altso** [comment]
@RSuter any hints on how to exclude a header if I use `NSwag.MSBuild`?

**Comment by chrispiasecki** [comment]
Since this was not mentioned above, here is the JSON setting where you can exclude the authorization header from the generated methods. I was looking at doing @greenmooseSE's method until I randomly found the **excludedParameterNames** parameter. 

`
 "codeGenerators": {
    "openApiToCSharpClient": 
{"excludedParameterNames": [
        "Authorization"
      ].....`

**Comment by tyghnyh** [comment]
> > No, there is no such functionality at the moment. ATM, you need to preprocess the swagger spec before feeding it into the code generator
> 
> Thanks, that was easy enough :)
> 
> ```cs
>         private static string GenerateApiClientCode(string swaggerJsonContent)
>         {
>             SwaggerDocument swaggerDoc = SwaggerDocument.FromJsonAsync(swaggerJsonContent).ResultEx();
> 
>             //Remove auth header in operations since we supply it in API client base class
>             swaggerDoc.Operations.ForEach(operation =>
>             {
>                 SwaggerParameter headerParam = operation.Operation.Parameters.FirstOrDefault((param) =>
>                     param.Kind == SwaggerParameterKind.Header &&
>                     param.Name == "auth-token");
>                 if (headerParam != null)
>                     operation.Operation.Parameters.Remove(headerParam);
>             });
>             var settings = new SwaggerToCSharpClientGeneratorSettings
>             {
> ```

It seems what I need, but I can't get how to apply this code to nswag, can you give an example?
