### ISSUE TITLE
Nullable fields are implemented as non-nullable.

### ISSUE THREAD

**Issue by Prooskalia** [NSwag/NSwag#82]
Hi All

When a response value from a method is a structured object, and a field in that object is a nullable type (for example, in C#, an "int?") and is not flagged as required, when client-code is generated the field is implemented as the non-nullable version of the type (in the example, as an "int").  That means that when the response object is deserialized and the nullable field is actually null, a deserialization exception occurs.

The Swagger markup for my response class does not indicate that the field is required (though it does indicate the other required fields) and NSwag generates the JsonPropery attribute with "Required = Required.Default" (so, not required) but the type is non-nullable.

Hope I'm not just being confused?  Reproducible example attached.
Many thanks for your thoughts.
Nx

**Swagger script** (below) ... client code as attachment (search for [NullableInteger)]

```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "SampleApi"
  },
  "host": "localhost:50332",
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/v1/Sample": {
      "get": {
        "tags": [
          "Sample"
        ],
        "operationId": "Sample_Get",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/MyTestClass"
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "MyTestClass": {
      "required": [
        "NonNullString",
        "NonNullInteger"
      ],
      "type": "object",
      "properties": {
        "NonNullString": {
          "type": "string"
        },
        "NullableString": {
          "type": "string"
        },
        "NonNullInteger": {
          "format": "int32",
          "type": "integer"
        },
        "NullableInteger": {
          "format": "int32",
          "type": "integer"
        }
      }
    }
  }
}
```

[NullableFieldClientCode.txt](https://github.com/NSwag/NSwag/files/246620/NullableFieldClientCode.txt)

**Comment by rsuter** [comment]
I also had to learn this: Required does not define if a property can be null, but if the property must be defined in the JSON data (it still can be null). If you want a nullable property, use `type: ["null", "string"]`: 

```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "SampleApi"
  },
  "host": "localhost:50332",
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/v1/Sample": {
      "get": {
        "tags": [
          "Sample"
        ],
        "operationId": "Sample_Get",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/MyTestClass"
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "MyTestClass": {
      "required": [
        "NonNullString",
        "NonNullInteger"
      ],
      "type": "object",
      "properties": {
        "NonNullString": {
          "type": "string"
        },
        "NullableString": {
          "type": ["null", "string"]
        },
        "NonNullInteger": {
          "format": "int32",
          "type": "integer"
        },
        "NullableInteger": {
          "format": "int32",
          "type": ["null", "integer"]
        }
      }
    }
  }
}
```

**Comment by Prooskalia** [comment]
Awww - thanks very much, and apologies for the bogus issue.
I can easily add a mapping into Swashbuckle to generate those "null" entries for me.
Many thanks again for the response (and for the excellent application).
Have a good day!
