### ISSUE TITLE
Client returns type object instead of supplied return type

### ISSUE THREAD

**Issue by ertjeeh** [NSwag/NSwag#820]
Hi,

I'm currently running into a problem which I can't seem to fix. Please have a look at my swagger docs:

```
{
	"swagger": "2.0",
	"info": {
		"version": "v1",
		"title": "VoIP.SettingApi",
		"description": "v1.0.0.0"
	},
	"host": "localhost:50369",
	"schemes": ["http"],
	"paths": {
		"/api/v1/settings/{sipName}@{sipDomain}": {
			"get": {
				"tags": ["Setting"],
				"operationId": "Setting_GetSettings",
				"consumes": [],
				"produces": ["application/json",
				"text/json",
				"text/html",
				"application/xml",
				"text/xml"],
				"parameters": [{
					"name": "sipName",
					"in": "path",
					"required": true,
					"type": "string"
				},
				{
					"name": "sipDomain",
					"in": "path",
					"required": true,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "OK",
						"schema": {
							"$ref": "#/definitions/SettingsGetViewModel"
						}
					},
					"400": {
						"description": "BadRequest",
						"schema": {
							"$ref": "#/definitions/BadRequestResult"
						}
					},
					"500": {
						"description": "InternalServerError",
						"schema": {
							"$ref": "#/definitions/InternalErrorResult"
						}
					}
				}
			},
			"put": {
				"tags": ["Setting"],
				"operationId": "Setting_UpdateSettings",
				"consumes": ["application/json",
				"text/json",
				"text/html",
				"application/xml",
				"text/xml",
				"application/x-www-form-urlencoded"],
				"produces": ["application/json",
				"text/json",
				"text/html",
				"application/xml",
				"text/xml"],
				"parameters": [{
					"name": "sipName",
					"in": "path",
					"required": true,
					"type": "string"
				},
				{
					"name": "sipDomain",
					"in": "path",
					"required": true,
					"type": "string"
				},
				{
					"name": "subscriberSettingsUpdateViewModel",
					"in": "body",
					"required": true,
					"schema": {
						"$ref": "#/definitions/SettingsUpdateViewModel"
					}
				}],
				"responses": {
					"200": {
						"description": "OK"
					},
					"400": {
						"description": "BadRequest",
						"schema": {
							"$ref": "#/definitions/BadRequestResult"
						}
					},
					"500": {
						"description": "InternalServerError",
						"schema": {
							"$ref": "#/definitions/InternalErrorResult"
						}
					}
				}
			},
			"delete": {
				"tags": ["Setting"],
				"operationId": "Setting_DeleteSettings",
				"consumes": [],
				"produces": ["application/json",
				"text/json",
				"text/html",
				"application/xml",
				"text/xml"],
				"parameters": [{
					"name": "sipName",
					"in": "path",
					"required": true,
					"type": "string"
				},
				{
					"name": "sipDomain",
					"in": "path",
					"required": true,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "OK"
					},
					"400": {
						"description": "BadRequest",
						"schema": {
							"$ref": "#/definitions/BadRequestResult"
						}
					},
					"500": {
						"description": "InternalServerError",
						"schema": {
							"$ref": "#/definitions/InternalErrorResult"
						}
					}
				}
			}
		}
	},
	"definitions": {
		"SettingsGetViewModel": {
			"type": "object",
			"properties": {
				"SubscriberIdentificationViewModel": {
					"$ref": "#/definitions/SubscriberIdentificationViewModel"
				},
				"SubscriberSettings": {
					"$ref": "#/definitions/SubscriberSettingsViewModel"
				}
			}
		},
		"SubscriberIdentificationViewModel": {
			"required": ["SipName",
			"SipDomain"],
			"type": "object",
			"properties": {
				"SipName": {
					"type": "string"
				},
				"SipDomain": {
					"type": "string"
				}
			}
		},
		"SubscriberSettingsViewModel": {
			"required": ["Bar0900",
			"Bar0906",
			"Bar0909",
			"BarInternational",
			"BarMobile",
			"Clir",
			"BNumberHide",
			"RingTimeOut",
			"VoicemailEnabled",
			"PaperDirectory",
			"DigitalDirectory",
			"OperationalDirectory",
			"GlobalForwarding"],
			"type": "object",
			"properties": {
				"Bar0900": {
					"type": "boolean"
				},
				"Bar0906": {
					"type": "boolean"
				},
				"Bar0909": {
					"type": "boolean"
				},
				"BarInternational": {
					"type": "boolean"
				},
				"BarMobile": {
					"type": "boolean"
				},
				"Clir": {
					"type": "boolean"
				},
				"BNumberHide": {
					"type": "boolean"
				},
				"RingTimeOut": {
					"format": "int32",
					"maximum": 120,
					"minimum": 5,
					"type": "integer"
				},
				"VoicemailEnabled": {
					"type": "boolean"
				},
				"VoicemailEmail": {
					"type": "string"
				},
				"VoicemailPassword": {
					"type": "string"
				},
				"PaperDirectory": {
					"type": "boolean"
				},
				"DigitalDirectory": {
					"type": "boolean"
				},
				"OperationalDirectory": {
					"type": "boolean"
				},
				"GlobalForwarding": {
					"type": "boolean"
				},
				"GlobalForwardingTarget": {
					"type": "string"
				}
			}
		},
		"BadRequestResult": {
			"type": "object",
			"properties": {
				"Message": {
					"type": "string"
				}
			}
		},
		"InternalErrorResult": {
			"type": "object",
			"properties": {
				"Message": {
					"type": "string"
				}
			}
		},
		"SettingsUpdateViewModel": {
			"type": "object",
			"properties": {
				"Bar0900": {
					"type": "boolean"
				},
				"Bar0906": {
					"type": "boolean"
				},
				"Bar0909": {
					"type": "boolean"
				},
				"BarInternational": {
					"type": "boolean"
				},
				"BarMobile": {
					"type": "boolean"
				},
				"Clir": {
					"type": "boolean"
				},
				"BNumberHide": {
					"type": "boolean"
				},
				"RingTimeout": {
					"format": "int32",
					"maximum": 120,
					"minimum": 5,
					"type": "integer"
				},
				"VoicemailEnabled": {
					"type": "boolean"
				},
				"VoicemailEmail": {
					"type": "string"
				},
				"VoicemailPassword": {
					"type": "string"
				},
				"PaperDirectory": {
					"type": "boolean"
				},
				"DigitalDirectory": {
					"type": "boolean"
				},
				"OperationalDirectory": {
					"type": "boolean"
				},
				"GlobalForwarding": {
					"type": "boolean"
				},
				"GlobalForwardingTarget": {
					"type": "string"
				}
			}
		}
	}
}
```

As you can see I'm using `InternalErrorResult` and `BadRequestResult` as return types for Internal Server Errors and Bad Requests respectively.

Take a look at this piece of code (I took a screenshot because the code formatting is horrible):
![image](https://user-images.githubusercontent.com/29705590/27537184-f7764a14-5a72-11e7-8d7b-545ff1eb95a4.png)

And at the generated client (NSwagStudio 11.1.2.0):
![image](https://user-images.githubusercontent.com/29705590/27536990-f95e36c6-5a71-11e7-92bf-b1ea82dd2f4b.png)

Can somebody tell me why the SwaggerException in case of a statuscode of 400 is of the correct type (`BadRequestResult`) but in the case of statuscode 500 it's `object` and not `InternalErrorResult`

Please let me know if I need to supply more info. Thanks in advance.

**Comment by RSuter** [comment]
I just tried with the latest source code ("master") and it looks good: 

        public async System.Threading.Tasks.Task<SettingsGetViewModel> GetSettingsAsync(string sipName, string sipDomain, System.Threading.CancellationToken cancellationToken)
        {
            if (sipName == null)
                throw new System.ArgumentNullException("sipName");
    
            if (sipDomain == null)
                throw new System.ArgumentNullException("sipDomain");
    
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl).Append("/api/v1/settings/{sipName}@{sipDomain}");
            urlBuilder_.Replace("{sipName}", System.Uri.EscapeDataString(System.Convert.ToString(sipName, System.Globalization.CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{sipDomain}", System.Uri.EscapeDataString(System.Convert.ToString(sipDomain, System.Globalization.CultureInfo.InvariantCulture)));
    
            var client_ = new System.Net.Http.HttpClient();
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
    
                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);
    
                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        foreach (var item_ in response_.Content.Headers)
                            headers_[item_.Key] = item_.Value;
    
                        ProcessResponse(client_, response_);
    
                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200") 
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(SettingsGetViewModel); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<SettingsGetViewModel>(responseData_);
                                return result_; 
                            } 
                            catch (System.Exception exception) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                        }
                        else
                        if (status_ == "400") 
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(BadRequestResult); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<BadRequestResult>(responseData_);
                            } 
                            catch (System.Exception exception) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                            throw new SwaggerException<BadRequestResult>("BadRequest", status_, responseData_, headers_, result_, null);
                        }
                        else
                        if (status_ == "500") 
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(InternalErrorResult); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<InternalErrorResult>(responseData_);
                            } 
                            catch (System.Exception exception) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                            throw new SwaggerException<InternalErrorResult>("InternalServerError", status_, responseData_, headers_, result_, null);
                        }


[nswag.zip](https://github.com/NSwag/NSwag/files/1102815/nswag.zip)

Can you post your "nswag.json" file or do you use special settings?

**Comment by ertjeeh** [comment]
Yes, this here is my nswag.sjon:

```{
  "swaggerGenerator": {
    "fromSwagger": {
      "url": "****",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToCSharpClient": {
      "generateClientClasses": true,
      "generateClientInterfaces": true,
      "generateDtoTypes": true,
      "injectHttpClient": false,
      "disposeHttpClient": true,
      "generateExceptionClasses": false,
      "exceptionClass": "SwaggerException",
      "wrapDtoExceptions": true,
      "useHttpClientCreationMethod": false,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": false,
      "useBaseUrl": true,
      "generateSyncMethods": false,
      "clientClassAccessModifier": "public",
      "generateContractsOutput": false,
      "contractsNamespace": "VoIP.SettingApi.Contracts",
      "className": "{controller}SettingClient",
      "namespace": "VoIP.SettingApi.Client",
      "additionalNamespaceUsages": [
        "VoIP.Api.Library.Exceptions",
        "VoIP.Api.Library.ActionResults"
      ],
      "generateOptionalParameters": false,
      "requiredPropertiesMustBeDefined": false,
      "dateType": "System.DateTimeOffset",
      "dateTimeType": "System.DateTimeOffset",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.ObjectModel.ObservableCollection",
      "dictionaryType": "System.Collections.Generic.Dictionary",
      "classStyle": "Poco",
      "operationGenerationMode": "SingleClientFromOperationId",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [
        "BadRequestResult",
        "InternalErrorResult"
      ],
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "output": "SettingClient.cs"
    }
  }
}```

**Comment by RSuter** [comment]
I think this is a problem with excludedTypeNames

**Comment by ertjeeh** [comment]
Like an error of me configuring that way? Or a bug in the code? I would really like to exclude them because I've added them into a NuGet package so that I can use them in multiple clients (hence the additionalNamespaceUsages).

**Comment by RSuter** [comment]
With your config, it still looks good to me (with the code in "master": https://ci.appveyor.com/project/rsuter/nswag-25x6o/build/artifacts): 

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.1.2.0")]
    public partial class SettingClient : ISettingClient
    {
        private string _baseUrl = "http://localhost:50369";
        
        public string BaseUrl 
        {
            get { return _baseUrl; }
            set { _baseUrl = value; }
        }
    
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);
    
        /// <returns>OK</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Threading.Tasks.Task<SettingsGetViewModel> Setting_GetSettingsAsync(string sipName, string sipDomain)
        {
            return Setting_GetSettingsAsync(sipName, sipDomain, System.Threading.CancellationToken.None);
        }
    
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <returns>OK</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public async System.Threading.Tasks.Task<SettingsGetViewModel> Setting_GetSettingsAsync(string sipName, string sipDomain, System.Threading.CancellationToken cancellationToken)
        {
            if (sipName == null)
                throw new System.ArgumentNullException("sipName");
    
            if (sipDomain == null)
                throw new System.ArgumentNullException("sipDomain");
    
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl).Append("/api/v1/settings/{sipName}@{sipDomain}");
            urlBuilder_.Replace("{sipName}", System.Uri.EscapeDataString(System.Convert.ToString(sipName, System.Globalization.CultureInfo.InvariantCulture)));
            urlBuilder_.Replace("{sipDomain}", System.Uri.EscapeDataString(System.Convert.ToString(sipDomain, System.Globalization.CultureInfo.InvariantCulture)));
    
            var client_ = new System.Net.Http.HttpClient();
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
    
                    PrepareRequest(client_, request_, urlBuilder_);
                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
                    PrepareRequest(client_, request_, url_);
    
                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    try
                    {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        foreach (var item_ in response_.Content.Headers)
                            headers_[item_.Key] = item_.Value;
    
                        ProcessResponse(client_, response_);
    
                        var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200") 
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(SettingsGetViewModel); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<SettingsGetViewModel>(responseData_);
                                return result_; 
                            } 
                            catch (System.Exception exception) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                        }
                        else
                        if (status_ == "400") 
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(BadRequestResult); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<BadRequestResult>(responseData_);
                            } 
                            catch (System.Exception exception) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                            throw new SwaggerException<BadRequestResult>("BadRequest", status_, responseData_, headers_, result_, null);
                        }
                        else
                        if (status_ == "500") 
                        {
                            var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(InternalErrorResult); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<InternalErrorResult>(responseData_);
                            } 
                            catch (System.Exception exception) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
                            }
                            throw new SwaggerException<InternalErrorResult>("InternalServerError", status_, responseData_, headers_, result_, null);
                        }

[nswag.zip](https://github.com/NSwag/NSwag/files/1104315/nswag.zip)

**Comment by ertjeeh** [comment]
Okay, so you suggest I download the master artifact and generate my clients with that?

Thanks!

**Comment by RSuter** [comment]
Yes, just try with the latest version - with this version it looks good for me. This is just to avoid searching for problems which are already solved :-)

**Comment by ertjeeh** [comment]
Thanks for your help, I'll try it later this morning and I'll let you know if it works for me as well.

**Comment by ertjeeh** [comment]
Works like a charm, thanks again :+1:

**Comment by RSuter** [comment]
Strange, i dont know what code change might have fixed this... Anyway, the new version will be released soon...

**Comment by RSuter** [comment]
v11.2.0
