### ISSUE TITLE
Generics: Code generation - Convert List of types as array.

### ISSUE THREAD

**Issue by prakash-patel** [NSwag/NSwag#83]
I have method in Asp.NET WEB API controller look like below.
```c#
[ResponseType(typeof(SearchResponse<NewsResponse>))]
[SwaggerResponse(200,"Records Found",typeof(SearchResponse<NewsResponse>))]
public IHttpActionResult Get([FromUri] NewsRequest request)
```

In Swagger docs this is how it's looks
``` json
responses: {
200: {
description: "Records Found",
schema: {
                    $ref: "#/definitions/SearchResponse[NewsResponse]"
                }
     }
}
```

When i geneate the code using ```.tt``` file doesn't create code as List of type but use as array. see below _SearchResponse[NewsResponse]_

``` C#
/// <exception cref="SwaggerException">A server side error occurred.</exception>
public Task<SearchResponse[NewsResponse]> News_GetAsync()
```
I think it should be genate below code.

``` c#
/// <exception cref="SwaggerException">A server side error occurred.</exception>
public Task<SearchResponse<NewsResponse>> News_GetAsync()
```
Could you please tell me what is best way to solve this issue?

**Comment by rsuter** [comment]
Generics are not supported by the Swagger spec and JSON Schema.

https://github.com/domaindrivendev/Swashbuckle/issues/600

**Comment by rsuter** [comment]
This ref syntax is not allowed in JSON Schema.. But it is an interesting approach... 

Generics are currently stil open: https://github.com/NJsonSchema/NJsonSchema/issues/23

**Comment by prakash-patel** [comment]
Thanks for your response. I have found a work around after doing some search.
https://github.com/domaindrivendev/Swashbuckle/issues/600#issuecomment-171777175

**Comment by rsuter** [comment]
Closed, see issue for NJsonSchema...
