### ISSUE TITLE
NSwag.MSBuild nuget missing dll's so it errors in build step.

### ISSUE THREAD

**Issue by ksmithRenweb** [NSwag/NSwag#830]
*** Error ***
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at NSwag.Program.Main(String[] args)

NSwag.Console from solution works. Difference is about a dozen dll's that are not NSwag's.

I added this line to the nuspec file:

    <file src="..\NSwag.Console\bin\Release\net46\*.dll" target="build" />

Packaged the nuspec locally and put it in a local nuget repo. Referencing the local package works.

Please update the official nuget. If you wish I'll set up a pull request with this change.

Thanks,
Kevin

**Comment by RSuter** [comment]
https://www.nuget.org/packages/NSwag.MSBuild/11.2.1

**Comment by ksmithRenweb** [comment]
@RSuter Thank you

**Comment by RSuter** [comment]
Thanks for reporting.
