### ISSUE TITLE
How to call this function

### ISSUE THREAD

**Issue by yanqui92** [NSwag/NSwag#832]
Hi!

I'm new to NSwag and I succesfully generated the Typescript Client from my WebApi assembly.

I'm having a problem trying to call this method for example:
`  getAll(): Observable<Blob | null> {
        let url_ = this.baseUrl + "/api/categorias";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = {
            method: "get",
            responseType: ResponseContentType.Blob,
            headers: new Headers({
                "Content-Type": "application/json", 
                "Accept": "application/json"
            })
        };

        return this.http.request(url_, options_).flatMap((response_) => {
            return this.transformResult(url_, response_, (r) => this.processGetAll(r));
        }).catch((response_: any) => {
            if (response_ instanceof Response) {
                try {
                    return this.transformResult(url_, response_, (r) => this.processGetAll(r));
                } catch (e) {
                    return <Observable<Blob>><any>Observable.throw(e);
                }
            } else
                return <Observable<Blob>><any>Observable.throw(response_);
        });
    }`

When I call it from my component I see that the request is going to the server and returning something with status 200 but I don't know how to use this data since it is in Blob format. This is my console.log:

`Blob {size: 2161, type: "application/json"}
size
:
2161
type
:
"application/json"`

Any help would be great.

Thanks

**Comment by RSuter** [comment]
Can you post the web api action method signature?

**Comment by yanqui92** [comment]
Here it is:

`[HttpGet]
        [Route("", Name = "GetCategories")]
        public async Task<IHttpActionResult> GetAll()
        {
            using (var unitOfWork = new UnitOfWork(this.WippinContext))
            {
                return Ok(unitOfWork.Categorias.GetAll());
            }
        }`

**Comment by RSuter** [comment]
See https://github.com/NSwag/NSwag/wiki/WebApiToSwaggerGenerator#specify-the-response-type-of-an-action

**Comment by yanqui92** [comment]
Oooh Thank you a lot!!
It's working now!
