### ISSUE TITLE
The order of definition in swagger specification generate a wrong typescript client file

### ISSUE THREAD

**Issue by moustafarai** [NSwag/NSwag#833]
Hello
Today I spent a large part of my day spinning around on the generation of my webapi.
Following the generation via nswag I found myself with consistant objects and others with a bad signature.
After many tests I was able to conclude that the order of the definitions is important.
Indeed when my swagger specification file looks like this:

{
  "Swagger": "2.0",
  "Info": {
    "Version": "v1",
    "Title": "App"
  }
  "Host": "localhost",
  "BasePath": "/ AppV2",
  "Schemes": [
    "Http"
  ]
  "Consumes": [],
  "Produces": [],
  "Paths": {
    "/ Api / user / user": {
      "Get": {
        "Tags": [
          "User"
        ]
        "OperationId": "User_GetUser",
        "Consumes": [],
        "Produces": [
          "Application / json"
          "Text / json"
        ]
        "Responses": {
          "200": {
            "Description": "OK",
            "diagram": {
              "$ Ref": "# / definitions / ActionResponse [System.Net.HttpStatusCode, User]"
            }
          }
        }
      }
    }
  }
  "Definitions": {
     
   "User": {
      "Type": "object",
      "Properties": {
        "NetworkName": {
          "Type": "string"
        }
        "FirstName": {
          "Type": "string"
        }
        "LastName": {
          "Type": "string"
        }
        "E-mail": {
          "Type": "string"
        }
      }
    }
    "ActionResponse [System.Net.HttpStatusCode, User]": {
      "Type": "object",
      "Properties": {
        "Data": {
          "$ Ref": "# / definitions / User",
          "ReadOnly": true
        }
        "Status": {
          "Format": "int32",
          "Enum": [
            100
            101
          ]
          "Type": "integer",
          "ReadOnly": true
        }
        "Message": {
          "Type": "string",
          "ReadOnly": true
        }
       
      }
    }
    
  }
  "Parameters": {},
  "Responses": {},
  "SecurityDefinitions": {},
  "Security": [],
  "Tags": []
}

When generating the user object is incoherent:

Export interface User {
    NetworkName ?: string;
    FirstName ?: string;
    LastName ?: string;
    Email ?: string;
}

But if I switch the definitions like this:
{
  "Swagger": "2.0",
  "Info": {
    "Version": "v1",
    "Title": "App"
  }
  "Host": "localhost",
  "BasePath": "/ AppV2",
  "Schemes": [
    "Http"
  ]
  "Consumes": [],
  "Produces": [],
  "Paths": {
    "/ Api / user / user": {
      "Get": {
        "Tags": [
          "User"
        ]
        "OperationId": "User_GetUser",
        "Consumes": [],
        "Produces": [
          "Application / json"
          "Text / json"
        ]
        "Responses": {
          "200": {
            "Description": "OK",
            "diagram": {
              "$ Ref": "# / definitions / ActionResponse [System.Net.HttpStatusCode, User]"
            }
          }
        }
      }
    }
  }
  "Definitions": {
 
    "ActionResponse [System.Net.HttpStatusCode, User]": {
      "Type": "object",
      "Properties": {
        "Data": {
          "$ Ref": "# / definitions / User",
          "ReadOnly": true
        }
        "Status": {
          "Format": "int32",
          "Enum": [
            100
            101
          ]
          "Type": "integer",
          "ReadOnly": true
        }
        "Message": {
          "Type": "string",
          "ReadOnly": true
        }
       
      }
    }
    ,
        
   "User": {
      "Type": "object",
      "Properties": {
        "NetworkName": {
          "Type": "string"
        }
        "FirstName": {
          "Type": "string"
        }
        "LastName": {
          "Type": "string"
        }
        "E-mail": {
          "Type": "string"
        }
      }
    }
  }
  "Parameters": {},
  "Responses": {},
  "SecurityDefinitions": {},
  "Security": [],
  "Tags": []
}

The result becomes correct:

Export interface HttpStatusCodeAndUser {
    Data ?: User;
    Status ?: HttpStatusCodeAndUserStatus;
    Message: string;
}

Export interface User {
    NetworkName ?: string;
    FirstName ?: string;
    LastName ?: string;
    Email ?: string;
}

Is this a bug? Is this a standard?
Thank you in advance for your answer.

cordially

**Comment by moustafarai** [comment]
Hello,
It's me again :)

I found a bug when generating names in this method:

TypeScriptTypeNameGenerator.Generate ()

In this example:
`"Definitions": {
    "A.toto": {
      "Type": "object",
      "Properties": {
        "Status": {
          "Enum": [
            "Keep on going",
            "SwitchingProtocols"]
        }
      }
    }
    "MyGeneric [a.toto]": {
      "Type": "object",
      "Properties": {
        "Statam": {
          "Enum": [
            "Keep on going",
            "SwitchingProtocols"
        }
      }
    }
}
`
A single object is returned "Toto". We have a conflict on these 2 names.

Here is the wrong part of the code:

 `Public virtual string Generate (JsonSchema4 schema, string typeNameHint, IEnumerable <string> reservedTypeNames)
        {
            If (string.IsNullOrEmpty (typeNameHint) &&! String.IsNullOrEmpty (schema.DocumentPath))
                TypeNameHint = schema.DocumentPath.Replace ("\\", "/") Split ('/').Last ();

            Var typeName = Generate (schema, typeNameHint);
            If (string.IsNullOrEmpty (typeName) || reservedTypeNames.Contains(typeName))
                TypeName = GenerateTypeName (typeNameHint, reservedTypeNames);

            Return type
                .Replace ("[", "Of"]
                .Replace ("]", string.Empty)
                .Replace (",", "And")
                .Replace ("", string.Empty);
        }`    

TypeName is checked and modified after ...

We have made a fix:

`Public virtual string Generate (JsonSchema4 schema, string typeNameHint, IEnumerable <string> reservedTypeNames)
        {
            If (string.IsNullOrEmpty (typeNameHint) &&! String.IsNullOrEmpty (schema.DocumentPath))
                TypeNameHint = schema.DocumentPath.Replace ("\\", "/") Split ('/') Last ();

            TypeNameHint = typeNameHint
                .Replace ("[", "Of"]
                .Replace ("]", "")
                .Replace (",", "And")
                .Replace ("", "");

            Var parts = typeNameHint.Split ('');
            TypeNameHint = string.Join (string.Empty, parts.Select (x => Generate (schema, x)));

            Var typeName = Generate (schema, typeNameHint);
            If (string.IsNullOrEmpty (typeName) || reservedTypeNames.Contains (typeName))
                TypeName = GenerateTypeName (typeNameHint, reservedTypeNames);

            Return typeName;
        }`
 

Now it works better with generics.
And we have 2 objects created:  Toto & MyGeneriqueOfToto

If you wish I can make a pull request

thank you in advance

**Comment by RSuter** [comment]
The Problem is that JSON Schema and Swagger does not support generics and the usage of names like "ActionResponse [System.Net.HttpStatusCode, User]" is extremely dangerous..

**Comment by RSuter** [comment]
How did you generate or retrieve your Swagger spec?

**Comment by moustafarai** [comment]
The swagger spec is valid.
the matter is the collision beetween object in this algo.

step 1 : you generate  a name
step 2 : you check collision
step 3 : you modify  the name 
and after you don't check collision with this new name.

**Comment by moustafarai** [comment]
sorry but my english is soo bad ...

**Comment by RSuter** [comment]
Can you post the correct Swagger spec (without spaces in the names for example?)

**Comment by moustafarai** [comment]
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "SysOp"
  },
  "host": "localhost",
  "basePath": "/SysOpV2",
  "schemes": [
    "http"
  ],
  "consumes": [],
  "produces": [],
  "paths": {
    "/api/websiteinstancecontroller/{id}": {
      "put": {
        "tags": [
          "PUT"
        ],
        "operationId": "WebsiteInstance_UpdateById",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
         {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "model",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/a.toto"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/a.toto"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "a.toto": {
      "type": "object",
      "properties": {
        "Status": {
          "enum": [
            "Continue",
            "SwitchingProtocols",
            "OK",
            "Created",
            "Accepted",
            "NonAuthoritativeInformation",
            "NoContent",
            "ResetContent",
            "PartialContent",
            "MultipleChoices",
            "Ambiguous",
            "MovedPermanently",
            "Moved",
            "Found",
            "Redirect",
            "SeeOther",
            "RedirectMethod",
            "NotModified",
            "UseProxy",
            "Unused",
            "TemporaryRedirect",
            "RedirectKeepVerb",
            "BadRequest",
            "Unauthorized",
            "PaymentRequired",
            "Forbidden",
            "NotFound",
            "MethodNotAllowed",
            "NotAcceptable",
            "ProxyAuthenticationRequired",
            "RequestTimeout",
            "Conflict",
            "Gone",
            "LengthRequired",
            "PreconditionFailed",
            "RequestEntityTooLarge",
            "RequestUriTooLong",
            "UnsupportedMediaType",
            "RequestedRangeNotSatisfiable",
            "ExpectationFailed",
            "UpgradeRequired",
            "InternalServerError",
            "NotImplemented",
            "BadGateway",
            "ServiceUnavailable",
            "GatewayTimeout",
            "HttpVersionNotSupported"
          ],
          "type": "string",
          "readOnly": true
        },
       "Message": {
          "type": "string",
          "readOnly": true
        },
        "Messages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/a.toto"
          },
          "readOnly": true
        }
      }
    },
    "MonGenerique[a.toto]": {
      "type": "object",
      "properties": {
        "Statam": {
          "enum": [
            "Continue",
            "SwitchingProtocols",
            "OK",
            "Created",
            "Accepted",
            "NonAuthoritativeInformation",
            "NoContent",
            "ResetContent",
            "PartialContent",
            "MultipleChoices",
            "Ambiguous",
            "MovedPermanently",
            "Moved",
            "Found",
            "Redirect",
            "SeeOther",
            "RedirectMethod",
            "NotModified",
            "UseProxy",
            "Unused",
            "TemporaryRedirect",
            "RedirectKeepVerb",
            "BadRequest",
            "Unauthorized",
            "PaymentRequired",
            "Forbidden",
            "NotFound",
            "MethodNotAllowed",
            "NotAcceptable",
            "ProxyAuthenticationRequired",
            "RequestTimeout",
            "Conflict",
            "Gone",
            "LengthRequired",
            "PreconditionFailed",
            "RequestEntityTooLarge",
            "RequestUriTooLong",
            "UnsupportedMediaType",
            "RequestedRangeNotSatisfiable",
            "ExpectationFailed",
            "UpgradeRequired",
            "InternalServerError",
            "NotImplemented",
            "BadGateway",
            "ServiceUnavailable",
            "GatewayTimeout",
            "HttpVersionNotSupported"
          ],
          "type": "string",
          "readOnly": true
        }
      }
    }
  },
  "parameters": {},
  "responses": {},
  "securityDefinitions": {},
  "security": [],
  "tags": []
}

**Comment by moustafarai** [comment]
````
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "SysOp"
  },
  "host": "localhost",
  "basePath": "/SysOpV2",
  "schemes": [
    "http"
  ],
  "consumes": [],
  "produces": [],
  "paths": {
    "/api/websiteinstancecontroller/{id}": {
      "put": {
        "tags": [
          "PUT"
        ],
        "operationId": "WebsiteInstance_UpdateById",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json"
        ],
        "parameters": [
         {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "model",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/a.toto"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/a.toto"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "a.toto": {
      "type": "object",
      "properties": {
        "Status": {
          "enum": [
            "Continue",
            "SwitchingProtocols",
            "OK",
            "Created",
            "Accepted",
            "NonAuthoritativeInformation",
            "NoContent",
            "ResetContent",
            "PartialContent",
            "MultipleChoices",
            "Ambiguous",
            "MovedPermanently",
            "Moved",
            "Found",
            "Redirect",
            "SeeOther",
            "RedirectMethod",
            "NotModified",
            "UseProxy",
            "Unused",
            "TemporaryRedirect",
            "RedirectKeepVerb",
            "BadRequest",
            "Unauthorized",
            "PaymentRequired",
            "Forbidden",
            "NotFound",
            "MethodNotAllowed",
            "NotAcceptable",
            "ProxyAuthenticationRequired",
            "RequestTimeout",
            "Conflict",
            "Gone",
            "LengthRequired",
            "PreconditionFailed",
            "RequestEntityTooLarge",
            "RequestUriTooLong",
            "UnsupportedMediaType",
            "RequestedRangeNotSatisfiable",
            "ExpectationFailed",
            "UpgradeRequired",
            "InternalServerError",
            "NotImplemented",
            "BadGateway",
            "ServiceUnavailable",
            "GatewayTimeout",
            "HttpVersionNotSupported"
          ],
          "type": "string",
          "readOnly": true
        },
       "Message": {
          "type": "string",
          "readOnly": true
        },
        "Messages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/a.toto"
          },
          "readOnly": true
        }
      }
    },
    "MonGenerique[a.toto]": {
      "type": "object",
      "properties": {
        "Statam": {
          "enum": [
            "Continue",
            "SwitchingProtocols",
            "OK",
            "Created",
            "Accepted",
            "NonAuthoritativeInformation",
            "NoContent",
            "ResetContent",
            "PartialContent",
            "MultipleChoices",
            "Ambiguous",
            "MovedPermanently",
            "Moved",
            "Found",
            "Redirect",
            "SeeOther",
            "RedirectMethod",
            "NotModified",
            "UseProxy",
            "Unused",
            "TemporaryRedirect",
            "RedirectKeepVerb",
            "BadRequest",
            "Unauthorized",
            "PaymentRequired",
            "Forbidden",
            "NotFound",
            "MethodNotAllowed",
            "NotAcceptable",
            "ProxyAuthenticationRequired",
            "RequestTimeout",
            "Conflict",
            "Gone",
            "LengthRequired",
            "PreconditionFailed",
            "RequestEntityTooLarge",
            "RequestUriTooLong",
            "UnsupportedMediaType",
            "RequestedRangeNotSatisfiable",
            "ExpectationFailed",
            "UpgradeRequired",
            "InternalServerError",
            "NotImplemented",
            "BadGateway",
            "ServiceUnavailable",
            "GatewayTimeout",
            "HttpVersionNotSupported"
          ],
          "type": "string",
          "readOnly": true
        }
      }
    }
  },
  "parameters": {},
  "responses": {},
  "securityDefinitions": {},
  "security": [],
  "tags": []
}
````

**Comment by RSuter** [comment]
This is not the same spec - this one looks good...

**Comment by moustafarai** [comment]
And the typescript client generated with the fix :
````
/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.2.0.0 (NJsonSchema v9.2.5.0) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import * as ng from 'angular';

export class Client {
    private baseUrl: string | undefined = undefined; 
    private http: ng.IHttpService; 
    private q: ng.IQService; 
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor($http: ng.IHttpService, $q: ng.IQService, baseUrl?: string) {
        this.http = $http;
        this.q = $q;
        this.baseUrl = baseUrl ? baseUrl : "http://localhost/SysOpV2";
    }

    /**
     * @return OK
     */
    websiteInstance_UpdateById(id: number, model: Toto): ng.IPromise<Toto | null> {
        let url_ = this.baseUrl + "/api/websiteinstancecontroller/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(model);

        var options_ = <ng.IRequestConfig>{
            url: url_,
            method: "PUT",
            data: content_,
            transformResponse: [], 
            headers: {
                "Content-Type": "application/json", 
                "Accept": "application/json"
            }
        };

        return this.http(options_).then((_response) => {
            return this.processWebsiteInstance_UpdateById(_response);
        }, (_response) => {
            if (_response.status)
                return this.processWebsiteInstance_UpdateById(_response);
            throw _response;
        });
    }

    protected processWebsiteInstance_UpdateById(response: any): ng.IPromise<Toto | null> {
        const status = response.status; 

        if (status === 200) {
            const _responseText = response.data;
            let result200: Toto | null = null;
            result200 = _responseText === "" ? null : <Toto>JSON.parse(_responseText, this.jsonParseReviver);
            return this.q.resolve(result200);
        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException(this.q, "An unexpected server error occurred.", status, _responseText);
        }
        return this.q.resolve<Toto | null>(<any>null);
    }
}

export interface Toto {
    readonly Status?: TotoStatus | undefined;
    readonly Message?: string | undefined;
    readonly Messages?: Toto[] | undefined;
}

export interface MonGeneriqueOfToto {
    readonly Statam?: MonGeneriqueOfTotoStatam | undefined;
}

export enum TotoStatus {
    Continue = <any>"Continue", 
    SwitchingProtocols = <any>"SwitchingProtocols", 
    OK = <any>"OK", 
    Created = <any>"Created", 
    Accepted = <any>"Accepted", 
    NonAuthoritativeInformation = <any>"NonAuthoritativeInformation", 
    NoContent = <any>"NoContent", 
    ResetContent = <any>"ResetContent", 
    PartialContent = <any>"PartialContent", 
    MultipleChoices = <any>"MultipleChoices", 
    Ambiguous = <any>"Ambiguous", 
    MovedPermanently = <any>"MovedPermanently", 
    Moved = <any>"Moved", 
    Found = <any>"Found", 
    Redirect = <any>"Redirect", 
    SeeOther = <any>"SeeOther", 
    RedirectMethod = <any>"RedirectMethod", 
    NotModified = <any>"NotModified", 
    UseProxy = <any>"UseProxy", 
    Unused = <any>"Unused", 
    TemporaryRedirect = <any>"TemporaryRedirect", 
    RedirectKeepVerb = <any>"RedirectKeepVerb", 
    BadRequest = <any>"BadRequest", 
    Unauthorized = <any>"Unauthorized", 
    PaymentRequired = <any>"PaymentRequired", 
    Forbidden = <any>"Forbidden", 
    NotFound = <any>"NotFound", 
    MethodNotAllowed = <any>"MethodNotAllowed", 
    NotAcceptable = <any>"NotAcceptable", 
    ProxyAuthenticationRequired = <any>"ProxyAuthenticationRequired", 
    RequestTimeout = <any>"RequestTimeout", 
    Conflict = <any>"Conflict", 
    Gone = <any>"Gone", 
    LengthRequired = <any>"LengthRequired", 
    PreconditionFailed = <any>"PreconditionFailed", 
    RequestEntityTooLarge = <any>"RequestEntityTooLarge", 
    RequestUriTooLong = <any>"RequestUriTooLong", 
    UnsupportedMediaType = <any>"UnsupportedMediaType", 
    RequestedRangeNotSatisfiable = <any>"RequestedRangeNotSatisfiable", 
    ExpectationFailed = <any>"ExpectationFailed", 
    UpgradeRequired = <any>"UpgradeRequired", 
    InternalServerError = <any>"InternalServerError", 
    NotImplemented = <any>"NotImplemented", 
    BadGateway = <any>"BadGateway", 
    ServiceUnavailable = <any>"ServiceUnavailable", 
    GatewayTimeout = <any>"GatewayTimeout", 
    HttpVersionNotSupported = <any>"HttpVersionNotSupported", 
}

export enum MonGeneriqueOfTotoStatam {
    Continue = <any>"Continue", 
    SwitchingProtocols = <any>"SwitchingProtocols", 
    OK = <any>"OK", 
    Created = <any>"Created", 
    Accepted = <any>"Accepted", 
    NonAuthoritativeInformation = <any>"NonAuthoritativeInformation", 
    NoContent = <any>"NoContent", 
    ResetContent = <any>"ResetContent", 
    PartialContent = <any>"PartialContent", 
    MultipleChoices = <any>"MultipleChoices", 
    Ambiguous = <any>"Ambiguous", 
    MovedPermanently = <any>"MovedPermanently", 
    Moved = <any>"Moved", 
    Found = <any>"Found", 
    Redirect = <any>"Redirect", 
    SeeOther = <any>"SeeOther", 
    RedirectMethod = <any>"RedirectMethod", 
    NotModified = <any>"NotModified", 
    UseProxy = <any>"UseProxy", 
    Unused = <any>"Unused", 
    TemporaryRedirect = <any>"TemporaryRedirect", 
    RedirectKeepVerb = <any>"RedirectKeepVerb", 
    BadRequest = <any>"BadRequest", 
    Unauthorized = <any>"Unauthorized", 
    PaymentRequired = <any>"PaymentRequired", 
    Forbidden = <any>"Forbidden", 
    NotFound = <any>"NotFound", 
    MethodNotAllowed = <any>"MethodNotAllowed", 
    NotAcceptable = <any>"NotAcceptable", 
    ProxyAuthenticationRequired = <any>"ProxyAuthenticationRequired", 
    RequestTimeout = <any>"RequestTimeout", 
    Conflict = <any>"Conflict", 
    Gone = <any>"Gone", 
    LengthRequired = <any>"LengthRequired", 
    PreconditionFailed = <any>"PreconditionFailed", 
    RequestEntityTooLarge = <any>"RequestEntityTooLarge", 
    RequestUriTooLong = <any>"RequestUriTooLong", 
    UnsupportedMediaType = <any>"UnsupportedMediaType", 
    RequestedRangeNotSatisfiable = <any>"RequestedRangeNotSatisfiable", 
    ExpectationFailed = <any>"ExpectationFailed", 
    UpgradeRequired = <any>"UpgradeRequired", 
    InternalServerError = <any>"InternalServerError", 
    NotImplemented = <any>"NotImplemented", 
    BadGateway = <any>"BadGateway", 
    ServiceUnavailable = <any>"ServiceUnavailable", 
    GatewayTimeout = <any>"GatewayTimeout", 
    HttpVersionNotSupported = <any>"HttpVersionNotSupported", 
}

export class SwaggerException extends Error {
    message: string;
    status: number; 
    response: string; 
    result: any; 

    constructor(message: string, status: number, response: string, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.result = result;
    }
}

function throwException(q: ng.IQService, message: string, status: number, response: string, result?: any): ng.IPromise<any> {
    if(result !== null && result !== undefined)
        return q.reject(result);
    else
        return q.reject(new SwaggerException(message, status, response, null));
}

function blobToText(blob: Blob, q: ng.IQService): ng.IPromise<string> {
    return new q((resolve) => { 
        let reader = new FileReader(); 
        reader.onload = function() { 
            resolve(this.result);
        }
        reader.readAsText(blob); 
    });
}
````

**Comment by RSuter** [comment]
The type "MonGenerique[a.toto]" is not generated because it is not used in the public Web API...

**Comment by moustafarai** [comment]
It s not our complete Swagger spec . Our spec is very big. MonGenerique[a.toto] is a example to explain the problem.

**Comment by RSuter** [comment]
OK. I suggest that you write a sample spec (as short as possible) where the Problem is demonstrated (update you original issue with that). Then we delete the other posts because this issue gets way too long...

**Comment by doubret** [comment]
Hi,
I work with moustafarai, we spent some time today to investigate the issue.

Here is a simple swagger spec demonstrating the issue :
`{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "ws"
  },
  "host": "localhost",
  "basePath": "/ws",
  "schemes": [
    "http"
  ],
  "consumes": [],
  "produces": [],
  "paths": {
    "/api/sample1": {
      "get": {
        "operationId": "Controller_Sample1",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/a.dto"
            }
          }
        }
      }
    },
    "/api/sample2": {
      "get": {
        "operationId": "Controller_Sample2",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/generic[a.dto]"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "a.dto": {
      "type": "object",
      "properties": {
        "prop": {
          "type": "string"
        }
      }
    },
    "generic[a.dto]": {
      "type": "object",
      "properties": {
        "another_prop": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {},
  "responses": {},
  "securityDefinitions": {},
  "security": [],
  "tags": []
}`

And the generated typescript : 
`/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v10.6.6324.28497 (NJsonSchema v8.33.6323.36213) (http://NSwag.org)
// </auto-generated>
//----------------------


export class ControllerClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: (key: string, value: any) => any = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.baseUrl = baseUrl ? baseUrl : "";
        this.http = http ? http : <any>window;
    }

    /**
     * @return OK
     */
    sample1(): Promise<Dto> {
        let url_ = this.baseUrl + "/api/sample1";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Content-Type": "application/json; charset=UTF-8", 
                "Accept": "application/json; charset=UTF-8"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSample1(_response);
        });
    }

    protected processSample1(response: Response): Promise<Dto> {
        const status = response.status;
        if (status === 200) {
            return response.text().then((responseText) => {
            let result200: Dto = null;
            result200 = responseText === "" ? null : <Dto>JSON.parse(responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((responseText) => {
            return throwException("An unexpected server error occurred.", status, responseText);
            });
        }
        return Promise.resolve<Dto>(<any>null);
    }

    /**
     * @return OK
     */
    sample2(): Promise<Dto> {
        let url_ = this.baseUrl + "/api/sample2";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Content-Type": "application/json; charset=UTF-8", 
                "Accept": "application/json; charset=UTF-8"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSample2(_response);
        });
    }

    protected processSample2(response: Response): Promise<Dto> {
        const status = response.status;
        if (status === 200) {
            return response.text().then((responseText) => {
            let result200: Dto = null;
            result200 = responseText === "" ? null : <Dto>JSON.parse(responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((responseText) => {
            return throwException("An unexpected server error occurred.", status, responseText);
            });
        }
        return Promise.resolve<Dto>(<any>null);
    }
}

export interface Dto {
    prop?: string;
}

export class SwaggerException extends Error {
    message: string;
    status: number; 
    response: string; 
    result: any; 

    constructor(message: string, status: number, response: string, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.result = result;
    }
}

function throwException(message: string, status: number, response: string, result?: any): any {
    if(result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, null);
}`

As you can see, only one definition is generated instead of two. This is because the name generated for generic[a.dto] definition overwrites the one generated for a.dto.

As moustafarai explained, the issue is the NJsonSchema DefaultTypeNameGenerator class, line 39 (https://github.com/RSuter/NJsonSchema/blob/141ce52320697533e2444a12bd8d727a2664c905/src/NJsonSchema/DefaultTypeNameGenerator.cs).

`        public virtual string Generate(JsonSchema4 schema, string typeNameHint, IEnumerable<string> reservedTypeNames)
        {
            if (string.IsNullOrEmpty(typeNameHint) && !string.IsNullOrEmpty(schema.DocumentPath))
                typeNameHint = schema.DocumentPath.Replace("\\", "/").Split('/').Last();

            var typeName = Generate(schema, typeNameHint);
            if (string.IsNullOrEmpty(typeName) || reservedTypeNames.Contains(typeName))
                typeName = GenerateTypeName(typeNameHint, reservedTypeNames);

            return typeName
                .Replace("[", "Of")
                .Replace("]", string.Empty)
                .Replace(",", "And")
                .Replace(" ", string.Empty);
        }
`

When this code is called with generic[a.dto] as typeNameHint (reservedTypeNames already containing 'dto'), the line `var typeName = Generate(schema, typeNameHint);` returns 'dto]' as candidate.
'dto]' doesn't clash because of the trailing ']', then the last line removes the ']' and returns a name that clashes with the reserved type names.

In this code, the type name used for clashing names detection and the type name returned to the caller are definitely not the same, that leaves room for returning an undected clashing type name and that's exactly what we experienced.

I hope it's more clear now, don't hesitate if you need more details.
Thanks.

**Comment by RSuter** [comment]
Thank you for this explanation. You can write your own implementation of ITypeNameGenerator and provide it via settings. But we should also fix this in the default implementation. How should we change the behavior of `Generate(a, b)` with `generic[a.dto]`. I think it should be: 

- `foo.bar[a.b]` => `bar[b]`

**Comment by doubret** [comment]
Hi,
We implemented ITypeNameGenerator on our side. 
We're using nswag npm package to create the typescript client at build time with gulp. I didn't know we could register it in config, thanks. 

Look at the alternate implementation provided by moustafarai in an earlier message, I think it's the correct implementation. 
Basically it first replaces '[' by ' Of ', ',' by ' And ' etc (notice the spaces in the replacements) then it splits against space, then each part is split against '.' and only the last part is kept (to remove the namespace), and finally all parts are join together, run through the name clashing detection (that adds a number in case of clash) and the name is returned to the caller. 

This way there's no chance to return a clashing name. 

In the case of foo.bar[a.b] it generates BarOfB. 
In the case of foo.bar[a.b, foo.baz[c.d]] it generates BarOfBAndBazOfD. 
It looks pretty good to me.

**Comment by RSuter** [comment]
Currently, you cant use custom TypeNameGenerators in the command line - you need to write your own simple cmd line tool... (this is because everything is run in an isolated AppDomain and we need something like a plugin system)

Ill look into the alternative implementation soon
