### ISSUE TITLE
Description property  in SwaggerResponseAttribute not being used constructor

### ISSUE THREAD

**Issue by DDAndyChen** [NSwag/NSwag#835]
Description property not being used in *SwaggerResponseAttribute* constructor

https://github.com/NSwag/NSwag/blob/master/src/NSwag.Annotations/SwaggerResponseAttribute.cs#L56

This property is used in:
https://github.com/NSwag/NSwag/blob/master/src/NSwag.SwaggerGeneration.WebApi/Processors/OperationResponseProcessor.cs#L81

**Comment by RSuter** [comment]
Usage: 

    [SwaggerResponse(typeof(object), Description = "Foobar")]

**Comment by DDAndyChen** [comment]
I learnt something today.
