### ISSUE TITLE
C#: Swagger basePath doesn't include in clientside generated code.

### ISSUE THREAD

**Issue by prakash-patel** [NSwag/NSwag#88]
My swagger spec looks like below
```json
{
   swagger: "2.0",
   info: {
      version: "v2",
      title: "News"
},
host: "www.goodinfo.com",
basePath: "/news",
schemes: [
   "https"
],
paths: {}
}
...
```
My application running under `www.whatever.com/News`. Look like NSwag doesn't include BasePath (/News) when it's generate client code. Or am i doing something wrong?

**Comment by rsuter** [comment]
fixed in v2.17: https://github.com/NSwag/NSwag/commit/348d1c05dbe5cd7da5365b03afca5af258ae843b#diff-575f68badce095a685dfe19b4377aaa6L120
