### ISSUE TITLE
httpclient calls ends in deadlock when used in asp.net

### ISSUE THREAD

**Issue by tkwpfo** [NSwag/NSwag#9]
If the client is used in a asp.net request the httpclient calls ends in deadlock. To avoid that all httpclient calls should look something like this:

var response = await client.PostAsync(url, new StringContent("")).ConfigureAwait(false);

properly best if this is configurable, via the prepareRequest partial method.

**Comment by rsuter** [comment]
The main problem here is that you probably try to synchronize an async method (e.g. calling `.Result`) which is always very problematic... Nonetheless I've added `ConfigureAwait(false)` because it is correct to use here...

**Comment by rsuter** [comment]
https://github.com/NSwag/NSwag/commit/fb3be1c81d19193ed3c370af2f82b4463a5b041b

**Comment by rsuter** [comment]
Fixed in v1.1, is it working correctly now?

**Comment by tkwpfo** [comment]
Yes, thanks for fast response.
