### ISSUE TITLE
jQuery.parseJSON in Angular 2 Clients

### ISSUE THREAD

**Issue by berhir** [NSwag/NSwag#90]
The generated Angular 2 clients use` jQuery.parseJSON(data, this.jsonParseReviver)` instead of `JSON.parse(data, this.jsonParseReviver)`

**Comment by rsuter** [comment]
Will fix this in the next days...

**Comment by rsuter** [comment]
Fixed in: https://github.com/NSwag/NSwag/commit/82c37be5398eff4533c389dbb5ca140cf956a13b
